### ISSUE TITLE
Combining cert with old chain

### ISSUE THREAD

**Issue by BorysekOndrej** [webprofusion/Certify#1]
Hi,
Certify seems to be combining the fetched certificate with the old (i.e., **pre-XP patch**) **chain**.
As I don't see any hard coded certs in your app, I would assume the old ACMESharp dlls need to be replaced with new ones. But that's more less guessing from my side…

Thanks for this great tool, it really speeded up the deployment process.

**Comment by webprofusion-chrisc** [comment]
Hi Ondřej,
Sorry I dont know what you mean, it would be possible for old certificate conponents to get mixed up with new ones when building the pfx file I suppose. What is the pre-xp patch?
Chris
Sent from my Samsung Galaxy smartphone.-------- Original message --------From: Ondřej Borýsek <notifications@github.com> Date: 28/03/2016  4:33 pm  (GMT+08:00) To: webprofusion/Certify <Certify@noreply.github.com> Subject: [Certify] Combining cert with old chain (#1) 
Hi,

Certify seems to be combining the fetched certificate with the old (i.e., pre-XP patch) chain.

As I don't see any hard coded certs in your app, I would assume the old ACMESharp dlls need to be replaced with new ones. But that's more less guessing from my side…

Thanks for this great tool, it really speeded up the deployment process.

**Comment by BorysekOndrej** [comment]
Hi Chris.
Sorry for the unclarities in the first post. I've setup an example site, which shows the problem.
Few days ago, there has been an **update to Let's Encrypt certificate export process** allowing the **support for Win XP** systems. That involved stopping the use of "Let's Encrypt Authority X1" (intermediate) and using **new crossigned intermediate cert called "Let's Encrypt Authority X3"**. The generated cert for sites correctly identifies its issuer as X3, but the intermediate cert supplied with it is X1.

I have of course tried uninstalling and reinstalling several times and even full reboot on a development server, yet it doesn't seem to do the trick.

Test site: https://test3.borysek.eu/
SSL Checker: https://www.sslshopper.com/ssl-checker.html#hostname=https://test3.borysek.eu/
**SSL Labs** (the most visual and clear one): https://www.ssllabs.com/ssltest/analyze.html?d=test3.borysek.eu&hideResults=on

For me it certainly isn't a pressing issue, I've generated all necessary certs few days before the update, so they have few months of time and adding new support can certainly wait. Sorry for disturbing you on Easter.

PS: It seems like there has already been a discusion on this topic with authors of several third party clients (like this one for [acme-tiny](https://github.com/diafygi/acme-tiny/issues/77#issuecomment-187417037)).

**Comment by webprofusion-chrisc** [comment]
Hi Ondřej,

Thanks for the information, that's much appreciated. The issue is with 
ACMESharp to resolve as Certify is a GUI on top of that (it calls 
ACMESharp PowerShell commands to do it's work). They have an issue 
logged for this: https://github.com/ebekker/ACMESharp/issues/119

Thanks again,

Chris

**Comment by webprofusion-chrisc** [comment]
Here is some further information on how to resolve the X1 certificate chain issue:https://community.letsencrypt.org/t/iis-8-5-building-incorrect-chain-with-lets-encrypt-authority-x3/13320/82
