### ISSUE TITLE
Error upon starting Certify

### ISSUE THREAD

**Issue by AFAde** [webprofusion/Certify#10]
Hi, 
I successfully installed Certify on Windows Server 2008 R2. Upon starting the application, an error dialog pops up, here below the details

> 
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.InvalidOperationException: Vault has not been initialized
>    at ACMESharp.Vault.Providers.LocalDiskVault.LoadVault(Boolean required)
>    at Certify.VaultManager.LoadVaultFromFile()
>    at Certify.VaultManager..ctor(String vaultFolderPath, String vaultFilename)
>    at Certify.MainForm.MainForm_Shown(Object sender, EventArgs e)
>    at System.Windows.Forms.Form.OnShown(EventArgs e)
>    at System.Windows.Forms.Form.CallShownEvent()
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> Certify
>     Assembly Version: 1.0.0.0
>     Win32 Version: 0.9.85
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/Certify.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Net.Http
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 8.0.0.0
>     Win32 Version: 8.0.2.19309
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/Newtonsoft.Json.DLL
> ----------------------------------------
> ACMESharp.Vault
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.Vault.DLL
> ----------------------------------------
> Microsoft.ApplicationInsights
>     Assembly Version: 1.2.3.490
>     Win32 Version: 1.2.3.490
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/Microsoft.ApplicationInsights.DLL
> ----------------------------------------
> System.Xml.Linq
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
> ----------------------------------------
> System.Management.Automation
>     Assembly Version: 1.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management.Automation/1.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
> ----------------------------------------
> System.Management
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
> ----------------------------------------
> System.DirectoryServices
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> Microsoft.PowerShell.Commands.Diagnostics
>     Assembly Version: 1.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll
> ----------------------------------------
> System.Configuration.Install
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
> ----------------------------------------
> Microsoft.WSMan.Management
>     Assembly Version: 1.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.WSMan.Management/1.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll
> ----------------------------------------
> Microsoft.WSMan.Runtime
>     Assembly Version: 1.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.WSMan.Runtime/1.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Runtime.dll
> ----------------------------------------
> System.Transactions
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
> ----------------------------------------
> Microsoft.PowerShell.Commands.Utility
>     Assembly Version: 1.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll
> ----------------------------------------
> Microsoft.PowerShell.ConsoleHost
>     Assembly Version: 1.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll
> ----------------------------------------
> Microsoft.PowerShell.Commands.Management
>     Assembly Version: 1.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll
> ----------------------------------------
> System.ServiceProcess
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
> ----------------------------------------
> Microsoft.PowerShell.Security
>     Assembly Version: 1.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.Security/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll
> ----------------------------------------
> ACMESharp.POSH
>     Assembly Version: 0.8.1.0
>     Win32 Version: 0.8.1.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.POSH.DLL
> ----------------------------------------
> ACMESharp
>     Assembly Version: 0.8.1.0
>     Win32 Version: 0.8.1.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.DLL
> ----------------------------------------
> System.ComponentModel.Composition
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
> ----------------------------------------
> ACMESharp.PKI.Providers.OpenSslLib32
>     Assembly Version: 0.8.1.0
>     Win32 Version: 0.8.1.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.PKI.Providers.OpenSslLib32.DLL
> ----------------------------------------
> ACMESharp.PKI.Providers.OpenSslLib64
>     Assembly Version: 0.8.1.0
>     Win32 Version: 0.8.1.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.PKI.Providers.OpenSslLib64.DLL
> ----------------------------------------
> AWSSDK.Core
>     Assembly Version: 3.1.0.0
>     Win32 Version: 3.1.1.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.Core.DLL
> ----------------------------------------
> AWSSDK.Route53
>     Assembly Version: 3.1.0.0
>     Win32 Version: 3.1.0.1
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.Route53.DLL
> ----------------------------------------
> AWSSDK.S3
>     Assembly Version: 3.1.0.0
>     Win32 Version: 3.1.2.1
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.S3.DLL
> ----------------------------------------
> ManagedOpenSsl
>     Assembly Version: 0.6.1.0
>     Win32 Version: 0.6.1.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ManagedOpenSsl.DLL
> ----------------------------------------
> Microsoft.Web.Administration
>     Assembly Version: 7.0.0.0
>     Win32 Version: 6.1.7600.16385
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Web.Administration/7.0.0.0__31bf3856ad364e35/Microsoft.Web.Administration.dll
> ----------------------------------------
> MetadataViewProxies_6f45f5a3-b750-4d04-8b1e-b6486ced9e9f
>     Assembly Version: 0.0.0.0
>     Win32 Version: 4.0.30319.34209
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
>

**Comment by webprofusion-chrisc** [comment]
Hi, can you confirm which version of Powershell you have? Powershell V4 or higher is required.

**Comment by Andreyul** [comment]
PS C:\Windows\System32\WindowsPowerShell\v1.0> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  117

**Comment by Andreyul** [comment]
Issue resolved after installing ACMESharp.

**Comment by AFAde** [comment]
Hi,
I can confirm that the issue was the powershell version. After upgrading to the V4 the problem was solved.

Thanks

**Comment by mirsaeedi** [comment]
I Have this issue. I`m running Certify on Windows Server 2008 R2 SP1. I installed Poweshell 4 and ACMESharp. but this issue did not resolve. Can you help me on this issue?
