### ISSUE TITLE
Command Line?

### ISSUE THREAD

**Issue by shoecake** [webprofusion/certify#100]
I have quite a few SSL certs to generate and wondered, is there a command line interface? I can see that data is being stored at C:\ProgramData\ACMESharp\sysVault - does this mean that I could use the powershell project to create the certificates and they would still be manageable in Certify?

**Comment by webprofusion-chrisc** [comment]
You can use the ACMESharp powershell scripts to get new certificates etc but they wouldn't show up in Certify. Certify is doing the work of making the process repeatable (see c:\programdata\certify\) by having the additional concept of Managed Sites, that way renewals can have setting re-applied when bindings are updated. It's quite easy to set up each site (and multiple domains for each site) and once you've done that you shouldn't need to set them up again.

There is a basic CLI (certify.exe) but currently that only runs auto renewals. If you would prefer a CLI for everything there is https://github.com/Lone-Coder/letsencrypt-win-simple but the only thing is common is the use of ACMESharp to talk to Let's Encrypt.

**Comment by shoecake** [comment]
ok, thanks for the info, I took a look at letsencrypt-win-simple and if you create the cert in unattended mode then it doesn't know which IIS site to bind to. Even if I did this bit manually, I am worried what would happen on renewal.

Do you think it would be a big task to create a pull request to extend the command line?  If you give me some pointers I don't mind spending a few days on this.

The other option I thought of is to programmatically generate the manageditems.json file, but that feels like I will be opening a can or worms.

**Comment by webprofusion-chrisc** [comment]
@shoecake well it's there if you want to try! At the very start of the CLI I did envision having an auto setup wizard that would suggest a bunch of migrations to perform then do it but it's too open to variables in each sites configurations. People have some very, very weird IIS site setups.

You'll see the mention of 'Preview Auto Manage' here: https://github.com/webprofusion/certify/blob/master/src/Certify.CLI/Program.cs 

The 'Preview' method here (https://github.com/webprofusion/certify/blob/master/src/Certify.Core/Management/ItemManager.cs) hints at creating a list of Managed Sites, which we would then save if we were happy with them. Note that the bulk of the code should be applicable to the UI as well as the CLI, so if building anything the majority of the code should not be in the CLI (program.cs).

Also relevant as an example is the import from the old version of Certify to the new one: https://github.com/webprofusion/certify/blob/master/src/Cert9/ify.Core/Management/CertifyManager.cs#L426

While you can generate the managed sites, each site generally(?) then would need a bit of tweaking to make sure it was properly configured.

**Comment by shoecake** [comment]
OK, it may be a week or so before I can take a proper look. My idea was to use the command line to generate the "Managed Sites" in the json file and then a button in the GUI to submit all outstanding requests. 

Rather than separate parameters on the command line, how do you feel about a csv file with the data to import. This could then be specified on the command line, or imported via the GUI.

**Comment by webprofusion-chrisc** [comment]
Yep, CSV -like import sounds OK, maybe values could be semicolon delimited, prefixed with variable like `domain:test.com; san:s1.test,com,s1.test.com; siteId:3; ip:1.2.3.4;sni:false;` ? I'm just thinking of changes to the format later.

**Comment by webprofusion-chrisc** [comment]
Further to this, you might want to wait - I want to add a UI feature to scan all IIS sites and offer to add them as managed sites anyway. That combined with a way to scan and validate the configuration for all sites (i.e report all domains ready/not ready to validate with Let's Encrypt) could be the easy way to set up large collections of sites.

**Comment by shoecake** [comment]
That sounds like a much easier way from the users point of view. 

In my case, I have a relatively few number of IIS sites, but each one has a lot of domains in. These sites are CMS's so the individual domains are not necessarily related to each other so I don’t want to create one SAN certificate for all of them. Rather I would want to import so a certificate was created on a per domain basis, not a per site basis. (grouping of www.domain.com and domain.com together would be nice but a big deal).

**Comment by webprofusion-chrisc** [comment]
Another user suggested having a filter on the SAN/domain list in the site settings (they had many subdomains on one site and hit the 100 SAN name per cert limit ), would a filter in the primary/san domain part of the UI when be useful to you?

**Comment by shoecake** [comment]
funny, I was already thinking of this and have just added another feature request for this.
