### ISSUE TITLE
[Feature] Improve the managed certificates list to better organise a large list of sites/domains

### ISSUE THREAD

**Issue by shoecake** [webprofusion/certify#101]
At the moment, all managed sites/domains are in one big list. This will get unwieldy when a large number of sites or domains are to be managed.

I propose adding some searching/filtering/sorting features to this list. E.g.

- Free text search for name/site name, domain name
- Filter by a specific site
- Sort by name/site name/domain name

**Comment by Marcus-L** [comment]
This feature will be in the next release, please see #155 for details
