### ISSUE TITLE
Avast blocks Certify.UI.exe

### ISSUE THREAD

**Issue by ybbarng** [webprofusion/certify#102]
Hello,

I want to use this program to use Let's Encrypt certification on Windows 10, but Avast, a free anti-virus program, blocks Certify.UI.exe.

Is it safe for using this program?

**Comment by webprofusion-chrisc** [comment]
Hi, we do not yet Code Sign the Certify.UI.exe executable although that's likely to happen soon. This can result in various security warnings both from windows and from AV products. 

Yes it's safe, but ultimately you need to exercise caution with any software downloaded from the internet, so the decision is yours.

**Comment by ybbarng** [comment]
Thank you for your fast reply! I understand why it was happened.

**Comment by webprofusion-chrisc** [comment]
Closing. We now sign the UI installer and executables to avoid unnecessary security warnings.
