### ISSUE TITLE
Feature: Option to Export certificate into different formats

### ISSUE THREAD

**Issue by tggman** [webprofusion/certify#105]
I have a need to export the pfx cert file created by Certify into a pem files.  I tried to use the OpenSSL command pkcs12 to perform the export but it’s asking for a password.  What is that password?  Here’s an example command that I tried to use:  
OpenSSL pkcs12 -in cert_identdxxxxxxx-all.pfx -out cert-viacertify.pem -nodes 

Also, it sure would be great if Certify gave me the option to export my pfx into the various PEM files.

**Comment by webprofusion-chrisc** [comment]
HI Tom, have replied by email but currently none/blank password and the export feature is a great idea.

**Comment by webprofusion-chrisc** [comment]
This is now theoretically possible using scripting hooks #148 

More info can be found here:
https://github.com/webprofusion/certify/blob/master/docs/Request%20Script%20Hooks.md

**Comment by ThunderbyteComputer** [comment]
It would be really great if there is a built in option to export a PKCS12 Certificate (with password if possible). As there are many tools that require this format (most notably Apache)

Sure right now ist possible to install CygWin for OpenSSL (or pre compiled Binaries) and create a PKCS12 (.p12) file from the .pfx

This would make the already great tool you have even better

**Comment by webprofusion-chrisc** [comment]
@ThunderbyteComputer thanks, yes this would be a great option. 

I'd like to in the future allow users to choose from a selection of pre-built configurable outputs/actions when a renewal has completed. Things like activating a certificate in MS Exchange, Copying it, Exporting it etc - there's so many uses for the certificates once they've been generated it's hard to do everything and not clutter the UI. Ideally users could submit new 'recipes'/extensions for others to choose from and use.

**Comment by webprofusion-chrisc** [comment]
Have added a new issue for the pre-built extensions (most likely PowerShell scripts) idea: https://github.com/webprofusion/certify/issues/245

**Comment by webprofusion-chrisc** [comment]
Implemented via Deployment Tasks in v5.
