### ISSUE TITLE
Whether to increase the payment of Chinese users Alipay

### ISSUE THREAD

**Issue by qzwl** [webprofusion/certify#111]
Whether to increase the payment of Chinese users Alipay

**Comment by webprofusion-chrisc** [comment]
So do you we should support payment via Alipay? Are they the best/most popular payment provider for Chinese users?

**Comment by webprofusion-chrisc** [comment]
I'm planning to add support for Stripe and they apparently let people pay with Alipay, so that should be ok.

**Comment by qzwl** [comment]
https://global.alipay.com/   Alipay is China's largest payment platform, as well as for Chinese users $ 49.99 USD a little expensive
