### ISSUE TITLE
Microsoft RSA SChannel Cryptographic Provider

### ISSUE THREAD

**Issue by joerflyer** [webprofusion/certify#112]
Trying to secure an Exchange server with this - any chance of adding a check box for the legacy standard?  At the minute the cert obtains and deploys but breaks OWA and ECP due to the cert being signed in the new fashion.

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for reporting. Do you have any additional supporting information you could point me to on this? Perhaps an MSDN article etc - I don't know much about Exchange admin myself but is it a certain version that's affected or just any one? When you say it break where and what error messages do you get?

**Comment by joerflyer** [comment]
Wow, that was a quick reply!  Thanks.

I don’t either; I’m relatively new to it all but from what I gather, certs are now signed in a different way to the way they used to be, with Exchange 2013 not supporting the new cert type.

Link here<https://social.technet.microsoft.com/Forums/office/en-US/a9efd351-032d-47d1-8b68-2ad00f11bcc8/unable-to-access-ecpowa?forum=exchangesvrdeploy&prof=required> for more info, I think there may be a switch which allows the LE CA to accept a legacy CSR.  I’m trying to find another link for a page I’ve viewed in the past as well, as I had problems requesting a compatible cert from the GoDaddy CA also.

The link above describes exactly the issue I have; a login loop on ECP and OWA when the new cert is used.  Switch back to a self-signed cert and it works fine.

Thanks.

**Comment by webprofusion-chrisc** [comment]
You may have more luck with a command line tool so you can get low level access to the certificate keys, lots of people use letsencrypt-win-simple for exchange/owa type setups: https://github.com/Lone-Coder/letsencrypt-win-simple/wiki/Create-a-SAN-certificate-for-Microsoft-Exchange-2016,-2013-&-2010

**Comment by joerflyer** [comment]
I’ll take a look at that; many thanks for the link.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by GLotsapot** [comment]
I too would like to see this feature. Although Certify is absolutely amazing, it does indeed break the OWA and ECP in Exchange 2013 (not the fault of Certify at all though). The issue is that when you log into OWA the Exchange Server encrypts the cookie, but when the client tries to use it for authentication it is unable to and just kicks you back to the login screen without an error. This is primarily due to the OWA and ECP only supporting Microsoft RSA SChannel Cryptographic Provider and not Microsoft Software Key Storage Provider. Even at the latest CU, the issue persists.

**Comment by GLotsapot** [comment]
Oh, and I can confirm as well that @webprofusion-chrisc is correct and the letsencrypt-win-simple does store using the RSA SChannel Cryptographic Provider and works without issues.

**Comment by Marcus-L** [comment]
Automatically converting the certificate to CSP storage for Exchange is possible using a post-request script in the new version ([2.0.13](https://certifytheweb.com/home/download)). Please check [this docs page](https://github.com/webprofusion/certify/blob/master/docs/Request%20Script%20Hooks.md#example-convert-cng-certificate-storage-to-csp-for-exchange-2013) for a 7-line powershell example.

**Comment by tomchadwin** [comment]
Where does this stand with v4 beta? I've got Exchange 2010, but the sample script is for Exchange 2013+. Does anyone have a sample 2010 script?

**Comment by webprofusion-chrisc** [comment]
@tomchadwin I don't know much about Exchange myself but it looks like you could use the script at 
https://docs.certifytheweb.com/docs/script-hooks#example-convert-cng-certificate-storage-to-csp-for-exchange-2013
to convert your certificate.

Then you need to enable that cert in Exchange 2010. I believe 2010 requires a .cer fil, so you may need to convert it: https://stackoverflow.com/questions/403174/convert-pfx-to-cer

Enabling the final certificate:
https://support.comodo.com/index.php?/Knowledgebase/Article/View/712/37/certificate-installation-exchange-2010-powershell

I'll be looking at options to export the renewed certificate in a variety of formats shortly.
