### ISSUE TITLE
Register New Contact should reset the existing contact

### ISSUE THREAD

**Issue by Rokys** [webprofusion/certify#113]
I want to change my primary contact email to a new one, but after changing the primary contact email, ticking the Agree box, when I request a new certificate, it errors to:
> {
> "type": "urn:acme:error:unauthorized",
> "detail": "Must agree to subscriber agreement before any further actions",
> "status": 403
> }

If I change the primary contact to the old one, the process is completed without errors.

**Comment by webprofusion-chrisc** [comment]
Thanks for reporting this. A workaround is for you to remove the C:\ProgramData\ACMESharp\sysVault (or rename it), and start the app again, then enter the correct contact.

**Comment by potnoodles** [comment]
Hi , I also came across this and the workaround worked here.
thanks

**Comment by webprofusion-chrisc** [comment]
This is now resolved in the latest development builds (3.x)
