### ISSUE TITLE
Site with 10,000 hostname bindings results in very slow load time

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#114]
If there are several thousand site bindings the UI is slow to load. Ideally we should show loading progress and load IIS settings async if there are a lot of sites or a lot of bindings.

**Comment by Marcus-L** [comment]
Is this a real issue for someone? Not sure how you would test this other than creating thousands of bindings.

**Comment by webprofusion-chrisc** [comment]
Yes there is a user affected by this, which surprised me too. Basically it's a single site where each user gets a subdomain with their username. This issue was more around having some sort of async query of sites. It could tie in well with the idea of having a core management  service that the UI talks to. I have an integration test which scripts random domain bindings to replicate this, but you coukd use powershell. They don't have to be real domains, it's just a stress test of the query mechanism against IIS.

**Comment by laberator** [comment]
I can also confirm that we have this issue, although not thousands of bindings but several hundreds  of them. The system grinds to a halt whenever the UI is launched, and stays at 100% CPU-usage for quite some time and then goes down again. Same effect whenever the renewal process is launched.

**Comment by webprofusion-chrisc** [comment]
This is addressed in the latest development versions. UI now makes async queries to IIS via the background service and shows a progress indicator.
