### ISSUE TITLE
DNS Challenge Support

### ISSUE THREAD

**Issue by zman442** [webprofusion/certify#115]
We cannot support opening port 80 since LetsEncrypt will not publish their IPs for white listing.  Please provide an option for DNS challenge support.  It does not need to be automatic with APIs and TXT record creation as with some of the tools but at least give the option for manual updates and confirmation to resume the cert request within the tool once the TXT DNS token record has been created.

**Comment by webprofusion-chrisc** [comment]
Definitely on the To Do list - the main obstacle is that most people will want some automation for this to be considered useful. Manual creation of DNS entries every 60 days or so would obviously be the worst case.

**Comment by zman442** [comment]
Thanks for the response.  Updating DNS once every 60 days is far less troublesome than opening firewalls on port 80 where it is restricted by regulations or security requirements.  Many DNS providers have some sort of API to automate things but picking which one(s) to support could be troublesome.  Perhaps adding a way to program the methods ourselves based on the DNS provider REST API documentation but standardizing on the values supplied by certify could make things easier to implement.

**Comment by Marcus-L** [comment]
What DNS server/provider are you using? 

Maybe another script hook could be added which would be passed the DNS challenge information so you could handle updating the DNS automatically.

**Comment by cpu** [comment]
> We cannot support opening port 80 since LetsEncrypt will not publish their IPs for white listing. Please provide an option for DNS challenge support.

The TLS-SNI-01 challenge type might be easier to implement than DNS-01 in an automatable way. TLS-SNI-01 challenge requests arrive on port 443. If the issue is strictly the use of port 80 for the HTTP-01 challenge request then it might be another option to evaluate.

**Comment by webprofusion-chrisc** [comment]
Notes on other APIs which provide feature to adminster multiple DNS providers (ideally we would find a c#/.net one):

**Comment by webprofusion-chrisc** [comment]
https://github.com/Netflix/denominator

**Comment by webprofusion-chrisc** [comment]
There is potential scope for either bundling a python interpreter or using IronPython to make use of the above libraries. https://github.com/IronLanguages/ironpython2

**Comment by webprofusion-chrisc** [comment]
Implemented in next release v4 #270 - currently supporting Azure, AWS Route 53 and Cloudflare. Other providers will be added in the 4.x timeline including (very possibly) anything supported by apache libcloud.
