### ISSUE TITLE
Error: No Registrations Found

### ISSUE THREAD

**Issue by jfeilders** [webprofusion/certify#116]
I keep getting this error when I click on "Request Certificate"

(Win 2012 R2 Data Centre)

**Comment by webprofusion-chrisc** [comment]
A 'registration' is your contact details (as registered with Lets Encrypt). Can you try creating a new contact on the Settings tab and requesting again. If that doesn't work, try renaming the C:\ProgramData\ACMESharp\sysVault folder and run the app again, this should recreate the 'vault' and prompt you to register a contact again.

**Comment by jfeilders** [comment]
I did that. It created a new sysVault folder.

But same error.

“Request failed – No Registrations Found”

**Comment by Marcus-L** [comment]
I tried to reproduce this error on a few different configurations (Win 2012R2, Win 2008R2, Win10) but could not. If you are still experiencing this issue please try again with the latest version of Certify v2.0.13 and if you run into problems if you could create another issue with instructions on how to reproduce the error that would be very helpful.
