### ISSUE TITLE
Implement UI for certificate details

### ISSUE THREAD

**Issue by seanvree** [webprofusion/certify#117]
am I missing something or can I not view the cert within the ui?    I don't even see an option as to where the cert is stored on the box?

**Comment by webprofusion-chrisc** [comment]
Nope, there is currently no UI for viewing certificates or certificate info.

**Comment by webprofusion-chrisc** [comment]
Now what info do people actually need from cert details? Path to the pfx etc? Something tells me we should be using the built in windows cert info tools for any in-depth view of cert info.

**Comment by seanvree** [comment]
@webprofusion-chrisc  - 

AT LEAST it's location on the box, right?

non-secure data that would be good to know that's surprisingly not on the ui:


- Friendly name of the cert!
- location of where the cert files are located on the box
- Last update last renewal completed, next scheduled renewal


Would be good but not a deal killer:
Creation date of cert
Expiration


Would be super good, but may cause some security risks:
Hash
thumbprint
If the corresponding key is present. 




I love the UI, it's been long time coming, but it really needs some basic stuff on there.  I mean same stuff you get when you inspect a website and check out the security details in any modern browser.



Thanks for the work!

**Comment by Marcus-L** [comment]
A shortcut to the certificate PFX location and the certificate details was implemented in the UI in v2.0.9, on the "Info" tab:

![screenshot_092517_102214_am](https://user-images.githubusercontent.com/1369184/30816360-66f0e8a4-a1db-11e7-859a-aac75cf72b01.jpg)

**Comment by seanvree** [comment]
@Marcus-L  awesome brother!
