### ISSUE TITLE
Save settings under advanced tab doesn't work

### ISSUE THREAD

**Issue by matthewfair** [webprofusion/certify#118]
Windows 2008 R2
switching to the advanced tab in any managed site and changing a setting: uncheck "perform web application auto config" and then click save button.  Checkbox just reverts back to being checked.  If I change the setting "use specific IP/Port bindings". it changes the setting for all managed sites rather than the one selected managed site.

**Comment by webprofusion-chrisc** [comment]
Thanks for reporting this. See also #120. I'll check the 'use  Specific IP/Port bindings' part as I can't see why that would affect multiple things - I assume you mean it changes the certify Managed Site settings and not the bindings in IIS.

**Comment by matthewfair** [comment]
You are correct it changes the certify managed site settings for multiple sites and not the bindings in IIS.
