### ISSUE TITLE
Add option for custom web.config

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#119]
The default web.config used in auto configuration may sometime be incompatible with the parent application. 

Having the option to provide a custom web.config (per site, or for all sites) for extension-less file handling would enable users who have more advanced requirements.

**Comment by leifnel** [comment]
Add a "remove" for items which may conflict.

   <staticContent>
	  <remove fileExtension="." />
      <mimeMap fileExtension="." mimeType="text/json" />
    </staticContent>

**Comment by webprofusion-chrisc** [comment]
Rather than remove I wonder if we could just clear all handlers and all settings? Like: https://msdn.microsoft.com/en-us/library/ms228328(v=vs.100).aspx

We need the web.config to provide very specific functionality:
- Allow anonymous access to all (Let's Encrypt can't perform any authentication)
- Allow files to have no extension (challenge response files are text files but have no extension)
- Avoid conflict with previously set handlers/settings in the parent application (if any)

-

**Comment by DavidDeSloovere** [comment]
What about only creating a web.config if it doesn't exist yet. That way we can add our own web.config in the folder (source control, deployment, ..)?

**Comment by webprofusion-chrisc** [comment]
Yes the intended functionality currently is to only replace the web.config if our check for extension-less file support fails. However ideally we would find a universal solution as the .well-known/acme-challenge folder does not have another purpose (by definition), the issue is more if parent app web.config handlers prevent the folder content being accessed altogether.

**Comment by ebekker** [comment]
Something like [this](https://github.com/ebekker/ACMESharp/blob/master/ACMESharp/ACMESharp.Providers.IIS/IisChallengeHandler-WebConfig)?

**Comment by webprofusion-chrisc** [comment]
@ebekker lol, yeah something like that. From memory there's a couple of versions of wildcard mapping required to be compatible with different IIS versions but I never did narrow down the exact versions.

**Comment by webprofusion-chrisc** [comment]
Here is a further suggested variation, including authorization:
`
<?xml version="1.0" encoding="UTF-8"?>

<configuration>

  <system.webServer>

    <validation validateIntegratedModeConfiguration="false" />

    <staticContent>

     <remove fileExtension="." />

      <mimeMap fileExtension="." mimeType="text/json" />

    </staticContent>

  </system.webServer>

  <system.web>

    <authorization>

      <allow users="*" />

    </authorization>

  </system.web>

</configuration>`

**Comment by webprofusion-chrisc** [comment]
Ok, so this has come up again so the likelihood of find one (or two) configs that work for everyone is probably zero.

Suggested/Planned feature:
- Auto config as usual by default
- Provide a list of alternative web.configs and let user optionally select a default
- Let use add custom web.config (named) which they can also then optionally select as default
- Let each managedsite optionally override the default choice for another one

Some users are managing thousands of sites per server and have (relatively) few problems, others are not so lucky.

**Comment by PaulHuizer** [comment]
I had problem with default web.config. The reason was that the applicationhost.config contained:
`<section name="handlers" overrideModeDefault="Deny" />`
The handlers section in the web.config therefore was not allowed with the result that the challenge failed.
In my case the solutions were: 
Change applicationhost.config line to:
`<section name="handlers" overrideModeDefault="Allow" />`
Or remove the handlers setting from the web.config in acme-challenge folder.

**Comment by webprofusion-chrisc** [comment]
Thanks @PaulHuizer - we probably should try to detect that situation and inform the user.

**Comment by webprofusion-chrisc** [comment]
We should also figure out the last working web.config variant and use that by default, only trying other combinations if that one fails.

**Comment by webprofusion-chrisc** [comment]
Closing. This is no longer relevant as our builtin http challenge server is the default behaviour instead of modifying web.config.
