### ISSUE TITLE
Unchecking perform web application auto config has no effect

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#120]
A user has reported that unchecking auto config has no effect and that the app continues to overwrite their custom web.config in the acme-challenge folder.

**Comment by livesoftware** [comment]
Looks like web.config file got changed on only one of the sites so the setting does work but the checkbox doesn't reflect the actual value.   Ended up having some missing port 80 bindings so seems like the stock web.config is working in IIS 8.5

**Comment by Marcus-L** [comment]
The bug overwriting the PerformAutoConfig setting is resolved in #156 and the fix will be included in the next release.

**Comment by hscanlan** [comment]
This is really frustrating. I have a working web site, can serve extensionless files, but as soon as i goto verify, This program creates a new web.config and totally nukes my entire site. I check this box so it doesn't happen, but it doesn't do anything .... help

**Comment by webprofusion-chrisc** [comment]
@hscanlan thanks for reporting, I'm very surprised (and alarmed!) that it affects your entire site - try unchecking both 'Perform challenge response config checks' and 'Perform web application auto config'. Then fix the existing web.config under ./well-known/acme-challenge so you can browse to /.well-known/acme-challenge/configcheck successfully. If that's still being overwritten (which I wouldn't expect at this point), try making your web.config in that folder read-only.
