### ISSUE TITLE
 Consistent issues with Renewal of Certs in IIS with Certify Manager | All sites run off of one cert bug Server

### ISSUE THREAD

**Issue by PlantPoweredProphet** [webprofusion/certify#121]
I have been plagued with an issue since I started using Let's Encrypt. Getting all 9 certificates to run smoothly has been challenging. IIS will choose randomly one of the certs to use for all of the domains. Everything looks perfect inside of IIS. The certs are available and linked correctly but when I go to a browser to visit the site, I get an error saying that it is using the wrong cert. 

www.--------.org uses an invalid security certificate. The certificate is only valid for dev.fullcirclerescue.org Error code: SSL_ERROR_BAD_CERT_DOMAIN

In the past, I have just tried a bunch of different things to get it to work. Usually a server restart and killing IIS and the application pools a few times gets everything to work correctly again. The issue is that today it is not working. Certify is fully updated and I have the paid license. 

I am really hitting my head against the wall. Every 3 months I go through hell with this damn system :(

Also, if I try to change the cert in IIS, it does not acknowledge the change. It is totally stuck on the random cert.

**Comment by PlantPoweredProphet** [comment]
I have been running Certify for almost 2 years now and I have been able to get everything to run good but then when I go to renew my certs every 3 months I randomly run into issues. I think it was last November that I had problems last.

I am using Windows server 2016 dataserver edition on Windows Azure. I had the same issue with Windows 2012 on a dell server before I migrated to Azure.

All 9 domains share the same IP address but that is not a problem. I run and work with a handful of non-profits. These are simple non-profit wordpress websites.

Even after I erase the certificate from the server, the site still is still connected to this single domain. It makes no sense. I also deleted the cert from the IIS cert manager after deleting it from Certify.

**Comment by PlantPoweredProphet** [comment]
And now after 30 minutes of screwing with it, one of my domains has the correct certificate signed and the site is running.

I have restarted IIS countless times, restarted the whole server 4x, deleted certs and recreated them. I have no idea what makes things sort of work.

**Comment by PlantPoweredProphet** [comment]
And now, 10 minutes later,  it is totally fixed. All 9 sites are back up and using their correct certs. The hardest problem with this bug is I never know what I do to fix it. Sometimes renewal works flawlessly, sometimes it does not. Sometimes I can add a new domain into my certify list and other days it breaks all of the sites. I have had identical experiences with both my dell server and this azure server.

I would seriously love to know what causes this horrible bug.

**Comment by webprofusion-chrisc** [comment]
Hi, sorry to hear you're having such trouble. 

If you have one of your sites binding set as a fallback for the IP (so whatever requests that https://<ip-address> will resolve to that site, rather than "All Unassigned") that certificate takes precedence in http.sys when other sites are SNI with the same IP address, that's possibly the issue here?

**Comment by webprofusion-chrisc** [comment]
Can I also check that you're on the latest version of Certify?

**Comment by PlantPoweredProphet** [comment]
Interesting. I have always set the ip addresses for each of the domains. That could be the issue. I have done things this way since I began with IIS many years ago. I never thought it could cause an issue.
