### ISSUE TITLE
App should be aware of Let's Encrypt rate limits

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#123]
Ideally Let's Encrypt would publish their current service rate limits (those documented at https://letsencrypt.org/docs/rate-limits/) as a JSON feed. We would then ideally use this limit information to warn users and to manage the automated renewals process.

**Comment by webhostingnet** [comment]
When throttle limit is reached and I try and renew the only info returned is "Error failed to create certificate order: Failed to begin certificate order."

Can we report the actual error ie. Throttle Limit reached

The info is in the log file, but might be good to move it into the UI for easy status notification.

**Comment by webprofusion-chrisc** [comment]
Closing. Won't fix as currently there is no API for rate limits in ACME.
