### ISSUE TITLE
Configure Auto renewal period/day

### ISSUE THREAD

**Issue by StefanEgo** [webprofusion/certify#125]
The let's encrypt certificate is valid for 3 months. Certify's auto renewal feature seems to renew the certificate on earlier though (maybe retrying on a daily basis?). It'd be beneficial, if one can configure the auto renewal period/date (for instance: once per month, 2 weeks before the certificate becomes outdated, every first Monday in a month, etc.).

The rational for this are cases where the auto-renewal of a certificate also has other implications (in our case we'd need to update the corresponding JIRA/Confluence certificate) which might require manual interactions/work. So not being able to control when the auto renewal takes place might render this whole feature unsuitable in scenarios like these.

**Comment by webprofusion-chrisc** [comment]
Thanks, the next version of Certify has a setting to configure renewal frequency (in days) however you may benefit more from just editing the Windows Scheduled Task that Certify creates when you configure Auto Renewal.

**Comment by StefanEgo** [comment]
Thanks for the suggestion. We certainly will use this for the time being, then.

**Comment by StefanEgo** [comment]
Thanks for adding this directly to Certify. Really useful and works like a charm.
(closing since added --- think it was around 2.0.9 (no guarantee for correctness though))
