### ISSUE TITLE
mail notification upon successful certificate renewal

### ISSUE THREAD

**Issue by StefanEgo** [webprofusion/certify#126]
I understand that Certify is sending a mail upon a failure to renew a certificate. However, we'd also like to retrieve a mail notification, if the certificate was renewed.

The rational to have such a mail is:
- confirmation that the auto renewal feature worked correctly
- notification upon the certificate having been renewed (also for archiving purposes)

Without such a mail atm we have to manually verify on a regular basis that the auto renewal worked fine and didn't break.

**Comment by webprofusion-chrisc** [comment]
Thanks, Certify in fact doesn't yet send a mail on failed renewal - that's a feature intended for the final 2.0 release that's not currently completed.

One of the ideas that I've been bouncing around was that there would be a dashboard you could login to with stats (such as dashboard.certifytheweb.com) and see which sites/domains you are managing and see success/error reports. The benefit of this approach is you may be managing multiple servers and possibly hundreds of domains. This dashboard could optionally send periodic summary reports?

**Comment by StefanEgo** [comment]
Thanks for the quick reply.

Yes, that would be fine for us as well, if that summary report would be sent directly upon a successful renewal.
Bare in mind that we'd basically use it in combination with setting the task scheduler to renew the certificate once per month (every 1st Monday in a month actually). We'd then expect to have a mail received on that day and if it's missing, would have to check why. Hence a periodic summary report alone might not do the trick, unless it can be configured to be sent directly upon a renewal was done/attempted.

**Comment by Marcus-L** [comment]
@webprofusion-chrisc, the dashboard sounds great! I'd love to see that.

@StefanEgo - in the meantime you could use a post-request powershell script to email you the renewal status. The next release will probably have this functionality (from PR #148).

**Comment by Marcus-L** [comment]
Would be nice to have a webhook notification as well to integrate with other APIs. One example would be to have the notifications be posted into a Slack channel via their Web API

**Comment by webprofusion-chrisc** [comment]
@Marcus-L  For this one I'd eventually like the dashboard API to do the actual sending of notifications, that way it can be routed through the mail API of our choice without shipping credentials. What were you planning, a call to a users own custom api?

**Comment by Marcus-L** [comment]
I was thinking webhook (customizable verb/payload) plus basic smtp (server/port/ssl), checkboxes for notifications on success/error /both. 

If you'd rather take this one that's fine w/me. Or I could just do the webhook (I'd do it to support my personal slack channel) and leave the email part to you, just lmk what you want.

**Comment by webprofusion-chrisc** [comment]
Ok, you should go with your custom web hook to begin with. I don't want to send smtp out from the client as it also involves people having to configure firewall rules etc, when we could more simply post via https  to the dashboard api (when it exists, it's not a big deal to get that started I just haven't done it yet, and the mail send volume could be big enough to exceed free plans etc.). 

The idea was that the status of the renewal would be (optionally) sent to the dashboard, then the dashboard would send notifications if that was in the users pref for that dashboard account. Some people are managing more than 20 servers, so centralising the management of it is eventually important.

**Comment by Marcus-L** [comment]
only the webhook part was implemented, so I'm putting this back on the pile

**Comment by webprofusion-chrisc** [comment]
This feature is superseded by the dashboard, which would also be in charge of success reporting.

**Comment by StefanEgo** [comment]
K, understandable and even for smaller companies an achievable price tag of ~$35 per year. Thanks for the great work.

**Comment by webprofusion-chrisc** [comment]
@StefanEgo the dashboard reporting is free but we still don't give you the option of receiving success notifications instead we just report to the dashboard and send only failure notifications (and manual dns prompts etc).

**Comment by StefanEgo** [comment]
Oh I wasn't aware it's free. To me when clicking on the "View Dashboard" button in the client I ended up on the page to sign in: https://certifytheweb.com/profile

When clicking on the Sign in button on that page you land on the actual sign in page with the "Create Account" link stating: "Need to create a new account? Create Account": https://certifytheweb.com/profile/signin

Clicking the "Create Account" link I end up on the register page which states at the top that the SSL manager being free to up to 5 managed sites, but then only shows links to purchase either the professional or Enterprise licences: https://certifytheweb.com/register#reg-form

This (at least to me) made the impression that the dashboard is a paid service only. The fact that it's also available for free would be if that last register page would at least contain a link to create a free account (maybe with a box stating: "Free [...] limited for up to 5 managed services, no support via EMail, etc.").
From a business point of view I could understand if you want to keep things the way they are, just mentioning that feedback here in case it wasn't so obvious to you that someone might get things wrong.

With regards to the mail notifications upon successful renewals: Would still be great if that could be added as a feature to the dashboard eventually. I understand this is unreasonable for larger companies, but for small companies with only 1 or 2 pages, it's the easiest way to ease an admin's mind if he gets the renewal messages once per month since that's the confirmation that everything is still working and no manual checking is required.
