### ISSUE TITLE
Ignore * on IIS

### ISSUE THREAD

**Issue by jLynx** [webprofusion/certify#128]
On IIS I have a site setup to accept any domain which you use * for. Can you have Certify ignore * records? Because at the moment if it is selected it will just fail.

**Comment by webprofusion-chrisc** [comment]
Default bindings (Hostname: blank, IP:*) are a work in progress currently. Sometime they are required as people want to request a certificate for the domains they resolve to but they don't actually want to set the domain in the binding (so Certify doesn't know about that domain and can't request a certificate). 

We should ignore these by default and only action them if alt domains have been specified.

**Comment by webprofusion-chrisc** [comment]
Support for manual hostnames and flexiblity around binding updates will be included in the next release (#270)
