### ISSUE TITLE
Issue with Configure Auto Renew when using domain credentials

### ISSUE THREAD

**Issue by wb6vpm** [webprofusion/certify#130]
I am logged into my server as a domain administrator (DOMAIN\helpdesk). I am putting the same credentials into the application. When configuring auto-renew, the pop-up window asks for admin credentials in domain\username format, however, when you enter the information in that format, it keeps saying that the task could not be created. However, if you just put the username, it successfully accepts it and creates the task.

**Comment by webprofusion-chrisc** [comment]
This is no longer required as the default renewal runs as a background service under Local System.
