### ISSUE TITLE
License 2.0

### ISSUE THREAD

**Issue by Niko9911** [webprofusion/certify#131]
Because I host personal and our gaming community sites on Windows I do need now buy license????

Or I just stick with my version 0.98?

**Comment by webprofusion-chrisc** [comment]
The free version has a limit of 5 different managed IIS websites, each of which can have many associated domains. The idea is that if you are running your own windows server hosting many websites with many domains then you're probably running a business.

**Comment by Niko9911** [comment]
"Probably"

Yeh, I would like run business, but my SLA is not enought for that :+1: Also I'm mainly running only reverse proxys so... that's why I have 9 sites running IIS

This is not a good way to deduce who is running business, who is just hosting for own purposes / for non-profit usage!

**Comment by webprofusion-chrisc** [comment]
Sorry, this is just a restriction of the software's revenue model. You could possibly stick to the old version or use one of other other free command line apps/tools.
