### ISSUE TITLE
Bind to specific port does not work

### ISSUE THREAD

**Issue by stibra** [webprofusion/certify#136]
When configured with "Bind to specific port" it shows error when requesting certificate and message to check default url without port specified. The web site is available on the port and check is ok via browser.

**Comment by webprofusion-chrisc** [comment]
This option is for the final SSL binding, not the http binding of your site - only https bindings on port 80 are currently supported as Let's Encrypt will attempt to access your site via http on that port.

**Comment by webprofusion-chrisc** [comment]
The new version includes updates to how binding settings are configured. Please try it out. https://certifytheweb.com/
