### ISSUE TITLE
Non English characters not supported 

### ISSUE THREAD

**Issue by jLynx** [webprofusion/certify#140]
I have a few domains with non English characters in them such as "ü" and "ö". When I try to fetch a SSL cert for it I get this error. Are you able to fix this or is there a way around this?

![image](https://user-images.githubusercontent.com/4393979/29253445-3c8e6ec2-80d1-11e7-8a29-c21bdc25af7c.png)

Thanks

**Comment by webprofusion-chrisc** [comment]
Thanks, will investigate.  In the meantime your domain will have an ascii version (we have to convert to ascii to request certs from Lets Encrypt anyway), you could add a binding to the ascii version and request that cert?

**Comment by webprofusion-chrisc** [comment]
Fixed in next release v4.
