### ISSUE TITLE
 Too many pending authorizations 

### ISSUE THREAD

**Issue by kemstewa** [webprofusion/certify#141]
![dc6d854319f9a29c858e27e181cf36a872982682](https://user-images.githubusercontent.com/31046522/29330956-e1ce9d88-81c8-11e7-9e79-e621944f4e60.png)

How do I resolve this? we are using Certify SSL certificate management with IIS and have maybe 15+ domains using it.

It’s been close to 10 days since this error popped up, we saw it on the 5th. I’m not sure how to clear pending authorizations.

I'm having trouble even starting to solve this since I can't locate the Certify logs.

**Comment by webprofusion-chrisc** [comment]
@kemstewa have emailed for further info, your authorizations are most likely failing because Let's Encrypt can't access your site properly. We can narrow this down over email.
