### ISSUE TITLE
Crash when running from the command line.

### ISSUE THREAD

**Issue by Absoblogginlutely** [webprofusion/certify#142]
I was wondering what would happen if I attempt to run the renewal in advance of the 90 day window.
I checked the scheduled task and the last run result is 0xc0000374
When I run certify.exe from the command line I get certify.cli has stopped working with a crash report as below.
C:\Program Files (x86)\Certify>certify renew
Certify SSL Manager - CLI v1.0.0
For more information see https://certifytheweb.com

Let's Encrypt ACME API: https://acme-v01.api.letsencrypt.org/
ACMESharp Vault: C:\ProgramData\ACMESharp\sysVault

Performing Auto Renewals..

C:\Program Files (x86)\Certify>

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Certify.exe
  Application Version:	2.0.0.0
  Application Timestamp:	5922c58c
  Fault Module Name:	StackHash_82b4
  Fault Module Version:	6.2.9200.21941
  Fault Module Timestamp:	5792e533
  Exception Code:	c0000374
  Exception Offset:	PCH_01_FROM_ntdll+0x000302AC
  OS Version:	6.2.9200.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	82b4
  Additional Information 2:	82b4cc6b08aa9158c57882c5d61dc9a2
  Additional Information 3:	36b5
  Additional Information 4:	36b5543151bfc2880620053575c8d3f2
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Certify.exe
  Application Version:	2.0.0.0
  Application Timestamp:	5922c58c
  Fault Module Name:	StackHash_82b4
  Fault Module Version:	6.2.9200.21941
  Fault Module Timestamp:	5792e533
  Exception Code:	c0000374
  Exception Offset:	PCH_01_FROM_ntdll+0x000302AC
  OS Version:	6.2.9200.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	82b4
  Additional Information 2:	82b4cc6b08aa9158c57882c5d61dc9a2
  Additional Information 3:	36b5
  Additional Information 4:	36b5543151bfc2880620053575c8d3f2

Log file in programdata has the following (snipped)
2017-08-25 16:07:09.511 +00:00 [Information] Beginning Certificate Request Process: le.helsby.net
2017-08-25 16:07:09.751 +00:00 [Information] Attempting Domain Validation: le.helsby.net

Machine is a 2012 virtual server running in azure purely to test this..net 4.7 installed.
Nothing obvious in the acmesharp directory.

**Comment by webprofusion-chrisc** [comment]
Thanks, the only time I've seend the CLI crash before was to do with previous settings left over from the old version of Certify (0.9.8). Clearing the settings from local app data seemed to fix that.

Note that if you are running manually you also need to be running the command prompt as Administrator, otherwise certain things won't work (like updating IIS bindings) and that could be another reason for a crash.

**Comment by Absoblogginlutely** [comment]
Pretty sure that I ran this on an elevated command prompt last time, but just to be safe I ran it again today.
I did get a crash again on the machine today, but I did get extra information showing up in the dos prompt.

C:\Program Files (x86)\Certify>certify renew
Certify SSL Manager - CLI v1.0.0
For more information see https://certifytheweb.com

Let's Encrypt ACME API: https://acme-v01.api.letsencrypt.org/
ACMESharp Vault: C:\ProgramData\ACMESharp\sysVault


Performing Auto Renewals..

== Manual Challenge Handler - HTTP ==
  * Handle Time:      [8/29/2017 4:12:06 PM]
  * Challenge Token:  [PLsQoOhe2NKX7-ekM8tYDQOnoB2jihe_snippedhere_5Qy8]
To complete this Challenge please create a new file
under the server that is responding to the hostname
and path given with the following characteristics:
  * HTTP URL:     [http://le.helsby.net/.well-known/acme-challenge/PLsQoOhe2NKX7
-ekM8tYDQOnoB2jisnippedhere5Qy8]
  * File Path:    [.well-known/acme-challenge/PLsQoOhe2NKX7-ekM8tYDQOnoB2jisnipperhere5Qy8]
  * File Content: [PLsQoOhe2NKX7-ekM8tYDQOnoB2jihe78buT0cK5Qy8.CVCC16oQiZJlvomiQ
YLDdETbs2snippedhereyd-NRE]
  * MIME Type:    [text/plain]
------------------------------------

When I tried running through the Get Certificate process in the gui I got a message that too many certificates were already issued for exact set of domains.
This would be as expected as there is already a domain there and the cert has not expired yet. Not sure if this issue is related or not? I would expect that running a renewal of a cert that is not ready yet would fail gracefully though.

**Comment by webprofusion-chrisc** [comment]
Hi, there's something odd about your setup here. If you manually hit request certificate in the UI it will go ahead and try to get a new certifcate regardless of how old your current one is - it's not there to argue with you :)

The Certify CLI and Auto Renewal task (current version anyway) will check when it was last renewed and only attempt to renew if it was at least 14 days since last renewal - note that it doesn't check the cert for this, it stores it in c:\programdata\certify\manageditems.json 

In order to request too many certificates you'd have to do it 20 times in a week (see https://letsencrypt.org/docs/rate-limits/). 

If you change your admin password after configuring the Auto Renew task, remember to reconfigure the task.

**Comment by Absoblogginlutely** [comment]
Just an update as the certs are due for renewal today.
The cert was still failing and I get the attached error/output when running the task manually.
The process still crashed as per the screenshot.
![screenshot - 10_25_2017 11_15_50 am](https://user-images.githubusercontent.com/21364480/32007051-770445f8-b976-11e7-8a53-ded3ba2cc864.png)
However, running the Gui i was prompted to download a new version - version 2.1.20
Ran the new gui. Confirmed cert shows up in the gui with 0 days left.
Kicked off the update job from admin dos again.
This time it completed successfully and cert is up for renewal 1/23/18

Looks like the issue is fixed, although for sure I would need to check via the scheduled job in 75 days time....

**Comment by webprofusion-chrisc** [comment]
@Absoblogginlutely if you set your renewal period to a lower value (say 7-14 days) then you can check to see if renewals are working sooner. If renewal fails to complete your existing certificate will be kept. You can also now easily open the Log for a site under the 'Info' tab for that site, so you can also see the renewal history there. I recommend using the same user account for running the Auto Renew scheduled task as for the GUI as using service accounts etc has not yet been tested.
