### ISSUE TITLE
Cert renewed today and site is showing invalid certificate error

### ISSUE THREAD

**Issue by deejbee** [webprofusion/certify#143]
This isn't good.  A production site i have configured with auto renew, renewed today but when I visit the site it is showing and invalid certificate error.  What do I need to do to fix this?

**Comment by webprofusion-chrisc** [comment]
Hi, I believe there is an occasional bug whereby the primary domain does not get included in the renewal request. This appears where you have a few domains/subdomains listed on one certificate and the domain you are looking at hasn't been included on the renewed certificate. Check your site settings in Certify and run your certificate request manually to see if that resolves the problem.  We will be adding safe guards against this type of issue in the next release.

If this appears to be a different issue you can send a zip of your c:\programdata\certify folder to apps at webprofusion.com and I'll take a look.

**Comment by deejbee** [comment]
Hi,  I did have both mysite.com and www.mysite.com configured as a subdomain.  I tried running the request manually but it didn't fix it.   I had to wait some hours before the site became available again (I'm not sure if that was partly because chrome browser caching the incorrect cert though).

**Comment by webprofusion-chrisc** [comment]
interestingly I have also see the same behaviour recently, it's liek we're not getting all the domains we ask for in the cert. Currently investigating.

**Comment by webprofusion-chrisc** [comment]
Could you try the following alpha test version: https://certifytheweb.com/downloads/CertifySetup.2.0.8.exe  - we are trialing this ourselves in house but the most relevant change is a difference in how we handle domains that are already validated, this is likely to resolve the issue you are seeing.

**Comment by webprofusion-chrisc** [comment]
Fixed the newest release 2.0.9: https://certifytheweb.com/
