### ISSUE TITLE
where is the private key?

### ISSUE THREAD

**Issue by hubgitbb** [webprofusion/certify#145]
hi,

I've been using version 2.0.7.34309 to create an certificate for on the SBS 2011 default website. Which works on creating. the browsers shows everything is ok. but the certificate path pane the status is "The issuer of this certificate was not found"
i also cant export the certificate with the private key. 
if i check my site on www.ssllabs.com/ssltest/ i get this info: "this servers certificate chain is incomplete".

how can i fix all this?

regards

**Comment by webprofusion-chrisc** [comment]
Hi, which browser are you using to inspect the certificate details - you should be using IE 11 or better for reliable information. You can export the certificate normally (from Personal store) using "Manage computer certificates" in windows server, but I'm not familiar with SBS 2011 administration.

**Comment by hubgitbb** [comment]
i can export on IE11 but without the private key. 
the same problem exist on the personal store using "manage computer certificates" in windows server

**Comment by webprofusion-chrisc** [comment]
What error are you seeing when you try to export? Note that the private key is stored in the server only. You will also find a copy of your pfx under c:\programdata\acmesharp\sysvault\99-ASSETS, its the one pointed to by the entry in c:\programdata\certify\managedsites.json for your site. We hope to add some UI to make finding this easier soon.

**Comment by hubgitbb** [comment]
i dont get any error. the radio button for export private key is grayed out.
i found the pfx file under c:\programdata\acmesharp\sysvault\99-ASSETS. wich password do i need for import the pfx?

**Comment by webprofusion-chrisc** [comment]
Hi, the password is blank by default.
