### ISSUE TITLE
Load Balanced Servers SSL Certs - Enhancement

### ISSUE THREAD

**Issue by wilgeno** [webprofusion/certify#152]
I have a situation with load balanced Windows servers behind an AWS TCP Network load balancer with IP pass-through. The SSL certificates have to be managed per server node. Certify can't properly validate the SSL certificates because the requests don't always return to the same server.

For now I can export the SSLs from one server to the other. That will get old really fast. It would be nice if there was a way for Certify to replicate or copy or something each SSL certificate between defined authorized nodes provided Certify is installed on each node. I know, it's a huge request. But I think it's worth pondering at some point.

**Comment by Marcus-L** [comment]
RE: domain validation - did you solve this? You could set up [IIS virtual directories](https://support.microsoft.com/en-us/help/308150/how-to-create-a-virtual-directory-on-an-existing-web-site-to-a-folder) to point the ".well-known" directory on all your web servers to the ".well-known" folder on the Certify server, so they serve files from there and properly handle the domain validation.

RE: certificate sharing - Are you using [CCS](https://blogs.msdn.microsoft.com/kaushal/2012/10/11/central-certificate-store-ccs-with-iis-8-windows-server-2012/) for IIS certificate sharing? All you'd need to do is export the PFX to the CCS share after each renewal and all the web servers should pick up the change. You could use a [Post-Request hook](https://github.com/webprofusion/certify/blob/master/docs/Request%20Script%20Hooks.md) to script that.

**Comment by webprofusion-chrisc** [comment]
The other alternative method to shared validation folder is to use Dns validation instead http-01 but unfortunately Certify doesn't support that yet (there are many possible dns providers to talk to).

**Comment by Marcus-L** [comment]
Closing out due to inactivity. @wilgeno if you have more info to provide please let us know.
