### ISSUE TITLE
TLS-SNI-01 Challenge Support

### ISSUE THREAD

**Issue by Marcus-L** [webprofusion/certify#158]
Since Certify already supports automatic certificate installation and creation of IIS bindings, it should support the LetsEncrypt TLS-SNI-01 challenge. This challenge method would avoid the problems with the extensionless challenge files used in HTTP-01, and would support servers that do not have an open port 80.

(suggested by @cpu in #115)

**Comment by Marcus-L** [comment]
I have a branch with tls-sni-01 challenges working here: https://github.com/Marcus-L/Certify/tree/tls-sni-challenge

It requires a two other pull requests to be merged before I can PR it into the repo: https://github.com/WouterTinus/ACMESharp/pull/1, which builds on https://github.com/ebekker/ACMESharp/pull/295

When both of those changes are accepted into ebekker/ACMESharp, I'll put the PR in here.

![screenshot_092617_065348_pm](https://user-images.githubusercontent.com/1369184/30889442-091a7fb2-a2ec-11e7-8373-442c00cf5055.jpg)

**Comment by webprofusion-chrisc** [comment]
Excellent, plus your change (and that of @WouterTinus) benefit ACMESharp, and in turn letsencrypt-win-simple and others, which is great to see.

**Comment by Marcus-L** [comment]
This is done!

**Comment by webprofusion-chrisc** [comment]
Brilliant, will check this out in a few different environments. Great to have this in. DNS challenge will be the final frontier (really need a good C# library etc for many DNS api providers).

**Comment by webprofusion-chrisc** [comment]
Good stuff, just testing this properly now.  On my machine the tns-sni-01 test this was failing as it can't resolve it's public dns name to an internal IP, which is quite common (internal vs external dns/networks). Add an additional 127.0.0.1 entry for internal resolution fixes it for me.

**Comment by Marcus-L** [comment]
Good to hear it's working for you. I output the ActionLog in a MessageBox if it failed for debugging, but the messages in there might need to be reworded or otherwise made suitable for end-user debugging of failures. For a technical user there should be enough in there to debug, but maybe not. What do you think?

Also one thing I forgot to mention was that the "use proxy" checks for tls-sni-01 (and updates to the http-01 check) need to be done on your server and then [update the client code](https://github.com/webprofusion/certify/blob/e842f16cd800ca5d82e46f55d65ba238d918b78a/src/Certify.Core/Management/VaultManager.cs#L1114). I don't have access to your server code but I imagine it's probably pretty similar. Maybe you could even extract the CheckUrl and CheckSNI methods into a helper class and then just use the same class from your server code to avoid any code duplication.
