### ISSUE TITLE
Planning for ACME V2 API support

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#159]
Let's Encrypt will adopt the v2 ACME API (currently draft 07 of the acme spec).
https://tools.ietf.org/html/draft-ietf-acme-acme-07

A significant feature this will bring is wildcard certificate support.

In general we would like to track the latest version of the LE API and pass any new features on to our users.

Currently we depend upon ACMESharp (https://github.com/ebekker/ACMESharp/) for our ACME API implementation and we have provisionally started to also look at certes (https://github.com/fszlin/certes/). It may become necessary for us to consider our own ACME client implementation. This issue tracks the changes and additional features which are enabled by the new ACME version.

**Comment by Marcus-L** [comment]
What would you say are the downsides of staying with an existing ACME library like ACMESharp (or Certes) vs rolling your own? Leveraging an existing library would save time & effort. Aside from wildcard cert support (👍👍!) I'm not aware of any major _feature_ changes in v2, and having just skimmed over the changes in the protocol nothing looks disruptive in there either. 

ACMESharp seems sufficient and they have [plans to support ACME v2](https://github.com/ebekker/ACMESharp/issues/260). From what I can tell the benefit of Certes over ACMESharp would be .NET Core support and a slightly nicer programmatic API. I've already weighed in on #153, but to summarize I'm against a re-write for cross-platform UI vs platform-specific agents and migrating all the ACME functionality to a dashboard.

**Comment by webprofusion-chrisc** [comment]
Happy to stay with existing libraries (if they can keep up or are easily modified to do so), but I'd like to have the option to not take a permanent dependency on a single one.

**Comment by webprofusion-chrisc** [comment]
Currently though, ACMESharp doesn't support v2 and we can't predict what breaking changes  (if any) will be made to support it.

The LE v2 staging API is not accessible to my knowledge except through Pebble as a dev environment (tried this on windows linux subsytem with no luck). Whether we will see a v2 staging api soon is maybe a question for @cpu?

**Comment by cpu** [comment]
>  Whether we will see a v2 staging api soon is maybe a question for @cpu?

We don't have a firm schedule for when the staging API will be available. It will definitely be available prior to launch, likely later in the fall.

**Comment by cpu** [comment]
> The LE v2 staging API is not accessible to my knowledge except through Pebble as a dev environment (tried this on windows linux subsytem with no luck)

How is Docker support on Windows? Is that an option for running Pebble?

**Comment by webprofusion-chrisc** [comment]
Update on Let's Encrypt plans re: v2 API:
https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605

Key points:
- Changes to API mean ACMESharp has to upgrade (which may mean we need to move up a .net version to support .net standard 2.0) https://github.com/ebekker/ACMESharp/issues/260 - it looks like initial experiments are with a new library: https://github.com/PKISharp/ACMESharpCore
- Support for wildcard certs requires DNS challenges. Certify doesn't have any DNS challenge support yet, so this is an opportunity. Ideally we would working with LEWS etc to collaborate on a single .net implementation for a variety of DNS API providers if no current solution exists.
- Support for wildcard certs also means UI changes, the biggest of which is optionally chaining multiple sites to a single parent which will be responsible for the renewal/request process, then informs all the other managed sites to perform their certificate updates.

**Comment by ebekker** [comment]
@webprofusion-chrisc  -- refresh my memory, does Certify rely only on ACMESharp client library, or does it use the PowerShell module as well?

**Comment by webprofusion-chrisc** [comment]
@ebekker just looked at the updated https://github.com/PKISharp/ACMESharpCore - looks like progress!

**Comment by ebekker** [comment]
Yes, I was asking because I intend to focus and finish up a working v2 in the short term, but PWSH support may not get any love for a while.  So stay tuned, hopefully will have a usable client finished soon that you can start playing with...

**Comment by webprofusion-chrisc** [comment]
@ebekker  that's awesome, look forward to it, I appreciate that it's a lot of work.

**Comment by webprofusion-chrisc** [comment]
ACME v2 support is implemented as of v4 beta (using Certes). Plan for 4.x future is to also enable the use of ACMESharpCore: #323

Closing.
