### ISSUE TITLE
Need warning if Powershell version too old.

### ISSUE THREAD

**Issue by ryanmcdonough** [webprofusion/Certify#16]
As soon as I open I get:

*************\* Exception Text **************
System.InvalidOperationException: Vault has not been initialized
   at ACMESharp.Vault.Providers.LocalDiskVault.LoadVault(Boolean required)
   at Certify.VaultManager.LoadVaultFromFile()
   at Certify.VaultManager..ctor(String vaultFolderPath, String vaultFilename)
   at Certify.MainForm.MainForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

Certify
    Assembly Version: 1.0.0.0
    Win32 Version: 0.9.85
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/Certify.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34285 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34294 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34283 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.2.19309
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/Newtonsoft.Json.DLL

ACMESharp.Vault
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.Vault.DLL

Microsoft.ApplicationInsights
    Assembly Version: 1.2.3.490
    Win32 Version: 1.2.3.490
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/Microsoft.ApplicationInsights.DLL

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Management.Automation
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.6002.18111
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management.Automation/1.0.0.0__31bf3856ad364e35/System.Management.Automation.dll

System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll

System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34297 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

Microsoft.PowerShell.Commands.Diagnostics
    Assembly Version: 1.0.0.0
    Win32 Version: 6.1.7600.16385
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll

System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll

Microsoft.WSMan.Management
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.6002.18111
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.WSMan.Management/1.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll

Microsoft.WSMan.Runtime
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.6002.18111
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.WSMan.Runtime/1.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Runtime.dll

System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll

Microsoft.PowerShell.Commands.Utility
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.6002.18111
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll

Microsoft.PowerShell.ConsoleHost
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.6002.18111
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll

Microsoft.PowerShell.Commands.Management
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.6002.18111
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll

System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll

Microsoft.PowerShell.Security
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.6002.18111
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.PowerShell.Security/1.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll

ACMESharp.POSH
    Assembly Version: 0.8.1.0
    Win32 Version: 0.8.1.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.POSH.DLL

ACMESharp
    Assembly Version: 0.8.1.0
    Win32 Version: 0.8.1.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.DLL

System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll

ACMESharp.PKI.Providers.OpenSslLib32
    Assembly Version: 0.8.1.0
    Win32 Version: 0.8.1.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.PKI.Providers.OpenSslLib32.DLL

ACMESharp.PKI.Providers.OpenSslLib64
    Assembly Version: 0.8.1.0
    Win32 Version: 0.8.1.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.PKI.Providers.OpenSslLib64.DLL

AWSSDK.Core
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.1.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.Core.DLL

AWSSDK.Route53
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0.1
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.Route53.DLL

AWSSDK.S3
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.2.1
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.S3.DLL

ManagedOpenSsl
    Assembly Version: 0.6.1.0
    Win32 Version: 0.6.1.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Certify/ManagedOpenSsl.DLL

Microsoft.Web.Administration
    Assembly Version: 7.0.0.0
    Win32 Version: 6.0.6002.18005
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Web.Administration/7.0.0.0__31bf3856ad364e35/Microsoft.Web.Administration.dll

MetadataViewProxies_5837023f-afae-47b7-b1c7-ceed4cd7cff2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.34209
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by webprofusion-chrisc** [comment]
Thanks, what version of Windows are you on and what version of Powershell is installed?

**Comment by ryanmcdonough** [comment]
Windows Server 2008 R2
Powershell 2.0

**Comment by ryanmcdonough** [comment]
Just looked at AcmeSharp and that seems to need 3.0 onwards.

**Comment by webprofusion-chrisc** [comment]
Yes, we need to add a warning if your powershell version is too low (like it is in this case).
