### ISSUE TITLE
Should set user agent and language as per ACME spec when talking to LE

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#160]
https://tools.ietf.org/html/draft-ietf-acme-acme-07#section-6.1

> ACME clients SHOULD send a User-Agent header in accordance with
>    [RFC7231], including the name and version of the ACME software in
>    addition to the name and version of the underlying HTTP client
>    software.
> 
>    ACME clients SHOULD send an Accept-Language header in accordance with
>    [RFC7231] to enable localization of error messages.

**Comment by Marcus-L** [comment]
I think this is new for ACME v2 (draft 07). V1's spec is the draft 01 and does not have that language.

**Comment by cpu** [comment]
Hi @Marcus-L,

As a small point of clarity the "V1" API isn't strictly ACME draft 01. It's closer to somewhere between draft-03 and draft-07. We [document the important divergences here](https://github.com/letsencrypt/boulder/blob/master/docs/acme-divergences.md). I believe the User Agent "SHOULD" portion of the spec has been present since ~draft-04.

**Comment by Marcus-L** [comment]
Ah, ok, thanks for the clarification. I didn't know it was such a moving target. I'd just finished implementing tls-sni-01 (from ACME v1) for Certify, which was in the draft-01. It started being called tls-sni-02 in draft-02, so I assumed that was the cutover.

**Comment by cpu** [comment]
@Marcus-L I can definitely understand your confusion, its a bit of a mess :-) The individual challenges are "versioned" based on the draft they were introduced in, but Boulder has evolved alongside the drafts and doesn't strictly conform to any one.

**Comment by webprofusion-chrisc** [comment]
@cpu just as an aside, rather than an rfc it would be cool to see a swagger style API doc or docs by example for each request/responds. I find the rfc a little verbose (and diverged from, as noted) when I'm just really after an API guide.

**Comment by cpu** [comment]
@webprofusion-chrisc I'm not familiar with Swagger but I will take a look. Thanks for the idea!

**Comment by Marcus-L** [comment]
I submitted PR https://github.com/ebekker/ACMESharp/pull/300 to open up the UserAgent and Language.

**Comment by Marcus-L** [comment]
Closed via #180
