### ISSUE TITLE
Display Let's Encrypt error message if domain identifier validation fails

### ISSUE THREAD

**Issue by KalanVryce** [webprofusion/certify#170]
I did resolve the problem, however, the error was incorrect and vague.  I was avoiding using a different client as I was specifically testing Certify for Exchange compatibility.  I tried ZeroSSL after much frustration and it failed as well, however, it did give me a more specific error stating the issue was that my CAA record wouldn't allow it.  I removed the CAA Record and Certify was able to process the request properly.  Full documentation, screenshots, and notes are on the Let's Encrypt forums at the following link.

https://community.letsencrypt.org/t/problem-with-redirect-to-https/43479

**Comment by Marcus-L** [comment]
Thanks for reporting this. The current Certify release does not report the exact error message if an error occurs doing identifier validation, the "Validation of the required challenges did not complete successfully. Please ensure all domains to be referenced in the Certificate can be used to access this site without redirection." message is a generic message. We'll take a look and see if we can include more debug info from these sorts of failures in the future.

**Comment by Marcus-L** [comment]
I edited the title so that we can fix this issue (not reporting the error message) separately from the other issue I just created for doing an internal CAA/DNSSEC check.

**Comment by KalanVryce** [comment]
Awesome, thanks for responding and working on such a great product!

**Comment by webprofusion-chrisc** [comment]
@Marcus-L for info I'm looking at this (reporting the error properly) just now - we do report some errors but obviously not all.

**Comment by Marcus-L** [comment]
Thanks for the heads-up. Maybe in the future also assign yourself if you are taking "dibs" on an issue to avoid duplication of effort. 

Also I saw the GitHub "projects" feature on a different repo (it's an agile scrum board sort of thing) that might be fun to play with. It would help with coordination... but mainly I just want to play around with it :)

**Comment by webprofusion-chrisc** [comment]
@Marcus-L lol, yeah I'm not yet used to the idea of anyone other than me fixing stuff. Re: agile board, I'll check it out.

**Comment by webprofusion-chrisc** [comment]
@Marcus-L p.s. project for the desktop app now created. No ideas what to do with that but feel free to edit as you like. Issues are added as 'cards' and notes can be added free-form without an associated issue.

**Comment by Marcus-L** [comment]
Cool. Add to "on deck" (renamed todo) whatever you plan on working on next (if not yet started). Drag into "In Progress" once you start working (or spec-ing) something. I've used Jira before which had a pretty good agile board (and comes from 'Straya as well!), this one seems passable.  If you like it we can keep it, if not should be easy enough to turn off later.

**Comment by webprofusion-chrisc** [comment]
Identifier validation errors now being captured and presented as expected:

![image](https://user-images.githubusercontent.com/2445502/31267932-af5a2ed2-aaac-11e7-8c2a-c498dbc9dee2.png)
