### ISSUE TITLE
UI freezes when renewing a large number of sites

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#177]
The UI currently freezes when running a large number of renewal tasks. We need to go full async on requests so that be don't block the UI thread.

**Comment by webprofusion-chrisc** [comment]
The core issue here is that our query against IIS is synchronous and on the current thread. This issue would effectively go away if/when we move to a core service that provides an API for the UI, as the calls to the service would all be async. The target here should be to support 10's of thousands of sites on a single server.

**Comment by webprofusion-chrisc** [comment]
[manageditems.zip](https://github.com/webprofusion/certify/files/1445443/manageditems.zip)
Attached is an example (generated) manageditems.json - this is 10,000 managed sites and totals 132MB unzipped. I actually get an out of memory exception trying to load this. The largest reported user manageditems.json is 222MB(!). Related to this I've been looking at using LiteDB or SqlLite as a general storage mechanism for settings.

**Comment by Marcus-L** [comment]
Thanks for the test case, it was helpful as a benchmark to fix the test and also for testing loading things in the UI. I agree it's probably necessary to update the storage mechanism, as the time taken for each ItemManager.StoreSettings() call will increase linearly with the number of sites being managed, which is not good, on my machine it takes about 3.5 seconds to save 100K records.

I do find it mind boggling that someone has a real settings file that's 222MB!

**Comment by webprofusion-chrisc** [comment]
Closing this for now. We have recently completed massive changes to how settings are stored, how IIS is queried and how the UI renders.
