### ISSUE TITLE
Need to show some progress indicator when running config tests

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#178]
Currently when you use the 'Test' button on a managed site it goes off and runs the necessary checks, this can take some time. We should show a progress indicator/spinner and perhaps some progress text.

**Comment by Marcus-L** [comment]
Looks like you added the spinner! 👍

**Comment by webprofusion-chrisc** [comment]
Oh yeah, I did. I probably meant to add another somewhere else but I'll close this for now!
