### ISSUE TITLE
script hooks don't have admin access or file path access or something

### ISSUE THREAD

**Issue by beowulfs** [webprofusion/certify#181]
The powershell script hooks cannot access the powershell modules or .net assemblies, both of which are required to use the RemoteDesktop module. I copied the powershell v1.0 directory to the folder I’m saving the scripts in and that allowed me to load the RemoteDesktop module, but it calls a .net assembly that I can’t copy out. Is there something I can do to make it work?

**Comment by Marcus-L** [comment]
Hi there. What are you trying to do with the Remote Desktop powershell module? Why can't you copy the .net assembly? Can you provide more information about the error message you are receiving and an example of how to reproduce the problem you are having?

**Comment by beowulfs** [comment]
I'm just trying to call the RemoteDesktop module to swap out the Remote Desktop Certificates after the letsencrypt certificate is renewed. The first log below is the script as is. The second points to a sub folder for the modules that I copied out of the windows powershell folder. I copied the dll from the GAC_64 folder as well and pasted it here. C:\certs\v1.0\Modules\RemoteDesktop\Microsoft.RemoteDesktopServices.Management.Activities.dll

`param($result)
if ($result.IsSuccess)
{
$pfxpath = $result.MangagedItem.CertificatePath
$mypwd = ConvertTo-SecureString -String "sanitized" -Force -AsPlainText


import-module -name RemoteDesktop


Set-RDCertificate -Role RDPublishing -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
Set-RDCertificate -Role RDWebAcces -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
Set-RDCertificate -Role RDGateway -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
Set-RDCertificate -Role RDRedirector -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
}`

2017-10-11 12:26:46.842 -05:00 [Information] Post-Request Script output:
Import-Module: The specified module 'RemoteDesktop' was not loaded because no valid module file was found in any module directory.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:8 char:1
+ import-module -name RemoteDesktop -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Set-RDCertificate: The term 'Set-RDCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:11 char:1
+ Set-RDCertificate -Role RDPublishing -ImportPath $pfxpath -Password $mypwd -Conn ...
+ ~~~~~~~~~~~~~~~~~
Set-RDCertificate: The term 'Set-RDCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:12 char:1
+ Set-RDCertificate -Role RDWebAcces -ImportPath $pfxpath -Password $mypwd -Connec ...
+ ~~~~~~~~~~~~~~~~~
Set-RDCertificate: The term 'Set-RDCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:13 char:1
+ Set-RDCertificate -Role RDGateway -ImportPath $pfxpath -Password $mypwd -Connect ...
+ ~~~~~~~~~~~~~~~~~
Set-RDCertificate: The term 'Set-RDCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:14 char:1
+ Set-RDCertificate -Role RDRedirector -ImportPath $pfxpath -Password $mypwd -Conn ...
+ ~~~~~~~~~~~~~~~~~


2017-10-11 13:24:58.638 -05:00 [Information] Post-Request Script output:
Loading module from path 'C:\certs\v1.0\Modules\RemoteDesktop\RemoteDesktop.psd1'.
Loading 'Assembly' from path 'C:\certs\v1.0\Modules\RemoteDesktop\Microsoft.RemoteDesktopServices.Management.Activities.dll'.
Loading 'FormatsToProcess' from path 'C:\certs\v1.0\Modules\RemoteDesktop\RDMgmt.format.ps1xml'.
Import-Module: Could not load file or assembly 'Microsoft.RemoteDesktopServices.Management.Activities, Version=6.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:8 char:1
+ import-module -name C:\certs\v1.0\Modules\RemoteDesktop -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Set-RDCertificate: The term 'Set-RDCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:11 char:1
+ Set-RDCertificate -Role RDPublishing -ImportPath $pfxpath -Password $mypwd -Conn ...
+ ~~~~~~~~~~~~~~~~~
Set-RDCertificate: The term 'Set-RDCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:12 char:1
+ Set-RDCertificate -Role RDWebAcces -ImportPath $pfxpath -Password $mypwd -Connec ...
+ ~~~~~~~~~~~~~~~~~
Set-RDCertificate: The term 'Set-RDCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:13 char:1
+ Set-RDCertificate -Role RDGateway -ImportPath $pfxpath -Password $mypwd -Connect ...
+ ~~~~~~~~~~~~~~~~~
Set-RDCertificate: The term 'Set-RDCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\certs\LetsEncryptPostSuccessScriptForRDS.ps1:14 char:1
+ Set-RDCertificate -Role RDRedirector -ImportPath $pfxpath -Password $mypwd -Conn ...
+ ~~~~~~~~~~~~~~~~~

**Comment by Marcus-L** [comment]
This might be a problem if the powershell module is only available for x64 (the powershell hooks run in x86 by default). Try doing something like this:
```powershell
param($result)
set-alias ps64 "$env:windir\sysnative\WindowsPowerShell\v1.0\powershell.exe" 
ps64 {
   import-module -name RemoteDesktop
   Set-RDCertificate -Role RDPublishing -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
}
```

**Comment by beowulfs** [comment]
the syntax is quite correct. i'm working on it too. i'm thinking it's the arguments not passing as well. i got something that said something to the affect that the path couldn't be empty (the importpath from set-rdcertificate), but i haven't been able to get that again.

**Comment by beowulfs** [comment]
The powershell hanging is from me being an idiot and dropping the open bracket { down on a new line.

**Comment by beowulfs** [comment]
I'm getting this, 4 times:
'''
powershell.exe: Empty path name is not legal.
At C:\certs\LetsEncryptPostSuccessScriptfor RDS.ps1:3 char:1
+ps64 -args $result - command {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''

**Comment by beowulfs** [comment]
This is what I'm trying to run now:
```
param($result)
set-alias ps64 "$env:windir\sysnative\WindowsPowerShell\v1.0\powershell.exe" 
ps64 -args $result -command {
$result = $args[0]
$pfxpath = $result.MangagedItem.CertificatePath
$mypwd = ConvertTo-SecureString -String "sanitized" -Force -AsPlainText
import-module -name RemoteDesktop
Set-RDCertificate -Role RDPublishing -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
Set-RDCertificate -Role RDWebAcces -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
Set-RDCertificate -Role RDGateway -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
Set-RDCertificate -Role RDRedirector -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "ts.sanitizeddomain.com" -Force
}
```

**Comment by Marcus-L** [comment]
Sounds like it's working for you aside from any remaining issues with your powershell script. I'll update the docs to include info about using 64-bit modules.

**Comment by beowulfs** [comment]
I think i'm going to have to use a function instead of an alias because i need to pass the $result paramater

**Comment by Marcus-L** [comment]
The `$result` parameter is passed. In your example you have a typo, you misspelled `ManagedItem`.

**Comment by beowulfs** [comment]
doh. and that's closed.

**Comment by Marcus-L** [comment]
If your script ends up working for updating Remote Desktop certificates, please post it here so we can add it as an example on the powershell hooks documentation page. Or better yet (if you know how to do it) send in a pull request!

**Comment by beowulfs** [comment]
I had planned on it. I've got it working, but I've found an issue with the main gui. When it generates the pfx file, it gives it a null password. Using "" in my script accomplishes the import, but then I've got a certificate with a blank password.

**Comment by beowulfs** [comment]
I looked at doing a pull request, but I think I'd have to dedicate a little more time than I have to read how to do it correctly. I'll post the working, sanitized script below this in its own post.

Where should I put the add password request for the GUI?

**Comment by beowulfs** [comment]
Declare the $result parameters
set the alias to use 64-bit powershell
call the alias and pass the $result parameters
reload the $result parameters
store your new pfx password in a securestring format in $mypwd
get the certify pfx file using no password and store it in $oldpfxpath
enter a path for a new pfx file that will have your new password in $pfxpath
convert the certify pfx file in $oldpfxpath to your new pfx file with your new password and save it to your $pfxpath
import the remotedesktop powershell modules
update the 4 remote desktop roles with the new pfx file
```
param($result)
set-alias ps64 "$env:windir\sysnative\WindowsPowerShell\v1.0\powershell.exe" 
ps64 -args $result -command {
$result = $args[0]
$mypwd = ConvertTo-SecureString -String "youpasswordhere" -Force -AsPlainText
$oldpfxpath = Get-PfxData -FilePath $result.ManagedItem.CertificatePath
$pfxpath = "c:\certs\mypfx.pfx"
Export-PfxCertificate -PFXData $oldpfxpath -FilePath $pfxpath -Password $mypwd -Force
Import-Module RemoteDesktop
Set-RDCertificate -Role RDPublishing -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "cb.yourdomain.com" -Force
Set-RDCertificate -Role RDWebAcces -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "cb.yourdomain.com" -Force
Set-RDCertificate -Role RDGateway -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "cb.yourdomain.com" -Force
Set-RDCertificate -Role RDRedirector -ImportPath $pfxpath -Password $mypwd -ConnectionBroker "cb.yourdomain.com" -Force
}
```

**Comment by Marcus-L** [comment]
Thanks for the script, I'll put in an example into the docs. I probably wouldn't put in a request to add password to the PFX though, having it be an empty string is by design (otherwise the Certify app would have to keep track of the password as well, which would add complication to the app).

**Comment by beowulfs** [comment]
Roger that. Thanks again.

**Comment by beowulfs** [comment]
It would be nice if there was a link to the script hooks page in the FAQ.

**Comment by webprofusion-chrisc** [comment]
I'll see if I can get the docs integrated a bit more with the certifytheweb.com site, I need to decide if we're also going to link directly from the UI to docs.
