### ISSUE TITLE
DNS Check throws exception for some valid domains

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#184]
We are seeing exception reports for ARSoft.Tools.Net.Dns.DnsSecRecursiveDnsResolver whilst resolving pretty basic domain like 'cloudapp.net' suggesting there is a fault in that library.

**Comment by Marcus-L** [comment]
Is that a real domain? No A or AAAA record for me via nslookup:

![screenshot_101717_085936_pm](https://user-images.githubusercontent.com/1369184/31697584-1594fa72-b37e-11e7-8808-567ae808c4e3.jpg)

Also:
![screenshot_101717_085901_pm](https://user-images.githubusercontent.com/1369184/31697572-009ff586-b37e-11e7-81f4-7f737c7d3e58.jpg)

Is it causing a crash in the app?

**Comment by Marcus-L** [comment]
Ah, got it. Tried it in the app and saw the exception. Looking in to it.

**Comment by webprofusion-chrisc** [comment]
Much appreciated, getting about one crash per hour. I thought I'd caught the exception but obviously not.

**Comment by webprofusion-chrisc** [comment]
Asides from catching the exception my plan is to make DNS checks off by default. Maybe make it an extra option during 'test' run. Really as test is running multiple checks we'll eventually need to do a summary of what worked and what didn't so people can decide if their config is broken or not.
