### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by iccfish** [webprofusion/certify#186]
Hi guys.

I've forked this repo and add multi-language support.

Currently I have done following things:

- Move all UI strings to resource file
- Add Simplified Chinese Translation
- Add ability to show language translator in About Box (below thirty party libs)

I'd like to create pull request for this, but I'm not sure if you could accept these.

For screenshoot:
![20171020113810](https://user-images.githubusercontent.com/1091653/31804440-fa6a6be6-b58b-11e7-8010-1ee83f46395a.png)

You can view changes via my forked repo (https://github.com/iccfish/Certify/commit/cea0b1cd45246dd0ac3f20e74e873feb85b5ccee)

**Comment by webprofusion-chrisc** [comment]
Wow, thanks. Yes we will accept this is a PR. How should we go about notifying translators when new text needs translation?

**Comment by iccfish** [comment]
I suggest a tool called Resource Manager, this tool could display all resources in project with all languages in a single data grid, and it can tell which hasn't been translated.

Some other project uses some third-party translation platforms, for example, [dnspy](https://github.com/0xd4d/dnSpy) uses [Crowdin](https://crowdin.com/project/dnspy), seems that it support upload resx file directly, which fit my modification. So maybe you can doing some investigate on it before I create a PR 😄

**Comment by webprofusion-chrisc** [comment]
@iccfish thanks, I've previously supported an app with many translations - as long is every is happy that some releases/languages may not be fully translated it's fine for me. Please do submit this as a PR when you have time. Sooner will be easier as you have less change of merge conflicts.

**Comment by webprofusion-chrisc** [comment]
@iccfish or if you like and I can just create the pull request from your fork.

**Comment by iccfish** [comment]
I'll create a PR today later 😄

**Comment by webprofusion-chrisc** [comment]
@iccfish thank you! Very much appreciated. If you would also like a free license key you can email app {at} webprofusion.com with the link to your pull request 👍

**Comment by iccfish** [comment]
I'd like to close this issue due to PR has been created via #187
