### ISSUE TITLE
Auto-Renew?

### ISSUE THREAD

**Issue by Concept211** [webprofusion/certify#19]
Is it possible to run via command line so that we can schedule an automated auto-renewal of all configured certificates prior to the 90 day certificate lifespan?

**Comment by webprofusion-chrisc** [comment]
At some point in the future I intend to add auto renew as a service to the app. Until then though you could use the ACMESharp powershell scripts (which Certify uses) to script any action you like including renewal.

**Comment by Concept211** [comment]
Could you point me in the right direction to those PS scripts? I couldn't locate any scripts on his repository other than the ones he uses to build the solution.

**Comment by webprofusion-chrisc** [comment]
Certify has its own build of them in the Program Files\Certify folder, perhaps you could use those? Otherwise you need to build using visual studio.

**Comment by Concept211** [comment]
I checked but the only PS script I see is C:\Program Files (x86)\Certify\ACMESharp.psd1 which doesn't seem to help much. Is this what you're referring to?

**Comment by webprofusion-chrisc** [comment]
Yeah, not at a computer just now but you Import that in your powershell script (example on the acmesharp getting started) then that makes the other commands available.

**Comment by webprofusion-chrisc** [comment]
Closing. Auto renew now available in the v2 alpha version.
