### ISSUE TITLE
"Config checks failed to verify ..."

### ISSUE THREAD

**Issue by jeaniusdesign** [webprofusion/certify#191]
Hi,
I'm struggling a little with requesting the certificate.
I have added the .* extension for application/octet-stream in both the web.config and also tried setting in Mime, but I cannot get it to work.
I get a 403 on the configcheck file.
New to this, sorry. What am I missing?
Many thanks indeed.

**Comment by Marcus-L** [comment]
Please check my answer here for debugging tips: https://stackoverflow.com/a/46308114/490657

Also, make sure you update to the [latest version of Certify](https://certifytheweb.com/home/download) (2.1.20 as of today). You may want to try the "tls-sni-01" Challenge Type instead of "http-01", which should not require modifications to your web.config, so it may work better for your situation:

![screenshot_102517_121643_pm](https://user-images.githubusercontent.com/1369184/32012705-5e1c229c-b97e-11e7-9f0e-6474510f6b97.jpg)

**Comment by webprofusion-chrisc** [comment]
@jeaniusdesign so the idea is that we configure that all for you under the /.well-known/acme-challenge/ folder, usually that means you don't have to configure anything yourself unless there's a conflict with an existing handler in the parent web application. Note that depending on your IIS version the extension-less static file handler mapping can be "*" or ".*".

That said, a 403 is access denied, not file not found. That suggests your parent application has some form of basic authentication switched on, which you will have to clear for Let's Encrypt to be able to access the challenge answer file we generate.

**Comment by jeaniusdesign** [comment]
Thanks both!

I am on 2.1.20 and when I change to tls-sni-01, I get the following:

Failed prerequisite configuration checks (SSL_LetsEncrypt_LocalIIS)
Validation of the required challenges did not complete successfully.

:(

I do have the extensionless settings in web.config for the particular application - but when that didn't work, I thought I'd set it a bit higher, but that didn't work either.

I think you're probably right that there's something else in the application that's stopping this. It's an application that I've inherited, so I'm not at all familiar with it (based on Orchard CMS), but it's actually being replaced shortly - I just wanted to get the SSL ready for the domain before replacing it with the new application.

The good news is that the LetsEncrypt request completed fine on my development subdomain for that URL, so I'm hopeful I'll be okay once I make the switch.

Thanks again both. :)

**Comment by webprofusion-chrisc** [comment]
@jeaniusdesign is this article any help? https://flowerbunch.org.uk/using-letsencrypt-with-orchard-cms

**Comment by jeaniusdesign** [comment]
Oh, gosh! YES! Thank you so, so much. Certificates verified and installed!

Thanks again for all of your help - Certify is a wonderfully easy way to get certificates. Apologies for the support ticket here when it actually turned out to be unrelated. I'm over the moon.

**Comment by webprofusion-chrisc** [comment]
No problem :)
