### ISSUE TITLE
windows 2016 Application hangs after save

### ISSUE THREAD

**Issue by makeitsimple** [webprofusion/certify#198]
HI,

I installed on Windows 2016 server, and when i chose the website, after I click Save the application hangs and close.

I send the problem report, how can I help you more find the problem.

Regards,

SR

**Comment by danielcrabtree** [comment]
I manually created the file: `C:\ProgramData\Certify\manageditems.json` with contents: 
```
{
}
```

This seems to resolve the issue.

**Comment by webprofusion-chrisc** [comment]
Thanks, this is resolved in the latest release. It was trying to backup settings before saving, except you don't have any settings. Ouch.
