### ISSUE TITLE
UI Doesn't sort new bindings by domain

### ISSUE THREAD

**Issue by vulwaowf** [webprofusion/certify#199]
When new bindings are added to the applicationHost.config file or IIS UI (IIS has to be reset to load the applicationHost.config bindings) and you select "new certificate" the new bindings are not sorted by domain.

They are located at at the bottom of the list.  They should get read into the list in order as the domain.  The problem maybe the way IIS reads the list in instead of certify.  Just pointing out the issue.

BEFORE:

w1.domain.com
w2.domain.com
w3.domain.com
w4.domain.com
w1.domain2.com
w2.domain2.com
w3.domain2.com
w4.domain2.com

ADD NEW BINDINGS:

w5.domain.com
w5.domain2.com

AFTER:

w1.domain.com
w2.domain.com
w3.domain.com
w4.domain.com
w1.domain2.com
w2.domain2.com
w3.domain2.com
w4.domain2.com
w5.domain.com
w5.domain2.com

**Comment by Marcus-L** [comment]
Hi @vulwaowf - for your scenario, what order are the bindings listed in IIS Manager's Site Bindings list?

**Comment by webprofusion-chrisc** [comment]
Also relevant to this is #129 currently we don't automatically refresh the bindings after the managed site is created. We could consider also having an 'Automatically update bindings' option whereby be detect and include any added domain bindings (possibly with filter applied) when requesting new certs.

**Comment by vulwaowf** [comment]
IIS Manager bindings has it listed the same way, new bindings are added after the existing ones in the list.

-I suggest you close this case.  Thinking about it and considering that once #157 is implemented, this will really be a non issue.

**Comment by vulwaowf** [comment]
FYI, the filtering on the main Managed Sites area is also not working.

**Comment by Marcus-L** [comment]
Thanks for reporting everything @vulwaowf, it's super helpful. I found many bugs with the Managed Sites Filter and have some fixes coming soon. Will close this one out for now.
