### ISSUE TITLE
HTTPS only bindings and URL rewrites blocking successful configcheck

### ISSUE THREAD

**Issue by JesterEE** [webprofusion/Certify#2]
I'm not a network admin or IT guru ... just a poweruser, so please pardon my misuse of networky lingo or general naivety.

**Server Configuration**
I was using Certify to pull a certificate for a HTTPS IIS based front-end to another application on the back-end (java server).  I'm using IIS ARR and URL rewrite rules to reverse proxy the communication between the user and the java server through an IIS site that is acting as my SSL authentication mechanism.  The site is purposely only configured for HTTPS.  The certificate used when binding the site in IIS was set to another certificate (self-signed) temporarily just to appease the IIS software into letting me proceed.  So, the site is valid at this point.  Traffic goes where it needs to and back, just with an incorrect certificate binding.

**Certify Usage and Issue**
When using Certify with the HTTPS only binding and rewrite rules in place, the configcheck fails.  The failure due to rewrite rules is pretty obvious.  The less obvious is that the check fails over the HTTPS binding.  To work around this, I needed to:
1) Set up a temporary HTTP binding for the site in question.
2) Disable the rewrite rules so the traffic stayed in IIS to communicate with Certify during validation.

**Proposed Enhancement Request**
It would be a nice feature if Certify could identify these scenarios a priori and temporarily fix them on it's own.  Either extend the config check to work over HTTPS as well as HTTP, or validate/set a HTTP binding for the check.  Also, identifying rewrite rules at both the server and site levels that could cause fail-positives in the check, disable them during certificate verification, and then re-enable them afterward.

Thanks for the great software!

Server: Windows Server 2012 R2 (IIS8.5) Powershell v4

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for filing this issue. Unfortunately the LetsEncrypt service which Certify uses only makes http requests for validation. Some people have had luck using redirection, basically the files in ./well-known need to be accessible over http: https://community.letsencrypt.org/t/webroot-only-performs-http-01-challenge-which-doesnt-follow-http-redirects-to-https-site/5557/26
