### ISSUE TITLE
Installer doesn't install localized resource files

### ISSUE THREAD

**Issue by iccfish** [webprofusion/certify#214]
Download installer from offical website (https://certifytheweb.com/) and install it, seems that it doesn't install localized resource files(aka satellite assemblies), which were needed for localization.

Like these directories:

![20171121161416](https://user-images.githubusercontent.com/1091653/33061436-13fa2bb4-ced7-11e7-9db9-66954f61e169.png)

**Comment by webprofusion-chrisc** [comment]
Thanks, this will be fixed in the next release. The setup was missing the option to copy subdirectories.
