### ISSUE TITLE
SAN : can't request certificate

### ISSUE THREAD

**Issue by boscorelly** [webprofusion/certify#215]
#28 @Marcus-L 

Hi,

after reading #28, i am able to see domains i want to create a SAN for.

But i can't request a cert : 
`2017-11-22 15:20:32.866 +01:00 [Information] Beginning Certificate Request Process: Exchange
2017-11-22 15:20:33.080 +01:00 [Information] Attempting Domain Validation: remote.solutek.fr
2017-11-22 15:20:38.384 +01:00 [Information] Failed prerequisite configuration checks (SSL_LetsEncrypt_LocalIIS)
2017-11-22 15:20:38.385 +01:00 [Information] Validation of the required challenges did not complete successfully.`

Configcheck is served : 
`Extensionless File Config Test - OK` (https://remote.solutek.fr/.well-known/acme-challenge/configcheck)

Any idea will be good =)

**Comment by webprofusion-chrisc** [comment]
Hi, yes the config check looks fine. Are you using the http-01 or tls-sni-01 challenge type (under Advanced)? 
It looks like http-01 would work fine for you. If that still doesn't work you can also try unchecking 'Perform challenge response config checks'.

**Comment by boscorelly** [comment]
It worked by enabling http for default website.

My problem is now that i must reconfigure iis with multiples bindings, owa is not working with this config :(

Do you plan to support wildcard certs in january ?

**Comment by webprofusion-chrisc** [comment]
You should also try the tls-sni-01 (this creates a temporary certificate and binds to a temporary hostname on the same IP) - this is an alternative to using http (port 80).

When Let's Encrypt open up the staging API for v2 we will begin work to support wildcards yes, this is slightly dependant on the libraries we use (ACMESharp etc) but either way yes we will eventually support wildcards.

**Comment by webprofusion-chrisc** [comment]
Closing this but have opened a new tracking bug for general discussion around optimisations for Exchange support: #221
