### ISSUE TITLE
How do I create SAN certificate ?

### ISSUE THREAD

**Issue by jjonssondk** [webprofusion/certify#218]
I can't figure how I create a SAN certificate ?
Do I have to modify any files ?

Any help or guide would be very much appreciated :-)

**Comment by webprofusion-chrisc** [comment]
Hi, the main part is to setup bindings in IIS with your domains/subdomains. Then the app will know what they are when you select the website (reloading the app is necessary if you have changed website bindings).

In your IIS website you need to edit the bindings and add http bindings like 'yourdomain.com' and 'www.yourdomain.com', then in Certify choose 'New Certificate' and select your IIS site, it should then list all the domains from your website bindings and you can choose which ones to include in your certificate (usually all).

Hope that helps.

**Comment by jjonssondk** [comment]
Great! Will try that, thx!
