### ISSUE TITLE
Failure to access cert private keys (was 'Problem with extended, overlapping subdomains')

### ISSUE THREAD

**Issue by PromontoryProtean** [webprofusion/certify#219]
I ran into a problem yesterday that is a bit tough to explain, but resulted in me having to uninstall Certify and move sites to another server.

Before the problems began I was running V2.1.25. I had 4 IIS sites set up in the following scenario ("sample" substitutes for the actual domain). All 4 sites share an IP address, but the IP address is dedicated to only those sites.

- www.sample.com (single SSL certificate installed that covered sample.com, www.sample.com,  sample-variation1.com, www.samplevariation1.com, sample-variation2.com, www.samplevariation2.com,, sample-variation3.com, www.samplevariation3.com)
- admin1.sample.com (single SSL certificate installed that covered admin1.sample.com)
- admin2.sample.com (single SSL certificate installed that covered admin2.sample.com)
- admin3.sample.com (single SSL certificate installed that covered admin3.sample.com)

I installed and configured the SSL certificates using Certify. I ran into the IP binding issue (Fix issue where cert bindings are not updated if you have specific binding settings (IP, port etc)) but was able to work around it. I was confident with the app so I purchased a license. I have hundreds of sites that I eventually plan to use Certify with.

Yesterday I needed to set up a staging and development environment for the sample sites above. These sites needed to be on the same machine and used the same IP as the live sites above for various reasons. The IIS sites and domains were:

- dev.www.sample.com
- dev.admin1.sample.com
- dev.admin2.sample.com
- dev.admin3.sample.com

I added the sites to IIS and launched Certify. They were staging sites, but I still needed them to have SSL due to the information exchanged on them. When I launched Certify it informed me that an update was available. I saw that it fixed the IP binding issues so I downloaded and installed it (V2.1.27).

Next I added the dev sites to certify and installed a single certificate for each of the 4 dev domains. This is when the problems started.

Immediately after installing the certificates on the dev sites, my live sites started generating SSL certificate errors. My phone started ringing and I was in a panic so I did not document the exact messages that the browsers were giving me, but if I paraphrase, they were saying that the domain on the certificates did not match the domain in the browser. So somehow IIS was sending a certificate with the domain dev.www.sample.com when I was browsing to www.sample.com.

I checked and rechecked settings in both IIS and Certify, and everything seemed to be configured correctly. I reordered certificates using Certify, deleted and rebuilt bindings in IIS manually and tried some other steps but nothing resolved the issue. After about an hour of chaos I gave up and ordered a standard wildcard certificate for *.sample.com through my certificate provider. When I received the certificate and installed it the sites still did not work, and I continued to get the invalid certificate errors.

At this point I decided to move the live sites to another server. After moving them and installing the wildcard certificate on the other server the sites immediately started working.

So right now I am at a loss. I've done a little bit of research on how IIS stores SNI SSL bindings, and I found bindings for all of the sites at `HKLM/System/ControlSet002/Services/HTTP/Parameters/SslSniBindingInfo`. `netsh http show sslcert` did not show them, however, so I was unable to delete them and I am guessing this persistence may have been contributing to the problems (especially considering that the wildcard cert did not work). But the even weirder thing is that the bindings disappeared after a reboot last night. So I'm not sure if I have any corruption at this point.

If I had to theorize, my guess is that Certify somehow associated www.sample.com and dev.www.sample.com and/or their variations together, maybe due to the longer subdomain paths, and this resulted in some messed up certificates. I wish I could give you more exact error messages and better troubleshooting steps, but it was a live server and my priority at the time was getting the sites back up and running.

I haven't tried the V3 beta yet. Not sure where to go from here. Any idea what might have happened? Any troubleshooting steps that I did not think of that I should have tried?

**Comment by webprofusion-chrisc** [comment]
Hi sorry to hear your having such trouble. Can you provide any of your configuration information privately to apps {at} webprofusion.com and I can take a more detailed look. The configuration I'd need is a zip of your c:\programdata\certify folder.

**Comment by webprofusion-chrisc** [comment]
Looking at this further, thanks for point out the registry path - I wasn't aware of that binding store. I note that your registry path was CurrentControlSet002 which is an alternate (could be last known good) system configuration, although I believe it's normal for the system alternate these. It's possible your reboot switched back to the normal CurrentControlSet? https://support.microsoft.com/en-gb/help/100010/what-are-control-sets-what-is-currentcontrolset

If for some reason we failed to toggle the SNI flag on your binding our code would currently fallback to not using SNI, we should change this to be a hard error.

In windows/IIS in the event that an https binding doesn't use SNI it will effectively take over the https binding for all https bindings on the same IP address, that's the most common reason for the wrong cert being served up. 

The second one that I've found recently is if you have different user accounts for request and renewals IIS can get confused about how to read the private key for the certificate, so then it can't use that cert for TLS. Are all your requests (interactive desktop user) and renewals (scheduled task user) the same user account? 

As an aside, V3 switched to a background service for all requests/renewals using local system but it works around the (worrying) quirk in private key storage by importing the same cert twice which fixes access to the private key.

**Comment by PromontoryProtean** [comment]
Thanks for the feedback. Yesterday got away from me, but I will send the config files to you after I finish this post. Not sure how useful they will be because I uninstalled and reinstalled Certify while I was having problems, but I have a folder in the recycle bin that I think represents my config as the problems were starting.

Regarding the registry paths, I also have a CurrentControlSet001 that has some binding info. After the reboot I checked CurrentControlSet001, CurrentControlSet002 and CurrentControlSet and the sample domain settings were gone from all of them. The link you provided seems to explain this though - my machine was maybe working off of another control set at the time, and the reboot replaced CurrentControlSet002 with the current config.

I'm guessing that your explanation about https binding that doesn't use SNI taking over all the bindings on an IP may be the explanation for my problems. I do recall that each site that failed referenced the same certificate. So maybe a specific binding failed and took everything over. Hopefully/maybe my config files will back up that theory.

Regarding accounts, I did have the nightly task set to use the same account I used to login and install Certify. I noticed something weird yesterday though - my users folder contains an account for dev.admin2.sample.com as if it is a user account, with a desktop folder, my documents etc. No idea how that could have been created or if Certify was involved, but I figured I would mention it here to be thorough.

The private key import bug scares me. I have been working around a very annoying bug in Windows Server 2012 R2 for years - when I try to complete a certificate request in IIS and import it into the Web Hosting store it fails every time. I then have to use the certificate console and cut/paste the certificate from the personal store to the web store. I doubt this is related to the bug you are working around in V3 but it does go to show that certificate management in Windows can be a bit of a black box. I have never understood why such an obvious bug was never fixed.

That actually brings up another question. Any particular reason that Certify puts certificates in the Personal store instead of the Web Hosting store?

Thanks again for the feedback, I'll send the config files soon.

**Comment by webprofusion-chrisc** [comment]
We currently use the My store because that seems to be better supported at the .net API level and it's the one present on server 2008. The 'Personal' aspect of the store naming seems mostly arbitrary.

Currently I'm not aware of any real reason to switch to the Web Hosting store, some articles point to performance benefits but I haven't seen any proof of that. I'm very open to offering the option if there's a benefit though.

Looking at your config there is nothing unusual there. I wonder if you have hit the same bug (for some unknown reason) that I added the workaround for in v3 (the need to re-import the cert). This manifests itself as a successful cert renewal, which works temporarily (presumably while windows still knows the Private Key), then stops working after a short while. In my tests IIS then would fallback to the next working cert (one from a different SNI on the same host) which of course has the wrong domains. 

Then if you open the windows certificate manager and attempt to use All Tasks> Managed Private Keys - you get an error, even the looking at the cert details says that you have a private key. If you attempt to update an IIS binding with this certificate the error is 'Unspecified logon failure', which I think translates to IIS not being able to open the private key associated with the cert (I think the private key has been disposed by windows). 

The only fix I've found so far was to re-import the same pfx. For v3 I also added a 'Re-apply Certificate Bindings' button under the Info tab - this literally re-imports the same cert and re-applies the IIS bindings with the cert hash - this is useful if you delete the old https binding and want to create a new one without requesting a new cert (which counts against your LE rate limit). I am still gauging the permanence of this 'fix' but so far it seems to be holding up well.

**Comment by PromontoryProtean** [comment]
Regarding the Web Hosting store, if I recall correctly the main advantage is in performance when scaling. So 20 sites probably wouldn't matter, but 200-300 might. I think it would be nice to have the option, but it isn't critical for me. I was primarily curious if Certify used the Personal store to work around the import bug I mentioned in my last post. The bug you mentioned in your last post definitely is a weird one, but doesn't surprise me based on my experience with Windows certificate stores. Do you have to do that on all versions of Windows Server?

Based on everything you have described, I am guessing that I ran into the issue where SNI wasn't toggled so whatever binding was configured without SNI took over for all sites on that IP. This would explain why I kept seeing the same domain name in the certificate error. I wish I could go back to when I was having the problem to look for that, but I had to react quickly to bring the sites back online.

This issue does concern me because my plan was to eventually have 25-50 sites per server, using a shared IP, and configured with SSL using SNI. I noticed the recent commit "Fail to install cert if SNI flag requested but couldn't be set." How does this change the functionality? Does it prevent SSL binding from happening if SNI fails? And has this fix been incorporated into the V3 beta that is available on the certifytheweb.com website? I'll start working with V3 soon once that is included.

Appreciate the feedback and the help. These are definitely not easy scenarios to test and debug.

**Comment by webprofusion-chrisc** [comment]
Hi, The SNI flag fail to set issue is most likely to occur on server 2008 r2 or lower. That change was more of a safe guard and likely won't make a difference to you.

I'll be releasing v 2.1.28 with the workaround (double import pfx certificate) for the private key issue within the next hour or so. If were you I'd go ahead an use v3 anyway as that's what's about to become the main release (within the next week).

**Comment by PromontoryProtean** [comment]
Ok, since I'm in no rush to re-install at the moment, I think I'll wait until V3 becomes the main release and/or comes out of beta. Thanks again for the help, and I'll continue to offer whatever feedback I can as things move forward.

**Comment by webprofusion-chrisc** [comment]
Just as an update, V3 is now in general release.
