### ISSUE TITLE
Ceritificate renewal doesn't work

### ISSUE THREAD

**Issue by shelland** [webprofusion/Certify#22]
I'm trying to renew a certificate that was previously requested with the Certify application. I've selected a domain from the Vault -> Domains & Certificates -> my_sample_domain.com tree and clicked Renew and then Auto Apply buttons. A new certificate was created (i can see it in the Server Certificates window in IIS manager) and it's name contains today's date but it's expiration date is the same that was in the previously expired certificate. I've tried to clean SSL certificate cache but it didnt solve the problem. Checked in Windows Server 2012 x64.

**Comment by webprofusion-chrisc** [comment]
I have the same issue, the workaround I'm using is: delete the old certificate from the SSL Certificate manager in windows, then in Certify right-click the domain entry and choose delete. Then request the certificate again.

**Comment by Rookerith** [comment]
This would be a great one to fix!

**Comment by webprofusion-chrisc** [comment]
We also need a validation pass after the certificate has been retrieved from Lets Encrypt - it appears the renewal is working but the issued certificate has expired, which indicates we are requesting the old cert instead of a new one.

**Comment by elmartino** [comment]
+1

**Comment by srb24** [comment]
is there a way to automate renewal as otherwise visitors to the site will have get errors when this is all done manually...

**Comment by potnoodles** [comment]
+1  I have identical outcome on 2 sites with Certify obtained certs. Got email notifications 20 days to expiry. On renewal - new cert friendly names have todays date - but expiry date is same as old ones.

**Comment by soundshed** [comment]
@potnoodles right click the domain in Certify and choose delete. Then create a new certificate request. There is an issue where the old cert identifier is being passed as part of the new request so your getting the old certificate from LetsEncrypt.

**Comment by soundshed** [comment]
Renewal is resolved in the latest version. The issue was mainly to due with Identifier reuse - LE consider Identifiers no longer valid after 290 days
