### ISSUE TITLE
Managed sites list domains missing

### ISSUE THREAD

**Issue by Abrian** [webprofusion/certify#220]
I have created several certificates over the past few months and they always display in the managed sites list. Today they are gone and only showing three items?

What could be the problem?

![image](https://user-images.githubusercontent.com/1838915/33370086-2d15d1c4-d4ff-11e7-838f-6466d0da12ad.png)

**Comment by webprofusion-chrisc** [comment]
Hi Abrian, I've never seen this behaviour before (managed sites disappearing). Can you confirm what version you are on? Also can you confirm there is no text entered into the Filter.. box as that could be limiting the displayed list. I would try closing the app and check of they re-appear when you reload.

You will find your settings under c:\programdata\certify and you will normally have a manageditems.json file which lists all the managed sites if you open with a text editor. Depending on the version you may also have a managedsites.json.bak file with your previous saved list so it's also worth checking that.

From v3 onwards we are now using an SQLite database as saving/loading the json file was becoming problematic for large files (hundreds or thousands of managed sites).

**Comment by Abrian** [comment]
Hi there. Thank you for your reply. I am making use of the latest version. I have examined both the manageditems.json and manageitems.json.bak. They both contain a list of three items. All the other items are missing.

- Could this have happened with an upgrade to a newer version?
- How can I rectify this and get the list to appear as before?

**Comment by webprofusion-chrisc** [comment]
No there are no known bugs which would have caused any issues with upgrading. The most likely problem would be a fault while saving the settings file last time the app was used, then re-opening the app would have overwritten the backup. The only other possibility would be that the programdata has reverted to an older version (perhaps from a system backup being restored?).

Unfortunately there is no way to recover these settings unless you have a backup of that manageditems.json file from a previous date (if your server has backups you can retrieve it from there). Assuming you don't have a backup you will unfortunately need to re-add each of the managed sites.

I would recommend that you try out the beta v3.0 as this moves to a proper transactional database for the managed sites list and is likely to be more robust at managing large lists. I'm also considering the option of backing up settings to our cloud servers but that depends on demand for that sort of feature.

**Comment by Abrian** [comment]
Each missing domain has a certificate already assigned to it. When adding each domain manually again it does not see this generated certificate as per the "Expires in xx days". 

- Should I request a certificate again or leave it as is? 
- Will the auto renew work either case?
- Can the latest version 3 run with version 2 installed?

**Comment by webprofusion-chrisc** [comment]
Hi, v3 will install over the top of v2 so no they can't run side by side (and in fact they would compete with each other if they were). 

Sorry this has unconvinced you so much! Unfortunately the Expires in xx days is metadata held in managedsites so that has been lost here, the app will assume they should be renewed. 

I would set the max renewals per session in Settings to a low number (like 3-5 but greater than 0-unlimited) and re-add them and leave the existing certs. The app (v3 at least) will then gradually renew the certs over the next few hours.

**Comment by webprofusion-chrisc** [comment]
P.s. you could still use v2 but clearly the managedsites save/load has boy been robust enough for you, so you should try v3.

**Comment by webprofusion-chrisc** [comment]
Closing. v3 has a completely reworked database for storage of managedsites settings.
