### ISSUE TITLE
Update RDP Listener / Session Host Certificate

### ISSUE THREAD

**Issue by ThunderbyteComputer** [webprofusion/certify#225]
This is a Feature-Request (sort of)

First I really love yout tool and its way simpler than LEWS!
Specially love the post-request script hook funktion.

What I noticed for the update Remote Desktop Role Script, while working excelent, on Windows Server 2012 R2 / 2016 it does not replace the Certificate for the RDP Listener itself.

This could be done with the following Powershell Command:
`Set-WmiInstance -Path ((Get-WmiObject -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -Filter "TerminalName='RDP-tcp'").__path) -argument @{SSLCertificateSHA1Hash="THUMBPRINT"}`

However, I could not figure out how to obtain the Thumbprint to make this command work.
I'm by no means good at scripting, if you or someone could provide an example on how to make this work would be really great!

Thanks a lot!

**Comment by ThunderbyteComputer** [comment]
I think I figured it out:
`$thumbprint = (Get-PfxCertificate -FilePath $result.ManagedItem.CertificatePath).thumbprint
Set-WmiInstance -Path ((Get-WmiObject -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -Filter "TerminalName='RDP-tcp'").__path) -argument @{SSLCertificateSHA1Hash=$THUMBPRINT}`

I will check and report back if it works, maybe this helps someone else

**Comment by webprofusion-chrisc** [comment]
Cool, let us know how you get on an we could update the example script.

**Comment by ThunderbyteComputer** [comment]
It did the trick for me!

The thumbprint can be looked up in the registry:
Registry path: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
Value name:  SSLCertificateSHA1Hash

**Comment by webprofusion-chrisc** [comment]
We could probably include the cert thumbprint in our result, rather than have you look for it?

**Comment by ThunderbyteComputer** [comment]
This would make the command a one-liner instead of two lines!

However I'm fine with how this is right now. But I guess it would be nice for other scripts to have the thumbprint in the result. So I'd say go for it as it should be that big to code for you I guess (I'm no coder)

**Comment by webprofusion-chrisc** [comment]
Implemented as a sample script in v4
