### ISSUE TITLE
Config Check Failed?

### ISSUE THREAD

**Issue by mehrdadsafari** [webprofusion/certify#227]
why Config checks failed to verify domain address is both publicly accessible and can serve extensionless files e.g. http://domain/.well-know/acme-challenge/configcheck

**Comment by webprofusion-chrisc** [comment]
Hi,
When Let's Encrypt tries to validate your domain it ask us to create a file with a unique name (no file extension) within your website at http://<your domain>/.well-known/acme-challenge/

The 'configcheck' file is a created by Certify SSL Manager to test if your website is accessible and that it can server up an extensionless file. If that passes then it begins the certificate request with Let's Encrypt.

If you can browse to the /configcheck file OK in your web browser (from outside the web servers own network, like a public request would) then you should be good to go. You can try unchecking 'Perform challenge response config checks'.

This method is called 'http-01' validation, you can also try out 'tls-sni-01' validation (under Advanced) if http-01 doesn't work for you.

**Comment by wc-matteo** [comment]
There's something wrong with the latest versions. Config checks are failing even when the test url (e.g. http://domain/.well-know/acme-challenge/configcheck) is working. Disabling config checks works...

**Comment by webprofusion-chrisc** [comment]
Closing. V4 onwards has more robust http challenge validation.
