### ISSUE TITLE
Link to https://certifytheweb.com/ not working

### ISSUE THREAD

**Issue by RenniePet** [webprofusion/certify#232]
Your read-me says download the program from https://certifytheweb.com/ , but neither Firefox nor Edge on my PC can find that site.

**Comment by webprofusion-chrisc** [comment]
Thanks, I can confirm the download site is currently working. It may have been a temporary issue (we're on aws).

If it's still not working for you it's something to do with your connection (try accessing it through your phone data connection to check). It could be a security product blocking it or a DNS issue, or a block at the ISP level.

**Comment by RenniePet** [comment]
OK, your suggestion of trying to use my phone was interesting - it works with Chrome on my Android-based smartphone. But it still doesn't work with Firefox or Edge on my PC, and everything (?) else does work.

Strangely, if I right-click on the Edge error message I get this:

![image](https://user-images.githubusercontent.com/4259011/34282698-c4e6f940-e6c7-11e7-8270-bf0492e89af0.png)

**Comment by RenniePet** [comment]
Wait a minute, now it's working everywhere. But it wasn't working on my PC a few minutes ago, nor when I opened this issue some hours ago, and that worries me, if it possibly has something to do with your use of a Let's Encrypt certificate - assuming that's what you're using. 

Anyway, you're welcome to close this issue, and thanks for making your program available.

**Comment by RenniePet** [comment]
By the way, do you have an email address, for talking about stuff not exactly an "issue" with your program?

**Comment by webprofusion-chrisc** [comment]
This most likely has something to do with your DNS settings, either the server you use or your router settings. DNS error would be nothing to do with the certificate. There are many thousands of people using Certify for their websites, and millions of websites using Let's Encrypt certificates.

**Comment by webprofusion-chrisc** [comment]
If you have general questions you drop an email to apps at webprofusion.com
