### ISSUE TITLE
Add support for FTP sites

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#233]
Currently post request powershell scripting may be used to apply a new ssl cert to an ftp site but it would be ideal to make this process more intuitive and integrated.

**Comment by salarcode** [comment]
❗️

**Comment by frankmcc** [comment]
upvote - I need this also.  Does anyone have a sample powershell script for updating IIS FTP?  If I could implement this as a post-request script, it would solve my immediate problem.

**Comment by moshteitelbaum** [comment]
Another upvote. It would be great if Certify The Web could automatically update IIS FTP sites to use new certs, just as it does with websites.

**Comment by webprofusion-chrisc** [comment]
This feature will be included in the upcoming v5 which is due mid-year.

**Comment by webprofusion-chrisc** [comment]
Implemented in v5 beta.
