### ISSUE TITLE
Educational/Non-Profit Discount

### ISSUE THREAD

**Issue by jpickerell** [webprofusion/certify#235]
Do you offer any educational or non-profit discounts for Certify Professional? I work for a couple of school districts (and on the side sometimes volunteer work for non-profits). Do you offer any kind of discount to these customers?

Thanks!
Jared

**Comment by webprofusion-chrisc** [comment]
Hi Jared, yes we do offer free keys on a case by case basis (registered charities etc) but currently not for large funded organisations (it's $49 dollars, and currently Certify licensing revenue does not really cover all the costs of improving/maintain the project, so we probably need the money more than they need the discount). If your server is running 5 or less sites (i.e. you need less than 5 different certificates) you don't need to register for a key.

Non-profits can apply by sending an email to apps at webprofusion.com - alternatively if someone  provides a good pull request with fixes/changes we need then they can get a free OSS contributor license key that can be used many times.
