### ISSUE TITLE
Consider domain name validation for user input

### ISSUE THREAD

**Issue by cpu** [webprofusion/certify#236]
Hi folks,

I wanted to open a quick issue to mention that there might be benefit to doing some simple domain name validation for the names provided to Certify *before* attempting to create new authorizations for the name with the ACME server.

There seems to be a case where a user can provide a malformed domain name and won't know about it until there is an error returned from the server. This is also aggravated somewhat by the fact that the identifier that trips the DNS name validation error on the server-side may not be echoed back to the user.

See this [forum thread](https://community.letsencrypt.org/t/error-creating-new-authz-dns-name-does-not-have-enough-labels/49614) for a concrete instance where the illegal domain name `"Denver-demo"` was sent to the ACME server but the returned error did not mention this name.

Thanks!

**Comment by webprofusion-chrisc** [comment]
Hi @cpu thanks for passing this on. I was not aware that hyphens where invalid? Is that defined somewhere? From the references I can find hyphens are allowed as long as they are not at the start or end of the domain name.

**Comment by webprofusion-chrisc** [comment]
Ah sorry, I misunderstood. it wasn't the hyphen, it was the lack of .com etc

**Comment by cpu** [comment]
> Ah sorry, I misunderstood. it wasn't the hyphen, it was the lack of .com etc

Yup, exactly :-)

**Comment by webprofusion-chrisc** [comment]
Update: as of 3.0.10 we now filter domains with no "." from results so they can't be selected as certificate hostnames. Additionally updated logging is in place to make sure the dns label error message is carried over to the UI.

**Comment by cpu** [comment]
Thank you!
