### ISSUE TITLE
Certify SSL Manager Service is not started ...

### ISSUE THREAD

**Issue by svenzimmermann** [webprofusion/certify#237]
After Update to new version i can not start certify.

![screenshot_2](https://user-images.githubusercontent.com/27544406/34660926-59880586-f446-11e7-8b80-ab3f101a7cdd.jpg)

What is the name of the service? I can not find them in windows services.

**Comment by webprofusion-chrisc** [comment]
Hi, the service is called Certify.Service. If it's not present you should run the installer again, and ensure you are running as Administrator. If the problem persists please follow up details of the Operating System versions, .Net Framework installed and any other information you can provide that might help.

**Comment by svenzimmermann** [comment]
Thank you. I have reinstalled and the service is back now.

**Comment by webprofusion-chrisc** [comment]
Great, glad you got it working!

**Comment by radekhulan** [comment]
I have same error, with version 3.0.11.
Have installed as admin, reinstalled, verified that "Certify SSL Manager Service" is started, but app cannot connect to it.
