### ISSUE TITLE
Deployment to new Website Root Directory on every deployment

### ISSUE THREAD

**Issue by syska** [webprofusion/certify#239]
Maybe i have missed something.

But is it possible on every "Request Certificate" to update the the "Website Root Directory" path, since I use Octppus to deploy and it deployes to a new directory (the actual version of the website) ... I know I could change this, but I like this setup. Clean directory if some files should have been deleted in the src repository.

I guess it could be done with the "pre-request PS Script", but I feel like this should maybe be part of the actual Certify, since I can't be the only one missing this feature ... or?

**Comment by Marcus-L** [comment]
Try setting the website root directory in the config to `%websiteroot%`.

If you go the PS Script route, there's an example here: https://github.com/webprofusion/certify/blob/master/docs/Request%20Script%20Hooks.md#example-update-iis-site-root-directory-dynamically

**Comment by webprofusion-chrisc** [comment]
Using a blank website root directory or the %websiteroot% variable marcus mentioned then it should be fine. Note: your IIS site id must stay the same.

**Comment by syska** [comment]
@Marcus-L @webprofusion-chrisc 

Awesome, thanks ... so I have missed something ... sweet.

I will look into it.
