### ISSUE TITLE
Dashboard not updating in 3.0.10

### ISSUE THREAD

**Issue by tvanassche** [webprofusion/certify#242]
Last week I updated the app on our 2 production servers from 3.0.9 to 3.0.10. Since installing 3.0.10 however, it seems the dashboard does not get updated anymore. The 2 servers in the dashboard still show the version number as 3.0.9, and new certificates that were added are not visible in the lists.

Is it possible the dashboard updating got broken in the last update? Or does updating the dashboard only work when manually refreshing certificates, and not when using the background scheduler?

**Comment by webprofusion-chrisc** [comment]
Hi,
The client version reported in the dashboard is currently the version that was used to register initially and at the moment we don't update that with every status report.

I can confirm data is currently being received from 3.0.10 clients, and we should be getting your status reports unless there's a fault somewhere.

If you can email me at apps {at} webprofusion.com we can investigate further, I'll need the server machine name and your registered contact email address (or certifytheweb.com registered email address) to investigate.

**Comment by tvanassche** [comment]
Thanks for the quick answer.

I just doublechecked the domain names, and all active domain names seem to be listed for both server. So it seems I made a mistake while compairing the lists earlier this morning. My apologies for this.

One server however still shows 3 failures for sites that had errors while setting up the certificates (non-existing domains were in the bindings, causing the certificate request to fail). Those errors have since been corrected, but as stated above the sites still show as "failed" in the dashboard. 2 of these sites are listed as both succesful and failed. Is this normal? (we deleted the sites and recreated them in the manager to resolve the errors)

PS: I've mailed the account and server name to the email address you provided.

**Comment by webprofusion-chrisc** [comment]
Ah yes, recreating the managed site will make them appear twice - behind the scenes we generate a new GUID for each site, this then gets used as the key when reporting status. We need to add a delete option to the dashboard so you can remove old status reports (or perhaps just tell the dashboard to remove them when you delete them in the UI).

**Comment by tvanassche** [comment]
I see. It's just a minor inconvenience really. Now that I know why it happens, I can easily ignore those failure messages with peace of mind.

Thanks again for the fast replies.
