### ISSUE TITLE
Implement full Getting Started guide

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#244]
Some users struggle to get started, this is most likely due to configuration problems or missing pre-requisites.

We need a full guide (linked in the app) that covers:

- What you need before you start
- What the app will do, and how it does it
- What is Let's Encrypt, what are domain validation challenges (http, dns etc)
- Simple examples
- Common problems and resolutions
- Advanced topic (scripting etc)

**Comment by webprofusion-chrisc** [comment]
- For users with restrictions on outgoing http/https detail the api endpoints the app will need to connect to for normal functionality

**Comment by Zoly101** [comment]
Hi!
Can you help me with Certify The Web programme?
I wanted to use this for my own website that I'm running on my VPS.
This VPS is fully clear, so basically it's just an operating system which is windows server 2012.

Well...

I'm starting IIS 10... It's done, alright. I'm making a new domain, by freenom. (dot.tk)
It's also done, I'm setting up after this the IP address to my domain, that I made.
I'm checking what's up with my website... It's loaded, so everythings maybe gonna be alright.
I'm starting Certify The Web application, it's loaded. It request me an a valid e-mail address. I typed it, and press on the button what says, register contact. It's done, now I'm trying to make an SSL certificate by this application, I'm chosing my website from IIS 10, by the select input box. It's done. I'm going to press the save button in the application to save this stuff, and after this I'm pressing on Request Certificate button, and loading for a sec...But then, I always getting the next messeage: 

[INF] Config checks failed to verify http://*****.tk is both publicly accessible and can serve extensionless files e.g. http://*****.tk/.well-known/acme-challenge/configcheck

I had look for this error messeage, I found another application than supposedly I should to install to my VPS, I install it... It was the Let's enctryp or something like that. This application also have a problem, It needed me install the Visual Studio, I installed it, and tried to start the application, it was alright. I closed everything exepct IIS 10, and my website. After this, I'm just starting the Certify The Web application again, and remove my previous request, and trying to make another one, which is going to work... hopefully. Buuuuut, It also just saying the same messeage. 

What the holly fart that I should to do?
Please help me with this. I can't find on the internet what's the problem.







I also turned on, in IIS 10 later, to show me what's the problem more specifically, but It actually said nothing interesting.

**Comment by webprofusion-chrisc** [comment]
Implemented here https://docs.certifytheweb.com/
