### ISSUE TITLE
Staging Flag

### ISSUE THREAD

**Issue by Wxfisch** [webprofusion/certify#247]
It would be nice if we could test configuration against the staging environment for LetsEncrypt. This would be helpful to avoid hitting rate limits on failures while working out DNS and firewall issues for websites as well as any other configuration issues. Perhaps you could issue the first certificate for a new website against the staging environment until it is successful and then issue a new, valid one against the production environment for a valid certificate to be used going forward?

**Comment by webprofusion-chrisc** [comment]
Hi,
This has been requested via #162 also. Currently the design uses the ACMESharp vault for internal storage of account keys etc, this is tied to the endpoint (live/staging) being used, so we'd need to start a new vault.

There's a few bits of work required, so it's probably not likely to happen very soon, but I'm not dismissing the idea altogether.

Note that we purposefully try to do config check diagnostics before we make a request to LE (to avoid rate limits). That's also what the 'Test' button let's you do, under Advanced.

**Comment by webprofusion-chrisc** [comment]
Implemented in v5, use can add a staging account and select whether to use staging at the managed certificate level (Certificate> Certificate Authority, Let's Encrypt - Staging)
