### ISSUE TITLE
New update is incorrectly labeled v3.0.12

### ISSUE THREAD

**Issue by vulwaowf** [webprofusion/certify#249]
FYI, New update is incorrectly labeled 3.0.12 when the update is in fact 3.0.11.30336.

![image](https://user-images.githubusercontent.com/30328500/35416748-4ab133a6-01f8-11e8-9629-7db8438ff9a4.png)

**Comment by webprofusion-chrisc** [comment]
Thanks for pointing this out! Fixed now.
