### ISSUE TITLE
Implicit assumptions: http website dedicated to domain name.

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [webprofusion/certify#25]
Hello,

Using certify client. First it did not find website in IIS config. Had to figure out website had to specify domain. Perhaps program should hint.

When requesting certificate, a dialog said: "Automated checks for extensionless content failed."
https://my-website/.well-known/acme-challenge/configcheck is served okay.
Actual problem was: certify client assuming website had a http binding, while it actually had https binding (with a dummy certificate). Worked when changed binding to http. Perhaps program should hint.

Thank you for your attention.

**Comment by webprofusion-chrisc** [comment]
Thanks, yes we do need to provide more guidance, perhaps a configuration check summary screen.

**Comment by webprofusion-chrisc** [comment]
Closing. v2 UI now has text explaining the required access (http).
