### ISSUE TITLE
Windows SmartScreen Filter Reports CertifyTheWebSetup.exe as unsafe

### ISSUE THREAD

**Issue by kiddailey** [webprofusion/certify#250]
This is more of an FYI than a bug report, but figured it was worth mentioning.  When I attempted to download the CertifyTheWeb installer today from a machine using IE 11 with the default recommended settings, the browser refused to download the installer.  Instead it blocks the download and reports:

> This unsafe download was blocked by SmartScreen Filter. [Learn More](https://support.microsoft.com/en-us/help/17443/windows-internet-explorer-smartscreen-filter-faq)

I tested downloading some other well-known installers that are executable files and only the CertifyTheWebSetup.exe seems to have an issue.

Edit: I should also mention that if I download an uncommonly downloaded EXE, the download proceeds, but the browser gives a warning instead of blocking, stating:

> ... is not commonly downloaded and could harm your computer

So it appears that something with the CertifyTheWeb installer is specifically triggering a block.

**Comment by webprofusion-chrisc** [comment]
Thanks! This is new. We specifically go to the effort of digitally signing the exe and the contents of the build so that we can avoid problems with smart screen etc (and to assure the build comes from us). Will investigate.

**Comment by webprofusion-chrisc** [comment]
So further to this, I think someone 'pranked' us and reported the exe/site to microsoft (or they did it just to be malicious, which is ironic). Will see if we can get a dialogue going with Microsoft but that could take a while.

**Comment by kiddailey** [comment]
Thanks for the quick response!  Hoping it can be resolved and eager to hear when/if it is.

**Comment by webprofusion-chrisc** [comment]
Just to clarify, there's nothing actually wrong with the download, it's just MS. I suspect it's because we don't have a privacy policy link on our website maybe, and they've either automatically classified it or someone reported it to them as an issue without first asking us about it. 

If you can use google chrome to download (or curl, or powershell) then the direct link is
https://certifytheweb.com/downloads/CertifyTheWebSetup.exe

**Comment by webprofusion-chrisc** [comment]
This is now resolved.

**Comment by kiddailey** [comment]
Thanks and confirmed :)
