### ISSUE TITLE
Support for ECDSA private keys

### ISSUE THREAD

**Issue by rhymeswithmogul** [webprofusion/certify#252]
ECDSA private keys have several advantages over traditional RSA keys.  Are there any plans for Certify to offer the user a choice of algorithm and strength when generating a key?

**Comment by webprofusion-chrisc** [comment]
Hi, yes - it hasn't been requested very often but we can offer that. 

We're currently in the middle of a large set of changes for v4 so we'll just need to figure out what's involved, probably not much (famous last words!).

**Comment by webprofusion-chrisc** [comment]
So v4 will have support for ECDSA when creating your certificate signing request. The other key that may be relevant is the private account key used when talking to lets encrypt API (creating orders etc). I'm assuming that this is not the one you mean in your question?

**Comment by webprofusion-chrisc** [comment]
Closing. Implemented in the upcoming v4 alpha/beta,
