### ISSUE TITLE
New Issues save crt to diy folder

### ISSUE THREAD

**Issue by ckhker** [webprofusion/certify#253]
try to change VaultManager.ExportCertificate
`	string text8 = Environment.CurrentDirectory + "\\data\\" + identifierDns;
	if (!Directory.Exists(text8))
	{
		Directory.CreateDirectory(text8);
	}
	string destFileName = text8 + "\\" + identifierDns + "-key.pem";
	string destFileName2 = text8 + "\\" + identifierDns + "-csr.pem";
	string text9 = text8 + "\\" + identifierDns + "-crt.pem";
	string destFileName3 = text8 + "\\" + identifierDns + "-crt.der";
	string destFileName4 = text8 + "\\" + identifierDns + "-all.pfx";
	string text10 = text8 + "\\ca.pem";
	string destFileName5 = text8 + "\\ca.der";
	string path = text8 + "\\" + identifierDns + ".txt";
	ACMESharpUtils.GetCertificate(certRef, text, text2, text3, text4, text5, text6, text7, null, null, true, null);
	File.Copy(text, destFileName, true);
	File.Copy(text2, destFileName2, true);
	File.Copy(text3, text9, true);
	File.Copy(text4, destFileName3, true);
	File.Copy(text7, destFileName4, true);
	File.Copy(text5, text10, true);
	File.Copy(text6, destFileName5, true);
	string contents = File.ReadAllText(text9) + Environment.NewLine + File.ReadAllText(text10);
	File.WriteAllText(path, contents);`
default folder is hard to find Generated certificate. maybe you can save all certificate to a diy folder

**Comment by webprofusion-chrisc** [comment]
Hi, The generated certificate path is shown on the Info tab and is available for scripts using the CertificatePath property: https://github.com/webprofusion/certify/blob/master/docs/Request%20Script%20Hooks.md

**Comment by webprofusion-chrisc** [comment]
Closing. This feature (custom cert copying) is available via scripts.
