### ISSUE TITLE
Attempting to register product resulted in error

### ISSUE THREAD

**Issue by NCSAdmin** [webprofusion/certify#254]
<img width="897" alt="certify the web error" src="https://user-images.githubusercontent.com/35908281/35897647-d923f950-0b87-11e8-968c-bf60eb400cae.png">

This happened because of Chase fraud detection.  Once I accepted the transaction it charged my card but I don't have a registration key to use to register the product now.  Any help would be appreciated.

Thank,
Marshall Alan Hill
Nimble Cloud Solutions, LLC
ahill@nimblecloudsolutions.com

**Comment by webprofusion-chrisc** [comment]
Hi Marshall, thanks, your transaction failed and you have not been charged. I'll send you an email privately, this is a public issues register and not really for sensitive support issues like payments.
