### ISSUE TITLE
Make background service port configurable

### ISSUE THREAD

**Issue by radekhulan** [webprofusion/certify#256]
I am getting this error, with version 3.0.11. Had 2.* installed, which run well, upgraded, and getting this.

Have installed as admin, reinstalled, verified that "Certify SSL Manager Service" is started, but app cannot connect to it.

**Comment by radekhulan** [comment]
Windows 2012 R2, .NET 4.7

**Comment by webprofusion-chrisc** [comment]
Thanks, the service runs bound to localhost port 9696, assuming you have windows firewall running it could be it's set to block local port connections. Alternatively there may be something else running on that port already?

**Comment by radekhulan** [comment]
Service seems to be running on assigned (public) IP address, and I can connect to it, but not on 127.0.0.1.

**Comment by radekhulan** [comment]
Not sure how it is related, but adding localhost to IIS:
netsh http add iplisten ipaddress=127.0.0.1

made it working..

**Comment by webprofusion-chrisc** [comment]
Interesting. The reason we bind to localhost is so that the service it's not bound to the public IP, so that even if you don't have a firewall you still wouldn't be able to connect to it remotely (or via the internet). Do you have a custom entry in your hosts file for localhost? c:\windows\system32\drivers\etc\hosts

**Comment by webprofusion-chrisc** [comment]
Ah, according to this https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-http-and-https is any other service is registered in the 'IP Listen' list then every other service needs to also be registered in that list, so there's probably just some other app already running an http listener or similar (not just IIS).

**Comment by radekhulan** [comment]
I've used "netsh http add iplisten" command to force IIS to listen only on 2 public IP addresses I have on that server, and excluding (default) 127.0.0.1. Adding localhost back to IIS made your utility working again.

Interesting fact is service was using public IP address, but app is probably "hardwired" for localhost?

**Comment by webprofusion-chrisc** [comment]
Yes, the service http listener is bound to localhost:9696, however we could perhaps make it configurable through an environment variable

**Comment by webprofusion-chrisc** [comment]
Re-opening for now as I think making this configurable would be potentially useful.

**Comment by webprofusion-chrisc** [comment]
This now auto configured to an available port starting with the latest v4 beta. It is also now possible to specify config via a configuration file if required.
