### ISSUE TITLE
[QUESTION] What if you don't use IIS?

### ISSUE THREAD

**Issue by DumbJoe** [webprofusion/certify#257]
Is there a manual method of selecting your domain?

**Comment by webprofusion-chrisc** [comment]
Hi, in the current version there is no manual way to specify domains, however in the next version (4.x) currently in development you can also manually specify domains (including wildcard domains) and you won't need to deploy to IIS.

Out of interest, what are you trying to do?

**Comment by DumbJoe** [comment]
Oh cool, I guess I'll have to wait till then; any ETA on release 4.0?

I had a look at ACMESharp and apparently Certify is a GUI version of that full fledged command line shell program https://github.com/ebekker/ACMESharp (which is also comparable to the original certbot program by lets encrypt which only runs on *nix operating systems and I run windows.....) and I'm not much on CLI type interface person but was gonna try anyways, but then after reading their page fully I got to the end under the "Related Links" heading, I saw "A GUI interface to this project's PowerShell module" so thought oh hey that's neat, I might try that easier more noob/newb friendly version. 

So I come here, go to your website and download it, install it and then run it only to see domains is blanked out and is unselectable or any way to type in the domain yourself. So I looked it up on here why it is and apparently you need to have been using IIS for this to work.... Well I don't use IIS(if my google search is enough, it tells me IIS is more or less equivalent to my XAMPP that I use.....), I use XAMPP which is different.....yes XAMPP has it's own self-signed certificate but most users would not allow the installation of this self-signed certificate(either they don't know or don't want to after reading the warning or just can't be bothered to add it in everytime the browser removes it), whilst others who are computer literate would be fine and reading it as "Oh this guy has a self-signed certificate, fair enough, I'll just go add that to my collection; no biggie!" and then proceed to view the site's contents. 

And here I am wondering why IIS is a requirement....

So yeah besides solving the part where the user needs to re-save the self-signed certificate everytime they wanna visit the site, I would also like to have a nice green padlock next to my site's url to show that I'm authentic and not playing around! ☺

Also what initially sparked my interest was happening upon this reddit post: https://www.reddit.com/r/Steam/comments/7ivmwl/this_is_why_steam_needs_to_use_https_exclusively/ and then reading this page about *why* HTTPS is a *must* explaining various reasons(except the question "But what if I can't be bothered setting it up?" which someone already kindly pointed out in the comment section...hahahaha): https://doesmysiteneedhttps.com/ and yeah, that's the full story....

**Comment by webprofusion-chrisc** [comment]
Thanks for the info :)

v4 will most likely be March as it is built around the new v2 Let's Encrypt API (which comes our around then).

In the meantime you may have more luck using letsencrypt-win-simple (a popular command line tool) as I believe you can probably that with apache: https://github.com/Lone-Coder/letsencrypt-win-simple

We target IIS as that's the built-in windows web server (since about 1995), using Apache is more common on linux than it is on Windows, but plenty of people do indeed use it and we will eventually support it.

**Comment by webprofusion-chrisc** [comment]
p.s. yes, the self signed certificate route is just not worth going with as it's likely to cause more confusion than anything.

**Comment by DumbJoe** [comment]
> In the meantime you may have more luck using letsencrypt-win-simple (a popular command line tool) as I believe you can probably that with apache: https://github.com/Lone-Coder/letsencrypt-win-simple

yes I'll give them a try thanks.

>We target IIS as that's the built-in windows web server (since about 1995), using Apache is more common on linux than it is on Windows, but plenty of people do indeed use it and we will eventually support it.

Are you going to support Apache in v4.0?

>p.s. yes, the self signed certificate route is just not worth going with as it's likely to cause more confusion than anything.

I agree....only useful in a private organization where everyone knows what it is...

**Comment by webprofusion-chrisc** [comment]
@DumbJoe Apache (likewise nginx) won't specifically be in v4 however it will be possible using a combination of manual domain entries, a small amount of custom scripting (to deploy the certificate) together with one-time apache config to setup https/point to the certificate. 

I haven't used Apache in a long time so I'm not currently up on how to configure it.

**Comment by DumbJoe** [comment]
....oh lovely....

**Comment by n3cr0cr0w** [comment]
Once the Apache server is setup it is just a matter of saving the new certificate over the old one and restarting the Apache service. As long as you can save the certificate files in the PEM format and then setup a manual domain entry in Certify everything should be simple.

**Comment by webprofusion-chrisc** [comment]
TODO: Pem export option to avoid having to script the export yourself.

**Comment by webprofusion-chrisc** [comment]
Implemented in v5 as Deploy to Apache deployment task. Can be used with the new Service Manager task to then restart Apache service as required.
