### ISSUE TITLE
No applicable IIS sites configured

### ISSUE THREAD

**Issue by JasonBSteele** [webprofusion/Certify#26]
Hi, I'm a new user.

I get the message "No applicable IIS sites configured" when I click the button to create a new certificate. 

I am running on Windows 10 and IIS has the Default Web Site  running with bindings for ports 80 and 443, any IP.

Is there something I need to do to make the site suitable?
Thanks

**Comment by webprofusion-chrisc** [comment]
Before you can request a certificate from LetsEncrypt you need to have a domain configured on your site bindings and the site must be remotely accessible via http (ironically).

**Comment by JasonBSteele** [comment]
Thanks, that was it - the domain name needed to be added to the bindings too.
