### ISSUE TITLE
Let's Encrypt Account ID

### ISSUE THREAD

**Issue by kd8ssq** [webprofusion/certify#261]
I'm looking into adjusting the rate limits for lets encrypt and I'm told that I should request all certs through a single ACME account.  I have several servers that would need to be setup under the same account.  How would I go about doing this using the Certify software?  I don't see it mentioned anywhere in the docs.  

https://docs.google.com/forms/d/e/1FAIpQLSetFLqcyPrnnrom2Kw802ZjukDVex67dOM2g4O8jEbfWFs3dA/viewform

https://letsencrypt.org/docs/account-id/

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this. No we don't currently have support for sharing the account across installs.

You could theoretically copy and paste the Registrations part of c:\programdata\acmesharp\sysvault\00-VAULT but you'd also need to copy the related private key, I doubt that it would really work.

If you are requesting many subdomains we will be implementing wildcard support when the let's encrypt v2 api goes live, so you can request one cert for *.example.com then distribute it as required.

**Comment by kd8ssq** [comment]
Ok.  Yeah, I work for a hosting provider that's looking to implement Let's Encrypt and we have thousands of domains that will need to be setup. 

Thanks

**Comment by webprofusion-chrisc** [comment]
We have a bulk import from CSV feature that might be of interest. In general we do have some optimizations aimed at large installations. You can email apps (at) webprofusion.com if you would like to discuss in more detail.

**Comment by kd8ssq** [comment]
Will do.  Thanks
