### ISSUE TITLE
Request Certificate: Access Denied

### ISSUE THREAD

**Issue by maxelzon** [webprofusion/certify#262]
Tried to request a certificate for a domain.
Windows server 2012 r2
IIS 8.5

![image](https://user-images.githubusercontent.com/27772416/36435143-27811ac2-1661-11e8-8781-c9794fe51fa0.png)

**Comment by webprofusion-chrisc** [comment]
Very interesting! There are thousands of people using the app and this is the first time I've seen this. Have you customised the user account that the background service runs as? By default it's Local System.

**Comment by maxelzon** [comment]
Running the SSLManager as administrator probably solved the problem now. Thanks!
