### ISSUE TITLE
http-01 Keeps generating web.config file that causes 500 error

### ISSUE THREAD

**Issue by inthebrilliantblue** [webprofusion/certify#263]
Im trying to setup my site intheradicalred.com, I already have static files setup. I can see the configcheck file (or atleast download it in a browser). But whenever certify starts the cert process, it creates a web.config file (that I dont need) and breaks the acme-challenge folder with a 500 error. Is there a way to prevent it from generating the web.config file?

**Comment by inthebrilliantblue** [comment]
Just confirmed it by removing these lines from the web.config:

  <handlers>
      <clear />
    <add name="StaticFile" path="*" verb="*" type="" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" scriptProcessor="" resourceType="Either" requireAccess="Read" allowPathInfo="false" preCondition="" responseBufferLimit="4194304" />
  </handlers>

I also changed the text/json to text/plain for the mime type. It seems to work with that. I would still like more control over what it generates in the web.config file under acme-challenge.

Im currently running Server 2016, IIS10.

**Comment by webprofusion-chrisc** [comment]
Thanks, we do need to generate the web config usually but I thought we only overwrite the existing one if the current one doesn't work. The next release will have a broader set of alternative web.configs and have the option for you to specify a new default web.config used in configuring requests.
