### ISSUE TITLE
IIS 10 - Error 500 on test

### ISSUE THREAD

**Issue by SonycCZE** [webprofusion/certify#273]
Windows Server 2016 / IIS 10 / Certify 3.0.11

Windows Server 2016 / IIS 10 / Certify 3.0.11

Hi, when i try to test my site i get error about not accessible files from internet. Certify generate files for check, but when i try to get in folder (from different internet connection - publicly) ../acme-challenge/ i get error 500.

When i manualy delete web.config file in folder /acme-challenge/ it works fine, but "Test" will generate it again and error come back.

Thanks for any help.

**Comment by SonycCZE** [comment]
I wil disable "Perform web application auto config" but Certify still generate web.config file.

**Comment by SonycCZE** [comment]
From localhost i get this error page:

Error 500.19 - Internal Server Error
The requested page can not be accessed because the related page configuration data is not valid.

Error Code: 0x80070021

But i dont know what is it (i will found something about locking additional configuration of sites, but i dont know how to disable it).

**Comment by webprofusion-chrisc** [comment]
Hmm, sounds like IIS is getting confused, you may need to restart it. You generally need a web.config (so that extensionless files in the /acme-challenge folder can be served). The most common issue is that we have a <clear/> directive in the web.config that some setups (especially shared hosting configs) don't like, so taking that out should work.

Once you can manually brower to the http://<yourdomain>/.well-known/acme-challenge/configcheck file you should be ready to go.

**Comment by SonycCZE** [comment]
Hi, thanks for fast reply. I will restart site, service and whole server but whitout effect.

No sharing config. No server farm, just this one vanilla IIS (virtual server only for web server).

Whitout web.config file is all file accessible from internet whitout problem. Is any option to disable generating web.config file?

**Comment by SonycCZE** [comment]
When i will delete <handlers>...</handlers> from web.config it works. And test pass.

**Comment by SonycCZE** [comment]
Yes, the entire process WORKS!

https://https.mkostrov.cz/ (test site).

**Comment by webprofusion-chrisc** [comment]
Closing. An updated method for web.config auto configuration will be included in v4 #270

**Comment by dowen01** [comment]
I am still having this issue, I dont fully understand how you got past this as every time remove the web.config or change it, it gets reset and put back to its non working state

**Comment by webprofusion-chrisc** [comment]
@dowen01 outside of the app, if you fix access (by adjusting the web.config to suit your configuration) to the acme-challenge path the app will then test if it can make an http request to the configcheck file. If that's ok it doesn't do any further configuration. Alternatively if your web.config is fine,  disable the auto config and config check options under Advanced, then try your request.

**Comment by dowen01** [comment]
The tick box did not seem to stop the config being created, I rolled back to a v2 and it worked perfectly
