### ISSUE TITLE
Manually add Domains

### ISSUE THREAD

**Issue by Jaggl-AT** [webprofusion/certify#274]
Hi,
why is it not possible to manually add domains?

i run into a problem with Exchange 2010, there you can not define multiple domains on the same IP, because when you do this the Autodiscover Service is not working...

so i stay at the default bindings...
http *
http 127.0.0.1
https *
https 127.0.0.1

but with this, certify is not working, because no hostnames where defined :)

so what i did was, create my hostnames, so that certify let me create the cert and then i deleted the hostnames, so that Autodiscover is working....

but what is when the cert get renewed and there are no hostnames in the IIS website? Will certify renew the cert with the original configured hostnames or will certify fetch hostnames before the renewal?

**Comment by webprofusion-chrisc** [comment]
@Jaggl-AT Hi, manually added domains will be supported in the next release (v4) you can participate in the alpha/beta testing by joining the conversation in issue #270

I don't know much about Exchange configuration myself but I believe the automatic http/https binding for 127.0.0.1 (localhost) causes all sorts of problems: https://community.spiceworks.com/topic/348158-exchange-2013-ecp-owa-issue-something-went-wrong

**Comment by Jaggl-AT** [comment]
OK thx for the answer ;)

**Comment by webprofusion-chrisc** [comment]
Implemented in current v4 beta.
