### ISSUE TITLE
Problems with Certify 3.0.11

### ISSUE THREAD

**Issue by Teralaw** [webprofusion/certify#279]
Hi,
I upgraded Certify from version 2.0.11 too version 3.0.11 and now i got every time i requested a certificate this error:

2018-03-26 23:44:39.026 +02:00 [INF] Performing Config Tests
2018-03-26 23:44:42.241 +02:00 [INF] Config checks failed to verify http://beisei.de is both publicly accessible and can serve extensionless files e.g. http://beisei.de/.well-known/acme-challenge/configcheck

Befor the upgrade to version 3.0.11 i did not have this problem. So it is possible to get a Certify version 2.0.11 installer?

Best regards
Gerret Lose

**Comment by webprofusion-chrisc** [comment]
Hi Gerret, I've also replied to your email. Sorry we don't support downgrading.

 Your server is responding with error 500 to the configcheck url, can you try editing the web.config under /.well-known/acme-challenge and remove the <clear/> directive. This is normally an issue if your server is configured to disallow config override in web applications.


You can also uncheck config check etc under Advanced.

**Comment by Teralaw** [comment]
Removing the web.config and the /.well-known/acme-challenge directory + disabling config check under Advanced options fixed my problem.
Thanks for help
