### ISSUE TITLE
[Feature] - Implement SAN support (multiple domains per cert)

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#28]
Certify needs to allow multiple domains per cert using SAN. This requires that each domain binding is accessible and validated before the certificate can be issued by LetEncrypt. common scenarios are supporting www.domain.com and domain.com in single site but can include multiple different domain names).

**Comment by plan-reduc** [comment]
I'am looking for a similar solution, my problem is i have a cert for www.domain.com and i need to get it for all of my subdomain, then a cert for *.domain.com would be great, there is way to do it ? or another way is to get one cert for : domain.com and www.domain.com in the same cert

how to do this ?

thanks

**Comment by Concept211** [comment]
Is this being worked on?

In a thread on the Let's Encrypt forum, it seems it's just a matter of specifying the two domains (www.domain.com & domain.com) plus an alias parameter when requesting the certificate. Not sure how difficult it would be to implement into your existing code?

https://community.letsencrypt.org/t/www-and-non-www-one-certificate/18127/13

**Comment by soundshed** [comment]
This is being working on and there is preliminary UI in the branch san-and-auto-renew https://github.com/webprofusion/certify/tree/san-and-auto-renew - this will be included in the next release when completed.

**Comment by rklrkl** [comment]
That link to the san-and-auto-renew branch no longer works - does that mean that the SAN code is now in the master? SAN support, IMHO, is critical functionality that all Let's Encrypt clients should have (at the very least, you usually want www.domain.com and domain.com to both work on a single cert, even if you set it up to redirect one to the other). Until SAN support is added to Certify, it's not a Let's Encrypt client I could recommend to other people.

**Comment by webprofusion-chrisc** [comment]
@rklrkl yes, that feature work has been merged into Master. There are a couple of bugs and some features to finish off but the current estimate is that Certify 2.0 should be released in about 3-4 weeks, including configurable SAN support and Auto Renewal. 

SAN support was a feature that LE added after Certify was first developed, which is why it wasn't included in the first instance. Auto Renewal is a bit trickier as it requires extra information about the operation to be repeated (preferred bindings, optional SAN components etc) and required headless (CLI) renewal operation but that's mostly done now in the upcoming release.

**Comment by webprofusion-chrisc** [comment]
Closing. V2 alpha is now available and includes SAN support.

**Comment by Concept211** [comment]
Working great - thank you!

**Comment by 1liminal1** [comment]
Hi guys, 

Is there a guide for this? I don't see anyway to configure SAN certs. 

It only shows me my default website with no way to add domains from the server farm.

**Comment by webprofusion-chrisc** [comment]
Hi @1liminal1, your website on your server in IIS must have all the domain bindings you use for the app to see them  (as existing http or https bindings), it then uses this list as the entries for your SAN certificate. When you say server farm, what are you actually trying to do?

**Comment by 1liminal1** [comment]
Thanks for that info, so I'm using IIS for URL rewrite for all my internal websites, mail ect. Comes in on the one IP and then depending on the URL sends it to the appropriate site and port, using Server Farms

Basically this 

http://www.markc.me.uk/blog/files/ConfigureARR.html

**Comment by Marcus-L** [comment]
@1liminal1 - You have to add all the domains you want to create a SAN certificate for into the bindings for a site in IIS Manager, on the same server that Certify is installed:

![screenshot_111117_110147_pm](https://user-images.githubusercontent.com/1369184/32696098-59f3ff50-c734-11e7-87f9-f255e218bdb7.jpg)

After you do this, close and re-start Certify, then click "New Certificate" and ensure all the domains you would like to add to the SAN certificate have the "Include" checkbox checked:

![screenshot_111117_110430_pm](https://user-images.githubusercontent.com/1369184/32696104-ad822282-c734-11e7-9cb9-38164f41bb93.jpg)

**Comment by 1liminal1** [comment]
Thank you, I understood that. But I guess the question is, will this adversely affect the server farms I have set up?

**Comment by Marcus-L** [comment]
Try it on a few test domains, or a small subset of your web farm, and if it works go bigger. Certify is the easiest to use tool for configuring IIS with Let's Encrypt certificates, and it should be able to do what you are trying to do. Good luck.

**Comment by 1liminal1** [comment]
It didn't work, ill post the error when I get home :)

Thanks for all the help guys!

**Comment by 1liminal1** [comment]
Hey, sorry its taken a while to get back to this. 

Still getting an error unfortunately, any ideas where I'm going wrong?

Thanks so much 

![capture](https://user-images.githubusercontent.com/10505942/32976947-f37a3a80-cc76-11e7-8251-b4cd729da291.PNG)

**Comment by 1liminal1** [comment]
Hey, sorry its taken a while to get back to this.

Still getting an error unfortunately, any ideas where I'm going wrong?

Thanks so much
![capture](https://user-images.githubusercontent.com/10505942/32976960-53ac659a-cc77-11e7-9b2c-f3307d55f629.jpg)

**Comment by webprofusion-chrisc** [comment]
@1liminal1 yes, your server is not able to serve the files from the .well-known/acme-challenge/ path. Try using the 'Advanced' tab and change to tls-sni-01 instead of http-01. You are probably using a content management system or similar app which is configuring special handlers for extensionless file paths. 

If you need to stick to http-01, you can alternatively try also editing the web.config we generate in the  .well-known/acme-challenge/  to remove the <clear/> directive and see if that still errors in the browser. Once you can get http://<yourdomain>/.well-known/acme-challenge.configcheck file to serve up, just disable 'perform web application auto config' so we don't overwrite the web.config and request as normal.

**Comment by 1liminal1** [comment]
Hey, thanks for that, 

You have mentioned that before and I am running that setting.

If I set that challenge type and click test, it gives me; Configuration Check Failed. 

Im running IIS with URL rewrite and server farms to connect to multi backed websites. (Exchange, Kodi, other media stuff) and using LetsEncrypt so they have SSL certs.

**Comment by webprofusion-chrisc** [comment]
@1liminal1 ah yes, did you confirm which version of Certify you are on (the latest is 2.1.27) and that you are running Certify on your primary server (the one acting as the proxy to the other services). Only tns-sni-01 or a DNS challenge will work. We currently don't support DNS challenges, but you could look at letsencrypt-win-simple which does support some.

**Comment by 1liminal1** [comment]
Hi there, 

I just upgraded to the latest version. And yes, running this on the proxy, it finds all the domains after I set the bindings. But I'm not sure what the issue is with the challenge. 

Is there a more verbose logs I could run that would give more context. 

Shane

**Comment by 1liminal1** [comment]
Hi thanks so much for the advice, I managed to get this working though win-simple. 

Thanks
