### ISSUE TITLE
Challenge Test failed without any more specific error

### ISSUE THREAD

**Issue by StefanEgo** [webprofusion/certify#280]
When I run the tls-sni-01 challenge type test with "Perform challenge response config checks" enabled, I get an error popup:
"Challenge Test Failed

Configuration Check Failed:"

The confusing thing is that requesting the certificate actually works, and neither the popup window described above nor the log file shows any error. Still, I do get this error popup.

Please let me know if I can provide any further details to trace down the issue. Note that this has very low priority for me, since other than the unexpected error popup everything seems to work fine.

Environment is:
Certify 3.0.11.30336
Windows 2012R2
IIS 8.5

**Comment by webprofusion-chrisc** [comment]
@StefanEgo I'm not sure why the config check would fail but as Let's Encrypt have disabled tls-sni-01 for anything other than renewals I'll actually be removing this option from the next version. The good news is the new version (v4) will be getting a more details test results UI for config tests so most config check failures should detail some kind of explanation of what went wrong.

**Comment by StefanEgo** [comment]
@webprofusion-chrisc , thanks for getting back so quickly on the issue. FWIW: I agree with your action to close the issue in light of the upcoming version having more detailed test results.
