### ISSUE TITLE
[Question] support for load balanced website?

### ISSUE THREAD

**Issue by brechtvhb** [webprofusion/certify#281]
I have a website that is load balanced on 2 servers. Is it possible to automaticly renew the certificate on one server and update the other server with the new certificate?

**Comment by webprofusion-chrisc** [comment]
Yes, is your storage shared or replicated with minimal latency? If so you can have one server act as the primary in charge of certificate renewals, you can the use a PowerShell script to copy the new certificate (under Advanced Post-Request powershell) to a folder both servers can see. 

If your IIS config is manually kept in sync then your secondary server would need a script to pickup and apply the certificate or use central certificate storage.

**Comment by webprofusion-chrisc** [comment]
This is now supported in 5.x using DNS validation for your domains and the CCS Export tasks to share certs across servers using CCS.
