### ISSUE TITLE
[v4 alpha] - deployment to 'all websites' not being selective

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#283]
As per alpha/beta testing discussion https://github.com/webprofusion/certify/issues/270#issuecomment-378815800 choosing 'All Sites' as a deployment option does not currently work reliably.

**Comment by markive** [comment]
Just a comment. It seemed reading the notes that this was fixed in Alpha v4 but I've installed and run a test and it isn't fixed.

When you see the preview I can see that a wildcard: *.mydomain.com will try to add to IIS websites with hostname bindings of *.mydomain.com and *.mydomain.co.uk

**Comment by webprofusion-chrisc** [comment]
Thanks, still work to be done there - preview has improved but the deployment matching hasn't and is next on the list. The wildcard bit is tricky, confusingly there is an actual use case for wildcard bindings but that's generally not what people want.

**Comment by webprofusion-chrisc** [comment]
Update: work to re-organise and test the binding match/binding decision process is under way. Hoping to have a version out with this change in the next week or so.

**Comment by webprofusion-chrisc** [comment]
This should now be resolved (broadly), investigating separate issue with server 2008 bindings.
