### ISSUE TITLE
Backup / restore of Certify's config

### ISSUE THREAD

**Issue by mikewells** [webprofusion/certify#287]
Should a server need replacing/rebuilding for any reason, I suspect the Certify config will need to be re-applied manually.

Is there a way to backup and restore the configured sites?

**Comment by mikewells** [comment]
Giving this a bump.

I've now got just 2 certificates, but one has 99 domains using SANs, the other has 10 SANs and growing. This will be difficult to reconfigure by hand if the server fails or needs replacement for any reason.

Perhaps a phased approach starting with a CSV export of the basics? A CSV that contained (eg) the below and exported a listing of all domains in each certificate would at least provide a list that could be worked through manually would be very handy:

Doman Name | Challenge Type | Website Root Directory
-- | -- | --

_As an aside from a licencing perspective, make sure SANs are limited in the same way as profiles are. I did have 100+ certs in my profile, but now have just two. People like me should require a licence. (I now script export and deploy these certs to a load balancer.)_

**Comment by webprofusion-chrisc** [comment]
@mikewells the absolute easiest way to export (and then import again) settings would be a single JSON format archive and a little but of import/export UI. This would obviously be a little harder to work with outside of the app but is very high fidelity (and easy). The main issue I see is that we now have some encrypted credentials as part of the DNS API support, these would need decrypted and re-encrypted in a more portable (but probably less protected) form.

**Comment by webprofusion-chrisc** [comment]
@mikewells thanks also for considering licensing however I'd actually like to eventually move away from restrictions as much a possible (heading more towards Nagware as a licensing model), but that's obviously a balancing act.

**Comment by webprofusion-chrisc** [comment]
As workaround, it's also worth noting that you can query the settings database under c:\programdata\certify\manageditems.db using a GUI like DB Browser for SQLite

**Comment by mikewells** [comment]
Wonderful - have checked the manageditems.db and that has everything I'll need. Perfect!

**Comment by webprofusion-chrisc** [comment]
v5.x now has an preview feature for Import/Export (Settings > UI Settings > Import/Export Migration Tool). This needs users to try it out to prove that it caters for all possible combinations of settings. The tool manages the decryption of secrets and storage in an intermediate backup bundle which can then imported on another instance.
