### ISSUE TITLE
[v4 alpha 1] Log preview not working after renewal

### ISSUE THREAD

**Issue by tvanassche** [webprofusion/certify#290]
After updating to v4 alpha 1, the log preview shows an error after renewing a certificate: "Could not retrieve log entries". 

This is possibly because the logfiles seem to remain locked by the Certify SSL Manager Service. Restarting the service (so the locks are released) fixes this problem.

**Comment by webprofusion-chrisc** [comment]
Log preview has been removed from current UI, will be re-added in the future.
