### ISSUE TITLE
Allow manual DNS validation

### ISSUE THREAD

**Issue by tmmjelde** [webprofusion/certify#293]
I've moved my DNS to Azure because there's no support for manually entering the TXT record anymore.
This in itself incurs an extra cost as I now have to pay for this service.
I strongly recommend allowing manual updates to the TXT record, and there are a few ways to do this.
1: by code, modifying the UI and adding logic
2: Keep the value of the TXT record for subsequent requests, allowing one to at least read the log file and modify manually, then request again.

I followed MS guides to set up the DNS zones and made separate zones for each of my domains.
When I configure the certify application and attempt to request certificates, it does indeed successfully create **a** TXT record.
However, the TXT record is created as _acme-challenge.domain.fqdn **inside** the DNS zone.
This in reality creates the record as _acme-challenge.domain.fqdn.domain.fqdn and verification therefore fails.
When you create a record inside a zone, the zone itself is part of the full record, so the record name itself should not contain the entire FQDN.

So I can copy the value and create the correct TXT record, then re-request the certificate to get it to manually work.
However, the re-request actually creates a new value and updates the TXT record again.

I had to move VERY fast on this to get it to work,
1: Request certificate
2: Copy value of incorrect TXT record
3: Modify correct TXT record
All within the 30 second time frame given by the application.

This is doable as a workaround, as when the certificate first has been issued successfully, the _acme-challenge value does not change anymore even for subsequent renewals.

My suggestions:
1: Allow for manual TXT record creation, removing the necessity to pay for DNS services such as Azure, AWS or Cloudflare.
2: Create the record correctly in Azure DNS.
3: Modify subsequent requests to not create a new value for the TXT record.

Unless I'm not seeing the full picture, and messed up the Azure DNS setup, in which I'd love some feedback.
I am pretty new to this and trying to get a better understanding, so I will openly accept any criticism to my own mistakes.

I am also willing to work with someone to verify this in my lab to help improve the product.

**Comment by webprofusion-chrisc** [comment]
@tmmjelde thanks for your feedback, we have never offered DNS validation before so you may be thinking of another app regarding manual TXT entries. HTTP validation is still very much the primary method of validation and DNS validation is entirely optional.

In my own limited testing with Azure a fully qualified txt record value was required and did indeed validate, but it required not using the 3rd nameserver that Azure offers as it appeared not to propagate in the time required. I'll re-test that again though just to be sure.

We will eventually have a manual option for DNS TXT records, the plan is to provide UI to let you see what records to create and initiate the completion of the validation step, possibly with some automation to auto detect when you have made the required TXT record change,

Regarding cost, Cloudflare DNS is currently free on their basic plan: https://www.cloudflare.com/dns/ - Azure is about $0.30 per zone per month.

**Comment by tmmjelde** [comment]
You're probably right, I have likely been confused.

In my setup I've got a reverse proxy IIS server which doesn't handle HTTP validation very well because the websites are on different hosts internally, so DNS validation is definitely the go to option for me.
The reason I've done this is because I've only got one public IP, and I want multiple HTTPS services on the TCP/443 port pointing to various internal servers.
I also only want to manage Certify in one single location because I'm lazy, and having IIS certificates updated automatically in one single location really saves me a lot of time integrating into other services.

I've had no issues using all four of Azure's DNS servers in my setup with regards to propagation time, so it's possible that issue has been sorted from MS.

Thanks for the tip regarding Cloudflare. As I said I'm new to this, and my initial encounter with Cloudflare was a scary $20 per month cost, which is not going to happen for a personal lab environment :)
I didn't realize they provide DNS service for free, so I am now moving one of my lab domains in there to test it out.

Please let me know how you fare on Azure. 
If you want, I can create some access accounts into my Azure and Windows environment if that helps you in any way. I can keep one domain in there until my free credit runs out in a couple of months.
This is a pure lab environment with no production systems, intended only for learning.

**Comment by webprofusion-chrisc** [comment]
@tmmjelde  thank Thomas, sounds like you have the ideal test setup and yes DNS validation is best for complex environments like yours.

I'm currently working on splitting up the certificate request process so that we can pause the process and resume certificate orders once any manual steps have been completed, it's a fairly significant change but it's worthwhile.

**Comment by webprofusion-chrisc** [comment]
Manual DNS validation is now implemented in the latest v4 beta.
