### ISSUE TITLE
Support multiple contacts

### ISSUE THREAD

**Issue by JohnLBevan** [webprofusion/certify#295]
Currently when you click Settings, Add Contact, it replaces the primary contact.
It would be helpful to allow multiple contacts to be added; e.g. so our site administrators can add their own accounts but also provide a generic account to ensure that should they leave the company a valid mailbox's address is still available.

**Comment by webprofusion-chrisc** [comment]
The contact you register becomes the contact for your Let's Encrypt account. 

For that reason multiple accounts is not supported and you should forward to a mailing list or generic forwarder if you need to notify multiple people.
