### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by mark-milton** [webprofusion/certify#297]
Hi,
When Downloading from your site the file always failed with Network Error

**Comment by webprofusion-chrisc** [comment]
Hi Mark, thanks for raising this, it seem to be something that happens after the (windows) server hasn't been rebooted for a while. Rebooted now.

**Comment by mark-milton** [comment]
Still getting the same error

**Comment by webprofusion-chrisc** [comment]
@mark-milton thanks, updated again, unlikely to fail now. If the problem persist please try a different browser.
