### ISSUE TITLE
Problem with two sites on the same IP

### ISSUE THREAD

**Issue by tobybloem** [webprofusion/certify#298]
Hi,

I've got what I think is a weird use case and I'm not sure how to fix this. I've got two sites that I want to enable SSL on IIS 7. 

1. example1.com has multiple sub-sites/applications that can be accessed at example1.com/example1, example1.com/example2, e.t.c

2. example2.com is one of the applications from example1.com, but with its own URL. So example1.com/example2 can be accessed at example2.com

I tried to issue certs for both sites, but because they are the same IP address, IIS only lets me enable one cert for the 443 * binding at a time.

Now, I think I need to issue a SAN cert. Certify says that you need to add the domains you want to the bindings for the IIS site you are making the cert for. Well, if I add example2.com to the bindings for example1.com, the example2.com IIS site will stop because they have the same bindings.

Am I right that a SAN cert is needed? And if so, how can I do that in Certify/IIS?
Any help is appreciated.

**Comment by tvanassche** [comment]
How exactly have you set up the second site (example2.com)? 

Is it a seperate site in IIS that points to the application folder? Or is the domain "example2.com" bound to the first site (with the "binding" done in the code of the first site)?

**Comment by webprofusion-chrisc** [comment]
@tobybloem As @tvanassche SNI is your friend - it stands for Service Name Indication and basically uses the  browser request to determine which website you wanted to connect to from the list of ones you have bound to the same port (as all will be bound to port 443).

Not that you should not specify the IP address in the binding settings for https, let IIS direct the traffic for you. Specifying an IP address defeats SNI and means you can only have one website bound per IP/port combination (on windows anyway). This is the source of endless confusion.

**Comment by tobybloem** [comment]
Thanks @tvanassche @webprofusion-chrisc 
SNI looks like it's what I need. But it looks like my server version, 2008 R2, IIS 7, doesn't support it. Guess I need to beg the IT guy for an upgrade :)
