### ISSUE TITLE
Links on main website are incorrect.

### ISSUE THREAD

**Issue by Absoblogginlutely** [webprofusion/certify#306]
Just a heads up that the links at https://docs.certifytheweb.com/docs/faq.html for getting started, Faqs both error out with 404's

**Comment by Absoblogginlutely** [comment]
Correct, at the bottom left.

**Comment by webprofusion-chrisc** [comment]
Fixed (replaced with more useful footer links). A separate issue is that our FAQ page content is outdated and not really that useful, a potential candidate for deletion.
