### ISSUE TITLE
Need better defaults on Server 2008 R2 w/o SNI

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#307]
The lack of SNI support pre Server 2012 means that our default 'auto' binding with SNI is confusing.

On servers without SNI support we should make specifying the binding IP address mandatory.

**Comment by markive** [comment]
Hi @webprofusion-chrisc, can you give me more info. I've got the beta now.. Will I need to use the old system of one certificate per IIS website for 2008r2? This will mean I still hit their 20 per week limits right?

**Comment by markive** [comment]
Seems to just work now on 2008r2.. I'll add a comment to the beta thread..
