### ISSUE TITLE
Multiple registrations on crt.sh for each domain

### ISSUE THREAD

**Issue by bildsoe** [webprofusion/certify#315]
Hello 

Software: CertifyTheWeb Professional Edition 3.0.11
Platform: Windows Server 2012

We are using CertifyTheWeb to get and install certificates from LetsEncrypt. But we're hitting the rate-limit fast and get the 429-error which states that we have requested too many certificates.

Upon checking the logs on crt.sh we can see that for each of the subdomains we've requested certificates for, there are 2 certificates. This would explain why we're hitting the limit, but why does CertifyTheWeb request 2 certificates each time. The software clearly states: 
The following selected domains will be included as a single certificate request.

Can you help us?

BR
Thomas

**Comment by webprofusion-chrisc** [comment]
Hi Thomas, to assess this a bit more I'd need to see the log file (which you can also review yourself) - it's under the Managed Certificate's details in the app, in the Advanced tab.

I'm assuming you don't have the same website added twice, as that would result in the behaviour you are seeing. When the renewals occur are they completing OK?

You can email the log to app at webprofusion.com if you'd like to discuss it in more detail.

**Comment by webprofusion-chrisc** [comment]
Thanks Thomas, I've replied to your email with my suggestions.
