### ISSUE TITLE
Main Window Does Not Retain Last Position

### ISSUE THREAD

**Issue by TheOfficeMaven** [webprofusion/certify#316]
Minor bug (but somewhat annoying nonetheless). When Certify the web's main UI window is in a normal state (i.e. not maximized or minimized), it does not remember its last position when the application is re-opened.

**Comment by webprofusion-chrisc** [comment]
Thanks, this requires specific code to store and retrieve the settings.  I'll leave this as low hanging fruit for any potential contributors for now.

**Comment by webprofusion-chrisc** [comment]
Implemented in PR #435
