### ISSUE TITLE
Missing stored keyset

### ISSUE THREAD

**Issue by DawidGK** [webprofusion/certify#319]
First of all I really appreciate your huge effort in building this great app! Big thank you guys :)

Meanwhile, I was trying to copy newly requested cert from one server with installed Certify the web V 4.0.0.40001 (Windows Server 2008 R2 SP1) to another (same OS) and experienced strange errors. My simple PowerShell script just opens System.Security.Cryptography.X509Certificates.X509Store on source server, reads the new cert which thumbprint equals to $result.ManagedItem.CertificateThumbprintHash, and tries to add it to target server Personal store. I've found out I cannot Manage Private Keys… of the copied cert on target server because "**Cannot find the certificate and private key for decryption**." After running CertUtil on source server I discovered the requested new cert by Certify the web has:
Provider = Microsoft Enhanced Cryptographic Provider v1.0
**Missing stored keyset**

Am I missing something or is it a bug of V4 Beta?

**Comment by webprofusion-chrisc** [comment]
@DawidGK thanks for the feedback, it could indeed be a bug in the beta version but there's a lot going on here so I'd check first that you can access the certificate normally in the original server as unless you have also exported the private key the copied cert won't work on a different server.

On the original server, open the Certificate Management windows ui (certlm), find the cert in the Personal store, right click on it and go to All Tasks> Manage Private keys. If the key permissions open OK then your private key if fine (on that server).

To copy the cert to another server you usually need to export including the private key, but the easier option is just to copy the PFX file, which is still on your C: drive, you can optionally do this as post-request powershell. If you look at the docs here: https://docs.certifytheweb.com/docs/script-hooks.html you can use the $result.MangagedItem.CertificatePath variable to get the path for the file to copy. This still has the private key included. You can also see the path to this file if you click 'Show Advanced Options' and go to the Other Options tab.
