### ISSUE TITLE
Implement validation to prevent mixing wildcard requests with first-level subdomains/labels

### ISSUE THREAD

**Issue by miranoff** [webprofusion/certify#321]
I have a domain with a previously issued single domain cert from letsencrypt.

There are two bindings in IIS for this domain:
miranoff.com
www.miranoff.com

I added a wildcard to the certificate domains section and forgot to deselect the two other entries before requesting the wildcard certificate so all three were included in the request like so:

X - miranoff.com
X - www.miranoff.com
X - *.miranoff.com

When I tried to request a wildcard cert I got this error: 
Failed to create certificate order: New Order Failed [*.miranoff.com] : Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-order'.

I can't see the payloads being sent to the API so I can't help with that unfortunately.

After deselecting the two non-wildcard entries and only including the wildcard entry and requesting again, my request was processed properly and the wildcard cert bound to the site. 

Since I am sure I won't be the only dumby to try this, some error checking on it might be prudent before attempting to send the request.

Here is the log:
2018-06-07 23:37:22.318 -04:00 [INF] Beginning Certificate Request Process: Miranoff using ACME Provider:Certes
2018-06-07 23:37:22.322 -04:00 [INF] Registering Domain Identifiers
2018-06-07 23:37:23.234 -04:00 [ERR] New Order Failed [*.miranoff.com] : Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-order'.
2018-06-07 23:37:23.268 -04:00 [INF] Failed to create certificate order: New Order Failed [*.miranoff.com] : Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-order'.
2018-06-07 23:37:24.946 -04:00 [INF] Failed to create certificate order: New Order Failed [*.miranoff.com] : Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-order'.

**Comment by webprofusion-chrisc** [comment]
Thanks for reporting this - we have validation that checks to prevent adding labels to certs with existing wildcards but not the other way round (like this example). We also need to report the detail of New Order Failed back to the user.

**Comment by ScottRFrost** [comment]
Related issue:

I'm trying to use a wildcard for *.domain.com that is then applied to 3 websites and then regular HTTP for domain.com on a single website (domain.com and www.domain.com).

The wildcard cert is ONLY valid for *.domain.com, but it's applying itself to the binding for domain.com no matter what settings I select in Deployment.  A cert for *.domain.com is not valid for domain.com, so this is a problem.

**Comment by webprofusion-chrisc** [comment]
@ScottRFrost thanks for raising the domain matching issue, yes wildcards shouldn't equal the top level domain so we need to fix that. The NXDOMAIN thing is quite an interesting error message - do you have multiple DNS zones in the same AWS account?
