### ISSUE TITLE
Feature: Implement support for Central Certificate Store

### ISSUE THREAD

**Issue by SKFish** [webprofusion/certify#324]
Is this a normal process? Is there a way to change where the cert is going to? When we ran them manually, a part in our script would tell them to go to Centralized Store.

**Comment by webprofusion-chrisc** [comment]
Hi, the app does not currently support Centralized store for certificates but it's likely in the near future. Do you have a post-request powershell script as part of your request? If so, once the certificate renew (by clickng Request Centrificate , or automatically) your script will then run, at that point it's up to your script to perform the required actions.

You don't mention what version of the app you are running? Which operating system? There are big differences between v3 and v4 for instance.

**Comment by webprofusion-chrisc** [comment]
https://blogs.msdn.microsoft.com/kaushal/2012/10/11/central-certificate-store-ccs-with-iis-8-windows-server-2012/

**Comment by SKFish** [comment]
Sorry about the lack of details Chris, I am currently using the latest Beta version V4. The flags in our original LE script were as follows: letsencrypt.exe --accepttos --keepexisting --centralsslstore C:\inetpub\Certificates\ --iismanualhosts. I will see if I can come up with a PS Script to continue using these flags.

**Comment by SKFish** [comment]
OS: Win Server 2012 R2

**Comment by webprofusion-chrisc** [comment]
Thanks, we can use this bug to track the Central Certificate Store feature request.

Currently I think this requires UI (which we can probably do as a stored credential) for:
- Local or UNC path to store location
- Optional windows credentials storage to access the storage path
- Optional password storage for common private key password

On a per managed certificate basis this requires UI to select CCS as a cert storage option and select the store (in most cases there's probably only one), plus possibly UI options for cert naming. I'm not sure if we should be creating new CCS bindings directly (perhaps these should be up to the user to create initially?).

In this situation I'm assuming you would normally make one server in charge of renewals?

**Comment by SKFish** [comment]
We create the binding in IIS and then run our script to generate the HTTPS site with the cert in the CCS. Yes, one server handles the renewals of the certs.

**Comment by webprofusion-chrisc** [comment]
Thanks, so currently you let LE generate the initial https binding for you, based on the http binding?

**Comment by SKFish** [comment]
Correct. If I generate the http binding (www.contoso.com), I would run our script like this: letsencrypt.exe --accepttos --keepexisting --centralsslstore C:\inetpub\Certificates\ --iismanualhosts www.contoso.com

After running this, the binding for HTTPS gets created in the same Site, and the LE Cert gets created/updated in the CCS.

**Comment by SKFish** [comment]
Any update on this? We would love to snag a license for our production environment if you have been able to implement or make progress on this feature.

Thanks,

**Comment by webprofusion-chrisc** [comment]
Hi, no sorry, I'm trying to wrap up the 4.0 release before adding any other significant new features. It's worth checking up every now and then though as I do get distracted by other feature requests!

**Comment by SKFish** [comment]
Any luck on the CCS implementation? BTW, thanks for everything you are doing with this project :D

**Comment by webprofusion-chrisc** [comment]
@SKFish no progress on this so far, just a lack of time currently! Still planned but likely to be next year.

**Comment by webprofusion-chrisc** [comment]
Update: v5 now includes a CCS deployment task which will write out to a CCS store (local or network) but there is no automatic binding creation for other servers in a load balanced pool except on the machine running Certify. Öther servers in the pool would need https bindings created.
