### ISSUE TITLE
Error when CN is too long.

### ISSUE THREAD

**Issue by gristxx** [webprofusion/certify#326]
[errLogCN64.txt](https://github.com/webprofusion/certify/files/2103588/errLogCN64.txt)
Line 52. CN is too Long.

Do you have an option to put something else in the CN when it's too long, and using alternate subjects for the real domain name ?

In reference to https://community.letsencrypt.org/t/ssl-for-a-63-character-max-number-of-characters-domain-name-s/36387/16

Thanks for your work.

greg

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this, currently the best way to set the CN would be to use an alternative short dns name for the CN and set that as Primary in the app UI, which will make it the CN subject. The shorter DNS name also has to validate normally.

**Comment by gristxx** [comment]
Yes, typically I will use an unique identifier within a specific tld... I wonder what they had in mind when making the CN length so short...

**Comment by webprofusion-chrisc** [comment]
I'll keep this open for now as the error you get back doesn't seems to be handled very well by the app.

**Comment by gristxx** [comment]
Well ok. Do you think there is a way to address the issue with no workaround on your side, or do you assume it's on Let's Encrypt / the SSL standard side ?

I really would like to see long names as primary subject in certs !

**Comment by webprofusion-chrisc** [comment]
Hi, it's definitely on the LE/SSL standard side (as currently we don't care what length the domain is, but they do), so I can't currently think of an automatic workaround. All we can do is validate/warn/recommend a workaround.

**Comment by gristxx** [comment]
Hi Chris, 
The current workaround is not that simple for I have to maintain 2 DN running for a single cert, and this cert is "labelled" with a fake domain name in the subject.

I would like something like CN=a885d4a8-3b10-441c-882c-9db31639d850 in the subject, and not a DN... Do you think it's possible to issue the request by specifying such a subject ?
I hope the question is not trivial...
Thanks

**Comment by webprofusion-chrisc** [comment]
Hi, as far as I can determine Let's Encrypt will only issue certificates with the CN set to a validated domain.  So as far as I can see the only solution is to have a short name that you can set as the subject. Let's Encrypt dont appear to offer a way to have the serial number as the CN.
