### ISSUE TITLE
Feature: Implement scheduled deployment

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#329]
While a certificate can generally be renewed at any time, the updated certificate file (or stored cert) may not actually be applied until a service restarts (such as Apache, MS Remote Desktop Gateway etc). 

Ideally a user should be able to specify when to deploy a renewed certificate:
- Time of day
- Day of Week/Month

This would effectively be the post-request stage of the renewal process, including the post-request scripting (if any). This would require determining how to handle certificate stored before deployment (is it applied to the certificate store already?) and UI to specify target date/time preferences.

This overall concept is that many users will have a 'maintenance window' where they can tolerate service restarts etc. The assumption is that this would only take place if the certificate renewal has already succeeded (as a renewal can take multiple attempts and must tolerate failure, whereas deployment is generally expected to only happen once per renewed certificate).

**Comment by flashbacknl** [comment]
Quick fix currently is to stop/start the Certify background service via task scheduler . but a option in the software is prefered 

a professional license user

**Comment by webprofusion-chrisc** [comment]
Yes, this is planned for v5 (the next major version) which already has most of this functionality in the new Deployment Tasks feature (some or all deployment steps can be deferred and run from command line or as a scheduled task, or from the UI on demand).

**Comment by webprofusion-chrisc** [comment]
And v5 beta release is currently expected in March.

**Comment by webprofusion-chrisc** [comment]
Closing. Deployment Tasks (which can be deferred and controlled by the user) are now implemented in v5.
