### ISSUE TITLE
Failed to create certificate order: Failed to begin certificate order: Error creating new order :: too many failed authorizations recently

### ISSUE THREAD

**Issue by djpbessems** [webprofusion/certify#337]
It seems that failed certificate requests do not clean up authorization requests and eventually you might run into the error `Failed to create certificate order: Failed to begin certificate order: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/`

If you check the paragraph about **Clearing Pending Authorizations** on the above url, you can see that there is a way to clear authorizations with a specific POST-request.

Alternatively, I think it would be beneficial if Certify had a toggle somewhere to swap over to the staging-environment (if it already has, I'm completely missing it :( ), so we can develop custom scripts for updating DNS-entries.

**Comment by webprofusion-chrisc** [comment]
Thanks, yes we need to do more in that area however the purpose of the Test button (I'm assuming your are using v4?) is to identify validation problems before they become an issue with failed authorizations, so really we need to improve the Test feature if it's not catching the error first.

**Comment by djpbessems** [comment]
I am using v4, but was not using the Test-button (I had to test wether my script would work with both '_acme-challenge' as well as '_acme-challenge-test' records) when I discovered my DNS-provider's API had issues. Throughout resolving those issues I ran into the rate-limits.

Maybe the Test-button should be the 'toggle' that I was looking for, it could initiate a request against the staging-environment of LE?

**Comment by webprofusion-chrisc** [comment]
It's certainly possible, but not completely trivial so there would be a few things to iron out. 

Requests to staging require a different LE account registration (a different account key) which also raises the question of whether the contact email might be different for staging. If you succeed in requesting a staging cert you will also receive expiration reminder emails from LE which can be confusing if you don't understand what they are. 

To be a real test you may also want to bind to the resulting cert, which could be a further source of confusion if done by accident. 

So I'm not saying its a bad idea, I just think it needs a fair bit of thought as to how it would be presented (and how to protect against causing users confusion).

**Comment by djpbessems** [comment]
Hmm, sounds indeed like it requires more planning than I assumed :D.

So, would cleaning up failed authorizations be more sensible then?

**Comment by webprofusion-chrisc** [comment]
@djpbessems that's not to say we won't do it but we'd need the user to be fully aware of what they're doing to avoid any confusion, we get quite a lot of support requests just for basic http validation so the more variables we add the trickier it gets, although it could be an advanced option (where we hide all the gnarly stuff).

I see you were talking about about Failed authorizations, I'd originally assumed this was Pending authorizations (which are technically possible to clear if we keep a log of the auth urls), but Failed authorizations are different, they have a limit of 5 per hour according to https://letsencrypt.org/docs/rate-limits/ - although you can bypass it by modifying your certificate request (like adding a new SAN to the cert like test1.example.com).
