### ISSUE TITLE
Add support for non-LE services

### ISSUE THREAD

**Issue by pkiguy** [webprofusion/certify#339]
Please consider the attached patch... It's fairly simple IMHO, but it works.
[supportOtherCAs.diff.txt](https://github.com/webprofusion/certify/files/2195618/supportOtherCAs.diff.txt)

**Comment by webprofusion-chrisc** [comment]
Thanks, a PR would be better than a diff because it give more obvious context and I can try the fork out directly. Certify stores settings in the CoreAppSettings and Preferences classes and serialises to a json file in c:\prograndata\certify\appsettings.json and will likely never use the registry for storage. Can you explain what you are generally intending with this patch?

**Comment by pkiguy** [comment]
I'm trying to enable CertifyTheWeb to work with other CAs than Let's Encrypt...
I'm using the Registry, because the Certes wrapper binds statically to LE's URI at low level. If there's another way to implement it, that would be nice, of course.

**Comment by webprofusion-chrisc** [comment]
Related to #340 

Thanks, so the full implementation of this would/will be a UI to add new endpoints (or perhaps select from a list/catalog of known endpoints) then let you set a default overall and also let you set a specific once for a given managed certificate. As mentioned before we will require the CAs to be compliant with the right version of ACME (draft 09 onwards I think) and I'm not sure that BuyPass is - so we'd need to go back and re-implement an ACME v1 workflow (which is mainly different in how identifiers get registered before validation). Ideally we would have a test function in the UI to check the connection with the CA.

**Comment by webprofusion-chrisc** [comment]
Update: BuyPass are working on providing an ACME V2 endpoint, current testing shows that it has some implementation differences that prevent is working just now but it's looking promising.

I'm planning to implement the UI/services to properly support multiple CAs:
- User can select a default CA for all new managed certs
- User can select a specific cert per managed cert
- UI references/errors need to be dynamic depending on the selected CA
- CAs need to be defined with their respective limitations (e.g. SAN name limits, cert lifetime etc)
- User may opt for automatic fallback if renewal fails via their chosen CA (if cert requirements will be compatible)

**Comment by webprofusion-chrisc** [comment]
Implemented in v5 as multi-ca support. Still some work to do on UI (add/remove CAs).
