### ISSUE TITLE
Auto Renewal status is incorrectly displayed/set

### ISSUE THREAD

**Issue by Xalaxis** [webprofusion/certify#341]
I'm running the v4 beta, v4.0.1.40004.

Unsure if this is limited to the beta, but when I untick 'Enable Auto Renewal' under 'Other Options' (and save) the status tab still indicates 'Auto Renewal Active'.
![image](https://user-images.githubusercontent.com/12937964/42772844-8fd9413c-8923-11e8-8739-e77456f62405.png)
![image](https://user-images.githubusercontent.com/12937964/42772867-94fd351a-8923-11e8-9316-46273393f431.png)

**Comment by webprofusion-chrisc** [comment]
Thanks, I'll check it out.
