### ISSUE TITLE
No warning that a certificate is going to be 'overridden' on IIS 7.5

### ISSUE THREAD

**Issue by VorTechS** [webprofusion/certify#345]
I've been experimenting with Certify and Let's Encrypt certificates on one of our servers which is an IIS 7.5 installation.

When I added a second domain (I'm on a steep learning curve with all of these things) to Certify and requested a certificate, it happily went away and altered the Bindings with the new certificate.

However, IIS 7.5 doesn't support multiple certificates for multiple domain names on the same port.

So, the previous site also adopted the new certificate.

This should be taken into consideration to warn a user that they are about to potentially break a website by over-writing an existing certificate binding.

Version 3.0.11.30336
Windows Server 2008R2
IIS 7.5

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for reporting this. This (warning users of IIS below v8) has been addressed in V4 - currently at release candidate and about to be released.
