### ISSUE TITLE
Dashboard "App Version"

### ISSUE THREAD

**Issue by tvanassche** [webprofusion/certify#346]
At the moment, the dashboard shows the version number of the app when it was first installed.

It would be handy though if the "App Version" on the dashboard actually reflects the installed version, so we can easily check if there are any servers that need updating. And if possible, maybe also show on the dashboard if there are updates available.

**Comment by webprofusion-chrisc** [comment]
Thanks, the version info update is now shown on the dashboard. I'll keep this issue open as the second issue of perhaps showing app updates available is not yet addressed. Broadly the plan is to re-implement the dashboard UI as a more extensive app when time allows, currently it's very basic.

**Comment by tvanassche** [comment]
Thanks for this update. It's quite handy to see which version a server is actually on. 

In my case it already helped me identify a small oversight of mine when updating one of our servers to 4.x. I was using a background task for auto-renewal in the old 32bit version (3.x), and I had forgot to switch to the (better) built-in service.

And thanks to this small dashboard update I was able to spot this quickly, since that server still showed as running 3.x instead of 4.x. 


PS: I appreciate the effort you're putting into the tool and dashboard. It helped me save a lot of time and possible headaches when it comes to SSL for our hosted websites.
