### ISSUE TITLE
How to create binding for another port instead of default 443 without SNI

### ISSUE THREAD

**Issue by smarques84** [webprofusion/certify#347]
I read that by default the ssl is binded to port 443 and I should use SNI, but please bear with me the following scenario:

I have client with a domain that represents a group of 3 companies all 3 companies have 3 websites (apis to be exact) with their respective db on the same IIS instance. In other words all 3 apis will use the same ssl certificate and same domain. Differing between each api we are using ports

Company 1: domainGroup:9000 -> iis: 9000
Company 2: domainGroup:9001 -> iis: 9001
Company 3: domainGroup:9002 -> iis: 9002

Using your software i successfully generated the ssl certificate using port 80 but since it binds automatically all 3 websites to port 443 i have no other choice then to assign the ssl manually to each api each is cumbersome since this has to be done with each renewal.

Any thoughts about how can i fix my problem? Should i try to make a script to update the ssl of each api in IIS after ssl certificate is generated?

The server is running Windows Server 2012 with IIS 8

**Comment by webprofusion-chrisc** [comment]
Assuming your are using v4 there are a number of deployment modes available (https://docs.certifytheweb.com/docs/ui-options.html#deployment). However it looks like there may also be a bug here as I've tried to recreate your example locally and so far I think you're right about the port 443 problem.

The intended way to do this type of configuration is to use either http or DNS validation (sound like you're using http validation for authorization already), and only update your existing defined https bindings.  So for Deployment choose:
- Deployment Mode: All Sites (which applies to all sites using a matching domain)
- Binding Add/Update: Update existing https bindings only (so no new bindings should be created)
- Matching any of: Existing binding hostname matches certificate domains

I'll investigate this and let you know if I find a solution.

**Comment by webprofusion-chrisc** [comment]
p.s. as a workaround you could choose the 'Certificate Store Only' deployment option, then use your own Post-Request script to apply the new/renewed certificate as required to the bindings.

**Comment by smarques84** [comment]
@webprofusion-chrisc Yes i am already using http validation and everything works fine the problem are the bindings, after your suggestions i tried playing around and found out the following:

If you choose: 

- Deployment Mode : All Sites
- Binding: Add or Update Https Bindings
- Matching any of: Existing binding hostname matches certificate domains

And then in IIS Binding Settings choose:

- Use Specify Port
- Binding to Specific Port: 9000

And then return to

- Binding Add/Update option to: Update existing https bindings only (so no new bindings should be created)

And then go to preview you will notice that all websites will get assigned to port 9000, which makes me think that the port being used by the website is completely discard and Certify tries to bind with default port 443 or with the specified port in the field in IIS Bindings.

Until a fix is provided could point me in the right direction for could i create such a script?

Thank you

**Comment by smarques84** [comment]
So I found an article (https://weblog.west-wind.com/posts/2016/Jun/23/Use-Powershell-to-bind-SSL-Certificates-to-an-IIS-Host-Header-Site) that helped to get to a possible fix by using a Powershell script:

Declare your domain name variable
`$domain = "MyDomain"`

Get the certificate thumbprint with this command:
`$cert = (Get-ChildItem cert:\LocalMachine\My | where-object { $_.Subject -like "*$domain*" } |
Select-Object -First 1).Thumbprint`

Get the IIS bindings that are using the current domain as host name
`$binding = Get-WebBinding -HostHeader $domain -Protocol https`

Assign the certicate to each binding with:
`$binding.AddSslCertificate($cert, "MyCert")`

But after the last command i getting the following error:
```
Uma sessão de início de sessão especificada não existe. Esta sessão pode ter sido terminada. (Excepção de HRESULT:
0x80070520)
At line:1 char:1
+ $binding.AddSslCertificate($cert, "MyCert")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : OperationStopped: (:) [], COMException
   + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException

```

Which is the same error reported here: https://github.com/ebekker/ACMESharp/issues/135

I am currently stuck at this point any further advice?

**Comment by webprofusion-chrisc** [comment]
Just checking if this is still an issue for you, the latest v4.0.12 has updated binding handling behaviour which may help. In my tests working with custom ports was fine. You can also chose to 'Update Only' and set whichever ports you like manually in IIS.

**Comment by webprofusion-chrisc** [comment]
Closing as resolved.
