### ISSUE TITLE
Split solution into projects for Core and Winforms

### ISSUE THREAD

**Issue by soundshed** [webprofusion/certify#35]
The current solution is monolithic and cannot be reused in a console app, service etc.

Split current single project into a core for managing the vault interaction, certificate requests and certificate installation etc, and a separate project for the UI.

**Comment by ndouthit** [comment]
Do you have a list of features that still need to be implemented in gui-revisions in order to catch it up with master?

**Comment by soundshed** [comment]
@ndouthit other than the list of issues on github no, nothing formal. I'm in discussions to get some corporate sponsorship for certify that will take it from a 'hobby' level project to a more serious offering. Certify only needs a couple of weeks of serious development to get it to where it needs to be, so getting the time for that is the key to turning it around.

**Comment by ndouthit** [comment]
FYI I compared the branches and only found two differences.

- The changing of SiteListItem to SiteBindingItem.
- The DeleteRegistrationInfo method with the Guid parameter is used in one but it's a string in the other project.

**Comment by soundshed** [comment]
@ndouthit the main difference is the project split (moves into different folder structure and solution split into Core CLI and GUI projects)

**Comment by soundshed** [comment]
Merged with master now, main work now is rework the process for the IIS Request Cert dialog - this should be centralised to work from CLI or GUI and report progress async. 

There is some example code that better shows the direction we should be using (although it's still IIS specific), as the code in the current IIS Request Dialog (CertRequestIISSettings) is horrible:
https://github.com/webprofusion/Certify/blob/master/src/Certify.CLI/Program.cs#L92

**Comment by soundshed** [comment]
Closing. Basic split is completed, remaining work is in refactor of IIS cert request workflow.
