### ISSUE TITLE
save/import certificates into the "Web Hosting" store 

### ISSUE THREAD

**Issue by criwayc** [webprofusion/certify#353]
Would it be possible to add an option to use the WebHosting instead of Personal store of Windows, maybe even make it the default?
Also see https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-server-name-indication-sni-ssl-scalability  as to why it's preferred to use that store for this scenario.

**Comment by webprofusion-chrisc** [comment]
Implemented under Settings in latest version.
