### ISSUE TITLE
Trying to run OpenSSL to scipt a PFX conversion to PEM fails

### ISSUE THREAD

**Issue by swinster** [webprofusion/certify#355]
Hi,

v4.06 

I have a simple script that I think (according to https://github.com/webprofusion/certify/blob/master/docs/Request%20Script%20Hooks.md) should take the created PFX file and pass it to OpenSSL to convert to PEM, however it seem that OpenSSL is not being passed a file:

```
param($result)

C:\OpenSSL-Win64\bin\openssl pkcs12 -in $result.MangagedItem.CertificatePath -out "C:\Users\Me\Desktop\myCert.pem" –nodes
```

result:

```
openssl.exe: pkcs12: Cannot open input file -out, No such file or directory
At C:\Users\me\Desktop\CreatePEMCert.ps1:8 char:1
+ C:\OpenSSL-Win64\bin\openssl pkcs12 -in $result.MangagedItem.Certific ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Ideas?

**Comment by webprofusion-chrisc** [comment]
Does this happen during a real certificate request or during a test? You should indeed be getting the certificate path passed in that variable during a real request.  We could do with having an option to re-apply only the post-request script part of deployment with the most recent values.

**Comment by swinster** [comment]
@webprofusion-chrisc that output was from a successful cert request (not a test).

**Comment by webprofusion-chrisc** [comment]
As an aside, there is a plan to implement a feature whereby you can choose to export to various formats (post-certificate renewed but before we run the script) as users of other non-iis services obviously need a variety of formats. No idea when that would be though as I'm currently focused on bug fixes.

**Comment by swinster** [comment]
Ok, that seem to have done it, so : 

```
param($result)

C:\OpenSSL-Win64\bin\openssl pkcs12 -in $result.ManagedItem.CertificatePath -out "C:\Users\me\Desktop\MyCert.pem" -nodes -passin pass:
```

Seems to do the trick.

Of course, this required OpenSSL to be installed on the Widows Box, so a way of doign this antivly would be cool.

For Example, with ACMESharp you have things like:

```
Get-ACMECertificate $CertFileName -ExportKeyPEM
Get-ACMECertificate $CertFileName -ExportCertificatePEM
Get-ACMECertificate $CertFileName -ExportIssuerPEM
```

**Comment by swinster** [comment]
Ah, @webprofusion-chrisc just saw your update - great 👍

**Comment by webprofusion-chrisc** [comment]
Closing. v5 now includes various export Deployment Tasks to remove the need to call openssl for certificate file conversions.
