### ISSUE TITLE
why only a pfx file?

### ISSUE THREAD

**Issue by carlsue** [webprofusion/certify#359]
i get *.expalm.com ssl by api,buy only a pfx ,not suit for nginx

**Comment by webprofusion-chrisc** [comment]
Hi, we currently only produce a pfx file but you can use a post request script to convert that to other formats using OpenSSL or other tools. We will likely offer other export formats in the future.

**Comment by jianbosu** [comment]
i can't program,can u post the script?
i study your code:
param($result)
$tempfile = "$env:TEMP\CertifyTemp.pfx"
$pfx = get-pfxcertificate -filepath $result.ManagedItem.CertificatePath
certutil -f -p Certify -exportpfx $pfx.SerialNumber $tempfile
certutil -delstore my $pfx.SerialNumber
certutil -p Certify -csp "Microsoft RSA SChannel Cryptographic Provider" -importpfx $tempfile
remove-item $tempfile

but i can't follow

**Comment by jianbosu** [comment]
i try this ,but out file is empty:
`param($result)
$pfxpath = $result.ManagedItem.CertificatePath
set-alias openssl "D:\Program Files\openssl\openssl.exe" 
openssl pkcs12 -in $pfxpath -out c:\a.pem -nodes -nokeys
`

**Comment by webprofusion-chrisc** [comment]
@jianbosu thanks, does the script work outside of the app if you just include the paths manually? Openssl may require an argument for the blank password: https://community.certifytheweb.com/t/filezilla-server-ps-script/141/3

**Comment by jianbosu** [comment]
@webprofusion-chrisc thanks，it is correct。：
`param($result)

set-alias ossl "D:\Program Files\openssl\openssl.exe" 

$domain = $result.ManagedItem.RequestConfig.PrimaryDomain
$pfxpath = $result.ManagedItem.CertificatePath
$keypath = "C:\TEMP\"
$key = $keypath + $domain + ".key"
$rsakey = $keypath + $domain + "_rsa.key"
$pem = $keypath + $domain + ".pem"

ossl pkcs12 -in $pfxpath -out $key -nocerts -nodes -passin pass:
ossl rsa -in $key -out $rsakey
ossl pkcs12 -in $pfxpath -out $pem -nokeys -clcerts -passin pass:
`

**Comment by MichelZ** [comment]
Duplicate of #105

**Comment by webprofusion-chrisc** [comment]
Closing as duplicate
