### ISSUE TITLE
Implement Loopia API (Swedish DNS provider)

### ISSUE THREAD

**Issue by nilsjonsson** [webprofusion/certify#361]
Hi everyone!

Loopia is probably the biggest domain registrar and DNS provider in Sweden.

I hope someone can help me with this or at least give me some pointers to make the changes myself. (Mostly done PHP programming...)

They have a XML-RPC API, link to their API docs in english;
https://www.loopia.com/api/

There is an implementation in the acme.sh project if it is to any help, see: 
https://github.com/Neilpang/acme.sh

**Comment by webprofusion-chrisc** [comment]
Loopia support is coming in v5 courtesy of the Posh-ACME project: https://github.com/rmbolger/Posh-ACME/tree/master/Posh-ACME/DnsPlugins

**Comment by nilsjonsson** [comment]
Thanks for the good news! I will be looking forward to v5 then.

**Comment by webprofusion-chrisc** [comment]
Closing. Implemented in v5.
