### ISSUE TITLE
If a domain is already managed as part of another certificate, show indication in UI

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#367]
Let's Encrypt certificates have a maximum of 100 domains for certificates. When managing hundreds of domains against a single site it is necessary to split the site into one or more additional certificates.

It is currently difficult to see which ones are already being managed as part of another managed certificate, so the suggestion is to grey out or otherwise indicate that a domain is currently selected as part of another managed certificate.

**Comment by codeendevor** [comment]
@webprofusion-chrisc Great application you have here, i just downloaded this to deal with Exchange and smartermail servers,  I currently have a C# .net application that checks all the domains in IIS and displays ones with Cert applied and also shows valid and expire date. I am new to your application but will review your code and see if i can incorporate to achieve what you are looking for. Shouldn't be to hard once i get familiar with your code. I will fork this now and get back to you after the holiday.

**Comment by webprofusion-chrisc** [comment]
@codeendevor thanks! Currently when you look at a managed certificate your seeing a cached version of the bindings we read, but this could be refreshed on demand. Some users have hundreds or thousands of bindings under one site.

**Comment by codeendevor** [comment]
Are we caching them for a reason? I get all my sites live in my application, do you have a reason for not getting live data? Maybe show all websites available on the left with sorts for sites without ssl, sites with other ssl providers, Ect.   Also looking we might be able to create a master and slaves the way i currently control my servers with my portal.

**Comment by webprofusion-chrisc** [comment]
@codeendevor Yes, when you change between different managed certificates we don't have time to query IIS bindings before displaying the UI, although we could do a background refresh instead - it should probably wait a second as user may just be scrolling through a bunch of them.

Your idea of sites on the left - currently the list is for managed certificates (which can each be a single site or many matching IIS sites, or not related to IIS at all etc, ) Maybe we need a different tab for this type of full server summary report (because it's a list of all site and all domains and their matching managed certificates). I do have an item on my todo list asking for something quite similar (more of 
 sortable/filterable management report).

**Comment by codeendevor** [comment]
I think i know what you mean, Sounds good. Let me try and put something together over the holiday,
