### ISSUE TITLE
Override certificate when create for new binding from IIS

### ISSUE THREAD

**Issue by Devangsinh** [webprofusion/certify#368]
Hi,
I am facing an issue in generating a certificate when I am generating a new certificate and that new certificate is **reflected all binding** which is in IIS. I am using the same Ip for all binding in IIS.

**Comment by webprofusion-chrisc** [comment]
@Devangsinh Hi, sorry I don't understand your description of the problem, could you phrase it differently or provide screenshots etc?

By default if you select a website in the app it will prepare to create a certificate for all domain bindings in IIS against that website. If you don't want to include some of those you can uncheck them.

You mention you are using the same IP for all bindings, this is only relevant if you are using non-SNI bindings on Server 2008 R2 (as Server 2012 onwards can share IPs for certificates using SNI). If you can use the default SNI bindings with no IP address specified then you should as creating explicit IP bindings can cause conflicts at the operating system level (windows can only map one specific port/IP address combination to one SSL cert, unless using SNI).

**Comment by andmattia** [comment]
I have the same issue.

IIS on Windows 2012 R2
3 site use AllUnassigned IP and foreach site I specify the URL(hostname) to bind

If I create a certificate for site A all site in HTTPS move to A certifcate and if I try to change on IIS config manually I get the waring

![image](https://user-images.githubusercontent.com/8192217/46725038-935a1c00-cc7b-11e8-81b0-9ab5f4e6dae2.png)

**Comment by webprofusion-chrisc** [comment]
@andmattia - if you have used Certify to create new https bindings can you please check that these are all set to have the IP as All Unassigned and that SNI is checked. Without SNI (and if a fixed IP is used) windows can only maintain one https certificate per IP address on the machine.

**Comment by andmattia** [comment]
@webprofusion-chrisc - Thank you so much it works fine for me

**Comment by webprofusion-chrisc** [comment]
@Devangsinh Static IP handling has been modified in v4.0.12 can you confirm if this issue is resolved or if you still have a problem? If still an issue, please provide more details.

**Comment by webprofusion-chrisc** [comment]
Closing as resolved.
