### ISSUE TITLE
Feature: surrogate validation domain/zone support

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#369]
Using DNS validation it can be useful to have a surrogate domain for validation only, this means that DNS API credentials only have access to the validation domain/subdomain instead of the real domain DNS.

Example:
- _acme-challenge.domain.com is a CNAME pointing to TXT record _acme-challenge.validation.domain.com (or any other domain) in the surrogate domain/subdomain.
- Let's Encrypt will follow the CNAME redirection when checking the challenge response.

Currently Certify DNS api's will attempt to create/update the TXT record in the 'domain.com' zone related to the API credentials, if the credentials actually apply to the surrogate domain zone 'validation.domain.com' this fails because 'domain.com' is not found in the zone.

The app needs to allow an optional surrogate domain to be specified for validation to allow for this case.

**Comment by webprofusion-chrisc** [comment]
See also #391 regarding acme-dns support

**Comment by webprofusion-chrisc** [comment]
As an extension to this idea, the proposed solution for CNAME redirection is to provide a hosted/managed service for DNS validation:
- User selected to use DNS Validation, CNAME Redirection Service
- Service provides user a TXT record name in a CTW managed domain (e.g. ABC123.managed.certifytheweb.com) with they point the acme-challenge.theirdomain.com CNAME to.
- Service then takes care up updating and managing the validation TXT record values.

This approach is similar to acme-dns, but perhaps simpler.
- Advantages: easy for the user, no more DNS APIs required, DNS credentials don't need to be stored on server etc.
- Disadvantage: if the managed CNAME service is compromised then the attacker has control over validation for those domains and can issue certificates from their own ACME client. So 2FA client registration etc is likely necessary as well as other access control safe guards.

Proposal is to host the redirected TXT records within AWS Route53 or other cloud DNS providers.

**Comment by BornToBeRoot** [comment]
Hey @webprofusion-chrisc,

are there any plans to integrate this? This would be great for Route53 if you have a subdomain `acme.example.com` (hosted zone) where the api user has write access to.

Other tools like lego (and traefik) already implemented this: https://go-acme.github.io/lego/dns/#experimental-features
Or cert-manager: https://cert-manager.io/docs/configuration/acme/dns01/#delegated-domains-for-dns01

Here is also a good documentation:
https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation

**Comment by webprofusion-chrisc** [comment]
HI @BornToBeRoot - I'd say yes but it's gotten a little low on the list of things to do. I have pages and pages of to-do list :)
We do provide the Certify DNS service (which is an alternative implementation of acme-dns and is CNAME delegation from your domain to our cloud based challenge response DNS service) but we also heavily rely on Posh-ACME for a lot of our DNS providers, I'm not sure if we want to support delegated challenge domains differently across multiple providers or if there is a way we can implement this for everything at once.

**Comment by webprofusion-chrisc** [comment]
@BornToBeRoot thinking about this a bit more, if we simply replace the primary domain with the delegated domain at the root of our dns update it should just work. I'll need to look into it.

**Comment by BornToBeRoot** [comment]
@webprofusion-chrisc in this case both zones are hosted in route53
 - example.com
 - acme.example.com

and we have a CNAME pointing from `_acme-challenge.service.example.com` to `_acme-challenge.service.acme.example.com`

The api credentials only have permissions for `acme.example.com`.  So you would only select the acme zone and maybe have a checkbox "Follow CNAME" to implenent the logic.

It would be great if you could look into it😄

**Comment by webprofusion-chrisc** [comment]
@BornToBeRoot so it wasn't quite as simple as I thought but it wasn't too bad. This feature will be in the next update. 

This will add a `CNAME Delegation Rule` option, where you can map your source domain to a target auth domain, this is because some/most of our DNS API providers expect to the fully qualified name of the _acme-challenge record, requiring that name to be translated before it's passed on to the DNS API providers.

**Comment by BornToBeRoot** [comment]
@webprofusion-chrisc Thanks! I eagerly await the next release 😄
