### ISSUE TITLE
Update to 4.0.9 issue

### ISSUE THREAD

**Issue by kd8ssq** [webprofusion/certify#371]
When trying to click the Update button in the UI, the software attempts to update the existing software and ends up throwing 2 different errors on multiple machines.
  
The first issue seems to be that the updater is trying to replace the service files prior to stopping the service.  If you manually stop the service, this error goes away.
![update issue 1](https://user-images.githubusercontent.com/6402523/46675401-48bd9e80-cbac-11e8-96b5-023ccced5746.PNG)

The second issue has to do with replacing a DLL file which I cannot seem to get around.  Clicking retry multiple times doesn't do anything.  I had to abort the upgrade on both servers.
![update issue 2](https://user-images.githubusercontent.com/6402523/46675402-48bd9e80-cbac-11e8-8615-59d1cb76cc08.PNG)

I'm trying to run the update from v4.0.8.

**Comment by webprofusion-chrisc** [comment]
Thanks, it looks like the installer failed to stop the running background service. 

As a workaround you can stop the Certify background service if it's still running and close the UI, then run the latest install (via the website download if required). In most cases this would normally work ok however. Are there any special considerations? i.e. are you running as Administrator (or some other account) when you run the setup, could anyone else also be logged in?

**Comment by kd8ssq** [comment]
I did try to run the update from the downloader off the site as well and ran into the same issues.  It kept failing at the DLL update after I manually stopped the service.  

I am running as an administrator w/ no one else logged into the server.  Windows Server 2012 R2

**Comment by webprofusion-chrisc** [comment]
Thanks, no similar reports so far but I have seen it happen in development. Assuming the update is not being prevented by an AV product can you confirm both the UI and background service are not running (under Task manager, kill anything that is still running).

**Comment by webprofusion-chrisc** [comment]
Glad you got it working. File locks can sometimes be tricky if for some reason its the system that's holding the lock.
