### ISSUE TITLE
Window disappears from task bar after minimizing and restoring

### ISSUE THREAD

**Issue by karelkrivanek** [webprofusion/certify#374]
Steps to reproduce:

- Run Certify
- Maximize window
- Click on Certify in taskbar to minimize
- Click on Certify in taskbar to restore the window
- Window is restored but it also disappears from taskbar

Windows Server 2012R2, version 4.0.8 and 4.0.10

**Comment by karelkrivanek** [comment]
Printscreen of active window but with it missing from taskbar
![certifywindowbug](https://user-images.githubusercontent.com/10894433/46866989-c0e1c980-ce23-11e8-9af6-56252725f6b4.png)

**Comment by webprofusion-chrisc** [comment]
Closing as not reproducible. This appears to be a transient windows shell issue and would likely be resolved by relaunching explorer.exe (the windows start/task shell)
