### ISSUE TITLE
System.ArgumentException during installation of a website certificate

### ISSUE THREAD

**Issue by 5chw4hn** [webprofusion/certify#377]
Dear Sir or Madam,

an error is occuring during our installation of a website certificate (IIS, SNI, IP-Bounded). "System.ArgumentException" in "D:\Work\GIT\certify\src\Certify.Core\Management\Servers\ServerProviderIIS.cs:Line 277."
This is the case in multiple websites. What could be misconfigured? I would greatly appreciate some feedback on this matter (We use Version 4.0.10.0). Thank you in advance.

> 2018-11-01 16:46:37.353 +01:00 [INF] Performing Automated Certificate Binding
2018-11-01 16:46:45.137 +01:00 [INF] System.ArgumentException: Der Wert liegt außerhalb des erwarteten Bereichs.
   bei Certify.Management.Servers.ServerProviderIIS.<AddOrUpdateSiteBinding>d__15.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\Servers\ServerProviderIIS.cs:Zeile 277.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Certify.Management.Servers.IISBindingDeploymentTarget.<AddBinding>d__2.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\Servers\ServerProviderIIS.cs:Zeile 784.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Certify.Core.Management.BindingDeploymentManager.<UpdateBinding>d__8.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\BindingDeploymentManager.cs:Zeile 348.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Certify.Core.Management.BindingDeploymentManager.<DeployToAllTargetBindings>d__6.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\BindingDeploymentManager.cs:Zeile 237.

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for reporting this. This exception has not been reported before, and it's occurring at an unusual part of the code (related to checking that the IIS site has a site Id).

Does this same exception appear when you look at the Preview tab for one of the managed certificates?

Do any of the site on your server contain unusual protocol bindings (such as message queues etc) outside of the usual http or https?

**Comment by 5chw4hn** [comment]
Hi, thank you for your response.

in the Preview tab no error occurs.  The preview contains following content (I have anonymised the domains and IP address):
> Summary
> 
> A new certificate will be requested from the Let's Encrypt certificate authority for the following domains:
> 
> www.customdomain.de (Primary Domain) and will include the following Subject Alternative Names:
> - customdomain.de
> - beta.customdomain.de
> - customdomain.net
> - www.customdomain.de
> - www.customdomain.net
> 
> 1. Domain Validation
> 
> Authorization will be attempted using the http-01 challenge type.
> 
> The following matching domains will use this challenge:
> 
> - beta.customdomain.de
> - customdomain.de
> - customdomain.net
> - www.customdomain.de
> - www.customdomain.net
> 
> This will involve the creation of a randomly named (extensionless) text file for each domain (website) included in the certificate.
> 
> The Http Challenge Server option is enabled. This will create a temporary web service on port 80 during validation. This process co-exists with your main web server and listens for http challenge requests to /.well-known/acme-challenge/. If you are using a web server on port 80 other than IIS (or other http.sys enabled server), that will be used instead.
> 
> The file will be created at the path {CustomServerPath}\CustomDomain\Http\.well-known\acme-challenge\
> 
> The text file will need to be accessible from the URL http://<yourdomain>/.well-known/acme-challenge/<randomfilename>
> 
> Let's Encrypt will follow any redirection in place (such as rewriting the URL to https) but the initial request will be made via http on port 80.
> 
> This challenge type will be selected for all domains.
> 
> 2. Certificate Request
> 
> A Certificate Signing Request (CSR) will be submitted to the Let's Encrypt certificate authority, using the RS256 signing algorithm.
> 
> 3. Deployment
> -  Deploy to hostname bindings matching certificate domains.
> -  Add or Update https bindings as required
> 
> Deploying to Site
> CustomDomain
> 
> Action Site Binding
> Add https binding CustomDomain SpecificIP:443:beta.customdomain.de 
> Add https binding CustomDomain SpecificIP:443:customdomain.de 
> Add https binding CustomDomain SpecificIP:443:customdomain.net 
> Add https binding CustomDomain SpecificIP:443:www.customdomain.de 
> Add https binding CustomDomain SpecificIP:443:www.customdomain.net 

We are using following protocols:
- http
- https
- ftp

There are also a few protocols defined per default:
- net.tcp
- net.pipe
- net.msmq
- msmq.formatname

**Comment by webprofusion-chrisc** [comment]
You mention you are using a specific IP - is there a reason for this? On server 2012 onwards SNI is available, making the requirement for a specific IP address unnecessary. Binding certificates to a specific IP can in some cases cause unpredictable results, especially if there is any possibility that two certificates might try to bind to the same IP. That said, using that option shouldn't cause an exception (unless there is a conflict).

**Comment by 5chw4hn** [comment]
Our web server can be accessed through approx. 10 IP addresses. SNI should only be activated for one IP address. The other IP addresses are permanently linked to a domain, so that clients without SNI compatibility can address these specific domains via SSL. These specific domains can only be addressed under this exact IP address, and not via SNI.

**Comment by webprofusion-chrisc** [comment]
Thanks, I understand, yes you'll need the fixed IP to support non-SNI capable clients. So currently I've been unable to reproduce this issue. Can you try manually adding the https bindings you require, then set Deployment to Single Site and set Binding Add/Update to Update Only, then try that.

**Comment by 5chw4hn** [comment]
Please excuse the delayed reply.

I manually added the following bindings in the IIS:

Type | Hostname | Port | IP-Address
------------ | ------------- | ------------- | -------------
https | beta.customdomain.de | 443 | SpecificIP
https | customdomain.de | 443 | SpecificIP
https | customdomain.net | 443 | SpecificIP
https | www.customdomain.de | 443 | SpecificIP
https | www.customdomain.net | 443 | SpecificIP

I registered the same certificate for each entry.

Under "Deployment" in "Certifiy The Web" I used the following settings:

Deployment Mode: Single Site
Binding Add/Update: Update existing https bindings only
Matching any of: Existing binding hostname matches certificate domains

Then I requested a new certificate. This was successful.

Now the following HTTPS entries exist in the ISS bindings:

Type | Hostname | Port | IP-Address
------------ | ------------- | ------------- | -------------
https | beta.customdomain.de | 443 | *
https | customdomain.de | 443 | *
https | customdomain.net | 443 | *
https | www.customdomain.de | 443 | *
https | www.customdomain.net | 443 | *
https | beta.customdomain.de | 443 | SpecificIP
https | customdomain.de | 443 | SpecificIP
https | customdomain.net | 443 | SpecificIP
https | www.customdomain.de | 443 | SpecificIP
https | www.customdomain.net | 443 | SpecificIP

The domains for which I requested a certificate, now exist twice. One with a SpecificIP and one with the Wildcard "*".
Requesting the certificate anew brings about the same error as before.

**Comment by webprofusion-chrisc** [comment]
@5chw4hn  thanks, I think there is duplication occurring when specific IP bindings exist, I am investigating just now. In the meantime you should set deployment to binding Update Only (the Auto option uses add/update bindings as required), and clearly it's getting confused.

**Comment by webprofusion-chrisc** [comment]
@5chw4hn v4.0.12 now has updated handling of static IP bindings and also the clearing of previous custom options if now using Auto options. Can you update and confirm if you still have issues with static IP handling?

**Comment by 5chw4hn** [comment]
Hello @webprofusion-chrisc,

it's been a while since my last reply, but in the last couple of days I spent some more time debugging the issue and to finally come up with a workaround:

First I downloaded the CertifyTheWeb-Project from GIT (https://github.com/webprofusion/certify/tree/4.1.6), put dozens of Log-Entries into the code, compiled the project and ran the project successfully on our server where the issue occurs. With the help of my log entries I found that the error occurs in following line:
_[Line 348](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/Servers/ServerProviderIIS.cs#L348)._ `binding.CertificateStoreName = bindingSpec.CertificateStore;`

Following exception occurred: 

> AddOrUpdateSiteBinding (ServerProviderIIS.cs) - error: System.ArgumentException: Der Wert liegt außerhalb des erwarteten Bereichs.
>    bei Microsoft.Web.Administration.Interop.IAppHostProperty.get_Value()
>    bei Microsoft.Web.Administration.ConfigurationElement.GetPropertyValue(IAppHostProperty property)
>    bei Microsoft.Web.Administration.Binding.GetBindingAttributeValue(String attributeName)
>    bei Microsoft.Web.Administration.Binding.get_CertificateHash()
>    bei Microsoft.Web.Administration.Binding.set_CertificateStoreName(String value)

I spent a lot of time searching for a solution. It seems that in case of **using SNI with a bounded IP-address** the Microsoft-Binding-Object has a bug that removes or does not set the property "CertificateHash" after setting the binding-informations.
I found a workaround for this bug: I moved following line 
_[Line 347](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/Servers/ServerProviderIIS.cs#L347)._ `binding.BindingInformation = bindingSpecString;` below the 
_[Line 349](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/Servers/ServerProviderIIS.cs#L349)._ `binding.CertificateHash = bindingSpec.CertificateHashBytes;` line.

**Old code block from GIT** (lines [343](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/Servers/ServerProviderIIS.cs#L343) to [351](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/Servers/ServerProviderIIS.cs#L351)):
```
// Set binding values
if (bindingSpec.IsHTTPS)
{
    binding.Protocol = "https";
    binding.BindingInformation = bindingSpecString;
    binding.CertificateStoreName = bindingSpec.CertificateStore;//This is the line where the error occurs
    binding.CertificateHash = bindingSpec.CertificateHashBytes;
}
else
...
```
**New code block with my changes** (lines 343 to 351):
```
// Set binding values
if (bindingSpec.IsHTTPS)
{
    binding.Protocol = "https";
    binding.CertificateStoreName = bindingSpec.CertificateStore;//The error occurs no longer
    binding.CertificateHash = bindingSpec.CertificateHashBytes;
    binding.BindingInformation = bindingSpecString;//moved from line 347
}
else
...
```

With this change the error occurs no longer. **I successfully updated all my certificates**. I think that this change has no effect to bindings without using SNI with a bounded IP-address, but it fixes the issue for this particular case.

Using this workaround, we were now able to request a **new certificate** for a **new website**, which led us straight to the next problem:
After a successful certificate request, we now ran into the problem that the **SNI-Flag was not set to 'true'**. Reason for that was our use of **SNI with a bounded IP-address**, which sets the 'useSNI'-bool to false in the [BindingDeploymentManager in line 357](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/BindingDeploymentManager.cs#L357).

**Old code block from GIT** (lines [356](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/BindingDeploymentManager.cs#L356) to [357](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/BindingDeploymentManager.cs#L357)):
```
// specific IP address, SNI is not applicable
useSNI = false;
```

On our local version of the program, we just commented out the [line 357](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/BindingDeploymentManager.cs#L357) to prevent setting the bool to false, which works for us, but I think it is obviously not the "cleanest" way to handle it. You may have a better fix for it.

**New code block with my changes** (lines 356 to 357):
```
// specific IP address, SNI is not applicable
//useSNI = false;//do not set useSNI to false if it is a specific ip address.
```

I would be glad if you insert this change into your GIT-Project and send me a new version with these changes that I can test on our server.

**Comment by webprofusion-chrisc** [comment]
@5chwhm thanks! I'll need to review this. The order properties are set could perhaps make a difference.

Regarding setting SNI with a fixed IP- SNI is all about hostnames and IP shouldn't even come into it. We are making a decision (in the code) to skip SNI if you force an IP binding, the correct fix is to not set an IP if you're using SNI.

**Comment by 5chw4hn** [comment]
Hello @webprofusion-chrisc,

thank you for your response. [Like commented above](https://github.com/webprofusion/certify/issues/377#issuecomment-436551062): 

> Our web server can be accessed through approx. 10 IP addresses. SNI should only be activated for one IP address. The other IP addresses are permanently linked to a domain, so that clients without SNI compatibility can address these specific domains via SSL. These specific domains can only be addressed under this exact IP address, and not via SNI.

So I have no choice: I have to use SNI with IP-binding.
I do have a **suggestion**, perhaps you can insert following changes:

1. In the global settings, add two more checkboxes.
1.1. Checkbox "**Enable SNI with IP-binding (experimental)**"
1.2. Checkbox "**Use alternative binding-order while updating certificates (experimental)**"
2. In the [BindingDeploymentManager in line 357](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/BindingDeploymentManager.cs#L357), update the following in the code: 
```
// specific IP address, SNI is not applicable
if (useSNI && (!enableSniWithIpBinding)) //enableSniWithIpBinding is CheckBox 1.1
{
    useSNI = false;//do not set useSNI to false if it is a specific ip address.
}
```
3. In the [ServerProviderIIS in line 347](https://github.com/webprofusion/certify/blob/4.1.6/src/Certify.Core/Management/Servers/ServerProviderIIS.cs#L347), update the following in the code:
```
// Set binding values
if (bindingSpec.IsHTTPS)
{
    binding.Protocol = "https";
    if (alternativeBindingOrder) //alternativeBindingOrder is CheckBox 1.2
    {
        binding.CertificateStoreName = bindingSpec.CertificateStore;//The error occurs no longer
        binding.CertificateHash = bindingSpec.CertificateHashBytes;
        binding.BindingInformation = bindingSpecString;//moved from line 347
    }
    else
    {
        binding.BindingInformation = bindingSpecString;
        binding.CertificateStoreName = bindingSpec.CertificateStore;
        binding.CertificateHash = bindingSpec.CertificateHashBytes;
    }
}
else
...
```

With these options I can use every new CertifyTheWeb-Version in the future without modifying the changes manually. I would be glad if you could incorporate these changes.

**Comment by 5chw4hn** [comment]
Hello @webprofusion-chrisc,
I just checked [your commit](https://github.com/webprofusion/certify/commit/17e81270afe98d46905de58ee07136bf93e69038) and saw that you have already implemented ServerProviderIIS in line 347
I apologize and kindly request you to ignore the 3. point in my previous post.

With that, point 1.2. Checkbox *"Use alternative binding-order while updating certificates (experimental)"* can also be ignored as it's already implemented.

If you could however please insert point 1.1. Checkbox and point 2, I would be extremely thankful.

**Comment by webprofusion-chrisc** [comment]
@5chw4hn thanks, I understand the issue regarding clients that don't support SNI having to fallback to the IP. As you are specifying a fixed IP per certificate (one or more domains all point to the same website) it sounds like you don't need Use SNI checked at all, the certificate will instead be bound to the IP you specify instead of depending on the hostname?

Edit: note that you can preview how your bindings will be applied in the Deployment section of the Preview Tab, updates to existing https bindings recreate the *current* binding settings (with the new certificate applied) so existing https binding need to be removed to take on the new settings we you re-deploy.

**Comment by 5chw4hn** [comment]
Hi @webprofusion-chrisc,

We operate dozens of websites on our web servers.
Some sites have separate IPs and others use the same standard IP.
For websites that use a separate IP, SNI is not checked, but for websites that use the standard IP, SNI must be checked for the correct certificate to be delivered to the domain.
That's why we need this functionality.
