### ISSUE TITLE
Support for tomcat or non-IIS web server in Windows?

### ISSUE THREAD

**Issue by vicperdana** [webprofusion/certify#382]
Can this work with a tomcat?  Or can it work natively with Windows Certificate manager and without binding to IIS?

We could possibly script the binding to Tomcat if it's not supported natively by this tool.

**Comment by webprofusion-chrisc** [comment]
Hi, yes you could use it with Tomcat if you can script the conversion of the PFX file into the component certificate parts you need - I haven't tried it myself but should be do-able using a post-request script (see Show Advanced Options). You can deploy the certificate itself to the store only (or disk only) and you don't need to use have/IIS at all.
