### ISSUE TITLE
Please add 2008 R2 Script Hook for RDP

### ISSUE THREAD

**Issue by amayatsky** [webprofusion/certify#383]
```param($result)
if ($result.IsSuccess) {
    if ($result.ManagedItem) {
        if ($result.ManagedItem.CertificateThumbprintHash) {
        # get a reference to the config instance
        $tsgs = gwmi -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -Filter "TerminalName='RDP-tcp'"
        # grab the thumbprint
        $thumb = $result.ManagedItem.CertificateThumbprintHash.ToString().ToUpper()
        # set the new thumbprint value
        swmi -path $tsgs.__path -argument @{SSLCertificateSHA1Hash="$thumb"}
        }
    }    
}
```

**Comment by webprofusion-chrisc** [comment]
Thanks, this looks similar to the[ current example script ](https://github.com/webprofusion/certify/blob/development/src/Certify.Shared/Scripts/Common/RDPListenerService.ps1) but doesn't use WMI, does the WMI method not work on 2008 R2?

**Comment by amayatsky** [comment]
Indeed it's the same but I haven't seen this example anywhere.
I was suggesting that probably the WMI approach should be added here: https://docs.certifytheweb.com/docs/script-hooks.html

**Comment by webprofusion-chrisc** [comment]
Thanks, we also have some example scripts distributed with the 4.x app, which was the link I gave.
