### ISSUE TITLE
Support acme-dns

### ISSUE THREAD

**Issue by Daniel15** [webprofusion/certify#391]
Is it possible to add support for acme-dns as a DNS provider?

https://github.com/joohoi/acme-dns

**Comment by webprofusion-chrisc** [comment]
Thanks, yes, it certainly is. I'll be starting work on support for acme-dns this week or next. 

I'm also hoping to provide a simpler option hosted via an API to certifytheweb.com (with the usual caveats) for those who need to reduce complexity.

**Comment by webprofusion-chrisc** [comment]
This is now implemented in it's most basic form in the latest beta (4.1.0). 

To use, just select Authorization> DNS > acme-dns and specify your preferred acme-dns API + optional IP range restrictions. Hitting Test will then do the initial registration and provide the CNAME redirection settings, you can now click to copy the values to the clipboard.

As mentioned before elsewhere I'm currently evaluating offering hosted acme-dns services as part of https://certifytheweb.com (requiring additional auth credentials and behind an API gateway).

**Comment by webprofusion-chrisc** [comment]
Closing. This is now included in the current release. Docs still to do.
