### ISSUE TITLE
Service crashes if System account does not have permission to access certificate artifacts

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#399]
If folder permissions to C:\ProgramData\Microsoft\Crypto\DSS\MachineKeys (and other related folders) are modified it may prevent access for the local SYSTEM account and therefore the background service may fail to access and write certificate info. The Service currently crashes and this in turn causes exceptions in the UI. 

The service should instead report the error and continue as normal.

**Comment by ptr2null** [comment]
I've encountered a similar bug as #398 and modified the permission on folder 
C:\ProgramData\Microsoft\Crypto\DSS\MachineKeys, but still get errors. 

Installed the latest version 2 days ago. 

Log file is attached to this.

[log_09125dde-c02a-4451-8c79-c38ed0a9604e_.txt](https://github.com/webprofusion/certify/files/2913865/log_09125dde-c02a-4451-8c79-c38ed0a9604e_.txt)

**Comment by webprofusion-chrisc** [comment]
@ptr2null thanks, there's nothing to suggest this is related to either of these bugs though. Your log says "Name does not end in a public suffix" - let's encrypt can only issue certs for public domains (not internal intranet names etc). Or perhaps your domain is an unusual one? Either way it appears to not be supported by Let's Encrypt.

**Comment by ptr2null** [comment]
Thanks. I've missed that point... it is for sure an issue with our internal intranet name which ends with .local. Seems, the previous sys-admin did a good job... *sigh*

**Comment by webprofusion-chrisc** [comment]
@ptr2null if your current managed cert in Certify includes both the public domain name and the intranet name, uncheck the intranet name under the 'Domains' tab then try your certificate request again. You will need to use an alternative self-signed cert (or other method) if you need the .local intranet name to be https as well.
