### ISSUE TITLE
Failed to generate PFX file for Certificate

### ISSUE THREAD

**Issue by RickStrahl** [webprofusion/certify#4]
I'm getting the above error on sites that previously worked. Is there anyway to get a better error message than this that gives a hint what might be going on?

More info:
- Removed all traces of X1 certificates which broke old certs
- Removed all sites from Certify and eventually removed entire Vault.
- Removed all certificates from IIS Certificate manager
- Tried to recreate sites with Certify

This is when I get the above error.

Now, I have about 10 sites on this server and there are a number of www. domains that previously did not use Certify, and **those** work and create proper certificates with the appropriate X3 certificate chain. Those sites work, the old ones that were previously created do not.  All of the ones that don't work are site.com domains (ie. no prefix) which shouldn't really matter and all were previously registered under Certify. Could be some sort of over the limit, but without any more error info it's hard to tell.

Is there some place where error information is dumped out?

**Comment by webprofusion-chrisc** [comment]
Here is some further information on how to fix the X1 cert chain problem: https://community.letsencrypt.org/t/iis-8-5-building-incorrect-chain-with-lets-encrypt-authority-x3/13320/82

**Comment by soundshed** [comment]
Closing old issue, previously resolved.
