### ISSUE TITLE
Add UI support for PasswordBox and ComboBox with differentiated ProviderParameters

### ISSUE THREAD

**Issue by AJH16** [webprofusion/certify#403]
Add support for multiple types of input for ProviderParameters.  Current providers already have need of PasswordBox and ComboBox inputs as there are passwords and secrets being displayed on-screen while creating a credential.  Similarly there are inputs which have a limited number of valid inputs which currently allow invalid input.  These should be replaced with ComboBoxes.

I have already done most of the underlying type refactor to enable this in [this branch](https://github.com/AJH16/certify/tree/UI_parameter_options), however I ran in to trouble on the XAML side as I'm not particularly good at XAML.  

This branch provides 3 new ProviderParameter classes and removes the setability of the IsPassword field as it is now tied directly to the ProviderPasswordParameter.  The ProviderStringParameter is the replacement for the current default ProviderParameter.  ProviderDropDownParameter allows for an Options collection to be specified to use to fill in the options of the ComboBox.

An added bonus for this would be to figure out how to work directly back in to SecureString for the password input when loading from DPAPI, but that doesn't appear to be easily doable and may not be worth the headaches involved since many providers don't support SecureString anyway.

**Comment by webprofusion-chrisc** [comment]
Sounds awesome, I'll check it out. 

Just as an aside, this could be related to other functionality I was thinking of for scripting. I'd like to be able to provide UI for certain PowerShell pre/post request script (particularly exchange etc) so users can enable/disable things etc for a standard script rather than having to edit the script itself.
