### ISSUE TITLE
Wildcard certificate should not make FQDN in the same domain redundant

### ISSUE THREAD

**Issue by swinster** [webprofusion/certify#407]
Version 4.0.12

Noted that it gives a error when you have a wildcard certificate and FQDN in the same domain, when the error says that that wildcard makes the FQDN redundant. This is not always the case.

For SIP, we require FQDNs to be added as DNS component to the SAN, however the same certificate may be used to also secure HTTPS traffic. **RFC 5922 - Domain Certificates in the Session Initiation Protocol (SIP)** -  https://tools.ietf.org/html/rfc5922, section 7.2 states that SIP identifier MUST NOT match any form of wildcard, however, if the DNS component in the SAN matches a host in its entirety, this is fine.

It is therefore great to have both wildcard and full FQDNs within the SAN of any given cert, e,g:

```
*.example.com 
host.example.com 
```

**Comment by webprofusion-chrisc** [comment]
I'll need to check but I'm almost certain this was a Let's Encrypt limitation, i.e. the order will be rejected.

**Comment by webprofusion-chrisc** [comment]
See this info on LE wildcard support:
https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578

Closing for now as this is enforced at the Let's Encrypt level.
