### ISSUE TITLE
Cannot start application on Windows Server 2008 R2 due to missing service dependency

### ISSUE THREAD

**Issue by graealex** [webprofusion/certify#408]
On Windows Server 2008 R2, when starting the Certify application, it quits due to the Certify SSL Manager service not being started.

The Certify SSL Manager service cannot be started from the Services snap-in due to a missing service dependency:

> Windows could not start the Certify SSL Manager Service service on XY.
> Error 1075: The dependency service does not exist or has been marked for deletion.

Certify introduced a new service dependency, visible in the registry in the key "DependOnService" -> "HTTP Service". On Windows Server 2008 R2, there is no service named "HTTP Service", and thus the dependency cannot be satisfied.

Installing and starting Certify worked for 4.0.12 stable, but does not work for 4.0.13-beta4. Workaround is to manually remove the dependency from the registry and restart the computer. Then the service can be started and Certify runs fine.

Adding a dependency to a non-existing service is not only unnecessary, but also wrong. Either the service runs without the dependency - then the dependency shouldn't be one, or the program installation should abort because the dependency can never be satisfied, thus terminating support for the OS entirely.

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this, this was added to debug an issue some users have whereby the local API cannot create an http listener due the the internal HTTP Service (which is the kernel service for HTTP.sys) being disabled (resulting an an 'unsupported on this platform' exception).

Perhaps it's just called HTTP on older versions of windows (or doesn't exists as an addressable service). I believe in old version of windows it can be found under Device Manager non-plug and play as Http (and enabled/disabled from there). You can start and stop if from the command line using 'net stop http/net start http'.

Either way we can remove the dependency.

**Comment by webprofusion-chrisc** [comment]
Just as an example of the service actually existing (it doesn't show under Local Services as it's too low level):
![image](https://user-images.githubusercontent.com/2445502/50063690-78120c80-01e8-11e9-8ab7-2634c3958dad.png)

**Comment by graealex** [comment]
Well, if the HTTP service is actually needed and the Certify service would fail without it, then the dependency should remain, but should reference the correct service names on different OSes or not reference it on older versions of Windows where it might not be addressable. IMHO.

**Comment by webprofusion-chrisc** [comment]
I think maybe it would work as "HTTP" and it just happens to work fine on newer windows of you ask for it as "HTTP Service".  We have other diagnostics we can do instead of adding the service dependency so it's still probably worth removing it, that way the service can still start enough to log the issue and we could possibly even inform the UI what the problem is via the config file.
