### ISSUE TITLE
Webhook variable

### ISSUE THREAD

**Issue by lifehome** [webprofusion/certify#416]
I am seeing that there are variables available in powershell scripting, but is there a list of variables for webhook? 

## Issues encountered
The current result of `https://localhost/?result=$result.IsSuccess` will let the webhook server receive `result=$result.IsSuccess` as parameter, instead of a boolean returned from the program.

## Expected result
The webhook server should receive either `result=true` or `result=false`, as well as other parsed variables, such as certificate expiry date and fingerprints.

**Comment by nconder** [comment]
Im looking for a complete list too but this may be all that is available. 
https://docs.certifytheweb.com/docs/script-hooks.html

**Comment by webprofusion-chrisc** [comment]
Hi, please do submit a PR for any docs you find lacking to the certify-docs repo. As noted the variables are mostly the same as powershell script hooks, so the main variables are from the ManagedCertificate object: 
https://github.com/webprofusion/certify/blob/development/src/Certify.Models/Config/ManagedCertificate.cs

The webhooks have and additional `success` which is true or false, and a string version of the `subjectalternativenames` list.

As you can probably guess, I don't use the webooks functionality myself but it appears to be useful to others. You can examine the logic behind it here: https://github.com/webprofusion/certify/blob/development/src/Certify.Shared/Utils/Webhook.cs

**Comment by lifehome** [comment]
Thanks for the suggestion @webprofusion-chrisc, I think I will leave the PR for others to do.

Instead, please kindly read my encounter stated in my issue, where contradicts to your saying on `variables are mostly the same as powershell script hooks`. By no means I want to go war, but this is so confuse given the webhook.cs does not provide interface to access the ManagedCertificate object.

**Comment by webprofusion-chrisc** [comment]
No problem, thanks for your feedback.
