### ISSUE TITLE
Support cPanel for DNS challenge

### ISSUE THREAD

**Issue by Magissia** [webprofusion/certify#418]
For domains managed by a cPanel instance, it would be useful to be able to use their API for DNS validation.

https://documentation.cpanel.net/display/DD/cPanel+API+2+Functions+-+ZoneEdit%3A%3Aedit_zone_record

**Comment by webprofusion-chrisc** [comment]
There hasn't been much interest in cPanel support, so closing this for now. Anyone interested in supporting cPanel can use DNS scripting (https://docs.certifytheweb.com/docs/dns/providers/scripting/)  or write a provider for Posh-Acme (https://github.com/rmbolger/Posh-ACME/tree/master/Posh-ACME/DnsPlugins)
