### ISSUE TITLE
TransIp DNS Api Support

### ISSUE THREAD

**Issue by WalterEbbers** [webprofusion/certify#419]
Hi,

I would like to request TransIp support for the DNS-01 challenge.
TransIp has a php api but i have found that there is a C# project that is build arround the api(which could maybe be used for this).

the API is available here: https://www.transip.nl/transip/api/

Kind regards,

Walter

P.S.: In my first post i accidentally pressed create issue, and immediately presses closed but this is a new issue so not closed :)

**Comment by ErikvO** [comment]
I’ve created a pull request for this issue: #488

**Comment by webprofusion-chrisc** [comment]
@ErikvO thanks very much for your contribution, I didn't really expect such a comprehensive solution! I have no way to test this provider so we'll need some other users to try it out during the v5 beta testing phase. If you would like a free license key for your contribution please email support {at} certifytheweb.com - with details of your preferred email address for the license key to be assigned to.

**Comment by ErikvO** [comment]
@webprofusion-chrisc No problem.
I've been using open source code for so long now. Glad I could finally do something back for the community. Plus: It's not entirely altruistic ;)

**Comment by webprofusion-chrisc** [comment]
Closing. Implement in v5 (beta).
