### ISSUE TITLE
Add certificate name request $result.ManagedItem.CertificateName

### ISSUE THREAD

**Issue by nconder** [webprofusion/certify#420]
Im writing a PS script for Office Online Server but [MS requires](https://docs.microsoft.com/en-us/officeonlineserver/deploy-office-online-server#step-1-create-the-office-online-server-farm-1) that it is passed the certificate name.

Please add $result.ManagedItem.**CertificateName**

`param($result)

Set-OfficeWebAppsFarm -InternalUrl "https://oos.XYZ.com" -ExternalUrl "https://oos.XYZ.com" -CertificateName $result.ManagedItem.CertificateName`

**Comment by nconder** [comment]
Microsoft Office Online Server script

Note that OOS does not have the ability to set certificate by thumbprint.

https://github.com/nconder/PowerShell-General/blob/master/CertifyTheWeb-OOS-Set_Cert.ps1

`Import-Module -Name OfficeWebApps 

$OOSUrl = "ENTER OOS URL"

$certFN = dir cert: -Recurse | Where-Object { $_.Thumbprint -eq "$result.ManagedItem.CertificateThumbprintHash" } | Select-Object FriendlyName

New-OfficeWebAppsFarm -InternalUrl $OOSUrl -ExternalUrl $OOSUrl -CertificateName $results -EditingEnabled -OfficeAddinEnabled -OnlinePictureEnabled -OnlineVideoEnabled -ClipartEnabled -TranslationEnabled -AllowOutboundHttp -ExcelAbortOnRefreshOnOpenFail $true -ExcelAllowExternalData`

**Comment by webprofusion-chrisc** [comment]
Implemented in next release as `CertificateFriendlyName`, there is also a new Certificate Store deployment task which allows a custom friendly name.
