### ISSUE TITLE
Problem with Auto renewal Certificate

### ISSUE THREAD

**Issue by Sepehrsystems** [webprofusion/certify#422]
Hi There.
I Have a problem.
I have Many sites and I use your program for SSL Certificates for these sites.
I Have problem with adding certificate bind to these sites.
Auto Renewal is enabled and for these sites completes successfully (it will add the certificate to server and IIS Successful).  but it won't set to the site successful sometimes.
for example look at this picture: 
the name of the site is frd5.net
![expire1](https://user-images.githubusercontent.com/46744081/51248750-661db800-19a6-11e9-8a25-249fb2edb253.JPG)
auto renewal for this site has been done and expires on 3/23/2019,
But the certificate that already is set to the site expires on 1/18/2019. 
look at this picture:
![expire2](https://user-images.githubusercontent.com/46744081/51248862-b432bb80-19a6-11e9-9fd5-8ba3636396bf.JPG)
in another word it doesn't set the certificate to site automatically, I have do it manual.
you can also look at the Server Certificates in iss at this picture:
![expire3](https://user-images.githubusercontent.com/46744081/51248890-c7de2200-19a6-11e9-97c5-a70510f86f5e.jpg)
I enabled "Automatic Rebind of Renewed Certificate" in IIS.
I am using IIS 8.My Program version is 4.0.12.0 .
I have about 200 sites that use this kind of Certificate and It happens for 40-60 percent of them.

**Comment by webprofusion-chrisc** [comment]
Hi, there was bug in 4.09 where binding weren't updated but that has been resolved for a while (unless you recently updated). If you were on that version and have updated then the problem will go away when the next renewal happens, or you can go to Show Advanced Options > Other Options > Re-apply certificate binding.

If you have been on 4.0.12 for a while, please can you check the Preview tab for your frd5.net managed certificate and ensure that the bindings section (scroll down to see it) says it will definitely update your binding. If the binding is not listed it will not be updated. There are several options for deployment and these can affect which bindings will get updated and which won't.

**Comment by Sepehrsystems** [comment]
You helped me a lot. 
I set Deployment to Auto and in the preview it shows them now. 
Now It does rebind automatically. 
Thank you.

**Comment by webprofusion-chrisc** [comment]
@Sepehrsystems good to hear, but what was Deployment set to before? The Single Site deployment should be the default if you have upgraded previously and that should work fine unless your IIS Site ID's have changed.

**Comment by Sepehrsystems** [comment]
It was set "Single site", but in the preview it didn't show bindings. I had to delete some of them and add them again to fix that. but about the others I set the deployment to Auto.
