### ISSUE TITLE
DNS-01 + OVH = 403 Forbidden

### ISSUE THREAD

**Issue by davidcie** [webprofusion/certify#425]
Have not come across the exact same issue so reporting to get others' feedback if this is server side vs client side. 

I followed the guide on setting up OVH DNS credentials and triple-checked if I'm copying the right app key, secret and consumer key. Additionally, I have developer access enabled in OVH admin panel just in case. But I still get a 403 error whenever I test my credentials:

![ovh 403](https://user-images.githubusercontent.com/1963866/51542289-30237c80-1e5b-11e9-8644-a9aa981cf6aa.png)

This happens on 4.0.12, 4.1.0-beta3 and when running a debug build of a6710c5 in Visual Studio. Unfortunately no more info is shared by OVH in the exception message and I was unable to intercept communication in Fiddler to have a peek. Contacted support but they were less than helpful. 

If you're aware of any other steps I should take before this works please let me know, will also be more than happy to help debug and nail this one down.

**Comment by webprofusion-chrisc** [comment]
@davidcie thanks for going to such effort to investigate, this does seem to be a problem with credentials, is there any way you can test a request using curl or other utility to see of the credentials are working?

To inspect with fiddler you need to launch fiddler before launching visual studio, otherwise it doesn't seem to intercept the http calls.

**Comment by davidcie** [comment]
Thanks for the VS + Fiddler tip, it's working as expected now. The exact response from `eu.api.ovh.com` is the following JSON:

```
{
    "errorCode":"NOT_GRANTED_CALL",
    "httpCode":"403 Forbidden",
    "message":"This call has not been granted"
}
```
Using OVH API console I have verified that permissions are set to `/domain/zone*` on all HTTP verbs for this app so this must be something else. There's a few threads with a similar problem and in one case setting up another account mysteriously worked. Any API call you are aware of that would allow me to check for required permissions?

**Comment by webprofusion-chrisc** [comment]
Yeah I would try creating a new API key if you can. If you can query the zones list that would be a good start but as they have different permissions for different verbs you won't know it's all working until you've run a full certificate test using those credentials (which will query the zone list and update test records).

**Comment by davidcie** [comment]
Worked with new credentials. Go figure... Perhaps you have to enable developer access first in OVH control panel and _then_ create credentials..? I can see no differences if I query `/me/api/credential/{credentialId}` for both apps (working and not working), and found no other API call to verify any other settings.

Anyway, glad to have this working. Thank you for your help!
