### ISSUE TITLE
Inplace version update crashed

### ISSUE THREAD

**Issue by thinairmarc** [webprofusion/certify#431]
attempting an in-place upgrade from v4.0.12 to v4.1.4, and it fails.

when clicking 'abort' installation, it rendered the existing installation non-functioning.

environment: Windows Server 2012 R2 Datacenter

I have certs expiring in less than five days, any suggestions?

is an uninstall/reinstall a non-destructive process?

thanks!
![4 1 4-install error](https://user-images.githubusercontent.com/47252490/52135062-399ea880-2602-11e9-8036-3483286939db.jpg)

**Comment by webprofusion-chrisc** [comment]
Hi Marc, 

This is fairly normal on windows.

Uninstall/reinstall vs add remove programs is not destructive, so applications settings will remain in C:\programdata\certify (good idea to have that folder in your backup plan) and you are safe to uninstall and reinstall manually.
