### ISSUE TITLE
Docs: aws route53 permissions don't have to be AmazonRoute53FullAccess 

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#432]
We need to identify the more granular set of permissions required for aws route53 API access as the current AmazonRoute53FullAccess is overly broad.

**Comment by ravemir** [comment]
I was able to have it work with the following policy:
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "route53:GetChange",
                "route53:GetHostedZone",
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets"
            ],
            "Resource": [
                "arn:aws:route53:::change/*",
                "arn:aws:route53:::hostedzone/<my hosted zone>"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZones",
                "route53:TestDNSAnswer",
                "route53:ListHostedZonesByName"
            ],
            "Resource": "*"
        }
    ]
}`

This includes listing the corresponding hosted zone when specifying the credentials.

**Comment by webprofusion-chrisc** [comment]
@ravemir thanks for that, Ideally we'd be able to reduce that to instructions on which boxes to check in the UI.

**Comment by webprofusion-chrisc** [comment]
Minimal route53 permission are now documented: https://docs.certifytheweb.com/docs/dns-awsroute53
