### ISSUE TITLE
Feature: configurable deployment tasks (alpha/beta testers wanted)

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#440]
**Testers wanted, please reply and indicate the deployment task type you'd like to test (or would like added)**

#329 
Currently our main deployment options are:
- Local Certificate Store + Local IIS
- Local Certificate Store

You can additionally use Scripting (Show Advanced Options > Scripting) post-request to perform custom deployment actions.

This planned feature *Deployment Tasks* intends to extend our current deployment options to have UI for optional selection and configuration of common deployment tasks which can be performed in a variety of configuration:
- Certificate Store
- Centralised Certificate Store (PFX export to UNC Path, Windows Credentials, CCS cert file naming)
- IIS
- Export to common formats with and without private keys/passwords (.pem, .crt, .pfx, .key) with local or remote destination file copying.
- Apache (local or remote)
- Nginx (local or remote)
- Exchange
- Custom Script (local or remote, e.g. for custom deployment scripting or service restarts etc)
- Webhook
- Others?

UI would likely be an options To [+ Add Deployment Task] and choose from the list, adding any number of tasks and re-ordering as required. 

We would default to an Auto deployment of Local Certificate Store (Personal) and Local IIS (same as we currently have), this way current users and users who don't require advanced deployment can just follow the simple process of Create Certificate > Select IIS Site > Request Certificate as normal.

- May need something for failure continuation yes/no
- This may involve moving scripting (or post request at least) and webhooks into the Deployment UI
- Some deployment tasks/steps may be deferred rather than performed as soon as renewal completes e.g. Deployment to Exchange during maintenance window. User would either manually start deployment (UI or CLI) or use a scheduled task to deploy latest. Tasks can be named uniquely (per managed cert) so the user can invoke them from the CLI.

**Comment by webprofusion-chrisc** [comment]
We could also have a command line to invoke specific custom named deployment steps for a particular managed cert, so for instance `certify deploy "mycert" steps="exchange 2016 deployment","sftp deployment","linux servers"` for easy invoke from scheduled tasks or manually during maintenance windows etc.

**Comment by webprofusion-chrisc** [comment]
Also ref #105 #257 #355

**Comment by webprofusion-chrisc** [comment]
Also ref #268 for webhook task

**Comment by matsmcp** [comment]
I can test pem formated cer + key file function. Would be great if it could be done against the acme test-ca

**Comment by webprofusion-chrisc** [comment]
@matsmcp thanks, I'm also looking at making the choice of ACME CA configurable, so staging would be an option. Each CA (and each production/staging variant) is a different account key so we'd need to track  those, each CA also has different sets of restrictions.

**Comment by Psionyde** [comment]
Happy to assist with Exchange/RDG deployment testing.
(Also suggest sanity check for Exchange deployments to raise a warning if there is no autodiscover record in the certificate)

**Comment by npodbielski** [comment]
>Custom Script (local or remote, e.g. for custom deployment scripting or service restarts etc)

It would be nice to have selection like in Webhook configuration to allow script run only for success or error.

**Comment by nsumner36** [comment]
Happy to test deployment to files (used for Apache), and to Exchange. I didn't realize how full featured this is at this point!

**Comment by webprofusion-chrisc** [comment]
Deployment tasks are now part of the v5 beta available for testing. Most of the planned features have been implemented including predefined tasks for many common certificate uses, remote deployment etc. Please give it a try and report any bugs.

**Comment by Tarjei-stavanger** [comment]
You might want to include Tomcat.
The certificate stuff is slightly more complicated than the official documentation indicates. Or most bloggers indicates so far.

**Comment by webprofusion-chrisc** [comment]
@Tarjei-stavanger thanks, yes we do include a basic tomcat deployment task. This feature was released in April 2020. If you find any particular problems with it please create a new issue for it.
