### ISSUE TITLE
Remaining days calculated incorrectly

### ISSUE THREAD

**Issue by pmcgn** [webprofusion/certify#445]
I have a site with a certificate which did expire on 27-NOV-2017, today we have 4-MAR-2019. Certify shows in green text '**Expires in 462 days**'. Issue occured with version 4.1.5.0.

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this, could you send through a copy of your manageditems.db from c:\programdata\certify to support at certifytheweb.com

**Comment by pmcgn** [comment]
I'm sorry, after I had the Issue, I updated the certificate via certify (which worked). Now I went through each json of every db entry in manageditems.db. It does not contain any information regarding the old certificate.

Just to be clear: I'm not complaining that the certificate didn't get updated (that's a configuration issue on my side). I opened the ticket because and expired certificate is shown as valid.

**Comment by webprofusion-chrisc** [comment]
Thanks, it seems like a valid bug  (although perhaps rare?) so we should get to the bottom of it. It's probably something to do with the ManagedItem data not being updated for that cert until a request was run again and the previous version of the underlying data model not having a particular field set.

**Comment by webprofusion-chrisc** [comment]
Fixed in v5 (beta).
