### ISSUE TITLE
Adding DuckDNS to DNS Update Methods would be awesome!

### ISSUE THREAD

**Issue by EpicLPer** [webprofusion/certify#450]
Not everyone has the luxury of a fixed IP to use with a bigger hoster (like me) so I'm currently using DuckDNS, a completely free alternative to, as example, DynDNS.
They have an API which is stated here https://www.duckdns.org/spec.jsp 

Would love to see that added :) Certify so far seems to be the only good way of getting an automated LE certificate on Windows, like, at all without using a reverse proxy.

**Comment by webprofusion-chrisc** [comment]
Hi, have a look around and see if you can find any cUrl examples or PowerShell to update DuckDNS then you can use the DNS scripting option, or the default acme-dns.

I'm seriously considering not adding more DNS providers (unless there is huge demand) and instead only having script examples. There are literally hundreds of DNS APIs and we will never be able to support them all. 

Instead, I want to offer managed acme-dns (where you point a CNAME record to an acme-dns server hosted by yourself or certifytheweb.com). That way we only have one provider to maintain and everything works the same way for everyone.

**Comment by EpicLPer** [comment]
I wonder if someone has made a project where they keep such services in one big list for other devs to easily use in their projects 🤔

**Comment by webprofusion-chrisc** [comment]
Posh Acme has quite a few useful looking ones, I haven't tried any though : https://github.com/rmbolger/Posh-ACME/tree/master/Posh-ACME/DnsPlugins

**Comment by webprofusion-chrisc** [comment]
This article has a few code hints for curl scripting DuckDNS for Let's Encrypt
https://www.splitbrain.org/blog/2017-08/10-homeassistant_duckdns_letsencrypt

**Comment by webprofusion-chrisc** [comment]
New DNS providers are now added by creating scripts for Posh-ACME: https://github.com/rmbolger/Posh-ACME/tree/master/Posh-ACME/DnsPlugins
