### ISSUE TITLE
feature: NS1.com Authorization update method

### ISSUE THREAD

**Issue by nconder** [webprofusion/certify#452]
NS1.com has a very nice API so it would be nice to have Authorization update method integrated into the app.
https://ns1.com/api 

Has anyone created these scripts for NS1 yet?

**Comment by webprofusion-chrisc** [comment]
Have added an issue to track creating a reference set of DNS batch files for scripting as I think many people are using DNS scripting but the scripts aren't being shared.

**Comment by nconder** [comment]
Starting script repo here 
https://github.com/nconder/CertifytheWeb_Scripts

**Comment by webprofusion-chrisc** [comment]
This has been implemented in v5.x via a Posh-ACME Dns provider: https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/NS1-Readme.md
