### ISSUE TITLE
Feature: Create repo for scripts that update products with new cert

### ISSUE THREAD

**Issue by nconder** [webprofusion/certify#455]
Feature: Create repo for scripts that update products with new cert
Here is one I'm sure almost no one will use but me but ;) 

Microsoft Office Online Server
https://github.com/nconder/PowerShell-General/blob/master/CertifyTheWeb-OOS-Set_Cert.ps1

**Comment by nconder** [comment]
Starting new repo here for now
https://github.com/nconder/CertifytheWeb_Scripts

**Comment by webprofusion-chrisc** [comment]
@nconder thanks, I note you used the GPL license, so we could never bundle those scripts (as opposed to LGPL or MIT). You appear to have copied some of the scripts we currently bundle, which would be incompatible with our license. Use MIT if you can.

Out of interest, whats the purpose of this script? : https://github.com/nconder/CertifytheWeb_Scripts/blob/master/Pre-request_scripts/RemoveIISWebBindingPort.ps1

**Comment by nconder** [comment]
I forgot Certify the Web has a pay product Ill update the Licence. 

Correct me if I'm wrong but to get a new cert you must verify port 80 and 443 and redirects are not supported?
EDIT:  [Requirements](https://certifytheweb.com/home/features) 
> Hostname being certified must be accessible via internet (http port 80) and not be a redirection, or you can use DNS validation.


RemoveIISWebBindingPort.ps1 is for people that don't want to leave port 80 exposed. The script to complement this is the AddIISWebBindingPort.ps1.

So you run AddIISWebBindingPort.ps1 as a "Pre-request PS Script" for port 80 then "Post-request PS Script" RemoveIISWebBindingPort.ps1 to remove port 80.

We can also work on an IIS un-redirect 80 redirect to 443 then redirect 80 to 443 script too.

**Comment by nconder** [comment]
[Licence has been updated to MIT](https://github.com/nconder/CertifytheWeb_Scripts/blob/master/LICENSE)

**Comment by webprofusion-chrisc** [comment]
Thanks, regardless of whether CTW is paid for or not the code copyright (and therefore licensing) remains with us. It's a trivial amount of code and not really a problem but it's important to maintain licensing properly in general.

Re: port 80 - probably just needs a comment in the script but should not be required by default. The current version of CTW has the built in http challenge handler enabled by default, this temporarily circumvents IIS (using http.sys) for /.well-known/acme-challenge/ port 80 http requests, removing the need to handle challenges with IIS. If you can't use that (i.e. if you have a non-http.sys aware web server using port 80) you may need to script port 80 enable/disable.

Port 80 > 443 (http to https) redirects are supported by Let's Encrypt during challenge validation (even if your https cert is broken) but you need to respond on port 80 for that redirect to work.
