### ISSUE TITLE
Get new nonce if delay is longer than 5 minutes.

### ISSUE THREAD

**Issue by mb300sd** [webprofusion/certify#459]
I keep getting the error

Submit Challenge failed: JWS has an invalid anti-replay nonce:

while renewing my domains. I need to wait more than 5 minutes for my secondary DNS servers to update. It seems from the link below, the client should fetch a new nonce if the current one is expired.

https://community.letsencrypt.org/t/keeping-getting-jws-has-an-invalid-anti-replay-nonce/81051

**Comment by webprofusion-chrisc** [comment]
Thanks for reporting this issue. Yes we should fetch a new nonce if the old one has errorred so I'll check that out. This has not been commonly reported though and some users wait up to an hour for DNS propagation. Can you confirm you are on v4.1.6 and can you try restarting your Certify background service in case we're holding onto a cached reference.

**Comment by mb300sd** [comment]
Yes, I'm on 4.1.6. I use scheduled task mode instead of the background service, since I need to run it with a domain account with permissions for my DNS update script.

**Comment by webprofusion-chrisc** [comment]
@mb300sd interesting! Scheduled task mode shouldn't make a difference to permissions as it still calls the background service (which is usually running as Local System, although you could perhaps use `runas` in your script batch file).

**Comment by mb300sd** [comment]
There is a dialog for an account when setting up scheduled task mode - it never worked until I set the proper credentials.

**Comment by webprofusion-chrisc** [comment]
@mb300sd  that is deprecated and from back when the renewals operated under a scheduled task all the time. From v4 onwards the background service does all the work, the scheduled task still needs to run as admin (or a Power User group member) in order for it to be allowed to call the background service API but once it's made the call the background service (and it's associated identity) does all the work.

**Comment by webprofusion-chrisc** [comment]
Closing. Our retry mechanism covers this scenario. Can be re-opened if this is a common issue.
