### ISSUE TITLE
Re-apply bindings from CLI

### ISSUE THREAD

**Issue by GerryWilko** [webprofusion/certify#461]
Hi,

I can see from f2c109be858f8642086a199c59521c523d7eee81 that you are building this support into Certify The Web.

Do you have any time frame for the release of this?

Thanks for the great work.

Gerard

**Comment by webprofusion-chrisc** [comment]
Hi Gerard, I expect the new version with new/updated deployment options (including new CLI options) to be released as a beta in late August, thereafter it will just depend on beta feedback for the final release (expected before end of October).

**Comment by GerryWilko** [comment]
Hi Chris,

Do you have an updated timeline for releasing this new beta version of certify the web?

Cheers,
Gerard

**Comment by webprofusion-chrisc** [comment]
@GerryWilko thanks for asking, unfortunately no I don't have an updated timeline. As you will have guessed I'm the only developer on this project and several other projects have gotten in the way, so if I'm being honest with myself it's probably looking early next year now. The main bottleneck (asides from myself) is testing and polish, as even with alpha/beta releases people then go on to use those versions for years afterwards without updating so I have to be pretty confident before releasing even to alpha.
