### ISSUE TITLE
Certify 4.1.6 stopped working

### ISSUE THREAD

**Issue by code0blue** [webprofusion/certify#463]
I have Certify 4.1.6 and it suddenly stopped working.
I found the Certify SSL Manager Service doesn't start, which is probably causing the UI to crash.
I'm running on Windows 10 (10.0.18362.267) with .NET Framework 3.5 & 4.8.
Here are the errors I found in the event log:

Fault bucket 2304366018375975321, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Certify.UI.exe
P2: 4.0.0.0
P3: 5c95c28b
P4: Certify.Client
P5: 4.0.1.0
P6: 8baf8e75
P7: 14
P8: 1c
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCCE.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD7B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD8B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD89.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDAA.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Certify.UI.exe_7e3d9e9381e1d7ac6532526d7fca28f34f58fd_fcc370f2_518c11af-adc8-44b2-a0e7-4c4b25ba5754

Analysis symbol: 
Rechecking for solution: 0
Report Id: 04dbb521-dab5-4555-afe7-c20f99ea62f5
Report Status: 268435456
Hashed bucket: 22f89b9ec459ab54dffac0af45c80199
Cab Guid: 0

Also for the service:

Service cannot be started. System.NullReferenceException: Object reference not set to an instance of an object.
   at Certify.Service.OwinService.Start() in C:\Work\GIT\certify\src\Certify.Service\Program.cs:line 184
   at Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClass2_0`1.<WhenStarted>b__0(T service, HostControl control)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

I'm attaching all the logs from C:\ProgramData\Certify\logs
[logs.zip](https://github.com/webprofusion/certify/files/3472850/logs.zip)

**Comment by webprofusion-chrisc** [comment]
Thanks, this seems to be becoming more common despite this version having been running well for several months!

If you look in C:\programdata\certify there is a file called serviceconfig.json - for users getting a crash this file seems to be empty and the fix is to delete the file and restart the certify background service (then re-open the GUI). Let me know if that works for you.

**Comment by code0blue** [comment]
Hello @webprofusion-chrisc,
It worked :)
Thank you, you're a life saver 👍

**Comment by hiclarity** [comment]
Worked for me as well :-) Thank you !
