### ISSUE TITLE
Feature Request - Cloudflare API Token support

### ISSUE THREAD

**Issue by bigben386** [webprofusion/certify#464]
Hi. Cloudflare now supports restricted API tokens. It would be nice if you could support that instead of having to use the global API key.
https://api.cloudflare.com/#getting-started-requests
Thanks

**Comment by webprofusion-chrisc** [comment]
Thanks, I'll check it out!

**Comment by jcbit** [comment]
Second this! Instead of using email and key you use the      -H "Authorization: Bearer YQSn-xWAQiiEh9qM58wZNnyQS7FUdoqGIUAbrh7T"

A minor change but I am much more comfortable using that than the global API. Many thanks in advance!

https://api.cloudflare.com/#getting-started-requests

**Comment by webprofusion-chrisc** [comment]
Thanks, this will be in the next release.
