### ISSUE TITLE
Feature: Support KeySpec=1 in CSR

### ISSUE THREAD

**Issue by cbasolutions** [webprofusion/certify#465]
Greetings,

SQL Server requires KeySpec=1 to be enabled in the CSR in order for the cert to be properly recognized. A recently generated cert did no have this set. The cert is not recognizable in the SQL Configuration Manager. 

Environment: 
Server 2008 R2
SQL Server 2012
Certify  4.1.6.0

Cert Settings:
Single domain
No IIS Website
Challenge type DNS-01
Cloudflare DNS API
Deployment Certificate Store Only
CSR Signing Algorithm ECDSA using P-384 and SHA-384

Thanks!

**Comment by webprofusion-chrisc** [comment]
This issue still needs further investigation. From memory the issue was that our default cert appears to be ok, but perhaps wasn't in some environments?

**Comment by cbasolutions** [comment]
The issue is actually a problem with the cert type. SQL Server only shows RSA certs and not ECC.
