### ISSUE TITLE
Support PowerShell transcripts

### ISSUE THREAD

**Issue by mythofechelon** [webprofusion/certify#467]
It seems that, currently, Certify The Web does not support properly transcripts that are used in PowerShell scripts (post-request at least) as the resulting log files look like this: https://stackoverflow.com/questions/2383605/powershell-transcript-is-empty-when-running-script-from-sql-agent-job-in-2005-sq

**Comment by webprofusion-chrisc** [comment]
Thanks, here's the code if you fancy trying to do a PR:
https://github.com/webprofusion/certify/blob/development/src/Certify.Shared/Management/PowerShellManager.cs
