### ISSUE TITLE
Windows service question

### ISSUE THREAD

**Issue by HughJeffner** [webprofusion/certify#468]
We recently upgraded from version 2.x where auto-renew was handled by the task scheduler.  In the new version this is handled by the windows service "Certify.Service".  Do you foresee any problems with the following?

- Setting the service startup to Manual
- Using a scheduled task to start the service off-peak hours and give it a 1h window to run before stopping it again.
- If any further configuration is needed then the service can be manually started but this should be rare after everything is set up

I know this sounds like a silly question, any input would be appreciated.

**Comment by webprofusion-chrisc** [comment]
Hi, yes you could start/stop on a schedule - I'd give it just over an hour as some internal timers are 1hr as well.

The next version will have an option for deployment to be deferred and run manually or via command line/scheduled task etc as this suits maintenance windows best. 

Renewal of the actual cert will still be automatic but it just won't be applied until you tell it.

**Comment by HughJeffner** [comment]
Excellent, thanks for letting me know!
