### ISSUE TITLE
Support matching multiple subdomain levels in the Authorization tab

### ISSUE THREAD

**Issue by artdedeco** [webprofusion/certify#470]
Today if you have a certificate for `a.com`, `b.com`, `*.a.com` and `*.api.a.com` and you need different authorization configurations for `a.com` and `b.com`, for example, you may create two configurations matching `*.a.com` and `*.b.com`, for example. However, that won't match `*.api.a.com`, and thus Certify the Web will try to use http-01 method. It would be nice if either `*.a.com` matched all levels or if there was syntax for matching all levels (maybe `**`)

**Comment by webprofusion-chrisc** [comment]
Thanks, yes we do need to offer more options there.

**Comment by webprofusion-chrisc** [comment]
Closing. Domain match rules support multiple domain specifiers so in the example it's possible to provide both using `*.a.com;*.api.a.com`. This appears to be sufficient for the majority of users.
