### ISSUE TITLE
Setting Root Directory and Certificate Store during CSV Import

### ISSUE THREAD

**Issue by wyeack** [webprofusion/certify#471]
I am using your CLI CSV upload feature to add a big list of domains.

Is there any way to set the Website Root Directory?  What about the certificate store (I want to have them added to WebHosting instead of Personal)?

**Comment by webprofusion-chrisc** [comment]
Sorry, missed this. You can't specify root directory (this will instead be automatically determined via IIS) .

Regarding the Web Hosting store,  the current version doesn't support the Web Hosting store at all. While there have been articles recommending the Web Hosting store, while researching it a few years ago there was no technical evidence that there was any benefit. Happy to be enlightened on that!

The next major version may include an option to export to the Web Hosting store if there is demand for that.

**Comment by webprofusion-chrisc** [comment]
Closing. 

Web Hosting store is now an option in the primary settings and specifying webroot in CSV will not be supported (there is a newer add from template CLI option which could accommodate this: https://docs.certifytheweb.com/docs/commandline).
