### ISSUE TITLE
Webhooks into Microsoft Teams return HTTP 400

### ISSUE THREAD

**Issue by areis422** [webprofusion/certify#472]
Best I can tell, content-length header needs to be passed along with the request to have Microsoft Teams Incoming Webhooks work correctly. Trying to have a channel update anytime a certificate renewal succeeds or fails.

**Comment by webprofusion-chrisc** [comment]
Thanks, will take a look.

**Comment by webprofusion-chrisc** [comment]
Sorry for not getting back on this. I can confirm the http request for the web-hook includes the 'Content-Length' header automatically. Tested with `npx http-echo-server`
