### ISSUE TITLE
Update the wrong website cert

### ISSUE THREAD

**Issue by joe-the-way** [webprofusion/certify#474]
Hello, i am using certify on IIS (W 2008-R2) since the start, i use now the latest version, i have 2 https website to update

When certify do the job i face to this issue

- website1 -> cert retrieved is OK -> update bind job are ok
- website2 - > cert retrieved is OK -> update bind job are ok but he do update the bind for site1 with the cert for site2 (instead updating site2 with site2 cert)

Got this issue with every version of certify

**Comment by webprofusion-chrisc** [comment]
Hi, you can preview the expected binding updates in the Preview tab, if these are incorrect then please show them here.

The most common issue is IP specific bindings. On windows an IP can only have one SSL cert bound to it, unless the binding is using hostnames and SNI (server name indication) and as SNI is only available from Server 2012 onwards you will instead need a different IP per certificate/https site. This is a limitation of windows and not of Certify.

One solution (if you only have one IP address) is to add all your domains to one certificate.

**Comment by joe-the-way** [comment]
Thank you for the answer

There is nothing bad on the preview tab

I think this is a windows / iis bug, not a certify issue, i will get an eye on it and come back again if i can add information on the next cert update

Thanks

**Comment by webprofusion-chrisc** [comment]
Hi, note that you can see whether this is going to cause a problem before automatic renewal by re-applying the certificate bindings: Show Advanced Options > Other Options> Re-Apply Certificate To Bindings.
