### ISSUE TITLE
Enhancement - NameSilo.com API

### ISSUE THREAD

**Issue by thehasty** [webprofusion/certify#475]
Hello,

Please add the NameSilo.com API to Certify. I noticed that you already have namecheap, which is a service I used to use until I found a better one.

Thank you!

**Comment by webprofusion-chrisc** [comment]
You can use custom DNS scripting to access any provider that offers and API, although that's much more work for you. At this point it's unlikely that we will add many more DNS providers and instead only add support for *very* large DNS providers. Some of our current DNS providers are seeing very little use so far and the effort required to build and support them isn't proportionate to the usefulness to the existing user base. 

Ideally, use AWS Route 53, Cloudflare, Azure, or an acme-dns service
