### ISSUE TITLE
download .exe error

### ISSUE THREAD

**Issue by shaik447** [webprofusion/certify#479]
Not able to download the program from the website
https://certifytheweb.s3.amazonaws.com/downloads/CertifyTheWebSetup.exe

Please check. Thank you

**Comment by webprofusion-chrisc** [comment]
Hi, I can confirm that downloads are working normally - they are powered by amazon s3, so you need to be able to connect to their IP (rather than the one for https://certifytheweb.com).

If the problem persists please check with your network administrator.
