### ISSUE TITLE
Setup fails: Out of memory.

### ISSUE THREAD

**Issue by petsuter** [webprofusion/certify#480]

**Comment by webprofusion-chrisc** [comment]
Hi @petsuter thanks for reporting this. There seems to be something wrong with your server, I'd suggest trying a reboot. Can you confirm the operating system version and server specification?

**Comment by petsuter** [comment]
Windows Server 2008 R2, 6GB RAM, 2 GB were still free according to Windows Task Manager.

This is just FYI, we switched to another tool.

Thanks anyway!

**Comment by webprofusion-chrisc** [comment]
Thanks for reporting this anyway. I will probably be wrapping up 2008 R2 support anyway so switching to another tool is probably a good idea for you. I can't really support an OS if Microsoft have given up on it :)
