### ISSUE TITLE
FriendlyName should be Set from the UI

### ISSUE THREAD

**Issue by coreyperkins** [webprofusion/certify#489]
I noticed that when I create a certificate the FriendlyName including some extra text. [Certify] along with the valid dates. We should be able to customize that for application lookup purposes.

Thanks,

Corey

**Comment by webprofusion-chrisc** [comment]
Hi Corey, this is implemented in the upcoming v5.x as a new 'Certificate Store' Deployment Task

 Currently the friendly name is used to help in the certificate cleanup process, so we'll need to look at how to cleanup certs with customised names.
