### ISSUE TITLE
ACMESharp doesn't get recognized

### ISSUE THREAD

**Issue by ZmorzynskiK** [webprofusion/certify#49]
I stumbled upon very strange and annoying issue. After starting Certify, it displays a MessageBox saying that ACMESharp isn't installed.
However, I installed it and when I execute:
`Get-Module -ListAvailable ACMESharp`
in Powershell console I get:

```
Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.8.1      ACMESharp                           {Get-Certificate, Get-ChallengeHandlerProfile, Get-Iden...
```

so it looks like ACMESharp is installed.

I run Certify as administrator on Windows Server 2012 R2.
What's going on? I'll appreciate any help.

**Comment by ZmorzynskiK** [comment]
Ok, so I figured it out. Maybe it'll help someone.

It turned out, that the `ACMESharp` module was installed, but was not in the proper directory. Apparently, `C:\Program Files\WindowsPowerShell\Modules` (the one that has `ACMESharp` module installed) isn't used by Powershell initialized in Certify, but other directories are taken into account. Not sure why it's like that, but it is.

So I copied whole `ACMESharp` module directory from `C:\Program Files\WindowsPowerShell\Modules\ACMESharp`
to
`c:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\` (for 32 bits apps usage)
and to
`c:\Windows\system32\WindowsPowerShell\v1.0\Modules\`  (just in case for 64 bits apps)

After restarting Certify - it started to work.

**Comment by soundshed** [comment]
Reopening to track this problem. We need to decide how best to handle this for others, the PowerShell module installation is likely one of the biggest hurdles for users.

**Comment by ZmorzynskiK** [comment]
Thinking about it, it looks like they're at least 2 or 3 Powershell "module repositories" in Windows 64 bit.

I'd expect modules to land in `c:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\` when installing from 32 bit Powershell, and to `c:\Windows\system32\WindowsPowerShell\v1.0\Modules\` when installing from 64 bit Powershell, but I don't understand why it landed in `C:\Program Files\WindowsPowerShell\Modules\ACMESharp` when installing from 64 bit Powershell (run as administrator). This prevented Certify from finding the module.

What may be the reason for this? Maybe it's a Nuget related issue?

**Comment by amilo2003** [comment]
I was using version 0.8? and I am now trying to renew the certificate. I ran into the same issue as above, thanks @ZmorzynskiK for your solution!

I however receive this error message now:
Challenge not yet completed. Check that http://www.test.com/ACMESharp.AuthorizeChallenge path/file is present and accessible in your web browser.

Thereafter app crashes with error:
Certificate has not been submitted yet, cannot update status.

The .well-known path exists

Do I need to create new path manually?

**Comment by ZmorzynskiK** [comment]
@amilo2003 I'm using the newest version of `ACMESharp` which is 0.8.1.
Do you have anything inside `.well-known` folder? There should be another folder (`acme-challenge`) inside with some files.

AFAIR just to be sure I created those two folders manually and placed there `web.config` with contents:

```
<?xml version = "1.0" encoding="UTF-8"?>
 <configuration>
     <system.webServer>
          <staticContent>
	        <mimeMap fileExtension="." mimeType="text/plain" />
   </staticContent>
     </system.webServer>
 </configuration>
```

Everything then went smoothly.

**Comment by amilo2003** [comment]
Thanks, it worked! All renewed now.

**Comment by HunterLine** [comment]
So I did above and still having the original issue. Using Windows Server 2012 R2 and the latest (at time of writing) version of Certify`PS C:\Users\Administrator> Get-Module -ListAvailable ACMESharp


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.8.1      ACMESharp                           {Get-Certificate, Get-ChallengeHandlerProfile, Get-Identif...


    Directory: C:\Windows\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.8.1      ACMESharp                           {Get-Certificate, Get-ChallengeHandlerProfile, Get-Identif...


PS C:\Users\Administrator>` Is there another command I'm not aware of? Not experienced with PowerShell or PowerShell Gallery.

**Comment by ZmorzynskiK** [comment]
@HunterLine did you copied the `ACMESharp` module also to `c:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\`?

**Comment by HunterLine** [comment]
It is a 64-bit OS, should I create the folder for 32-bit

**Comment by ZmorzynskiK** [comment]
Yes, `SysWOW64` is for 32 bit apps. Just check if you have folder named `c:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\` and copy `ACMESharp` there.

**Comment by alecrespo** [comment]
Hi @ZmorzynskiK  I run the ps and then copy the module to 

C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules
C:\Windows\system32\WindowsPowerShell\v1.0\Modules

Still Certify cannot find it. I'm missing something?

**Comment by ZmorzynskiK** [comment]
Just to be 100% sure: are you invoking all those PS commands and Certify app as administrator? Do you see the module (`Get-Module -ListAvailable ACMESharp`) in both those directories when running 32bit version of PS and 64bit version of PS?

**Comment by soundshed** [comment]
I think this answers my suspicion that using the ACMESharp from PowerShell gallery is just too complicated. We will migrate to using our own build of ACMESharp as soon as we can.

**Comment by ZmorzynskiK** [comment]
@soundshed  great, I can try to help if needed.

**Comment by soundshed** [comment]
A new version of Certify has now been release which bundles a local copy of ACMESharp, removing the need for the Install-Module step. Please try it out :)

**Comment by soundshed** [comment]
Resolved in latest release. Closing.
