### ISSUE TITLE
NO-IP Managed DNS

### ISSUE THREAD

**Issue by benjamynlynch** [webprofusion/certify#494]
I have purchased my domain and managed DNS through No-IP

is it possible to get a No-IP managed DNS API into CertifyTheWeb

**Comment by webprofusion-chrisc** [comment]
Hi, to directly use a DNS API for certificate validation you need to be able to automatically create and set the value of the `_acme-challenge.yourdomain.com` TXT record. I can't see any infomration that suggests no-ip has this feature for an API?

 In v5 we are adding a bunch of DNS providers via the Posh-ACME project so if a scripted solution can be added to that project then we can in turn add it to Certify. https://github.com/rmbolger/Posh-ACME/tree/master/Posh-ACME/DnsPlugins - this is only really a option if you are good at scripting and can create the script yourself.

**The easiest option is to use the acme-dns API provider**, if you point to the default server (which is managed/hosted by the creator of acme-dns. You can optionally run your own acme-dns server but it's complicated). :

Select acme-dns as the API, click 'Test' to generate a registration (details are also in the Log file), then adding the CNAME you are prompted to create into your DNS. Then when you click Request Certificate (or the cert auto renews) the app automatically updates the TXT value using acme-dns and so you don't have to mess with your own DNS.
