### ISSUE TITLE
Need Alias

### ISSUE THREAD

**Issue by masterhacka** [webprofusion/certify#495]
Hi there I try to set up a certificate for a Minecraft Plugin. I already have the Certificate.pfx file. But I need to know the following:

Config.Setting | Description
-- | --
SSL_certificate.KeyStore_path | Filename in /plugins/Plan/ folder or the absolute path to the file if the certificate is placed elsewhere.
SSL_certificate.Key_pass | The password of the certificate
SSL_certificate.Store_pass | The password of the keystore
SSL_certificate.Alias | The alias of the keystore

Should the Key_pass and Store_pass be empty? And I have no clue how to find the Alias.

**Comment by webprofusion-chrisc** [comment]
Hi, sorry I might not be able to help with Minecraft, yes Key_pass will be blank by default, and I assume Store_pass is as well?

**Comment by masterhacka** [comment]
Yes that might gonna work, but I can't find the certificate alias.

**Comment by webprofusion-chrisc** [comment]
Ah, looking at this: https://github.com/plan-player-analytics/Plan/wiki/SSL-Certificate-%28HTTPS%29-Set-Up

The app you're using is trying to create a java keystore.

Looks like you can use the JDK `keytool` command to convert to a java keystore (and set the alias):

https://stackoverflow.com/questions/4217107/how-to-convert-pfx-file-to-keystore-with-private-key

I think you should create a new keystore then import the certificate into it (you may need to convert from pfx to pem and key files):
https://www.sslshopper.com/article-most-common-java-keytool-keystore-commands.html

Note that certify v5 beta has a new Generic Server export deployment task which removes the need to use openssl just to create the .pem/crt/key files.

**Comment by masterhacka** [comment]
Great, thanks! That worked perfectly.

If I am going to use certify v5 beta. Then how can I create or convert to p12?

**Comment by masterhacka** [comment]
There is one problem left. After uploading the certificate and entering the secured website. My browser says it is not secured. Is there anything I can do that it is secured?

**Comment by webprofusion-chrisc** [comment]
The usual reasons are:

The Certificate is for 'XYZ.domain.com' and you're trying to access 'somethingelse.domain.com' - your certificate must match your domain.

You are accessing an https site but some elements on the page are loading via plain http

**Comment by masterhacka** [comment]
Nevermind it was the Cache of my browser. Everything works fine now. Thanks for your help!
