### ISSUE TITLE
Invalid response

### ISSUE THREAD

**Issue by boscorelly** [webprofusion/certify#497]
Hi,

on one server, we have this issue :

2020-05-12 11:04:16.407 +02:00 [INF] Validation of the required challenges did not complete successfully. Invalid response from http://sub.domain.fr/.well-known/acme-challenge/V04xXQ9j4lA-GnElb7PkRJNsZMdUNbDgXqfQv9Z19kY [12.34.56.789.]: "\ufeff<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n<head>\n  <title>"

Windows Server 2012 R2 with exchange only

**Comment by boscorelly** [comment]
and when i tried to access the page, i had a login/password prompt

**Comment by webprofusion-chrisc** [comment]
Hi, is this with the new Certify beta or just v4.1.8?

I'd need a full log file sent to 'support at certifytheweb.com' 

Note that certify doesn't touch anything to do with basic authentication so it can't cause a username/password prompt unless you have accidentally enabled client certificates (i.e. requiring end users to present a certificate).

**Comment by boscorelly** [comment]
i use the release branch.
i will send it to you ASAP.

i have the prompt on the url i pasted  above. The server is a dedicated server to exchange only. EXCH 2013 CU 23.

what is strange, it is the only one server doing it. We have about 10 EXCH servers with certify installed;

**Comment by webprofusion-chrisc** [comment]
I assume the server isn't load balanced (if it was the wrong server might be trying to respond to the http validation, so for that DNS validation is better). During http validation the default http challenge server should run so `http://<yourdomain>/.well-known/acme-challenge/configcheck` should return OK in a web browser. If not it suggests the http challenge server is failing to run - in which case I'd suggest a reboot. 

I assume the server has been operating normally and the problem has just suddenly occurred without anyone making administrative changes to IIS etc.
