### ISSUE TITLE
Error when Export Certificate P12 in SSH

### ISSUE THREAD

**Issue by badroum** [webprofusion/certify#498]
I get an error message about the filename parameter which is not available in the options.
Moreover it would be interesting, if only the path of the folder is filled, that it automatically proposes the name of the certificate. 
![mRemoteNG_ovGVnsGkhk](https://user-images.githubusercontent.com/6005086/81917781-ed4c6180-95d5-11ea-82dd-ae4f3bd727a1.png)
![mRemoteNG_BatiKYYUjo](https://user-images.githubusercontent.com/6005086/81917789-ee7d8e80-95d5-11ea-9a35-565e8058c7a1.png)
![mRemoteNG_2IZgbIGHbN](https://user-images.githubusercontent.com/6005086/81917823-f89f8d00-95d5-11ea-9299-b10a1d559db5.png)

**Comment by webprofusion-chrisc** [comment]
Thanks for reporting, this error says it can't find your ssh private key file - for the saved ssh credential `root - generique` - so I assume you are not using a private key and ssh is just a username and password?

**Comment by webprofusion-chrisc** [comment]
I see the problem, I tried it myself just now and if you're not using a private key file it errors. Fix will be in the next release.

**Comment by badroum** [comment]
Indeed, I don't use a private key. If I use a private key, will that solve the problem?

**Comment by webprofusion-chrisc** [comment]
Yes, it should work with a private key (if an app such as bitvise ssh also works with the same private key), but I'll try to fix the problem anyway - release should be out in a day or so.

**Comment by badroum** [comment]
Thank you for the answer,
one last thing, an error message appeared when I use the ssh key:
KEY 'OPENSSH' is not supported 
Do you have any idea what specs are left to generate the key and what utility if Openssh is not possible.
![image](https://user-images.githubusercontent.com/6005086/81931383-4de59980-95ea-11ea-923d-58670c7324cc.png)

**Comment by badroum** [comment]
> Yes, it should work with a private key (if an app such as bitvise ssh also works with the same private key), but I'll try to fix the problem anyway - release should be out in a day or so.

I managed the connection by generating the certificate with bitvise, I don't know why the certificate didn't work with ssh gen key.
I wanted to know if there was a way to get more details in the logs. Indeed, the Deployment tasks are a success, but no files are copied to the remote server.

**Comment by webprofusion-chrisc** [comment]
Hmm, let me investigate, I used the key generated by AWS for mine.

**Comment by webprofusion-chrisc** [comment]
So we're using the ssh.net library and the supported key options look pretty comprehensive - what options did you use to generate your key?  https://github.com/sshnet/SSH.NET#public-key-authentication

**Comment by badroum** [comment]
basically the command: ssh-keygen -t rsa -b 4096

but now that the connection is effective via certificate, during the task "Export certificate" no certificate is copied to the server.
I wanted to know if we could have more advanced logging?

**Comment by webprofusion-chrisc** [comment]
Thanks, yes I'll add more logging to see if we are hitting exceptions that are being caught somewhere.

**Comment by webprofusion-chrisc** [comment]
Ok, v5.0.7 is out now, if you open the app it will offer to update itself. I've added more logging for the sftp operations and refactored how SSH/Sftp connects so you should also be able to use username/password authentication without a key if required.

**Comment by badroum** [comment]
thank you this fixes the password error but I have no output on my linux server

**Comment by webprofusion-chrisc** [comment]
Sorry, I forgot to reply. I can confirm in my testing that the sftp file copy does happen if the destination path exists (the process does not create folders required by a path). If there is an error it should be being logged in the managed certificate log file. I'm assuming the user account has write permission to the destination path etc,

If it's silently failing I'll just need to figure out how to reproduce it but as far as see so far it would report the error to the log file and abort the task if something fails.
