### ISSUE TITLE
Where does the PFX file get exported to?

### ISSUE THREAD

**Issue by charlesroper** [webprofusion/certify#5]
When you click the Export button, where does the PFX file get exported to? Would be useful if that dialog provided that information.

Many thanks!

**Comment by webprofusion-chrisc** [comment]
The pfx is exported to a folder in the 'vault' (a concept inherited from ACMESharp) C:\ProgramData\ACMESharp\sysVault\99-ASSET\

The export feature is only really there for testing but it can be useful for manually applying the cert.

**Comment by charlesroper** [comment]
Great, thank you!

**Comment by soundshed** [comment]
Resolved.
