### ISSUE TITLE
Certify.Service stop on load after version 5 update

### ISSUE THREAD

**Issue by aprimio** [webprofusion/certify#505]
After I update my installation of Certify the Web to version Version 5.0.9 it stop working. Message says that Certify.Service is not started, tried to start it manually but receive an error messages on the screen.

Try to change default port on json file as explained on faq and run the windows commands indicated there with no effect.

Try to uninstall application, erase app folders and reboot the machine, also with no success.

Others investigations on event viewer file shows me that message:

Serviço não pode ser iniciado. System.Reflection.TargetInvocationException: Uma exceção foi acionada pelo destino de uma chamada. ---> System.AggregateException: Um ou mais erros. ---> Org.BouncyCastle.Security.Certificates.CertificateException: Failed to read certificate ---> System.ArgumentException: version 1 certificate contains extra data
   em Org.BouncyCastle.Asn1.X509.TbsCertificateStructure..ctor(Asn1Sequence seq)
   em Org.BouncyCastle.Asn1.X509.TbsCertificateStructure.GetInstance(Object obj)
   em Org.BouncyCastle.Asn1.X509.X509CertificateStructure..ctor(Asn1Sequence seq)
   em Org.BouncyCastle.Asn1.X509.X509CertificateStructure.GetInstance(Object obj)
   em Org.BouncyCastle.X509.X509CertificateParser.ReadDerCertificate(Asn1InputStream dIn)
   em Org.BouncyCastle.X509.X509CertificateParser.ReadCertificate(Stream inStream)
   --- Fim do rastreamento de pilha de exceções internas ---
   em Org.BouncyCastle.X509.X509CertificateParser.ReadCertificate(Stream inStream)
   em Certify.Providers.ACME.Certes.CertesACMEProvider...

Does not appears that I have a issue with http port as suggested on FAQ.

Tried to exclude certificates created with the old version but I did not have success on it.

There anything else i should try?

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this issue. Could you zip up your C:\ProgramData\Certify folder and send it to `support at certifytheweb.com` for review?

So this crash occurs as soon as you start the Certify SSL Manager background service or when you attempt to do something in the program?
You mentioned

**Comment by webprofusion-chrisc** [comment]
So I found the issue, we build a cache of root certificates and CA intermediate certificates so we don't have to read them every time we build a certificate. On your machine this is causing an exception, meaning one of the certificates in the `Trusted Root Certification` or `Intermediate Certification Authorities` collections is corrupt or invalid. I'll do a release later today (5.0.10) with a fix to not crash in the invalid cert. You will need to manually download the update assuming you can't launch the app to use the auto update.

**Comment by aprimio** [comment]
> Thanks for raising this issue. Could you zip up your C:\ProgramData\Certify folder and send it to `support at certifytheweb.com` for review?
> 
> So this crash occurs as soon as you start the Certify SSL Manager background service or when you attempt to do something in the program?
> You mentioned

It is preventing service to start.

Thanks for the prompt solution, should I still send you C:\ProgramData\Certify folder?
