### ISSUE TITLE
Add support for DirectAdmin

### ISSUE THREAD

**Issue by damousys** [webprofusion/certify#506]
I would like to see Support for DirectAdmin

**Comment by webprofusion-chrisc** [comment]
Thanks, DirectAdmin is a control panel yes? Don't they already offer Let's Encrypt support? If not, is there an API?

**Comment by webprofusion-chrisc** [comment]
Note that with v5 you can export your certificate to any server using remote file copy or SSH/Sftp as a Deployment Task. It looks like you can do that with DirectAdmin: https://help.directadmin.com/item.php?id=2137

**Comment by damousys** [comment]
Yes that could also be possible if you are the admin of the DirectAdmin, but most of us are not 
and there is an API
https://www.directadmin.com/api.html
don't know if you know Home Assistant, but maybe you can get some info from theyre add-on

https://github.com/home-assistant/hassio-addons/tree/master/letsencrypt

**Comment by webprofusion-chrisc** [comment]
Thanks, I do know Home Assistant quite well, however their Let's Encrypt plugin is not related to Direct Admin in any way is it? Exporting and installing certs on Linux is no problem, Certify can already do that via SSH, so it's publishing (Deployment) that's the issue. 

As a workaround however you can use a combination of the Certificate Export or Generic Server deployment tasks (to get the cert files) and your own scripting to push the certificate to Direct Admin using their API.

**Comment by damousys** [comment]
No I know that it's not related to DirectAdmin, but they can use the API from DirectAdmin
I use certify on a Windows OS ofcourse
what I can do is try to copy the 2 PEM files to my windows machine
Can Certify do anything with those files, to bind them to an IIS instance ?

**Comment by webprofusion-chrisc** [comment]
I'm really confused as to what it is you are trying to do, initially I thought you wanted to get your cert using Certify then deploy it to Direct Admin. Can you explain exactly what you are trying to do?

Certify runs on Windows, by default it is optimized to work with IIS - i.e. You start up Certify, Hit New Certificate, selected the IIS website (which has hostname bindings) and hit Request Certificate. From then you have an automatically renewed and applied certificate. This is it's core functionality but it can be used to request certificates and then deploy them elsewhere. 

It doesn't currently have any functionality to fetch certificate from other systems and apply them locally, it assumes it is primary means of acquiring certificates. Eventually we will probably add ways to fetch certs from elsewhere then apply them locally but that's never been requested before.

**Comment by damousys** [comment]
that's what I am trying to do, but I need DNS Challange 
I am trying to use DNS challange to create a wildcard certificate

**Comment by webprofusion-chrisc** [comment]
Ah! So your DNS is hosted using Direct Admin. Ok, the best path is to get support for Direct Admin added to Posh-ACME (https://github.com/rmbolger/Posh-ACME) which is where many of our DNS providers come from now. There are basically thousands of possible DNS APIs and we won't be directly adding support for any more of the smaller/less common providers.

The fastest solution for you is to either:
- script your DNS updates: https://docs.certifytheweb.com/docs/dns/providers/scripting  - this can be written in any language/method you can call from a batch file (PowerShell, curl, python, node etc)
- move your DNS to something that's already supported (e.g. Cloudflare (free), AWS Route53 etc) or more likely to

**Comment by damousys** [comment]
The scripting option I have tried, but I keep getting the message that the ACME key doesn't match
But when I compare them the are an exact match ?
And I was under the impression that DirectAdmin was one of the biggest, my bad

**Comment by webprofusion-chrisc** [comment]
So when you are scripting remember to have a long enough DNS propagation time. Let's Encrypt will check all your domains nameservers so the TXT record changes have to have replicated to all of your servers before it proceeds to the validation step. To diagnose that further I'd need your log file and domain name.

An alternative approach is acme-dns (you can try it with the default acme-dns service). With that you create a CNAME that redirects to the acme-dns server.

DirectAdmin could possibly be huge, I just haven't heard of them, as I say we're deferring to Posh-ACME for DNS providers where we can.

**Comment by damousys** [comment]
aha oke so if I want it to be added, I need to ask it there 
I am going to ask my DNS provider what i should use for propagation time
that could be my scripting issue

**Comment by webprofusion-chrisc** [comment]
You can check by updating a TXT record then using dig to check the TXT record value against each nameserver. Usually 5 minutes (so 300 seconds) would be enough but it will depend.

**Comment by damousys** [comment]
thanks for the tip with the time.
The removal process isn't quite oke, but I can try to fix that
