### ISSUE TITLE
CAA record check issue

### ISSUE THREAD

**Issue by jcnewman83** [webprofusion/certify#507]
Hi 
I have recently come across an issue in the last 2 days when trying to get a new certificate issued to our test sites which are hosted in azure. I am getting the following error:

`Validation of the required challenges did not complete successfully. CAA record for engagerelease.uksouth.cloudapp.azure.com prevents issuance`

I have checked out the DNS records for the site and although there is a restriction to only allow digicert for the top level domain azure.com there does not appear to be anything set for the subdomain I am using.

Is anyone able to shed some light as to what is going on here, have I hit a bug?

I have attached a log and the CAA DNS record information which I hope will be helpful. Let me know if I can provide any more information.

Thank you in advance.

<img width="1676" alt="Screenshot 2020-06-19 at 11 16 04" src="https://user-images.githubusercontent.com/45239068/85122356-5307bb00-b21e-11ea-8023-428a5d55471a.png">
[log_59bcc51b-3626-48c6-930b-4277aee7c6fd_.txt](https://github.com/webprofusion/certify/files/4803896/log_59bcc51b-3626-48c6-930b-4277aee7c6fd_.txt)

**Comment by webprofusion-chrisc** [comment]
Hi, I can't seem to access that log you linked but you'll also hit the Let's Encrypt 50 cert per domain rate limit for azure.com

https://letsdebug.net/engagerelease.uksouth.cloudapp.azure.com/184231

You should raise the CAA check issue on https://community.letsencrypt.org - we could be reporting the wrong error by I don't think we are. You can switch on debug logging to see the http conversation with the API by changing the log level to debug in C:\programdata\certify\serviceconfig.json

As a workaround you could try switching the CA to BuyPass Go (add a new account under Settings, then choose BuyPass Go under Certificate  - Certificate Authority

**Comment by webprofusion-chrisc** [comment]
Note also that the existence of the azure.com CAA prevents your subdomain issuing unless you define your own CAA at the subdomain level, which you probably can't do in azure.
https://letsencrypt.org/docs/caa/

You should probably use azure certificates unless you can put your app on a custom domain.
