### ISSUE TITLE
Route53 without API key

### ISSUE THREAD

**Issue by freefly42** [webprofusion/certify#508]
I am running the application on an EC2 instance using a role that has the proper permissions for DNS validation, but the application refuses to attempt Route53 verfication without using an API key, which is not needed.  It should not check for a key before trying the AWS API.

**Comment by webprofusion-chrisc** [comment]
Hi, the Certify background service does all the real work of the app, and this runs as Local System by default. I think you are referring to having the AWS role/config associated with your user account?
