### ISSUE TITLE
ERR_SSL_OBSOLETE_VERSION 

### ISSUE THREAD

**Issue by devfxplayer** [webprofusion/certify#515]
WebSocket connection to 'wss://*/ws' failed: Error in connection establishment: net::ERR_SSL_OBSOLETE_VERSION

Is there a way to define the TLS 1.2?

**Comment by webprofusion-chrisc** [comment]
Hi, the TLS support is defined by your operating system, not by the certificate. Supported TLS versions are controlled by modifying the registry.

I recommend using the Best Practices mode of the free IISCrypto tool: https://www.nartac.com/Products/IISCrypto/
