### ISSUE TITLE
Certify Says Cert Renewed, but my browser says expired

### ISSUE THREAD

**Issue by chobo2** [webprofusion/certify#52]
Hi

I was able to get certify to finally load and show my websites. I renewed one of my sites and Certify says my new cert won't expire for 89 days.

If I go to my site it says the cert is still expired.

I am on windows 2012 R2

**Comment by soundshed** [comment]
Hi, can you check the bindings in IIS (right click website in iis > bindings, look at the https binding and View the certificate, is the certificate it's bound to expired? If not, it's browser caching. if it is bound to an expired certificate then its a problem with the automated binding, remove the SSL binding and run certify again.
