### ISSUE TITLE
Certify.Core.Service.sln has invalid filepaths

### ISSUE THREAD

**Issue by Lillecarl** [webprofusion/certify#520]
src\Certify.Providers\DNS\Cloudflare\Plugin.DNS.Cloudflare.csproj is the filepath to the Cloudflare DNS plugin
src\Certify.Providers\DNS\Cloudflare\Cloudflare.csproj is the path in Certify.Core.Service.sln

Is there a reason behind the solution file only being able to load 12 out of 24 projects? If not i could resolve the paths in a PR.

**Comment by webprofusion-chrisc** [comment]
Ah yeah, my fault, I work using a private solution file that links all sorts of other stuff and haven't updated this solution when the DNS plugins got renamed. That should be it fixed now!

**Comment by Lillecarl** [comment]
========== Build: 23 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

Cheers mate!
