### ISSUE TITLE
No persistent script repository, custom scripts deleted during updates

### ISSUE THREAD

**Issue by jaycenornin** [webprofusion/certify#523]
The default path for deployment scripts is C:\Program Files\CertifyTheWeb\Scripts\
This seems like an OK place to store custom deployment scripts, since it is specific to CTW, has the required folder permissions, and would not be tied to a specific user account (for systems managed by multiple admins). 

However, this folder is entirely deleted whenever CTW is updated. **Any customized scripts in this location are permanently lost** if not previously backed up. There is no warning during updates that custom data in this folder will be deleted.

I recommend that the \Scripts\ folder should remain persistent across updates by default, and that when uninstalled CTW should prompt the user if they want to delete the \Scripts\ folder and its contents.

I also recommend the establishment of a recommended/default script repository folder in another location. C:\ProgramData\Certify\Scripts\ would be a good location for individuals, but still needs the above safeguards to prevent custom scripts from being deleted. For businesses, support for UNC paths would be ideal, so customized scripts could be stored on a file share, but I haven't tested thoroughly enough to determine if this is already possible in current versions.

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for your feedback and I understand your frustration, sorry about that. Yes our example scripts have been annotated with a warning not to store scripts under Program Files for the past few versions (it's been that way for just under 2 years) and our docs also warn not to store scripts there: https://docs.certifytheweb.com/docs/script-hooks

v5.x onwards no longer presents a script chooser as these common scripts have been replaced by Deployment Tasks. Custom scripts can still run but I agree we should show an error if the path is to Program Files.

The conventional method to have a scripts folder that persist across updates is just to not put your scripts under program files (e.g. use C:\CertifyScripts or similar, or if you prefer C:\ProgramData\Certify\Scripts).

Regarding UNC paths, these are supported from 5.x onwards. Previous versions could only run as the background service account (SYSTEM by default) so didn't have network credentials, 5.x scripting Tasks now have the option to impersonate specific users the login for which can be kept as Stored Credentials.

**Comment by webprofusion-chrisc** [comment]
Scripts are no longer deleted during upgrade from v5.1.5 onwards (unless you use the same name as one of our built in scripts).
