### ISSUE TITLE
Generic Server Deployment Task Produces Invalid Chain Certificate

### ISSUE THREAD

**Issue by AB933** [webprofusion/certify#529]
Hello,
I use the generic server deployment task to provide certificates for hMailSever and it has worked flawlessly.  The last update failed and I traced the problem to a bad chain certificate.  The server certificate worked fine except I need to use the chain certificate.  Reverting from version 5.1.2 to 5.0.12 solved the problem and it works fine again.  Before reverting, I tried 5.1.5 but that didn't fix the problem.  This is all done on Windows 8.1.

**Comment by webprofusion-chrisc** [comment]
In 5.1 there were some fixed applied relating to which parts of the certificate chain were included when you exported the chain, perhaps you were relying on part of the chain (such as the root or leaf cert) which shouldn't be/isn't included in the generic server export. If you look at the Certificate Export task you can see the various export type options.

Here is a recent community topic with a suggested strategy for hmailserver using deployment tasks (certificate export): https://community.certifytheweb.com/t/powershell-script-for-hmailserver/585/15?u=webprofusion

**Comment by AB933** [comment]
To make certificate export  work, I have to export the primary certificate and the intermediate/root certificate separately and merge the two with a batch file.

**Comment by webprofusion-chrisc** [comment]
So can you clarify, do you need one file with every cert component (full chain: leaf, intermediates and root) and a separate private key file? I assume you don't add the private key to that file. You should be able to use the Certificate export task without merging any files yourself.

**Comment by AB933** [comment]
Yes, I need the files like you described.  The private key is not added in.   The chain certificate produced by version 5.0.12 using generic server deployment worked perfectly.  
I don't know why but for some reason Android email clients need to see the entire chain.  That is why a complete chain certificate with all three is needed.

**Comment by webprofusion-chrisc** [comment]
Closing. Recent versions have new options for chain (intermediates + root only) and full chain (leaf + intermediates + root).
