### ISSUE TITLE
AzureAD Key Vault Task: Vault URI Validation Fails

### ISSUE THREAD

**Issue by RedwoodLiving** [webprofusion/certify#531]
In the "Deploy to Azure Key Vault" Deployment task, the validation of the "Azure Vault Uri" fails when the optional "Certificate Name" has non-alphanumeric characters.

This error should clearly define that the issue is with the certificate name, and not the vault uri.

**Comment by webprofusion-chrisc** [comment]
Thanks. This is fixed in the next version, the error message was wrong.
