### ISSUE TITLE
in new version (5.1.11) symantec antivirus recognize it as a threat

### ISSUE THREAD

**Issue by Sepehrsystems** [webprofusion/certify#534]
Hello, have a good time.
I have installed Symantec antivirus in my servers. but when I updated certify the web, my antivirus has problem with it.

**Comment by webprofusion-chrisc** [comment]
Thanks, in my own test with various scanners there is no issue. 
https://www.virustotal.com/gui/file/f8f19a94e9e8400b14afabdc7c11ca938b42d0133f5fe54143d6561992716f5c/detection

Please report the false positive to Symantec so they can investigate and either remove it from their database or explain their analysis.

Note that you can also download the app manually from certifytheweb.com and run the install manually if the update process is being interrupted. You can verify the downloaded file by checking it's expected sha256 hash:
`certutil -hashfile SHA256: f8f19a94e9e8400b14afabdc7c11ca938b42d0133f5fe54143d6561992716f5c`
