### ISSUE TITLE
 Validation fails after IIS uninstallation

### ISSUE THREAD

**Issue by xcabur1** [webprofusion/certify#535]
I use nginx as a webserver with a basic http listener on Port 80. IIS is no longer installed. If I request a certificate over CtW, the validation fails. It looks like CtW do not create the `.well-known` directory. The `configcheck` file or the validation file is not created even I create the folders manually. http://www.domain.tld is accessible from public. I also set the `site root directory` in CtW to the nginx root directory. Without any success.

https://i.imgur.com/JU9Kg26.png
I get a error on `Test` and folder and file is not created. Theye are also not created If I click `Request Certificate`.

Log https://hasteb.in/raw/odemojay

**Comment by webprofusion-chrisc** [comment]
Thanks, see my reply here https://community.certifytheweb.com/t/validation-failed-with-nginx-webserver/1111/4
