### ISSUE TITLE
Lets Encrypt ACME “alternate” link relation

### ISSUE THREAD

**Issue by hagaygo** [webprofusion/certify#536]
Hi

Is the  ACME “alternate” link relation option supported by certify the web ?

Issue is described fully on https://letsencrypt.org/2020/11/06/own-two-feet.html

**Comment by webprofusion-chrisc** [comment]
Hi, yes this has been implemented (as a 'preferred chain' option at the global or managed certificate level) and will be included in the next release which is likely to be within the next two weeks.

**Comment by hagaygo** [comment]
Thanks for your answer will check out new release when its available.

**Comment by hagaygo** [comment]
Hi , just downloaded 5.2.1 and can't seem to find the mentioned or any relevant settings, any pointers ?

**Comment by hagaygo** [comment]
Jumped the gun here , found it :

![image](https://user-images.githubusercontent.com/5015856/101329271-d7580400-3879-11eb-80df-e23d4d35a2d0.png)
