### ISSUE TITLE
Deploy to ADFS Server 2019 Not Working

### ISSUE THREAD

**Issue by joef12345** [webprofusion/certify#539]
I am receiving the following error while trying to deploy to ADFS for Server 2019:

`The specified directory service attribute or value does not exist.`

My solution was to create a new script to deploy the SSL cert:

![SSL 1](https://user-images.githubusercontent.com/42049508/103482937-d1d6d680-4db1-11eb-8470-2564c3718876.PNG)

![SSL](https://user-images.githubusercontent.com/42049508/103482921-b53a9e80-4db1-11eb-8c6e-4d42ef475a05.PNG)

```
param($result)

$ThumpPrint = $result.ManagedItem.CertificateThumbprintHash

Set-AdfsSslCertificate -Thumbprint $ThumpPrint
```

In server 2019, you do not need to reset ADFS for the change to take effect.

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for the feedback. This is the source code for our current ADFS provider:

https://github.com/webprofusion/certify-plugins/blob/master/src/DeploymentTasks/Core/Providers/Assets/ADFS.ps1

You should be able to choose whether to restart the service etc.

It looks like perhaps our call to `
Set-AdfsCertificate -CertificateType Service-Communications -Thumbprint $result.ManagedItem.CertificateThumbprintHash -Confirm:$false
` may be incompatible?

**Comment by webprofusion-chrisc** [comment]
Closing [Custom script].
