### ISSUE TITLE
[Feature] Show contact(s) for individual certificates on cert info panel.

### ISSUE THREAD

**Issue by potnoodles** [webprofusion/certify#54]
Only contacts at certificate creation get notified when expiry due. 
Is it possible for these contacts to be displayed alongside the certificate information? 
Im thinking of the scenario when a contact becomes redundant etc.

**Comment by soundshed** [comment]
Great idea! In the meantime you can delete (right click) a contact in Certify and Add a New Contact, the first contact on the list will be used as the contact for the next certificate request. So if a contact becomes redundant the next certificate renewal will update the contact associated with the certificate.

**Comment by potnoodles** [comment]
Thanks for the quick reply, and the workaround, but can you clarify - is it only the first contact on the list that wil be used as contact at next request or would any others on the list get added as well.?

**Comment by soundshed** [comment]
Yes, It's kind of more to do with ACMESharp that certify itself but yes, only one Registrant will be referenced, so in many case you'd want that to be a shared mailbox if your organisations has more than one person responsible for certificate management. If you don't renew your certificate and the expiry date gets closer, LetsEncrypt send you a reminder email.

**Comment by webprofusion-chrisc** [comment]
Just as an update: this now need additional UI in the Manage Site UI as the old treeview no longer exists in V2 onwards, it's still relevant though.

**Comment by webprofusion-chrisc** [comment]
Closing. We will only support one primary contact (so this should be the ops email address responsible for handling renewal issues).
