### ISSUE TITLE
Domain Validation using the http-01 challenge type.

### ISSUE THREAD

**Issue by sobujbd** [webprofusion/certify#540]
I wonder, is there such as option.... 

After creating the file in Local directory `\.well-known\acme-challenge\` Pause and ask me to confirm, do I have placed those files in web directory ` /.well-known/acme-challenge/` and can be accessible from the URL  `http://<yourdomain>/.well-known/acme-challenge/<randomfilename>` Then I press [Yes/Continue/Enter] to resume the validation process.

**Comment by webprofusion-chrisc** [comment]
Hi, we don't currently have a manual http validation option, this is mainly because we don't encourage manual certificate renewal processes. If you have a complex requirement for http validation perhaps you could look at using DNS validation?

**Comment by sobujbd** [comment]
Sir, thanks for the replay. Can you please take it as feature request. This way may helpful in some case... Since, is there `Wait N Seconds` options. I didn't try `dns-01` validation. If I own the **acme-dns** server, then I'll go forward with **dns-01** validation. Currently I prefer to use `http-01` but can't success due to, it's always generate `randomfilename`

**Comment by sobujbd** [comment]
Alright.
Today, I'm running **`acme-dns`** server. It's working perfectly. 

But CertifyTheWeb doesn't working with wildcard  *.example.com domain. It's always creating random TXT Record for wildcard  domain, therefore single domain works.

**Comment by webprofusion-chrisc** [comment]
@sobujbd acme-dns integrations works by asking you to setup a CNAME which points to your choice of acme-dns server, you create this once. When renewals happen the app automatically contacts the acme-dns server an tells it the new TXT record value. If your configuration is correct then the acme-dns server will then reply with that TXT value to Let's Encrypt when they query your TXT record.

As wildcards and non-wilcards both populate `_acme-challenge.<yourdomain.com>` acme-dns actually remembers the last two values for the TXT record, so it can server both values.

If you can share any more information I may be able to help you diagnose any configuration issues, for example which domain are you trying to validate? If I know that I can check the DNS records.

**Comment by sobujbd** [comment]
It's working now. Is there something wrong with DNS Records for **acme-dns** server.

**Comment by webprofusion-chrisc** [comment]
Thanks, got your email as well. Your acme-dns appears to be configured properly and I can see CNAME redirection for the TXT record using `dig`. I can also see using letsdebug.net that you have managed to fetch your wildcard certificate a few times already, so your configuration appears to be working.

If we experience further issues with validation I'd suggest you post to https://community.letsencrypt.org as while I can help with Certify related problems I can't help if it's Let's Encrypt that's failing to perform the validation.
