### ISSUE TITLE
IIS websites are not populated if either FTP is not started within an otherwise started site

### ISSUE THREAD

**Issue by MutantCarrot** [webprofusion/certify#543]
IIS site with working started HTTPS binding.  FTP binding also exists but the FTP service is disabled.  CertifyTheWeb will not recognise that the site IsEnabled. 

The code can be seen under GetPrimarySites in the service

I suggest that a single IsEnabled should be true for any event of ObjectState.Started = true 

This will trigger that the website is available for use by CTW

**Comment by webprofusion-chrisc** [comment]
Thanks, this fix will be in the next release.
