### ISSUE TITLE
Add support for Sectigo CA for SSL services 

### ISSUE THREAD

**Issue by XxPatrickxX** [webprofusion/certify#544]
https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA01N000000bvYj

SSL self enrollment URL: https://cert-manager.com/customer/<customer name>/ssl

The "<customer name>"  should reference a text field somewhere as the value is unique per customer.

**Comment by webprofusion-chrisc** [comment]
Hi, we do currently have the option for you to add your own CA:

- Settings > UI > Experimental> Certificate Authority Editor to enable the feature
- then Settings > Edit Certificate Authorities to add the CA and define its URLs
- then New Account to complete. You can set your EAB Key ID and HMAC on the Advanced tab. 
 
Please do try it out and let us know if it works or not.

We have previously requested demo access from Sectigo but received no response.
