### ISSUE TITLE
name.com DNS API authorization method crashes

### ISSUE THREAD

**Issue by Golynker** [webprofusion/certify#545]
name.com DNS API authorization crashes with the following error at "deleting" step (
Creating step passes successfully (even though no changes in DNS are actually made on Name.com side).

![image](https://user-images.githubusercontent.com/14768173/106279302-dd98aa00-6244-11eb-8b0b-26f13fbdf6e9.png)

"deleting" step fails with the following error:

![image](https://user-images.githubusercontent.com/14768173/106278980-5c411780-6244-11eb-9183-e2cf3ecf52b7.png)

Powershell/PoshACME DNS :: Error: Script invoke failed: System.Management.Automation.RuntimeException: Domain not found for _acme-challenge-test.istor-i.com ---> System.Management.Automation.RuntimeException: Domain not found for _acme-challenge-test.istor-i.com
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Certify.Management.PowerShellManager.InvokePowershell(CertificateRequestResult result, String executionPolicy, String scriptFile, Dictionary`2 parameters, String scriptContent, PowerShell shell, Boolean autoConvertBoolean) in C:\Work\GIT\certify_dev\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 254

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this, I think we need to sync to the latest version of posh-acme in order to pick up the fix for this, which will require some engineering and testing so will be a couple of weeks. In the meantime you should consider whether you can script your own dns create/delete script: https://docs.certifytheweb.com/docs/dns/providers/scripting

**Comment by Golynker** [comment]
Thanks! Custom script is a definitely useful feature. That's really good to know.
Look forward to getting a permanent fix in a couple of weeks too.
Will you update this ticket when the fix is available?

**Comment by webprofusion-chrisc** [comment]
Yes, the app will also offer to update when you launch it.

To try out the file we would be updating anyway you could copy this file:
https://raw.githubusercontent.com/rmbolger/Posh-ACME/3x/Posh-ACME/DnsPlugins/NameCom.ps1

and save it over the existing one under `C:\Program Files\CertifyTheWeb\Scripts\DNS\PoshACME\DnsPlugins` then run your test again.

**Comment by Golynker** [comment]
I might have misunderstood but after replacing the file and restarting Certify SSL Manager Service, I'm still getting the same error.
Would your please confirm if the following single change in NameCom.ps1 script supposed to do the job?
$hostShort = $RecordName -ireplace [regex]::Escape(".$domainName"), [string]::Empty
$hostShort = **(**$RecordName -ireplace [regex]::Escape($domainName), [string]::Empty**).TrimEnd('.')**

Another question - is it supposed to attempt "_acme-challenge**-test**.istor-i.com" record rather than "_acme-challenge.istor-i.com" for my target *.istor-i.com domain?

Thanks!

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for testing. - so my assumption was that fix would be enough, which apparently it's not.

Yes, when we create a test record (via the 'Test' button) it normally creates `_acme-challenge-test.yourdomain.com` then deletes it again. The full request will create and delete `_acme-challenge.yourdomain.com`.

I just remembered that you said no change is made on the name.com side - are you using your production  API credentials? **Test mode does not use the name.com test api, it just creates a test record in production.**

**Comment by Golynker** [comment]
Hi there,
Yes, using Production credentials. 
Guess the process fails to create the record behind the scenes for some reason, although it shows the progress as if it has succeeded and continues to the deletion step. So it fails when attempting to delete the record as it actually doesn't exist at this point.
BTW have tried to actually request the certificate, without testing. This fails too.

**Comment by webprofusion-chrisc** [comment]
Hi, I've been trying to check this myself (I don't have access to any name.com credentials to really test) and can confirm I get a similar error "Domain Not found" if I just use invalid credentials. I think this is likely what's happening here as we do have a few other name.com provider users who have yet to complain of any issue.

We need to handle the failed requests better however!

To test your credentials can you try:
`
 curl -u 'username:token' 'https://api.name.com/v4/hello'
`
If they are wrong you should get `{"message":"Permission Denied"}`
If they are in fact correct, please replace the credentials (settings > stored credentials) to ensure they are entered correctly.

It's possible to do the same in powershell but it's a bit more complicated to script.

**Comment by Golynker** [comment]
Hi Chris,
Thanks for the useful tip. The reason was two-factor auth :-)
Apparently I had to explicitly enable API access  in the respective Security settings as per this article:
https://www.name.com/support/articles/360007989433-Using-API-with-Two-step-Authentication

So the issue has been solved!

Cheers,
Oleg.
