### ISSUE TITLE
Windows 2019 Advanced Features

### ISSUE THREAD

**Issue by uhlhosting** [webprofusion/certify#550]
Hi,

It seems the button to enable advanced features is not active in 2019 Standard, any ideas?

**Comment by webprofusion-chrisc** [comment]
Sorry I don't know which button you mean, can you describe what you are looking for in more detail?

General questions are best asked here (whichever feature you mean, it probably isn't a bug in the code) : https://community.certifytheweb.com

**Comment by uhlhosting** [comment]
@webprofusion-chrisc there is an option to Enable Advanced features/functions such as allowing Scripts. Weird people who made these programs, do not know about what features we speak, I see it removed from what I can understand from your reply, or is this a sign to look for alternatives, since you do advertise yourselfves as Open Source, yet there is a Pro paid version to get proper support, maybe thats only for a PRO Advanced users, will look into alternatives, thanks for the help!

**Comment by webprofusion-chrisc** [comment]
Hi, yes we do provide paid support via support {at} certifytheweb.com. While the app source code is open we do also spend all day answering support requests, and that doesn't happen for free :) - the only limitation of the free version currently is managing up to 10 managed certificates, whereas the licensed version is unlimited. You are of course absolutely encouraged to review other available tools and make your own choices, some other tools also have great support from free volunteers.

The reason I didn't recognise 'Advanced features' is that we moved away from that option over a year ago in the newer version (5.x upwards). You now would access the 'Tasks' options option for Deployment Tasks (pre or post request tasks), one of which is `Run a PowerShell Script`, which is probably what you are looking for.
