### ISSUE TITLE
schlundtech API

### ISSUE THREAD

**Issue by perler** [webprofusion/certify#551]
any chance to see this API implemented? https://www.schlundtech.com/services/xml-gateway/

**Comment by webprofusion-chrisc** [comment]
Hi Pat, it's technically possible for that to be implemented but in general no, we are not adding more DNS APIs, instead we are using providers from the Posh-ACME project, so you could possibly request that provider there: https://github.com/rmbolger/Posh-ACME/tree/main/Posh-ACME/Plugins

There are thousands of different DNS providers and very few of them share their API with other providers so really we can only support extremely popular services like AWS Route53, Azure and Google Cloud, Cloudflare etc.

You have the option of scripting your own DNS updates, which I'm sure Schlundtech could advise you on. Our general DNS scripting info is here: https://docs.certifytheweb.com/docs/dns/validation#dns-scripting however I recommend also investigating acme-dns (CNAME redirection to an acme-dns server) or switching to a supported provider (which is not ideal but is sometimes generally beneficial and free, e.g. Cloudflare).

**Comment by perler** [comment]
thanks, I understand. and as of a comment [here](https://github.com/rmbolger/Posh-ACME/blob/main/Posh-ACME/Plugins/AutoDNS-Readme.md) from 4 days ago, schlundtech uses the same API as autodns, so we are covered. I am going to close the ticket.

**Comment by webprofusion-chrisc** [comment]
Great! That was fortunate :)
