### ISSUE TITLE
 Validation of the required challenges did not complete successfully. 

### ISSUE THREAD

**Issue by Salimanparas** [webprofusion/certify#554]
Validation of the required challenges did not complete successfully. Invalid response from https://api.fanz.az/.well-known/acme-challenge/wRPTv4LwgJIe0VK3akFzIPsK5bjPuN-wCMsx5m8rcAg [85.132.37.194]: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Not Found</TITLE>\r"

**Comment by webprofusion-chrisc** [comment]
Hi,

Our github is not used for support questions.

If you are a registered customer please email support {at} certifytheweb.com with details of this issue or if not please post a question to https://community.certifytheweb.com with details of your operating system version and any relevant configuration details.
