### ISSUE TITLE
Certify service not started

### ISSUE THREAD

**Issue by mr-le** [webprofusion/certify#556]
when I open the app I get the message "Certify service not started" please restart.
but the service is started, when I open http://localhost:9696/api/system/appversion with the browser it works
it shows <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">5.3.5.0</string>

service.exceptions.log shows : "Service API bound OK to http://localhost:9696"
ui.log : "[INF] UI Startup"

**Comment by webprofusion-chrisc** [comment]
Hi, this can happen for a few different reasons. Try editing `c:\programdata\certify\serviceconfig.json` and change `"host":"localhost" `to `"host":"127.0.0.1"` - also edit  `c:\programdata\certify\servers.json` to use the same host and port, then restart the Certify background service and re-open the app UI. 

See also: https://docs.certifytheweb.com/docs/backgroundservice

**Comment by mr-le** [comment]
thanks I changed both to 127.0.0.1 and changed port 9695 and it works.

**Comment by webprofusion-chrisc** [comment]
Great!
