### ISSUE TITLE
Two different domains that are substring of each other are mistaken to be subdomains 

### ISSUE THREAD

**Issue by artdedeco** [webprofusion/certify#559]
I have a SAN certificate for two similar domains that are a substring of one another (bar.com.br and foobar.com.br). I'm using Azure DNS and DNS challenge (using Azure Credentials).

When I try to renew my certificate, Certify the Web puts the TXT record in the wrong domain, because it seems it mistakes the longer one to be subdomain of the shorter one.

**Comment by webprofusion-chrisc** [comment]
Thanks @andre-ss6 I'll take a look at that. Are you supplying a ZoneID in your configuration (there's a dropdown list for that)? If not (or if it's wrong) it attempts to find the correct zone using a fallback technique and this is where the domain length could have an effect.
