### ISSUE TITLE
Language cannot be set

### ISSUE THREAD

**Issue by Tarjei-stavanger** [webprofusion/certify#560]
Hi,

I'm sure that you are proud of the fact that Certify the Web is autodetecting the language and uses it if it can.

For many, that is not good. Everything has weird names. And all documentation and support is in English.

So many of us want English language applications. We don't mind that you try to use the local language, but we want the ability to choose English by specifying English in the UI Settings section. Setting interface language elsewhere is fine.

I'm sure that I'm not the only Norwegian who don't know what a domenekonfeksjonskontroller is.

**Comment by webprofusion-chrisc** [comment]
Yes, I agree. It's very rare that anyone submits fixes for non-english text even though the app is open source (.e.g. anyone could submit fixes for https://github.com/webprofusion/certify/blob/development/src/Certify.Locales/SR.nb-NO.resx). I'll look into defaulting to english and offering a language switch.

**Comment by webprofusion-chrisc** [comment]
Fixed. Will be included in next release.
