### ISSUE TITLE
Missing Tomcat deployment documentation

### ISSUE THREAD

**Issue by Tarjei-stavanger** [webprofusion/certify#561]
https://docs.certifytheweb.com/docs/deployment/tasks_intro/

In the Tomcat section, the "more information" link leads nowhere. I get a Page Not Found error. Both in Chrome and Microsoft Edge.

**Comment by webprofusion-chrisc** [comment]
Hi, that looks like a bug in Docusaurus, I'll see if we can fix that with an update. Here's the link: https://docs.certifytheweb.com/docs/deployment/tasks/tomcat
