### ISSUE TITLE
Certificate not added to store when no IIS site is selected, subsequent task errors

### ISSUE THREAD

**Issue by dmeagor** [webprofusion/certify#562]
First off great tool BTW!

Anyway. after a few hours fiddling I’ve found a bug when no IIS site is selected which prevents the certificate from being added to the certificate store. I’ve tried changing the deployment mode from Auto to Certificate store only but that makes no difference.

In addition the RDP Listener service task fails, I guess due to the missing cert.

![image](https://user-images.githubusercontent.com/714902/118967980-4aa28d80-b963-11eb-845d-6be6388658ec.png)

Strangely if I use the Store Certificate task it completes successfully and the new cert can be found in the webhosting cert folder where I told it to go.

Workaround: I’ve created a dummy IIS website which seems to resolve everything.

**Comment by webprofusion-chrisc** [comment]
Hi, Is this a new problem? i.e. did it just start happening with the latest update? Are you using a custom script and if so can you share it here?

Certificates generated by Certify **always** go into the My/Personal certificate store (not Web Hosting) by default. The only way to make them go into the Web Hosting group is via your own scripting or using the Store Certificate task. If you need it to be in web hosting first, drag and drop the store certificate task up so that it happens first.

**Comment by dmeagor** [comment]
No this happened with yesterdays build (and wasn't fixed in todays update, although I can delete the previously undeletable cert now so thanks for that!)

No custom script, I've set this up on 3 servers and had the same issue with each.  Don't think I'm doing anything strange, just creating the non-iis entry, adding a single sub-domain (xyz.company.com) manually to the list.  Dns validation via cloudflare api. 
 Certificate is requested ok but doesn't get added to the My/Personal certificate store.  I was able to get it added to the web hosting store as a test using the separate task (I understand your point above about this not being automatic, I did this as a test.)

**Comment by webprofusion-chrisc** [comment]
Ok, thanks for raising the issue. The only change I can think of is related to how managed certificate IDs are created so I'll look at that. So to reproduce is the process just:

- create managed certificate with no IIS site selected -- - add a domain, request the certificate.

**Comment by dmeagor** [comment]
Yes that's correct

I've just run through it again (latest version) using those exact steps and and I can confirm that the certificate is saved here (correct timestamp etc.) but not added to the personal certificate store.

C:\ProgramData\certify\assets\anothertest.xyzcompany.co.uk

**Comment by webprofusion-chrisc** [comment]
Thanks, so after some investigation with different versions it appears that a tiny change in 5.4.0 to a null check fixed a code path that wasn't previously being activated for "manual" certificates (ones not associated with a specific IIS site), unfortunately this meant that no deployment happened. 

Testing of 5.4.2 is underway and an update will be released shortly. Existing certificates will start working/deploying to the cert store normally when next requested.
