### ISSUE TITLE
AWS Route53 API breaks when multiple domains are in a certificate, in Community verion 5.4.3.0

### ISSUE THREAD

**Issue by scratchbuild1** [webprofusion/certify#563]
Running Certify community version 5.4.3.0

I need to set up a certificate for Exchange Server, and there are two different domains involved, so the cert will look like:
outlook-aws.company1.com (primary)
autodiscover.company1.com
autodiscover.company2.com
outlook.company1.com
outlook.company2.com
owa.company1.com
owa.company2.com

Both company1.com and company2.com are managed through AWS Route 53, and the same credentials have access to both. I need two validation entries, because there are two different AWS zone entities. When I try to create two dns-01 validation entries, one for *.company1.com and the other for *.company2.com, whichever one I touch second, it changes the AWS Zone ID of the other one to match the one I just edited. As a result, it always fails validation because it's trying to make the records for company1.com in company2.com's zone, or vice versa. Any time I change the zone ID for one to be correct, it changes the other one to match, which is incorrect for the other one. I tried creating a second credential item in Certify so that it "thinks" it's two sets of credentials, and that did not help. 

Also, frustratingly, when it fails each time, it leaves behind its test validation records instead of cleaning them up, so I have to go manually delete them from AWS. Whether doing test mode or an actual request, if anything fails in validation, it seems like it leaves behind all the records it had started to make. It should delete them instead, which it does do if it succeeds in getting the certificate.

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this, I'll verify this today. Is it possible for you to manually enter the zoneid or does it not matter if the correct zoneid is present?

**Comment by scratchbuild1** [comment]
Thanks for the quick response! I can manually enter the zone id, yes, but as soon as I click out of the blank where it’s entered, or hit save, etc., the other blank that I didn’t edit will immediately change to match the one I just typed. Then if I try to fix the one that changed, the other one will change itself to match that one.

**Comment by webprofusion-chrisc** [comment]
I've tried recreating this with mixed success - if I add two new authorization configurations at the same time (before hitting save) then the zoneid gets copied. If I had one authorization configuration, then hit save before adding the next one then it seems to work normally. This is probably a long standing bug that hasn't been noticed before - a fix will be included in the next release.

**Comment by scratchbuild1** [comment]
Interesting, I had not tried that – I was doing what you described, creating both at the same time before hitting “save.” It seems like once it’s done that way, it thinks of them as being the same as each other, because no amount of saving afterwards causes them to be treated separately.

On a second server, I did try creating one auth entry, saving it, then creating the second, and requesting the certificate, and it failed authorization saying it was trying to create records for the first domain in the wrong zone. When I went back to the auth config, it had changed the zoneid of the first domain to match the one from the newly-added second, but this time when I changed it, it did seem to keep it because it passed authorization and was able to get a certificate. Maybe I did something wrong there, but now I’m a little afraid to mess with it because it’s working. I will try the new version when it is released though.

Can you also check on the behavior of seemingly not cleaning up the DNS records that got created during an unsuccessful attempt, i.e. if there are multiple records to be validated in DNS and it fails on the third one, the first two aren’t deleted? Or do you want a separate issue to be raised on that?

Thanks for your help!

**Comment by webprofusion-chrisc** [comment]
Thanks I'll check out the cleanup issue as well, the general idea is we maintain a queue of delete tasks as we create each record so it *should* cleanup whatever it can. What you're seeing could have been related to the zoneid mixup but I'll have a look.

**Comment by webprofusion-chrisc** [comment]
Resolved - update in next release.

**Comment by scratchbuild1** [comment]
Thank you!
