### ISSUE TITLE
Lists a certificate issued in crt.sh even when it says “Error” and no certificate has actually been issued.

### ISSUE THREAD

**Issue by BillyJC** [webprofusion/certify#564]
When you click on Request Certificate in Certify the Web, a bug in it puts a listing in crt.sh that a certificate has been issued even when it says “Error” and no certificate has actually been issued.

As in the screenshot, I have only one usable certificate that was issued, but crt.sh shows (5) instead.

How can l generate a second one?

If not, when willI I be able to?

Thanks,

Kenny

![bug-in-certifytheweb](https://user-images.githubusercontent.com/4697462/123553568-ec2eb300-d749-11eb-95ad-d047ae8f8906.jpg)

**Comment by webprofusion-chrisc** [comment]
Hi,

When you click Request Certificate it orders a new certificate from Let's Encrypt. The crt.sh log is a Certificate Transparency log which Let's Encrypt report new certificate issuance to (there are several other certificate transparency logs which will show the same thing). So all that's happening here is your certificate order is completing OK, as normal.
