### ISSUE TITLE
Certify the Web dont open aftear update install

### ISSUE THREAD

**Issue by hendersonandrade** [webprofusion/certify#567]
I have made the update of certify app to version 5.5.2 but now when i try to open the application, the taskbar menu in my Windows show the app in opened state but the app screen dont show

**Comment by webprofusion-chrisc** [comment]
Hi, last time you (or someone else) opened the app it was probably on a dual screen setup, the app should detect this and move the windows but if not, close the app and delete `C:\ProgramData\Certify\ui.json` - this is the file that stores UI preferences. Start the UI again.

**Comment by webprofusion-chrisc** [comment]
If that wasn't the case, you could attach the UI.json file here for info to see what went wrong.

**Comment by hendersonandrade** [comment]
Hi @webprofusion-chrisc thank you for the reply. The solution suggested worked like a charm to me :)
