### ISSUE TITLE
Exception: Certificate Has Not Been Updated Yet

### ISSUE THREAD

**Issue by qzwl** [webprofusion/certify#57]
The latest version of the Windows2012 error。

**Comment by qzwl** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Management.Automation.CmdletInvocationException: Certificate has not been submitted yet; cannot update status ---> System.Exception: Certificate has not been submitted yet; cannot update status
   在 ACMESharp.POSH.UpdateCertificate.ProcessRecord()
   在 System.Management.Automation.Cmdlet.DoProcessRecord()
   在 System.Management.Automation.CommandProcessor.ProcessRecord()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   在 System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   在 System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   在 System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   在 System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   在 System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   在 System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   在 Certify.PowershellManager.UpdateCertificate(String certAlias)
   在 Certify.Forms.Controls.CertRequestSettingsIIS.btnRequestCertificate_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Certify
    程序集版本:1.0.0.0
    Win32 版本:0.9.96
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/Certify.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Certify.Core
    程序集版本:1.0.0.0
    Win32 版本:0.9.96
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/Certify.Core.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:9.0.0.0
    Win32 版本:9.0.1.19813
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/Newtonsoft.Json.DLL
----------------------------------------
ACMESharp.Vault
    程序集版本:0.8.0.0
    Win32 版本:0.8.0.0
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.Vault.DLL
----------------------------------------
Microsoft.ApplicationInsights
    程序集版本:2.2.0.0
    Win32 版本:2.2.0.54037
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/Microsoft.ApplicationInsights.DLL
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.17929 built by: FX45RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
ACMESharp.PKI.Providers.BouncyCastle
    程序集版本:0.8.2.0
    Win32 版本:0.8.2.0
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.PKI.Providers.BouncyCastle.DLL
----------------------------------------
ACMESharp
    程序集版本:0.8.2.0
    Win32 版本:0.8.2.0
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.DLL
----------------------------------------
System.Management.Automation
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
System.Management.Automation.resources
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation.resources/v4.0_3.0.0.0_zh-Hans_31bf3856ad364e35/System.Management.Automation.resources.dll
----------------------------------------
Microsoft.PowerShell.Commands.Diagnostics
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll
----------------------------------------
System.Configuration.Install
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.17929 built by: FX45RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
Microsoft.PowerShell.ConsoleHost
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll
----------------------------------------
Microsoft.PowerShell.Commands.Utility
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll
----------------------------------------
Microsoft.PowerShell.Commands.Management
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll
----------------------------------------
Microsoft.Management.Infrastructure
    程序集版本:1.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
Microsoft.PowerShell.Security
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll
----------------------------------------
Microsoft.WSMan.Management
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Management
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.DirectoryServices
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Transactions
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.PowerShell.Security.resources
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security.resources/v4.0_3.0.0.0_zh-Hans_31bf3856ad364e35/Microsoft.PowerShell.Security.resources.dll
----------------------------------------
Microsoft.WSMan.Management.resources
    程序集版本:3.0.0.0
    Win32 版本:10.0.14409.1005
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management.resources/v4.0_3.0.0.0_zh-Hans_31bf3856ad364e35/Microsoft.WSMan.Management.resources.dll
----------------------------------------
ACMESharp.POSH
    程序集版本:0.8.2.0
    Win32 版本:0.8.2.0
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/ACMESharp.POSH.DLL
----------------------------------------
Microsoft.CSharp
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.17929
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.ComponentModel.Composition
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
AWSSDK.Core
    程序集版本:3.3.0.0
    Win32 版本:3.3.4.0
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.Core.DLL
----------------------------------------
AWSSDK.Route53
    程序集版本:3.3.0.0
    Win32 版本:3.3.1.1
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.Route53.DLL
----------------------------------------
AWSSDK.S3
    程序集版本:3.3.0.0
    Win32 版本:3.3.1.1
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/AWSSDK.S3.DLL
----------------------------------------
BouncyCastle.Crypto
    程序集版本:1.8.1.0
    Win32 版本:1.8.15362.1
    基本代码:file:///C:/Program%20Files%20(x86)/Certify/BouncyCastle.Crypto.DLL
----------------------------------------
Microsoft.Web.Administration
    程序集版本:7.0.0.0
    Win32 版本:8.0.9200.16384
    基本代码:file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Web.Administration/7.0.0.0__31bf3856ad364e35/Microsoft.Web.Administration.dll
----------------------------------------
System.ComponentModel.Composition.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.ComponentModel.Composition.resources.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.6.81.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
MetadataViewProxies_a14b38f5-ba4d-4f16-9e14-96feab1dea82
    程序集版本:0.0.0.0
    Win32 版本:4.6.81.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.34209 built by: FX452RTMGDR
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Net.Http.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.17929 built by: FX45RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http.resources/v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a/System.Net.Http.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.34209 built by: FX452RTMGDR
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by lkarlslund** [comment]
I have this on 2012R2 too

**Comment by held88** [comment]
I have such error on 2012R2 too. Certify not work for me.

**Comment by kirillkovalenko** [comment]
The same issue on Windows 2016 Server
ACME Sharp - version v0.8.1.0
Certify 0.9.98 alpha 15
[certify-exception.txt](https://github.com/webprofusion/certify/files/884927/certify-exception.txt)

**Comment by webprofusion-chrisc** [comment]
Please try the new alpha version of Certify 2.0:
https://certify.webprofusion.com/downloads/certifysetup2.0.0-alpha.exe

**Comment by webprofusion-chrisc** [comment]
Closing. v2 alpha now released.
