### ISSUE TITLE
Request Posh-ACME Plugin(s)

### ISSUE THREAD

**Issue by mucnet** [webprofusion/certify#570]
Is it possible to make additional [Posh-ACME Plugins](https://github.com/rmbolger/Posh-ACME/tree/main/Posh-ACME/Plugins) working in addition to [yours](https://docs.certifytheweb.com/docs/dns/validation/) for CertifyTheWeb?
I do intend to use All-Inkl as DNS service provider.

**Comment by webprofusion-chrisc** [comment]
Hi, we do currently integrate a number of Posh-ACME plugins but we are unlikely to integrate them all and increasingly we will not be supporting smaller DNS providers (there are thousands of them) , instead you can either :

- **use the Certify DNS service (managed CNAME challenge delegation based on acme-dns): https://docs.certifytheweb.com/docs/dns/providers/certifydns** - this is our supported service for automated DNS challenges. All other available DNS update methods are provided as a convenience but are not necessarily a core service we provide and support.
- use your own acme-dns server
-  or use your own PowerShell script for DNS scripting. You can in turn call Posh-ACME DNS providers in most cases.
- Move your DNS to a major DNS provider (AWS Route 53, Cloudflare, Azure DNS, Google Cloud DNS)

Here is an example powershell script calling parts of Posh-ACME (Linode in this case) which could be adapted, you would need to adjust paths etc and pass in arguments for the recordname and value (https://docs.certifytheweb.com/docs/dns/providers/scripting):
```
$PoshACMERoot = "C:\PoshACME" 
$Public  = @( Get-ChildItem -Path $PoshACMERoot\Public\*.ps1 -ErrorAction Ignore )
$Private = @( Get-ChildItem -Path $PoshACMERoot\Private\*.ps1 -ErrorAction Ignore )

Add-Type -Path "$($PoshACMERoot)\..\..\..\BouncyCastle.Crypto.dll"

# Dot source the files (in the same manner as Posh-ACME would)
Foreach($import in @($Public + $Private))
{
    Try { . $import.fullname }
    Catch
    {
        Write-Error -Message "Failed to import function $($import.fullname): $_"
    }
}

# Replace Posh-ACME specific methods which don't apply when we're using them
function Export-PluginVar {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory,Position=0)]
        [string]$VarName,
        [Parameter(Mandatory,Position=1)]
        [object]$VarValue
    )
 }


$script:UseBasic = @{} 

if ('UseBasicParsing' -in (Get-Command Invoke-WebRequest).Parameters.Keys) {  $script:UseBasic.UseBasicParsing = $true } 

. "C:\PoshACME\Plugins\Linode.ps1" 

$PluginArgs= @{} 
Add-DnsTxt -RecordName '_acme-challenge-test.wildcard.example.com' -TxtValue 'MsObHu283vtf58yJprS-qRz0xLCzSG__846qdo8N1nM' @PluginArgs 

```
