### ISSUE TITLE
Certify v5 locks up when website has a lot of bindings

### ISSUE THREAD

**Issue by kd8ssq** [webprofusion/certify#573]
Just recently upgraded from Certify v4 to the lastest version of v5 running on Windows Server 2012.  I have a website with almost 2000 bindings and when I try to view the domains list for the certificate, the application locks up.  If I let it sit for a few minutes, it might come back and start displaying the list, so it just seems like a timing issue.

**Comment by webprofusion-chrisc** [comment]
We did introduce an exponential back-off if we encounter exceptions committing IIS bindings changes, so gradually allows more and more time for applicationhost.config to save. I wonder if there is a flaw there - will investigate.

**Comment by webprofusion-chrisc** [comment]
It's also quite important that your write speed is good - there could be milliseconds between our last binding update and the next, and IIS was really more designed for ssl certs changing once a year. You may also want to exclude applicationhost.config from any virus scanners etc. so it doesn't get locked for writes.

**Comment by kd8ssq** [comment]
This doesn't happen when saving a cert, this happens when you select an existing cert from the list on the left and try and view the "Certificate" menu which displays all the Domains associated with the certificate.

**Comment by webprofusion-chrisc** [comment]
Thinking about this some more, how are you actually using this (or intending to)? I'd imagine that trying to sort through 2000 bindings is pretty difficult even if the UI was faster. Are you creating one cert per domain or trying to pick 100 names to include on a cert etc?

I'm wondering if there should be a better way to do this. While we can get the data grid to virtualize and show many items it seems likely it would be progressively less usable.

**Comment by kd8ssq** [comment]
I'm actually only using 1 or 2 of the bindings for that site for a
certificate.  It's for our mail server and we have customers connect to it
using their domains, but because of how things have to be set up for SSL
domains, we only have 1 secure domain for the mail server.  Customers use
their domains to connect, but we redirect automatically to the secure
website for them to use.

**Comment by kd8ssq** [comment]
Checking in to see if you've had any epiphanies regarding this problem.  Right now we're unable to make any changes to the pre-existing certificate when the IIS site has over 2000 bindings.  As soon as we click the "certificate" submenu in Certify, the app locks up and the CPU jumps up between 12-15% for the process.  Not sure if it's locking up on trying to read all the bindings from IIS or not.  I don't seem to recall having this issue in v4.

**Comment by kd8ssq** [comment]
Odd thing is, the app does eventually load and display the Certificate sub-menu, but as soon as I click into the UI, it becomes non-responsive again.

**Comment by webprofusion-chrisc** [comment]
The main issue is that the UI tries to render the list which in turn causes a bunch of layout refreshes (almost per row), this is a constraint of the WPF datagrid and the solution is to move away from trying to show the whole list and have pagination or 'infinite scroll' instead. I haven't abandoned the idea of improving this but all UI work is currently focused (for the next 6 weeks or so) on developing the Web version of the UI (for Windows, Linux and Mac etc) which in turn will have some very different UI elements. Long term it's likely the web UI will be re-used as the desktop UI so we don't have to maintain two UIs.

A workaround would be to simply not select the IIS site and manually add the domains you want in your certificate. These will still be using auto deployment, so you can see on the Preview tab that your bindings will then be updated on the correct site.

**Comment by webprofusion-chrisc** [comment]
I do believe the performance has gotten worse though and my suspicion is that it's something to do with the theming framework we use.

**Comment by webprofusion-chrisc** [comment]
Well, it was worth you checking back on this because it made me look at the problem again and I think I've found the fix. I'll release an update shortly.

**Comment by webprofusion-chrisc** [comment]
This fix has been included in the latest release v5.6.5

**Comment by kd8ssq** [comment]
Awesome!  Thanks a lot!  I tested and confirmed that the UI is 100 times better and now usable with sites with large bindings.  Thanks again!  Keep up the great work!
