### ISSUE TITLE
Issue with "č" in domain name

### ISSUE THREAD

**Issue by infiniteloopltd** [webprofusion/certify#575]
The letter "č" if contained in a domain name appears to be mis-interpreted as "c" without the accent.

The domain "[www.ečv.com](http://www.ečv.com)" is a binding on my IIS server. 

But in the CTW UI, it appears without the accent, and the request is made for the wrong domain;

2021-10-01 10:29:48.342 +01:00 [INF] Validation of the required challenges did not complete successfully. Domain validation failed: www.**ecv**.com 
Fetching http://leere.seite: Invalid hostname in redirect target, must end in IANA registered TLD BadRequest urn:ietf:params:acme:error:connection

In fact, if you to the domain www.ecv.com (no accent) it redirects to http://leere.seite

**Comment by webprofusion-chrisc** [comment]
Hi, Thanks for raising this. I assume the site was added to Certify The Web it was done simply using the Certify The Web UI and not through any other command line import etc?

We do have support for international domain names so we will need to investigate this issue further and get back to you.

**Comment by webprofusion-chrisc** [comment]
In a quick test using `ečv-test`

This is (correctly) converted to ascii as `xn--ev-test-j6a` using the Punycode schema required for domain names, however the issue I can see is when it tries to then save the final certificate PFX it fails, which is a bug.


If I try `http://www.ečv.com/` it gets (correctly) converted to `www.xn--ev-ema.com`

Are you entirely sure that CTW automatically read www.ecv.com from your IIS bindings or did you type it manually?
