### ISSUE TITLE
OVH DNS records not cleared after renewal

### ISSUE THREAD

**Issue by Nuklon** [webprofusion/certify#576]
This is very annoying and polutes the DNS records.

**Comment by webprofusion-chrisc** [comment]
Thanks, this was a provider implemented by a community member, if it's not working we should perhaps remove it. The source code is here if you can see what's wrong: https://github.com/webprofusion/certify/blob/development/src/Certify.Providers/DNS/OVH/OvhClient.cs

Double check you have permission to delete your TXT records using your API credentials  and that the correct zoneID is being provided.

**Comment by Nuklon** [comment]
Adding entries works OK (which is nice as it's much better than the alternatives), but removing does not.
It does say in the log 2021-10-02 14:51:04.751 +02:00 [INF] DNS: Deleting TXT Record 
but it's still in OVH backend. 
Looking at the code https://github.com/webprofusion/certify/blob/development/src/Certify.Providers/DNS/OVH/DnsProviderOvh.cs#L118, it does seem to call the correct API:
https://api.ovh.com/console/#/domain/zone/%7BzoneName%7D/record/%7Bid%7D#DELETE

All rules are OK, I have given it rights to everything.

**Comment by Nuklon** [comment]
I checked a bit more in the code and while I'm not that familar with it, I'm not sure this here is correct:
https://github.com/webprofusion/certify/blob/5c223ff90de38876f196971bc63c8d5aa205e512/src/Certify.Core/Management/Challenges/DNS/DnsChallengeHelper.cs#L384

It does not pass in the RecordId needed by OVH:
https://github.com/webprofusion/certify/blob/5c223ff90de38876f196971bc63c8d5aa205e512/src/Certify.Providers/DNS/OVH/DnsProviderOvh.cs#L118

**Comment by webprofusion-chrisc** [comment]
Thanks, I don't have any access to an OVH DNS account to test this but perhaps the code could be modified to query OVH for the records, match the TXT record by name to get the record ID, then perform the delete.

There is no way for the high level code in DnsChallengeHelper to know what the record id, to the Delete provide code needs to do more work to get that.

Interesting that nobody has reported this before, it suggest either nobody is really using this provider or if it only leaves one record in DNS perhaps nobody else so far has cared.

**Comment by webprofusion-chrisc** [comment]
Note, to test this yourself you need to build the Certify service, then copy the Plugin.DNS.OVH.dll file into C:\Program Files\CertifyTheWeb\Plugins and restart the certify background service.

**Comment by Nuklon** [comment]
> Thanks, I don't have any access to an OVH DNS account to test this but perhaps the code could be modified to query OVH for the records, match the TXT record by name to get the record ID, then perform the delete.
> 
> There is no way for the high level code in DnsChallengeHelper to know what the record id, to the Delete provide code needs to do more work to get that.
> 
> Interesting that nobody has reported this before, it suggest either nobody is really using this provider or if it only leaves one record in DNS perhaps nobody else so far has cared.

Hmm, what about storing used record ids in OVH provider. Then one can simply use that?

**Comment by webprofusion-chrisc** [comment]
Possibly? I don't have an OVH test system so it's not currently possible for me to develop it either way. We could perhaps switch to the Posh-ACME OVH provider instead.

**Comment by Nuklon** [comment]
I will take a look at this when I have some time, if you find storing the record ids acceptable then I can try.
