### ISSUE TITLE
Namecheap DNS API plugin only parses first 100 domains.

### ISSUE THREAD

**Issue by PeetMcK** [webprofusion/certify#578]
The NameCheap DNS API plugin seems to only parse the first 100 domains. 

If I attempt to pull a certificate listed in the first 100 of an API call like `https://api.namecheap.com/xml.response?ApiUser=apiexample&ApiKey=56b4c87ef4fd49cb96d915c0db68194&UserName=apiexample&Command=namecheap.domains.getList&ClientIp=192.168.1.109&pagesize=100` Certify correctly creates the txt record and pulls the certificate. 

If I attempt to pull a certificate listed in 101 or greater of an API call like `https://api.namecheap.com/xml.response?ApiUser=apiexample&ApiKey=56b4c87ef4fd49cb96d915c0db68194&UserName=apiexample&Command=namecheap.domains.getList&ClientIp=192.168.1.109&pagesize=100&page=2` Certify throws the error `Domain {domain} is not managed by this account!`

I'd fix it and get you a pull request if I could. It's just outside my wheel house.

Fixing the existing code may be simple and if so, please do. But if it is at a all a lift, it may be worth migrating to a "NameCheap (using Posh-ACME)” plugin. 

Either way, thanks!.

**Comment by webprofusion-chrisc** [comment]
Thanks, it would be really interesting if you could run fiddler and see what comes back for the second API call, in case it's a rate limit error.

**Comment by webprofusion-chrisc** [comment]
Closing. The built-in namecheap provider has been deprecated in favour of the Posh-AMCE provider.
