### ISSUE TITLE
Question about Reapplying Certs to bindings

### ISSUE THREAD

**Issue by kd8ssq** [webprofusion/certify#580]
I'm working on migrating Certify to a new server.  I found a post about moving a folder and executing "certify diag autofix" to reapply the certs to the bindings.  It looks like for each attempt it's calling out to a server online to do some kind of validation before it reapplies the certs.  Is this as intended?

I also though I could speed up the process by manually clicking the "Re-apply certificate to binding" button for each website, but again it seems to be calling out to a server to do some validation before applying the certs. 

Is there any way to only reapply without having to validate each site?  I have over 500 to do and when I rand the command line command, it took 4 hours to process 100 sites.

**Comment by webprofusion-chrisc** [comment]
Hi, please use `support at certifytheweb.com` for support questions.

I'll look into this for you today.

**Comment by kd8ssq** [comment]
Will do.  Sorry about that.
