### ISSUE TITLE
Enhancement request - Filter by expiration days

### ISSUE THREAD

**Issue by kd8ssq** [webprofusion/certify#581]
In larger lists, especially when you need to verify/test that certificates are updating, I think it could be beneficial to add the ability to sort/filter based on when the certificates are set to renew.

**Comment by webprofusion-chrisc** [comment]
Thanks, so is this for the left hand side list of managed certificates? We do have a right click context menu > Sort by expiry date (soonest first) but this is the actual certificate expiry, not the next scheduled renewal attempt.

**Comment by kd8ssq** [comment]
Yeah, I'm talking about the left hand list of certs.  Didn't know about the context menu.  That works for me!  Thank you very much!
