### ISSUE TITLE
Custom plugin fails to load from C:\ProgramData\Certify\plugins

### ISSUE THREAD

**Issue by pricewatermouse** [webprofusion/certify#584]
I made a custom Deployment Task plugin `Plugin.DeploymentTasks.MyPlugin.dll`

If I place it into `C:\ProgramData\Certify\plugins` the plugin load fails with error in plugins.log:

_[WRN] Plugin Load Failed [Certify.Models.Plugins.IDeploymentTaskProviderPlugin] File does not exist: Plugin.DeploymentTasks.MyPlugin.dll_

I investigated the issue with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and found out that CertifySSLManager.Service actually tries to load the plugin from `C:\Program Files\CertifyTheWeb\Plugins\Plugin.DeploymentTasks.MyPlugin.dll`

Please fix

P.S. If I place the plugin into `C:\Program Files\CertifyTheWeb\Plugins`, it works good, but it is removed with the next update  #583

**Comment by webprofusion-chrisc** [comment]
Thanks, a fix for this will included in the next release. At that time you will also be required to enable a new preference to Load Plugins.

**Comment by pricewatermouse** [comment]
Please also note that plugins generally can depend from other .Net assemblies. 

**What is the correct place to put dependent assemblies?**

Currently only `C:\Program Files\CertifyTheWeb` (application root) seem to work, but remember about #583

**Comment by webprofusion-chrisc** [comment]
@pricewatermouse great question, again I think you may be the only person who as ever tried to get their own plugin working. I believe we can either preload types or catch loader exceptions and then try to load them from the external plugins folder. I'll test this out this week.

**Comment by pricewatermouse** [comment]
This is minor issue for me since I’ve embedded all the dependencies into the single plugin assembly. Also there is an option to put dependencies into the GAC.

So you can close the issue as is, to keep things simple and secure – up to you

Thank you for fixing

**Comment by pricewatermouse** [comment]
@webprofusion-chrisc, what about a release build with this fix?

**Comment by webprofusion-chrisc** [comment]
This is being prepared now, along with a few other issues.
