### ISSUE TITLE
Feature Request - Ability to specify renewal order for multiple managed certificates.

### ISSUE THREAD

**Issue by TrevorRuppert** [webprofusion/certify#585]
I have been working with Certify for a while now and recently had a need to deploy 2 different certificates to a few different machines. I have the deployment down no problem but noticed a potential issue with the automatic renewal process. One of my certs is dependent upon another cert having been renewed and installed before it is able to be renewed and installed. This is because during the binding process for cert 2 it needs certain bits of information from cert 1 such as the thumbprint. Having the ability to specify a cert group or something similar where you can manually specify the order of renewal, as well as potential delays between renewal requests, would be an amazing feature in my opinion. If this is already a feature or has already been requested, I apologize. I did not see a similar request already posted.

**Comment by webprofusion-chrisc** [comment]
Thanks, can you explain a little more about how you have an interdependency between two certificates? I've never heard of that before.

Currently I don't think we would implement renewal order (A must be renewed before B etc), as it has never been requested before, but if the need for it is clear then it's more likely to be implemented. Are you sure that this process couldn't be implemented without the interdependency?
