### ISSUE TITLE
AutoUpdate.ps1 TLS compatibility issue between the download site and windows 2012 R2 / Windows 2016

### ISSUE THREAD

**Issue by Taasadi** [webprofusion/certify#587]
it seems there is a TLS compatibility issue between the download site and windows 2012 R2 / Windows 2016 adding the below line to the beginning of the AutoUpdate script to enforce TLS 1.2 connection fixes the issue.

So can you please add this to the source script so it can be shipped with the newer release of certifytheweb?

**[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;**

error message “Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive”

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this issue. The AutoUpdate script and a few other powershell script related items will be updated in the next release.
