### ISSUE TITLE
Disable Legacy TLS binding is reset

### ISSUE THREAD

**Issue by Nuklon** [webprofusion/certify#588]
On WS2022 or W11, you can disable legacy TLS:
![image](https://user-images.githubusercontent.com/23340481/142041649-a0863606-d804-47e6-9caf-511d52d0a206.png)

But after certificate binding this option is reset to the default value. It happens all the time so should be easy to reproduce.

**Comment by Nuklon** [comment]
Disable QUIC and Disable HTTP/2 also get reset.

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for raising this, we clearly need to preserve these newer binding flags when updating bindings.

**Comment by Nuklon** [comment]
Yes, I had this running and suddenly the legacy TLS option was gone. I suspect the other two options also have this issue as they're also new. All these options seem to rely only on the **sslFlags** attribute in the binding.

I see here https://github.com/webprofusion/certify/blob/807dfdee8c8a99dd35ea30f4f7d59e5ab1c836b6/src/Certify.Core/Management/Servers/ServerProviderIIS.cs#L459 is already something done with them but this is always set to 1.

**Comment by Nuklon** [comment]
Here are the possible values:
```csharp
        None = 0,
        SNI = 1,
        CentralSsl = 2,
        DisableHttp2 = 4,
        DisableOcspStapling = 8,
        DisableQuic = 16,
        DisableTls13OverTcp = 32,
        DisableLegacyTls = 64,
```

**Comment by webprofusion-chrisc** [comment]
Thanks, that's fixed in the next release which is expected this week or next.

**Comment by Nuklon** [comment]
Great, thanks, looking forward to that 👍
