### ISSUE TITLE
CSR with domains listed as common names instead of SANs are not included

### ISSUE THREAD

**Issue by lspiehler** [webprofusion/certify#590]
I received a CSR from a vendor that contained a domain as a common name that wasn't listed as a SAN. The domain wasn't listed in the request and it failed with the message "Error finalizing order :: Order includes different number of names than CSR specifies." Unfortunately, I'm not always responsible for CSR generation, so this sort of thing is sometimes unavoidable. I was able to use acme.sh to get a certificate, but we're trying to standardize on Certify the Web, so it would be great if either domains that are only listed as common names in the CSR would be recognized or if Certify the Web would allow for manual modification of the domains when using a CSR.

If you'd like a CSR to test with, the one below has test1.domain.com as a common name in the subject and test2.domain.com, test3.domain.com as SANs. You'll notice Certify the Web only lists test2.domain.com and test3.domain.com. If you'd like to generate your own for testing, https://certificatetools.com is a great way to quickly generate CSRs.

```
-----BEGIN CERTIFICATE REQUEST-----
MIIDBTCCAe0CAQAwTjEZMBcGA1UEAwwQdGVzdDEuZG9tYWluLmNvbTELMAkGA1UE
BhMCVVMxEjAQBgNVBAgMCUxvdWlzaWFuYTEQMA4GA1UEBwwHU2xpZGVsbDCCASIw
DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKVttuCpx+SZf+XHCyUMuHi8FQ5r
Rv97kCb5CiBh8WeFNUsXYA63srjHptkqp3d1AbL5UJDReJNXjOR05rIZZ1J9KtE1
cjrg2729r62tYqZNpzPcFVYb3aIHhUq39sZWp1yjc8HTneZ00hMlSdo0sMw5hmnt
WhRl0a1BhSGqt8lrenwl/vqD7JFESDLpSJbnFFTcVO5f3qSNrSr3R7sYIPqsoqqP
vgvRN4sp2kT4wuqVfJ8pG53lsIM/wRgkLPm7T/IK7pPVUr3cKxyAEIs0xkKaD9Ue
Q++srS8RrqhPpWwDzWvjKX3asw4BF+YAW+kKoeBDcTAyDmH/+lz4IkjxbOkCAwEA
AaByMHAGCSqGSIb3DQEJDjFjMGEwDgYDVR0PAQH/BAQDAgWgMCAGA1UdJQEB/wQW
MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAtBgNVHREEJjAkghB0ZXN0Mi5kb21haW4u
Y29tghB0ZXN0My5kb21haW4uY29tMA0GCSqGSIb3DQEBCwUAA4IBAQBh+WPuLrY8
kkm0ithTsMHsLUWDaA3eD9zQnA6YGinsOHwXrFNc0kX55P6LX8OlLzrebJvPnhjA
zM6ebm58tcpLwBeVpjb7Rd0hW5ZQ0N3NFnpWMTP8hBe24wYhXWEf6WpHamw62/FZ
zDqBx/03EXH1YGcaGpPlTOnriihtT/YcYmpKfa2Np0NkyYOijbBN2nHtBksEqQ2T
wuMMMaWHa/+SZ3gVwDE5GLpr2sUF00bfEQkv+U1DR42H3j+7G7VmLRpUxj/kWo8V
fuCfEAwx5UCvNPouzXdIoBz+CvlHgI7TkZBwFP0NG2w1aR3Ww42Tb64lxSHFzL9e
WHqs24zhmzJj
-----END CERTIFICATE REQUEST-----
```

**Comment by webprofusion-chrisc** [comment]
Thanks very much for raising this. A fix for this will be included in the next update.
