### ISSUE TITLE
The problem with updating the certificate

### ISSUE THREAD

**Issue by geor444** [webprofusion/certify#591]
I am trying to update my certificate for the devops.expasys.online domain, but when I try to update it, I get the following error
![image](https://user-images.githubusercontent.com/67157811/144444273-7e0fa8af-3cf3-4037-bc82-3901049c08b7.png)
The domain is specified in the error a.expasys.ru although I am updating a completely different domain, how do I update my devops.expasys.online domain ?

**Comment by webprofusion-chrisc** [comment]
Hi, support requests should be emailed to `support at certifytheweb.com`. If you are not a licensed user you can post to our community forum: https://community.certifytheweb.com/

The problem relates to either your configuration or Let's Encrypts API which recently had an outage: https://letsencrypt.status.io/
