### ISSUE TITLE
Certify SSL Manager Service does not start after upgrade to 5.6.0

### ISSUE THREAD

**Issue by glat** [webprofusion/certify#592]
As in subject.
Please fix ASAP.
Thanks

**Comment by webprofusion-chrisc** [comment]
We have received reports of a problems with the latest update and have reverted to the previous version.

Can you confirm if the file C:\Program Files\CertifyTheWeb\x64\SQLite.Interop.dll exists on your updated machine and if so which version does it show under Details? This is what it should be:

![image](https://user-images.githubusercontent.com/2445502/146162929-46381a33-d1c9-4e1d-a16c-e3e21e23335f.png)


We will investigate this issue further and release another update, in the meantime please uninstall 5.6.0 and install 5.5.7 from https://certifytheweb.com/ (settings are preserved in ProgramData so uninstalling does not remove any settings).

**Comment by glat** [comment]
Sorry. I already downgraded to renew some certificates.

**Comment by webprofusion-chrisc** [comment]
Same question to @criwayc

**Comment by criwayc** [comment]
shows same version as in your screenshot:

![certifytheweb](https://user-images.githubusercontent.com/42205140/146165555-f7c2ab18-5b38-4970-8481-664125c1b117.png)

**Comment by webprofusion-chrisc** [comment]
Interesting! Does your machine also have a C:\Program Files\CertifyTheWeb\x86\SQLite.Interop.dll file? I'm trying to figure out if our installer is not properly deleting old files before it copies new versions.

**Comment by glat** [comment]
I've one but in x64 directory. See here:

![image](https://user-images.githubusercontent.com/569200/146176776-d5c7c1cc-fe90-4662-a043-6bde2027f334.png)

There's no x86 directory.

**Comment by glat** [comment]
Recap:

I've:
a SQLLite.Interop.dll version 1.0.113.0 in C:\Program Files\CertifyTheWeb
and
a SQLLite.Interop.dll version 1.0.114.0 in C:\Program Files\CertifyTheWeb\x64

The wrong one is the first?

**Comment by criwayc** [comment]
Yeah, seems like the SQLLite.Interop.dll does linger in "C:\Program Files\CertifyTheWeb" on older instances.
We have servers using CertifyTheWeb that do not have this file there and all of them are newer ones.

Where this file is present, the installation of CertifyTheWeb was done way back, so I assume this was used by an old version and was not cleaned up properly on an upgrade. (but did not hurt till 5.6.0)

On the "newer" servers I talk about, v5.6.0 runs without any problems

**Comment by glat** [comment]
I see. Do you plan a fix in the installer or we need to delete it manually?
Thanks

**Comment by webprofusion-chrisc** [comment]
Great, no we'll fix the installer if we can. It should actually delete pretty much everything from C:\Program Files\CertifyTheWeb after stopping the Certify service, then it should add all the new files again. It's possible some stuff could be left (and need manually deleted) if the service refused to stop during the install or the UI was left open on a different user session on the same machine.

**Comment by glat** [comment]
Ok. Even we can fix it manually if the installer fails.
Thanks

**Comment by webprofusion-chrisc** [comment]
This link is to the release which will be formally published tomorrow:
https://certifytheweb.s3.us-east-1.amazonaws.com/downloads/archive/CertifyTheWebSetup_V5.6.1.exe

This version has a modified setup to clean up specific files from previous installs (such as the old SQLite dll).

**Comment by webprofusion-chrisc** [comment]
Further to this we are still seeing some reports of exceptions loading SQLite so we're going to revert to the older version until that can be figured out.

Can anyone confirm if they are using McAfee anti-virus and seeing this problem?
