### ISSUE TITLE
Request: Add Posh-acme Leaseweb plugin support

### ISSUE THREAD

**Issue by tmaniac** [webprofusion/certify#596]
Hello,

Since [v4.13](https://github.com/rmbolger/Posh-ACME/releases/tag/v4.13.0) of POSH-Acme there is [DNS-plugin support for Leaseweb](https://github.com/rmbolger/Posh-ACME/blob/v4.13.0/Posh-ACME/Plugins/LeaseWeb.ps1).

Can this support be added to Certifytheweb please?

**Comment by webprofusion-chrisc** [comment]
No problem, this will included in the next minor release (5.6.6), which could be next week.

**Comment by tmaniac** [comment]
Thank you very much! :)

**Comment by webprofusion-chrisc** [comment]
Closing. Update released.
