### ISSUE TITLE
Delete Registered Contacts fail

### ISSUE THREAD

**Issue by mhaegeleD** [webprofusion/certify#60]
I want do delete a "Registered contacts". 
But if I click with my right mousebutton on the item and choose 'Delete', Certify asks "Are you sure you whis to delete this item?" and I say "Yes", but nothing happens :-(
No chance to delte the Contact. What can I do?
(Windows Server 2012 R2, IIS 8.5)

**Comment by soundshed** [comment]
This is a bug and will be fixed in the next release.

**Comment by webprofusion-chrisc** [comment]
Closing. No longer applicable in v2.x
