### ISSUE TITLE
Using Azure DNS - missing information

### ISSUE THREAD

**Issue by Tarjei-stavanger** [webprofusion/certify#618]
This concerns the documentation in https://docs.certifytheweb.com/docs/dns/providers/azuredns/

The documentation shows how to find most of the necessary information, but there is no information on how to find the Resource Group Name.

**Comment by webprofusion-chrisc** [comment]
Thanks, yes we should update that. 

It assumes you are the azure administrator and that you already created your azure dns zone at some point previously (that's not covered either) and that you would know the resource group name for your DNS zone. If you sign into azure and look at your DNS zone you will see the resource group name (which all resources have in azure).

**Comment by Tarjei-stavanger** [comment]
It might be worth pointing out that the resource group name is for the DNS domain. I kept looking for something like that for the account that is used.
