### ISSUE TITLE
无法处理命令，因为一个或多个强制参数丢失

### ISSUE THREAD

**Issue by fansmarket** [webprofusion/certify#619]
2022-10-12 18:21:12.047 +08:00 [INF] Powershell/PoshACME DNS :: Powershell Task Completed.
Error: Add-DnsTxt: 无法处理命令，因为一个或多个强制参数丢失:  DNSPodKeyToken。
所在位置 行:33 字符: 1
+ Add-DnsTxt -RecordName '_acme-challenge.abc.net' -TxtValue 'Vql ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by webprofusion-chrisc** [comment]
Have you set your credentials for this provider?
