### ISSUE TITLE
Ability to specify zone parameter for DNS update via RFC2136

### ISSUE THREAD

**Issue by lavaground** [webprofusion/certify#620]
Hi Team,

as the title says, it would be nice to be able to specify the zone parameter for DNS update via RFC2136 since some providers, e.g. dynv6.net, require it for authentication.

I've worked around it by changing Lines 280 through 283 (added else statement) in RFC2136.ps1 from:

`    # add the zone if specified`
`    if ($Zone) {`
`        $cmds += @("zone $Zone")`
`    }`

to:

`# add the zone if specified`
`    if ($Zone) {`
 `       $cmds += @("zone $Zone")`
`    } else {`
`        $cmds += @("zone myzone.dynv6.net")`
`    }`

Kind regards,
Lava

**Comment by webprofusion-chrisc** [comment]
Thanks, so we use Posh-ACME's RFC2136 provider and it does appear to have an optional parameter for that value `DDNSZone` so I'll look into offering that option through our UI.

**Comment by webprofusion-chrisc** [comment]
This will be included in the next major release - the release date is not currently scheduled so for now continue with your own workaround. When you do update the posh-acme scripts will also be updated, overwriting your changes, so you will then need to go in and set the DDNS Zone value for subsequent renewal to work.
