### ISSUE TITLE
Certify the web (community edition) says it allows 5 domains, in fact (list) there are only 3 but on another entry i will see 4 and when i click new domain it tells me i have to pay - why?

### ISSUE THREAD

**Issue by xaxadev** [webprofusion/certify#621]
![2](https://user-images.githubusercontent.com/59201012/197552202-15a0f2af-3c22-45c4-8152-e4c28fec8542.jpg)
![3](https://user-images.githubusercontent.com/59201012/197552208-8c63a1f0-c055-4236-970e-5ed405fc31fb.JPG)
![1](https://user-images.githubusercontent.com/59201012/197552210-a93d31dc-f337-498d-9aa0-6ddf525ca7e7.jpg)

**Comment by xaxadev** [comment]
Does not make sense...!!

**Comment by webprofusion-chrisc** [comment]
It's just an information message. Just click OK, the next screen that comes up will let you add another managed certificate.

**Comment by xaxadev** [comment]
WTF... but thank you anyway!
