### ISSUE TITLE
Mark Certify.Web service depends on HTTP service

### ISSUE THREAD

**Issue by hibiyasleep** [webprofusion/certify#625]
(I have mispressed ctrl-enter while writing, sorry)

`net http stop` seems to be blocked by Certify, since dependency on http didn't specified on it's service.

---

full story:

- the somewhat program uses port 9696 for its OAuth redirect flow
- however Certify API lives there
  (at this moment, I didn't knew)
- 9696 is taken by PID 4, because Certify API lies behind HTTP.sys or whatever, even `net stop http` stucks.
  (atm again I have no clue about this at all)
- I tried debugging by interrupting port 9696 and event log
- it leaved clueless HttpEvent, and API moved to 9698 (…??)
- at this point I've finally learned `netsh http`, finally discovered Certify.Service here…

**Comment by webprofusion-chrisc** [comment]
Hi, support queries can be posted to https://community.certifytheweb.com/ and docs for how to change the default service port are here: https://docs.certifytheweb.com/docs/backgroundservice

You need to edit serviceconfig.json and servers.json under %PROGRAMDATA%\Certify to change to your preferred port, then restart the service.

There is also an option for "EnableAutoPortNegotiation" but it's probably best to set the preferred port manually.
