### ISSUE TITLE
Certify the Web does not send a request to the ACME server to deactivate the account when an account is deleted

### ISSUE THREAD

**Issue by lspiehler** [webprofusion/certify#626]
Certify the Web does not send a request to the ACME server to deactivate the account when an account is deleted. It is just removed locally. I was expecting certify the web to implement similar behavior to the "certbot unregister" command.

**Comment by webprofusion-chrisc** [comment]
Thanks, Lyas. You are quite correct, we should add an option for that. In some unusual cases accounts are shared across machines and in those cases you wouldn't necessarily want to unregister the acme account, which is why we'd make it optional.
