### ISSUE TITLE
Deployment Task - Stop Start or Restart a Service not able to restart service on remote machine

### ISSUE THREAD

**Issue by salusalpha** [webprofusion/certify#627]
Hi...

Stop Start or Restart a Service not able to restart service on remote machine since the non default service from remote machine is not shown in drop down list. 

Authentication     Windows Network
Target Host IP      192.168.111.2
Credentials           all set and working     
Service                  list shown seems to be from local machine but not from remote machine

Please fix so services from remote machine are shown so can be selected

cheers

**Comment by webprofusion-chrisc** [comment]
Thanks, I can confirm remote services are not currently supported and the next update will remove UI elements which suggest it's supported when it's not. We will plan to support remote services in the future.
