### ISSUE TITLE
[Feature] - Allow Pre and Post Request Custom Actions

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#63]
Before and after a certificate request has been prepared it would be useful to be able to specify custom process execution (batch file/powershell etc) optionally with variables from the input/output of the certification process as arguments. 

Allowing the user to specify these would enable custom configuration and certificate installation steps and would allow these steps to be repeated during automated renewal.

**Comment by webprofusion-chrisc** [comment]
To add to this: it would be good to have an optional custom step that can be added at different points during validation etc. So someone might script a custom DNS provider API interaction, or perform additional server config steps pre/post validation.

This could be implemented as both a custom scripting insertion (with variables that can be chosen to be passed in: batch files, powershell etc) or as a plugin (for more comprehensive steps). Ideally this would have a way to have common logs but isolate bugs caused by scripting components.

**Comment by StefanEgo** [comment]
I'm really missing this feature as well, since I'd like to make use of it to automate the update corresponding certificate we use for JIRA/Confluence (obviously a direct integration of JIRA/Confluence would be even better, but I take it that this is outside the scope of certify).

**Comment by webprofusion-chrisc** [comment]
This is now implemented in master. More info here:
https://github.com/webprofusion/certify/blob/master/docs/Request%20Script%20Hooks.md
