### ISSUE TITLE
Deployment Tasks - Run a program, batch file or custom script on windows

### ISSUE THREAD

**Issue by salusalpha** [webprofusion/certify#630]
Hi

It is impossible to get "Deployment Tasks - Run a program, batch file or custom script" on windows working.
I try to run a bat file with following command "Taskkill /F /IM notepad.exe". In the task parameters I choose "Local (as current service user).

Even when the "Certify SSL Manager Service" is running under the current user (i.e. Administrator) and "Log on as a service" right is given the task will not execute. 

What am I missing?

**Comment by webprofusion-chrisc** [comment]
Thanks, general support questions can be directed to our support community https://community.certifytheweb.com/ or if you are licensed user you can contact support directly `support {at} certifytheweb.com`.

The example command you are trying to run is privileged and there may be relevant restricting in group policy etc. In my test however, it worked OK.

If you try something much simpler like `dir C:\ > C:\temp\test.txt' does that work ok?

By default the service runs as Local System and we recommend you keep it that way for maximum compatibility. Some details such as account credentials are encrypted to the service user and changing the user can cause problems decrypting that information.


In my own testing I created the following bat file at `C:\temp\testing\test.bat`

```
DIR C:\> C:\Temp\test.txt

Taskkill /F /IM notepad.exe
```

I then added a `Run...` Task with the following settings and saved the managed certificate:

![image](https://user-images.githubusercontent.com/2445502/230835731-ef573a8a-225b-4b19-930c-ffc2d49253d1.png)

I then launched notepad and ran the Task via the Certify user interface. Notepad closes and the test text file is created,
