### ISSUE TITLE
AutoUpdate.ps1 script is broken

### ISSUE THREAD

**Issue by MisterSausage** [webprofusion/certify#634]
As of Certify The Web 6.0.1, the AutoUpdate.ps1 script (installed at CertifyTheWeb\Scripts\AutoUpdate) is broken. This is because it calls a Web API at `https://api.certifytheweb.com/v1/update` which still returns 5.6.8 as the current version.

As an additional enhancement, it might be a good idea to prevent the AutoUpdate script from downgrading the currently-installed version by default. (Currently, if it's run while 6.0.1 is installed, it'll silently downgrade the installation to 5.6.8!)

**Comment by webprofusion-chrisc** [comment]
Thanks you very much for raising this issue, it's much appreciated!

Currently our update API uses the version passed in the query string to identify which should get which update , and the PowerShell script isn't passing a version. Meanwhile our API isn't yet sending 6.x to everyone as we trickle feed the update.

Will review this.

**Comment by MisterSausage** [comment]
Is the API documented anywhere? I'm more than happy to update the script this weekend and submit a PR. (Although I can't actually find AutoUpdate.ps1 in the source tree!)

**Comment by webprofusion-chrisc** [comment]
Thanks, it's under https://github.com/webprofusion/certify/tree/development/src/Certify.Shared.Extensions/Scripts/AutoUpdate

I've updated that now to pass the version string to the API, this update will be included in our release early next week.

**Comment by MisterSausage** [comment]
Top notch! Thanks for looking into this so quickly.
