### ISSUE TITLE
Propagation timer not being preserved when using Constellix API (posh-acme) script

### ISSUE THREAD

**Issue by stephen-dunne** [webprofusion/certify#637]
v 6.0.5

The "Propagation Delay Seconds" timer value isn't being saved when changed away from the default 90s value. A change will only stick if you change the script to another provider, change it back to constellix and then lower the propagation delay timer before saving it. You're also not prompted to save the entry when only changing the timer.

I suspect you're not checking whether this particular field has changed..

**Comment by webprofusion-chrisc** [comment]
Thanks Stephen, yes it looks like there is a bug some field changed don't trigger the "IsChanged" property of our model and in some cases changes can get skipped, fix in the next update.
