### ISSUE TITLE
AcmeDNS Provider Error for API Update

### ISSUE THREAD

**Issue by armouredking** [webprofusion/certify#639]
I'm not sure what setting is wrong here. This was working previously (latest success for any cert was May 30 2023 1854), and seems to have failed during this cert renewal cycle (first fail was reported for mail server SSL recertify which was attempted July 30, 2023 1735 and has been failing every 48 hrs since - apparently the Certify Cert Manager emails hit the junk filter on 8/3 and I did not see them until investigating the mail server). So far only one certificate is dead, but the others also fail when attempting to test them so it is going to impact every setup I have.

The specific error message is generic, and provides little detail (logs are sanitised):
```
2023-09-11 06:21:42.279 -07:00 [INF] DNS: Creating TXT Record '_acme-challenge.mx.example.org' with value 'ZWwvbfjOCWRfgIaSy09tt2s6Mix-d7DBkeIBVe6e_90', [mx.example.org]  using API provider 'acme-dns DNS API'
2023-09-11 06:21:42.369 -07:00 [ERR] DNS update failed: acme-dns DNS API :: Update failed: Ensure the _acme-challenge.mx.example.org CNAME points to $uniquestring.auth.example.org
```

One quick check for KISS sake:
```
nslookup _acme-challenge.mx.example.org
Server: localhost
Address: 127.0.0.1

Non-authoritative answer:
Name: $uniquestring.auth.example.org
Address: $correctipaddress
Aliases: _acme-challenge.mx.example.org
```

Alright, looking deeper, lets see what AcmeDNS says:
```
time="2023-09-11T14:00:14Z" level=info msg="Using config file" file=/etc/acme-dns/config.cfg
time="2023-09-11T14:00:14Z" level=info msg="Connected to database"
time="2023-09-11T14:00:14Z" level=debug msg="Adding new record to domain" domain=auth.example.org. recordtype=A
time="2023-09-11T14:00:14Z" level=debug msg="Adding new record to domain" domain=auth.example.org. recordtype=NS
time="2023-09-11T14:00:14Z" level=debug msg="Adding new record to domain" domain=auth.example.org. recordtype=SOA
time="2023-09-11T14:00:14Z" level=info msg="Listening HTTP" host="0.0.0.0:80"
time="2023-09-11T14:00:14Z" level=info msg="Listening DNS" addr="0.0.0.0:53" proto=tcp
time="2023-09-11T14:00:14Z" level=info msg="Listening DNS" addr="0.0.0.0:53" proto=udp
time="2023-09-11T14:00:30Z" level=error msg="Error while trying to get user" error="no user"
time="2023-09-11T14:00:30Z" level=error msg="Error while trying to get user" error="Invalid username: $uniquestring"
```

Well. That's telling. Using commandline sqlite browser, and there is no issue with the database. All information is in there and correct.

Again, for the sake of KISS, let us walk through the example in AcmeDNS docs:
```
curl -X POST http://$correctipaddress/register

{"username":"$newuser","password":"$newpass","fulldomain":"$newstring.auth.example.org","subdomain":"$newstring","allowfrom":[]}

curl -X POST \
  -H "X-Api-User: $newuser" \
  -H "X-Api-Key: $newpass" \
  -d '{"subdomain": "$newstring", "txt": "___validation_token_received_from_the_ca___"}' \
  http://$correctipaddress/update

{"txt": "___validation_token_received_from_the_ca___"}

dig -t txt @auth.example.org $newstring.auth.example.org

; <<>> DiG 9.18.16-1~deb12u1-Debian <<>> -t txt @auth.example.org $newstring.auth.example.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11619
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;$newstring.auth.example.org. IN TXT

;; ANSWER SECTION:
$newstring.auth.example.org. 1 IN TXT "___validation_token_received_from_the_ca___"

;; Query time: 0 msec
;; SERVER: $correctipaddress#53(auth.example.org) (UDP)
;; WHEN: Mon Sep 11 07:39:39 MST 2023
;; MSG SIZE  rcvd: 189
```

I do not think this is something I can fix on my end. There does not appear to be any issue with AcmeDNS, I can do CURL and get expected results. Doing a CURL with incorrect password grants `{"error": "forbidden"}` from the API. Was there a recent change to code that impacts how CertifytheWeb makes requests of the AcmeDNS API? Specifically, with how username is provided? Just based on my limited knowledge, it appears like Certify is hitting AcmeDNS and getting rejected because the username is malformed or blank, but I don't know how to troubleshoot CTW app and debug this deeper.

**Comment by armouredking** [comment]
Well, I can confirm this is an issue specific to Certify. Since I could not find a troubleshooting method with Certify, I switched over to WACS instead, still using AcmeDNS, and it has no issues with using my setup. Granted, Certify didn't either, at least until the fails started in July.

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this issue. This seems like the original acme-dns registration details weren't being matched any more either by Certify or by the acme-dns server - I'll look into how that could be. The workaround would be to delete the registration stored under C:\ProgramData\certify\acmedns so that the next request has to re-register.

**Comment by webprofusion-chrisc** [comment]
Another thing to look at is the acme-dns registration C:\ProgramData\certify\acmedns - open the file in a text and look at what the "username" field is and whether that matches the "not found" error in acme-dns. It could be something simple like case or whitespace, likewise with password.

I assume your acme-dns service hasn't been updated. It would be interesting to see from your Certify The Web log if the failure coincides directly with a version update of Certify.

**Comment by webprofusion-chrisc** [comment]
Btw, people have infrequently raised the issue of lost acme-dns registrations before but we've never found a bug on our side for that. There could definitely be an issue somewhere and it would be nice to prove one way or the other.
