### ISSUE TITLE
Code question for VaultManager.

### ISSUE THREAD

**Issue by MichaelMcGlothlin** [webprofusion/certify#66]
I forked certify so I could add my own fixes.. in VaultManager there are several calls similar to:
```
var cmd = new ACMESharp.POSH.InitializeVault();
cmd.BaseUri = apiURI;
cmd.ExecuteCommand();
```

In each case it gives me a compiler warning that ExecuteCommand() is not defined. I don't see it defined in ACMESharp or Cmdlet. Any idea what I'm doing wrong?

**Comment by webprofusion-chrisc** [comment]
@MichaelMcGlothlin the master branch is currently in the middle of a significant re-write/refactor and requires a special fork of ACMESharp to build (I'm removing the dependency on powershell), it's also very much a work in progress and not really in a serviceable state for fixes, although we can discuss proposed changes here.

You can get the source tree for the latest release by switching to tag 0.9.96 
https://github.com/webprofusion/certify/tree/0.9.96

**Comment by MichaelMcGlothlin** [comment]
Removing PowerShell seems like a smart plan. Thanks.

**Comment by webprofusion-chrisc** [comment]
Closing. No longer applies for Certify 2.0
