### ISSUE TITLE
Wrong IIS binding updated

### ISSUE THREAD

**Issue by pacoteinnov** [webprofusion/certify#666]
We have two bindings on IIS, one that binds to '*' and another one that binds to 127.0.0.1.  The '*' has the CtW certificate and the one with 127.0.0.1 has a certificate that has been self-generated and expires in the year 9999.
When we update the certificate, sometimes it updates the 127.0.0.1 one and leaves the '*' with the out of date certificate.
First, is CtW supposed to updates all certificates, even the one that it didn't generate?
Second, is it possible to ensure that the right binding is updated?

**Comment by webprofusion-chrisc** [comment]
Hi, it's best to post general questions to https://community.certifytheweb.com/

If you are a licensed customer you can request support via email:  support {at}certifytheweb.com

**This particular issue is specific to your configuration and is not a bug, so please post to either of these to discuss further.**

The "sometimes" part of your description suggests that you are competing against the app to setup your https bindings somehow. The Preview tab will explain exactly which https bindings will be updated upon next renewal, you should review that to see which bindings it's matching and planning to update.

By default the app will match bindings with a specific hostname that matches the certificate name(s), or bindings that reference the last version of the same managed certificate. I would suspect that your 127.0.0.1 binding also has a hostname set that matches the certificate.

**Comment by pacoteinnov** [comment]
Sorry for posting to the wrong place!  We are a licensed customer, we will contact support after reviewing our setup.  Thanks for the quick response.
