### ISSUE TITLE
[bug] webcheck on a website with different bindings

### ISSUE THREAD

**Issue by pwn0r** [webprofusion/certify#67]
Apparently Certify cannot complete a check even though I can browse to that file

http://[removed]:5555/.well-known/acme-challenge/configcheck

I even enabled the directory browsing on that folder and it works just fine. 
So something tells me that the part ":5555" is a problem. That website does not have a binding on 80, especially accessible from outside.  In this case only 5555 and 443 are open (I'm using a test certificate for now but ideally I would need one which is accepted by browsers).

**Comment by webprofusion-chrisc** [comment]
Sorry, the Lets Encrypt service Certify uses does not support http validation over custom ports, only port 80 for http-01 and 443 for tls-sni-0 (not currently supported by Certify.
