### ISSUE TITLE
DNSPod (v2) DNS API (using Posh-ACME) :: Powershell Task Completed.Error

### ISSUE THREAD

**Issue by xiaotiannet** [webprofusion/certify#677]
App: Certify The Web 6.0.18.0
OS: Windows Server 2016

### **Step**
1. DNS Update Method : DNSPod (v2) DNS API (using Posh-ACME) 
2.  use true credentials
3. api root : https://dnsapi.cn
4. do Test

then show error 

### ****log message**** 
DNSPod (v2) DNS API (using Posh-ACME) :: Powershell Task Completed.Error: Add-DnsTxt: 无法处理命令，因为一个或多个强制参数丢失: DNSPodKeyToken。
所在位置 行:41 字符: 1

Add-DnsTxt -RecordName '_acme-challenge-test.cloud.******.com' -T ...
![image](https://github.com/webprofusion/certify/assets/7654347/3c26417b-e6ed-4e19-bc79-6d2eddbc843b)

### **try**

I try add log  in   \CertifyTheWeb\Scripts\DNS\PoshACME\Plugins\DNSPod.ps1
![image](https://github.com/webprofusion/certify/assets/7654347/a17b034e-4f9f-4123-9bde-cd71d58f81e5) 

see result , DNSPodKeyTokenInsecure and DNSPodKeyToken is empty !
![image](https://github.com/webprofusion/certify/assets/7654347/449faf9a-d593-41a0-909f-734f15f5e623)

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this issue, the problem is a misspelled argument for the powershell script. A fix will be included in a future update.

**Comment by xiaotiannet** [comment]
> Thanks for raising this issue, the problem is a misspelled argument for the powershell script. A fix will be included in a future update.

Thanks

**Comment by webprofusion-chrisc** [comment]
Hi, here is a link to a test version of 6.0.18 with updated DNS Pod arguments you could try:

https://certifytheweb.s3.amazonaws.com/downloads/test/CertifyTheWebSetup_DNSPodTest.zip

**Comment by xiaotiannet** [comment]
> Hi, here is a link to a test version of 6.0.18 with updated DNS Pod arguments you could try:
> 
> https://certifytheweb.s3.amazonaws.com/downloads/test/CertifyTheWebSetup_DNSPodTest.zip
Thank you very much for your help. The new version you sent, tested OK.

I temporarily modified the 'DNSPod.ps1' file in the Posh-ACME plugin and it works for now.
Temporarily add the parameter: $DNSPodToken
![Snipaste_2024-06-20_16-27-25](https://github.com/webprofusion/certify/assets/7654347/5a0b14e4-832b-43bd-8807-47c73797521f)

now，this close
