### ISSUE TITLE
problem with entering via old browsers

### ISSUE THREAD

**Issue by vovka36** [webprofusion/certify#68]
When i generate certificate and install it using Certify there was a problem with entering on site via old browsers such as ie7, ie8, opera 12. The message like  "Browser cannot display page..." displayed.
When i generate certificate using powershell and acmePOSH library there is all opened sucsessfully.
Please help me to understand why it is happened?

**Comment by webprofusion-chrisc** [comment]
I'm guessing your hosting on Server 2012 or higher. When you used ACMESharp you probably setup the binding for the domain certificate yourself and unchecked the 'SNI' option - this option lets you bind multiple certs to one IP address but is only understood by modern browsers/operating systems. 

To do the same in Certify you need to uncheck 'Use SNI' when requesting the certificate. You can also update the binding under IIS.
