### ISSUE TITLE
ERR_SSL_KEY_USAGE_INCOMPATIBLE on Windows 10 Pro x64 IIS with most current updates

### ISSUE THREAD

**Issue by kosuodhmwa** [webprofusion/certify#692]
As title says - so why?

**-> Certificate is Let's Encrypt**

Thank you very much for your feedback(s)

Best regards
Jan

**Comment by webprofusion-chrisc** [comment]
Good question but please direct support queries to https://community.certifytheweb.com and provide detail about what you are trying to do. This is not a bug in our application, this is specific to your own configuration.

**Comment by kosuodhmwa** [comment]
thank you for four feedback. 

i disabled that option in red rectangle - now it seems to work 

(but i don't know the exact reason for that behavior and i do not relly know what that option is... need to do some research when i have some time)

![image](https://github.com/user-attachments/assets/8f83c423-afe8-4802-997a-6fc531754c85)

**Comment by kosuodhmwa** [comment]
done... :-)  https://community.certifytheweb.com/t/err-ssl-key-usage-incompatible-on-windows-10-pro-x64-iis-with-most-current-updates-on-2024-11-25/2414
