### ISSUE TITLE
Support sites with default/blank hostname binding

### ISSUE THREAD

**Issue by StefanEgo** [webprofusion/certify#75]
I just evaluated Certify to use with our webpage. Unfortunately, it seems to miss our main website from the Website dropdown (while all other sites (including redirects) are shown). Is there some way to trouble shoot why our main website is not listed in Certify?

Case to reproduce for us;
1. Start Certify
2. Click on "New Certificate"
3. Click on the Website drop-down box

Actual result:
All sites except for our main page are listed here.

Expected result:
All sites are listed.

Environment:
Windows 2012 R2; IIS 8.5; Certify 0.9.98 - 20170311.Alpha15

**Comment by webprofusion-chrisc** [comment]
Hi Stefan, assuming the site is started and it has one or more domain bindings setup it should appear OK. If you open a powershell command prompt as administrator and run the following commands, does it list the missing site?

Import-Module Webadministration
Get-ChildItem -Path IIS:\Sites

**Comment by StefanEgo** [comment]
Yes, the missing site is listed there. I just sent you a mail with some detailed information which hopefully help to trace down the problem (don't want to make these details public here).

**Comment by StefanEgo** [comment]
FWIW: Problem identified. The issue in our case is that the site in question doesn't set a hostname in the bindings. Hence, Certify didn't list it. As a workaround: adding a hostname to the bindings solved the problem for us (still suggesting an improvement on Certify's site to handle these cases in some way).

**Comment by webprofusion-chrisc** [comment]
Need to figure out a way to update existing bindings for the right site if no hostname is selected, perhaps we can base it entirely on site id in those cases but it probably needs a confirmation step before being applied. We want to avoid automated binding changes which might disrupt an otherwise working site.

**Comment by glat** [comment]
If a site has blank hostname binding it must be the only one, so the answer to your question is to simply show first one on bindings.

This will be useful to add ssl to exchange which sets blank binding.

**Comment by webprofusion-chrisc** [comment]
@glat you can have a site with multiple blank host name bindings if they are mapped to different ips. Working on the UI for this now.

**Comment by glat** [comment]
Yes, it's per different IPs and for *.
Another hint: in IIS configuration "All IP Addresses" is *, not empty string. I sent a PR on another github project about this.

**Comment by webprofusion-chrisc** [comment]
@glat thanks - I'm fairly sure we're already using * for wildcard IP bindings but I'll double check.

**Comment by webprofusion-chrisc** [comment]
Update: the upcoming v4 will support this (bindings that don't specify a hostname) but it's likely you will have to create the https binding manually (pointing to your new certificate), then subsequent renewals will update the existing https binding.

**Comment by webprofusion-chrisc** [comment]
Support for sites with blank hostname bindings is now part of v4 beta.

**Comment by StefanEgo** [comment]
Just updated to the released 4.0.5 version. From our point of view: confirming the issue should be considered closed with Ceritfy >= 4.0.4.
