### ISSUE TITLE
Support for PowerShell / WMF 2.0 / Windows Small Business Server 2011 Standard

### ISSUE THREAD

**Issue by flaw19plane** [webprofusion/certify#78]
Systems that are running the following server applications should not run Windows Management Framework 4.0 at this time.
- System Center 2012 Configuration Manager (not including SP1)
- System Center Virtual Machine Manager 2008 R2 (including SP1)
- Microsoft Exchange Server 2007
- Windows Small Business Server 2011 Standard

source: https://www.microsoft.com/en-us/download/details.aspx?id=40855&751be11f-ede8-5a0c-058c-2ee190a24fa6=True&e6b34bbe-475b-1abd-2c51-b5034bcdd6d2=True

As a result _Windows Small Business Server 2011 Standard_ can't be used with _Certify_.

**Comment by webprofusion-chrisc** [comment]
Thanks, the next release of Certify (as per our current Master branch) is a few weeks away and no longer uses PowerShell. This will make installation much easier for everyone.

**Comment by webprofusion-chrisc** [comment]
The alpha of Certify v2 is now available and does not require PowerShell. Closing.
