### ISSUE TITLE
Support environments behind corporate proxy

### ISSUE THREAD

**Issue by baldpope** [webprofusion/certify#79]
Many corporate environments will only allow authenticated web access to the internet.  Certify should either prompt the user for proxy credentials or be proxy aware to use the system proxy.

**Comment by webprofusion-chrisc** [comment]
@baldpope Certify currently runs on the internet facing server that needs the certificate, and the new version will require unattended access to the internet to perform auto renewals. What scenario do you have? i.e. what are you generating certificates for?

**Comment by baldpope** [comment]
@webprofusion-chrisc the assumption here is that the server you're running Certify on is internet facing.  In many environments, that simply isn't the case.  For example, in our DC, our Exchange server does not directly serve internet requests.  Outlook Web Access is only exposed through an Apache reverse proxy and even the SMTP relay is directed at an alternate internal smart-host for additional routing.  

Even still, assuming I let these services serve content directly, a client making a connection inbound is not the same as a process making a new connection outbound (in this case Certify).  We require all outbound internet traffic to first pass through an authenticated proxy for two reasons - one to know the traffic occurred and two to ensure that the traffic is legitimate.  I'll admit, some sites likely allow servers to talk out unfiltered, but I'd hope those are exceptions and not the norm.

Ideally, Certify would either read the internet options values from either the user running it, the system proxy (set via netsh.exe) or have the option to configure proxy settings within Certify.

I could work around this by allowing my server to talk out to known ports/hosts, but I'd prefer to keep my firewall holes to a minimum.  Hopefully, my rationale makes sense.

**Comment by webprofusion-chrisc** [comment]
@baldpope OK, noted. In the meantime you might want to try the ACMESharp powershell scripts directly as I belive they have a Set Proxy option.

**Comment by EchoNBounce** [comment]
@baldpope - Hacky workaround with caveats about the possibility of unexpected failures...

Because CertifyTheWeb is a .NET application, it can be made to be proxy aware by modifying the application configuration.

1. Stop the Certify service (e.g. using services.msc)
2. For each of the files:
"C:\Program Files\CertifyTheWeb\Certify.UI.exe.config"
"C:\Program Files\CertifyTheWeb\CertifySSLManager.Service.exe.config"
Edit (requires elevation) by inserting the code block following at the end of the file, modified with your proxy details:
```
    <system.net>
        <defaultProxy enabled="true">
            <proxy bypassonlocal="true" proxyaddress="http://PROXYHOST:PROXYPORT/" />
        </defaultProxy>
    </system.net>
</configuration>
```

3. Restart the Certify service.

**Comment by webprofusion-chrisc** [comment]
@EchoNBounce interesting! I see the docs at: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration

I wonder if this works for proxies that require a username/password?

Looks like there is a also a usesystemdefault option but not sure if that would work as Local System (our default background service user).

Ideally we would support proxies directly - what proxy server are most people using?

**Comment by EchoNBounce** [comment]
@webprofusion-chrisc  Good question...

If the proxy supports URL-encoded HTTP basic authentication then you might be able to get away with: http://username:password@host:port/

**Comment by webprofusion-chrisc** [comment]
Closing. While proxy use is possible, it won't be officially supported. While we can enable it for the main process/service we can't control it for extended things like deployment tasks, powershell scripts etc so we have to leave this as an exercise for the user.
