### ISSUE TITLE
Auto apply is not working properly

### ISSUE THREAD

**Issue by Lisaj** [webprofusion/Certify#8]
Hello,
I renewed the certificate via Renew. Then click Apply Auto. The certificate for a site has the title of today's date, but has the same expiration date as the original certificate. In certify I see a new certificate with the extended expiry date.

using:
Certify 0.9.85
Windows Server 2012 R2

**Comment by webprofusion-chrisc** [comment]
Hi, as a workaround instead of using Renew/Auto Apply just request a new certificate for the same domain/site. This will perform a renewal.

**Comment by Lisaj** [comment]
Thank you it works

**Comment by frontier777** [comment]
I am having the same problem. Renew seems to renew the certificate and the expiry date/days remaining reset to 89 days in Certify, but I can't seem to affect the certificate in IIS in any way.

I've tried Renew and Auto Apply. I've tried the recommendation above and created a New Certificate. (haven't tried deleting the old cert though) I've tried to set the bindings manually but the only certificate to select is the original one.

The expiry date is not updated in IIS or the browser when I view the certificate, only in Certify.

**Comment by RickStrahl** [comment]
Ran into this today as well. Without the Renew feature updating sites becomes a major pain and effectively makes this an unsuable solution for cert management as having to recreate bindings manually in IIS (to map to explicit IP addresses and making sure the old certs are removed) are very time intensive and error prone.

I thought this worked before, but I might have just looked at Certify's output which shows the updated cert dates, but those dates don't actually match what's in the Windows Certificate store.

 Any chance of this getting fixed?

**Comment by webprofusion-chrisc** [comment]
Yes, the renew and auto apply buttons don't work properly in this version. Instead request the certificate again as if you were requesting for a new site.

I do want to get this working but just have other commitments at the moment.

**Comment by webprofusion-chrisc** [comment]
Ps. Pull requests are being accepted! Certify was built over a short period and has lots of room for improvement, most of which would be quite easy for those who would like to contribute time to it. Ultimately I'd like to have a Certify windows service to which the UI talks. That way renewals would be automated and monitored.

**Comment by Marcus-L** [comment]
I submitted a PR (#20) for this issue, it appeared to be partially working before the change (if you clicked "Renew", then "Export" after the renew, then "Auto Apply" after exporting, it would work), so it was a minor change to get it to work in my environment. Please let me know if it works for you!
