### ISSUE TITLE
does not give list of possible domains

### ISSUE THREAD

**Issue by tristanxtc** [webprofusion/certify#83]
when I go to create a new certificate, it does not populate the domain choice dropdown box

**Comment by tristanxtc** [comment]
i can reproduce this consistently ... would be a blocking bug in my mind

**Comment by webprofusion-chrisc** [comment]
Thanks, does your website have domain bindings setup in IIS? Certify uses those to work out what domains to request certificates for and also to match the new SSL certificates back to the site bindings.

**Comment by tristanxtc** [comment]
Yes it does, I have several

**Comment by webprofusion-chrisc** [comment]
Is this issue when you have have added a new domain binding in IIS then go back to certify? It won't currently auto-refresh the list against a site and you need to delete the managed site and add it again. Does that sounds like the problem you're seeing?

**Comment by tristanxtc** [comment]
That definitely could be it, I will give that a try and let you know.

**Comment by tristanxtc** [comment]
I gave that a quick try …I deleted the existing group/server from the app. Had to close it and reopen and get the import screen again to restore that group. And it still won’t show anything in that dropbox . Just to clarify this is the lower dropbox, not the one with sitetnames



From: Tristan Scharff
Sent: Tuesday, May 9, 2017 10:46 PM
To: webprofusion/certify
Subject: RE: [webprofusion/certify] does not give list of possibledomains(#83)

That definitely could be it, I will give that a try and let you know.

**Comment by webprofusion-chrisc** [comment]
Thanks the New Certificate screen top dropdown is the list of IIS sites, the next one if the domain selection for the primary domain to use in the certificate (the one that's not populating for you), then the checkboxes are for additional domains to include in the certificate.

If you open powershell and run the following commands, is your site listed with it's domain?:

```
Import-Module Webadministration
Get-ChildItem -Path IIS:\Sites
```

For example the output I get is:
```
Certify          1    Started    C:\inetpub\wwwroot\Certify     http *:80:certify.webprofusion.com
                                                                https *:443:certify.webprofusion.com sslFlags=1
                                                                http *:80:certifytheweb.com
                                                                http *:80:www.certifytheweb.com
                                                                https :443:certifytheweb.com sslFlags=1

```

**Comment by tristanxtc** [comment]
PS C:\WINDOWS\system32> Import-Module WebAdministration
PS C:\WINDOWS\system32> Get-ChildItem -Path IIS:\Sites

Name             ID   State      Physical Path                  Bindings
----             --   -----      -------------                  --------
Default Web Site 1    Started    %SystemDrive%\inetpub\wwwroot  http 192.168.1.3:83:tristanx.crabdance.com
Tristan          2    Started    D:\Downloads                   ftp *:21:
TristanX         3    Started    C:\inetpub\wwwroot\TristanX    http 192.168.1.3:80:tristanx.undo.it
                                                                ftp 192.168.1.3:21:
                                                                https 192.168.1.3:443:tristanx.undo.it sslFlags=0
wordpress        4    Started    C:\inetpub\wwwroot\Wordpress   http 192.168.1.3:800:tristanx.crabdance.com
                                                                https 192.168.1.3:85:tristanx.crabdance.com sslFlags=0

**Comment by webprofusion-chrisc** [comment]
Thanks. I'll have a look at these and see if I can create similar bindings to see what the problem is.

**Comment by picturepete** [comment]
Hi I am getting a similar problem, the drop down menu (select site) it only shows 3 sites 'default website' 'hostingcontroller' and 'Microsoft sharepoint administration' if I run the powershell commands as above it lists all the websites

**Comment by webprofusion-chrisc** [comment]
@picturepete can you confirm that all your website have a domain binding setup? If it is blank or default then Certify won't currently list it.

**Comment by picturepete** [comment]
they do, if I sue the older version it lists all the sites but crashes when trying to get a certificate.

**Comment by picturepete** [comment]
I am wondering if this is because the three domains mentioned are all on the C: drive whilst the other domains are all on the d: drive

**Comment by webprofusion-chrisc** [comment]
@picturepete thanks, the drive shouldn't matter so there's something else causing this. It could be related to the OS patch level - what OS and service pack etc are we on?

**Comment by picturepete** [comment]
Hi it is currently on 2008 server SP2 I have tried it on 2008 R2 with the same result.

Cheers Pete

**Comment by webprofusion-chrisc** [comment]
Could you email me a screenshot of the Right Click> Manage Website > Advanced Settings screen from IIS for one of the websites? I'm trying to see what's different.

**Comment by webprofusion-chrisc** [comment]
Is this still occurring in the current version of the app (3.0.11?)
