### ISSUE TITLE
import does not "stick"

### ISSUE THREAD

**Issue by tristanxtc** [webprofusion/certify#84]
When I import during the first run, it doesn't stay imported, it makes me import again next run or it leaves me with nothing in my certificate list

**Comment by tristanxtc** [comment]
this is consistent and happens every time. I would consider it a blocking bug.

**Comment by webprofusion-chrisc** [comment]
Thanks, so this is an upgrade form a previous install of Certify. Can you try running the import then editing the title of one of the imported sites and saving that site? I wonder if it's not saving the managed sites automatically for some reason.

**Comment by tristanxtc** [comment]
Sure I can do that … always willing to help out

**Comment by MGPenn** [comment]
I had the same problem.  I modified an entry (I turned off the auto renew) on each of the domains and exited the program.  Restarted Certify and it did not ask for an import.  The domains are showing as normal.

**Comment by webprofusion-chrisc** [comment]
Closing. Import now saves properly as of v2.0.7
