### ISSUE TITLE
crash when I discard a new cert form

### ISSUE THREAD

**Issue by tristanxtc** [webprofusion/certify#85]
The application crashes when I click on discard on the new certificate form

**Comment by tristanxtc** [comment]
i have not been able to repeat this reliably

**Comment by webprofusion-chrisc** [comment]
Thanks, what operating system are you on? Do you get a stack track window or something in the windows event log?

**Comment by tristanxtc** [comment]
I’m on windows 10 enterprise, I didn’t get a error log, I have most of that turned off in windows, I can enable it and see what happens.

**Comment by webprofusion-chrisc** [comment]
Thanks, I've found the issue causing this and the fix will be in the next release.
