### ISSUE TITLE
Expiry date is not showing

### ISSUE THREAD

**Issue by qwertyno** [webprofusion/certify#86]
The old (0.98 version) of Certify displayed the expiry date. Not so in 2.x alpha version.

**Comment by webprofusion-chrisc** [comment]
Thanks, we currently show the expiry as Days remaining, if you have Auto Renew configured then this should never get below 83 (currently we renew every 7 days but we may still increase that to 14 or 30 etc)

**Comment by yangar** [comment]
"Thanks, we currently show the expiry as Days remaining"
Where is it shown ? i can't see it too.

**Comment by webprofusion-chrisc** [comment]
So when a managed site has a successful certificate against it, it should show the expiry - what operating system are you on? If coming from a previous version of Certify you would need to request a renewal of the Certificate first.

![expiry](https://cloud.githubusercontent.com/assets/2445502/26272387/73635438-3d49-11e7-8a13-298320ec0b03.png)

**Comment by webprofusion-chrisc** [comment]
Can I confirm that operating system you're on if you can't see this info - could be a problem with default system colours.
