### ISSUE TITLE
Only show started web-sites / Ignore stopped web-sites

### ISSUE THREAD

**Issue by qwertyno** [webprofusion/certify#89]
Certify uses all registered web sites, whether they are started or not.
If several web sites are registered in IIS with the same bindings, but only one is started, this may result in the current/active site is not available, but a stopped/inactive site is.
I am looking into and may contribute on this issue.

**Comment by webprofusion-chrisc** [comment]
Thanks, this a regression from the older version and we should make this optional. Some users are still complaining of sites they have not showing up which is why the filter is currently disabled.

**Comment by webprofusion-chrisc** [comment]
Pretty sure this is resolved now.
