### ISSUE TITLE
How to create Certificate for both main domain and www. domain

### ISSUE THREAD

**Issue by RickStrahl** [webprofusion/Certify#9]
Since we currently can't generate certs that provide both the root domain and www I'm trying to create two separate certificates for both the root and and www domain. However, this is not working.

I initially created the root domain and that worked fine. When I then try to create the www. domain, that operation always fails. I get either PFX failed to generate or operation wasn't completed. The certificate entry gets created but all the Vault info fields are blank.

What do you suggest is the right way to create certificates for both root and www. domains at this point?

**Comment by webprofusion-chrisc** [comment]
Is your www a redirection to non-www? If so I'm pretty sure letsencrypt don't follow the redirection.

**Comment by RickStrahl** [comment]
Ah - crap I didn't think of that.  Yes that indeed works now. Thanks Chris...

**Comment by madman32395** [comment]
@RickStrahl why not use an alternative name, just enter www.<yourwebsite>.tld,<yourwebsite>.tld   

I have my site setup like that and both www and non-www are covered just fine.

**Comment by RickStrahl** [comment]
@madman32395 that only works if you **only** have tld and www. but not if you have a large number of subdomains as I do. Otherwise IIS chooses some random subdomain as your non-specified domain.
