### ISSUE TITLE
Validation of the required challenges did not complete successfully. please ensure all domains to be referenced in the certificate can be used to access this site without redirection. 

### ISSUE THREAD

**Issue by kdhoe1** [webprofusion/certify#93]
domain/.well-known/acme-challenge/configcheck returns Extensionless File Config Test - OK

can anyone advise what could be wrong?

regards

**Comment by kdhoe1** [comment]
in one of the logs 
Failed prerequisite configuration (SSL_LetsEncrypt_LocalIIS)
there is only http binding en no redirection.

**Comment by kdhoe1** [comment]
found the culprit, ipv6 dns issue.

**Comment by webprofusion-chrisc** [comment]
@kdhoe1 can you elaborate a bit more on that? Was the site only available externally over ipv6 and that's why it failed?

**Comment by SimonAntony** [comment]
I've just started to see this error and no idea why, logs state:

2017-12-06 16:18:29.520 +00:00 [Information] Attempting Domain Validation: www.mydomain.co.uk
2017-12-06 16:18:33.271 +00:00 [Information] Failed prerequisite configuration checks (SSL_LetsEncrypt_LocalIIS)
2017-12-06 16:18:33.274 +00:00 [Information] Validation of the required challenges did not complete successfully.

**Comment by webprofusion-chrisc** [comment]
@SimonAntony we can chat it through via email: apps {at} webprofusion.com - it sounds like there has been a configuration change since you last successfully renewed your certificate which is now causing validation to fail.

**Comment by SimonAntony** [comment]
Hi @webprofusion-chrisc - managed to sort it. Basically this site was recently upgraded so the previous certificate was applied to the new site, however the .well-known folder was not copied over - this seemed to cause some strangeness explained above.

I copied over the folder, re-requested the cert and it went straight in. Maybe an additional check is needed in these circumstances?

**Comment by webprofusion-chrisc** [comment]
@SimonAntony thanks, do you use a custom web.config for the content in the .well-known folder? Normally the app would recreate this folder as required which suggests there's a special case here (permissions?).

**Comment by webprofusion-chrisc** [comment]
@SimonAntony ah, if you have moved the site check the setting for the www path (under Advanced) and leave it blank if you would expect to move the site around much.

**Comment by SimonAntony** [comment]
Hi @webprofusion-chrisc - I append the rules below, permissions *should* in theory be fine but could not understand why the .well-known folder could not be created in the first place.

https://blog.tedd.no/2017/05/09/iis-redirect-http-to-https-but-allow-lets-encrypt/

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Allow LetsEncrypt" patternSyntax="Wildcard" stopProcessing="true">
                    <match url=".well-known/*" />
                    <action type="None" />
                </rule>
                <rule name="Redirect HTTP to HTTPS" patternSyntax="Wildcard" stopProcessing="true">
                    <match url="*" ignoreCase="false" />
                    <conditions>
                        <add input="{HTTPS}" pattern="off" />
                    </conditions>
                    <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
