### ISSUE TITLE
Can it work without named Bindings?

### ISSUE THREAD

**Issue by h3mp** [webprofusion/certify#94]
Trying to use on SBS2011 machine that has Exchange 2010 included.
Under "Select IIS Site" i choose "Default Web Site" but can go no further as no primary domain is selected 
- could this not be entered manually instead somehow?

(With no named bindings against the DefaultWebSite in IIS then no primary domain is available for selection. - I don't want to add a named binding as this breaks things in SBS2011 with exchange client connections)

**Comment by webprofusion-chrisc** [comment]
@h3mp thanks, this is a work in progress as per #75 - definitely something that needs to be added.
