### ISSUE TITLE
Access denied on step 45 (PEM file creation)

### ISSUE THREAD

**Issue by rstaub77** [webprofusion/certify#95]
Hello,

I just had the same error message discussed here : https://github.com/ebekker/ACMESharp/issues/203

I then downloaded and debugged Certify source code, to see where the error came from.
I ended on this block of code in the ACMESharpUtils class :
```
    var keyGenAsset = vlt.CreateAsset(VaultAssetType.KeyGen, keyGenFile, getOrCreate: force);
    var keyPemAsset = vlt.CreateAsset(VaultAssetType.KeyPem, keyPemFile, isSensitive: true, getOrCreate: force);
    var csrGenAsset = vlt.CreateAsset(VaultAssetType.CsrGen, csrGenFile, getOrCreate: force);
    var csrPemAsset = vlt.CreateAsset(VaultAssetType.CsrPem, csrPemFile, getOrCreate: force);
```
So it seems that specifically for the PEM file, the option "isSensitive" is used.
I tried to rebuild without this option, and then the process succeded to completion, issue was solved.
Maybe There is a problem with the syntax of the ProgramData filename, I don't know.
By the way I am not sure about the purpose of the isSensitive option, as it seems to works fine without it.

**Comment by webprofusion-chrisc** [comment]
This would affect the Home edition of windows. Can you confirm the OS version you are on?

**Comment by rstaub77** [comment]
Actually it was on a Windows Server 2008 R2 (English), with the latest patches from Windows Update.
File system is of course NTFS.

**Comment by webprofusion-chrisc** [comment]
Hmm, sorry - I can confirm that it normally works fine on server 2008 R2. I'd suggest deleting your c:\programdata\ACMESharp folder and trying the app again. It will prompt you to add register your domain contact again.

**Comment by rstaub77** [comment]
Recompiling Certify from source was not my first action.
Actually I started by deleting c:\programdata\ACMESharp folder many times, but even from a fresh start, I got the same error.
As the error message is about "access denied", I assumed it could be an issue with the ACL on the folder (thanks to NTFS), so I changed it and gave Users and Everyone full control over the folder and its children, but without any positive effect (any effect at all in fact).

About recompiling Certify, I first tried without any code modification : same error at the same step.
Then I modified the second CreateAsset, removing the isSensitive parameter, thus letting it at the default (false) value. And at this point it worked passed the step 45.
As Certify seems to works with this parameter set to "false", and as when it is set to "true" it seems to have problems on some machines, I really wonder what is the purpose of setting it to "true" in the first place.

**Comment by webprofusion-chrisc** [comment]
Yeah, what's interesting is why you're seeing this issue in the first place. We can certainly remove it as I don't really think it has much practical relevance.

**Comment by webprofusion-chrisc** [comment]
Ok, v2.0.5 is out now and makes using EFS for sensitive file storage optional and off by default. Please give this version a try and see if it fixes this for you.

**Comment by webprofusion-chrisc** [comment]
Ok, marking this as resolved.
