### ISSUE TITLE
App hangs after adding contact, if Let's Encrypt API not available.

### ISSUE THREAD

**Issue by scene316** [webprofusion/certify#96]
After installing version 2.0.3 on Windows Server 2016 the application opens, then prompts for a contact email address. Once this email address is supplied and Register Contact is clicked, the application just hangs in an unresponsive state before crashing.

**Comment by webprofusion-chrisc** [comment]
@scene316 Hi, do you know if you have TLS locked down to 1.2? That can cause issues on the current version but will be fixed shortly.

**Comment by scene316** [comment]
Thanks for the suggestion. Good news and bad news. The good news is that it doesn't hang in an unresponsive state. The bad news it that is now just crashes immediately after I click Register Contact.

**Comment by webprofusion-chrisc** [comment]
The hang seems to be that the Lets Encrypt service is currently not respond properly (right this minute). The crash is if you enable TLS1.2 then Certify doesn't know to change the default for .net (yet). That's fixed in the next release which should be this weekend.

**Comment by scene316** [comment]
Thanks for your quick replies! 

I should have checked the status of Let's Encrypt, I see there is an active incident now.

**Comment by bubach** [comment]
Same issue, and looks like there's an active incident at lets encrypt, so...  perhaps a timeout with user-friendly message telling us lets's encrypt service seems to be down?

**Comment by webprofusion-chrisc** [comment]
Yeah, it could with some more UI feedback.
