### ISSUE TITLE
Why does version 2 onwards requires a license to manage more than 5 sites?

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#98]
This will come up again so I thought I'd log the issue myself. I've been developing Certify in my spare time since the launch of Let's Encrypt. Recently I've put a lot more time into it to make it easier to use and try to give it the most common features people need.

Last week (May 2017) the company that was my day job went bust. I had previously been considering add paid features into Certify and losing your job when you have an enormous mortgage on your house is a great motivation for that.  Currently the Version 2.0 of Certify will let you manage up to 5 of your sites for free, thereafter if you purchase a license (which can go on multiple servers and lasts for 18-months) you can manage unlimited sites.

I realise some people will be adversely affected by this change, but probably not as much as I would be if I didn't make that change. If you have previously donated via PayPal to sponsor the project or if you have previously had PRs accepted on GitHub, email apps@webprofusion.com with the details and I'll get you set up with a free license key.

**Comment by kenwarner** [comment]
hey everybody has bills to pay. appreciate all your work on this project. good luck finding a new day job quickly!

**Comment by MichelZ** [comment]
@webprofusion-chrisc  Should this issue be closed? It's bad for the stats :D

**Comment by webprofusion-chrisc** [comment]
Lol, probably. 

It's also inaccurate as the current version does 10 instead of 5.
