### ISSUE TITLE
Certify has stopped working

### ISSUE THREAD

**Issue by Loomaanaatii** [webprofusion/certify#99]
Any idea what this means or how to fix it?

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: Certify.UI.exe
  Problem Signature 02: 2.0.0.0
  Problem Signature 03: 5921473d
  Problem Signature 04: Certify.Core
  Problem Signature 05: 2.0.0.0
  Problem Signature 06: 5921473a
  Problem Signature 07: 35
  Problem Signature 08: 9
  Problem Signature 09: N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
  OS Version:   6.3.9600.2.0.0.400.8
  Locale ID:    1033
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: 5f25
  Additional Information 4: 5f2531ae070278f893fa99352dadd49e

**Comment by webprofusion-chrisc** [comment]
Sorry, I can't tell anything from this. Were you just launching the app or did you click a particular button and then it crashed? Does it do it repeatedly?

**Comment by webprofusion-chrisc** [comment]
Also did you have an old version of Certify already installed? What operating system are you on? Thanks!

**Comment by Loomaanaatii** [comment]
This is opening the app it happens after every time I click on the app icon.

**Comment by Loomaanaatii** [comment]
Latest build. Windows server 2012 r2

**Comment by Loomaanaatii** [comment]
Also this is fist time using the program on this vm.

**Comment by webprofusion-chrisc** [comment]
Thanks, I'm starting up a 2012 r2 vm just now to test. Can you confirm which version of the .net framework you have installed?

**Comment by Loomaanaatii** [comment]
3.5. So it was working when I first installed it, then I rebooted the VM for updates and it stopped working.

I uninstalled it and reinstalled it twice and still the same error.

**Comment by webprofusion-chrisc** [comment]
Ok, perhaps you could try a repair on your .net 4.5 installation - thats the version required for Certify and if .net 3.5 was added after that could have an impact.

**Comment by Loomaanaatii** [comment]
Yeah, I have both installed since PHP needed the .net 3.5 package. 

I should try reinstalling 4.5?

**Comment by webprofusion-chrisc** [comment]
Yes, I think there's something unusual about the state of the software on your server. It could be a security issue, a missing file or something else. Best to try repairing .net 4.5 if you can.
